import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Crypto Licensing Guide (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Guide to cryptocurrency business licensing worldwide including exchange licenses, money transmitter registrations, and regulatory frameworks across jurisdictions.",
  keywords: ["crypto license", "exchange license", "money transmitter", "crypto business license", "VASP license", "crypto regulatory framework"],
};

export default function CryptoLicensingGuidePage() {
  return (
    <LearnPageLayout title="Crypto Licensing Guide" categoryName="Crypto Education" categorySlug="learn" readTime="7 min" intro="Cryptocurrency businesses operating as exchanges, custodians, payment processors, or other service providers need various licenses and registrations depending on their jurisdiction and activities. Understanding the licensing landscape helps users evaluate the regulatory standing of platforms they use and helps entrepreneurs navigate the compliance requirements for crypto businesses."
      toc={[
        { id: "overview", title: "Licensing Overview", level: 2 },
        { id: "us-licensing", title: "US Licensing Framework", level: 2 },
        { id: "eu-licensing", title: "EU Licensing (MiCA)", level: 2 },
        { id: "other-jurisdictions", title: "Other Jurisdictions", level: 2 },
        { id: "evaluating-platforms", title: "Evaluating Licensed Platforms", level: 2 },
      ]}
      faqs={[
        { question: "How can I verify if an exchange is licensed?", answer: "Most regulators maintain public registries of licensed entities. In the US, check state-level money transmitter lists and FinCEN registration. In the EU, check national regulator databases. In the UK, check the FCA register. Licensed exchanges typically display their license numbers and regulatory status on their websites." },
        { question: "Does a license guarantee safety?", answer: "A license indicates that the business has met regulatory requirements for compliance, capital, and operational standards at the time of licensing. It does not guarantee against fraud, insolvency, or hacking. However, licensed entities face ongoing supervision, reporting requirements, and potential penalties for non-compliance, which reduces (but does not eliminate) risk." },
        { question: "Why do some exchanges operate without licenses?", answer: "Some exchanges operate in jurisdictions without clear crypto licensing requirements, serve users in countries where they are not required to be licensed, or simply choose to operate without licenses (illegally in many jurisdictions). Using unlicensed exchanges carries additional counterparty risk since there is no regulatory oversight or consumer protection framework." },
      ]}
      relatedArticles={[
        { title: "Crypto Regulation Overview", href: "/learn/crypto-regulation-2026", category: "Learn" },
        { title: "AML/KYC in Crypto", href: "/learn/aml-kyc-crypto-guide", category: "Learn" },
        { title: "MiCA Regulation Guide", href: "/learn/mica-regulation-guide", category: "Learn" },
        { title: "Is Cryptocurrency Safe?", href: "/learn/is-cryptocurrency-safe", category: "Learn" },
      ]}
    >
      <section id="overview"><h2>Licensing Overview</h2><p>Crypto business licensing requirements vary significantly by jurisdiction and activity type. Common license categories include money transmitter or payment service provider licenses (for exchanges and payment processors), custodial licenses (for businesses holding customer assets), securities licenses (for platforms trading security tokens), and derivatives licenses (for futures and options platforms). Many jurisdictions are creating crypto-specific license categories.</p><p>The trend globally is toward mandatory licensing for crypto businesses, particularly those that custody customer funds or facilitate fiat-to-crypto conversion. Licensing requirements typically include capital adequacy, AML/KYC compliance infrastructure, cybersecurity standards, governance requirements, and ongoing reporting obligations. The cost and complexity of licensing varies dramatically between jurisdictions, influencing where crypto businesses choose to establish operations.</p></section>
      <section id="us-licensing"><h2>US Licensing Framework</h2><p>The US licensing landscape is complex due to its federal and state structure. At the federal level, crypto businesses must register with FinCEN as Money Services Businesses (MSBs). At the state level, most states require money transmitter licenses for crypto exchanges and payment processors. This means a nationwide US crypto business may need 40+ state licenses in addition to federal registration — a process that can take years and cost millions.</p><p>New York's BitLicense, created in 2015, was the first crypto-specific license and remains one of the most rigorous. It requires detailed compliance programs, capital requirements, and ongoing reporting. Some states have created more streamlined crypto-specific frameworks or joined the Nationwide Multistate Licensing System (NMLS) for coordinated processing. Federal legislation creating a unified licensing framework has been proposed but not yet enacted, leaving the fragmented state-by-state system in place.</p></section>
      <section id="eu-licensing"><h2>EU Licensing (MiCA)</h2><p>Under MiCA, Crypto-Asset Service Providers (CASPs) must obtain authorization from their home country's National Competent Authority. Once authorized, CASPs benefit from passporting — the ability to offer services across all EU member states without additional licenses. This is a significant advantage over the US system, providing a single license for access to a market of 450 million people across 27 countries.</p><p>MiCA authorization requires demonstrating adequate capital (varying by service type), governance arrangements, AML compliance, technology risk management, business continuity planning, and client complaint handling procedures. Existing businesses operating under national registration regimes have transitional periods to obtain full MiCA authorization. The harmonized framework provides regulatory clarity that has been attractive to crypto businesses seeking a stable operating environment in Europe.</p></section>
      <section id="other-jurisdictions"><h2>Other Jurisdictions</h2><p>Dubai (VARA — Virtual Assets Regulatory Authority) has created a dedicated crypto regulatory framework and licensing regime, attracting major exchanges. Singapore's Payment Services Act provides a clear licensing path under the Monetary Authority of Singapore. Switzerland offers a regulatory framework through FINMA that has made it a hub for crypto businesses. Offshore jurisdictions like Bermuda, Cayman Islands, and British Virgin Islands offer crypto-specific licensing with lighter requirements.</p><p>Hong Kong's SFC licensing regime targets virtual asset trading platforms. Japan's FSA registration for crypto exchanges is one of the longest-established frameworks. Each jurisdiction offers different trade-offs between regulatory rigor, market access, taxation, and operational costs, creating a competitive landscape where jurisdictions compete for crypto business activity through regulatory design.</p></section>
      <section id="evaluating-platforms"><h2>Evaluating Licensed Platforms</h2><p>When evaluating cryptocurrency platforms, consider their licensing status as one factor in your risk assessment. Verify licenses through official regulatory databases rather than trusting platform claims. Check the scope of the license — some licenses cover only specific activities, and a payment license does not necessarily mean a platform is licensed for custody or trading. Review any regulatory actions or warnings associated with the platform.</p><p>Licensed platforms generally offer stronger consumer protections, more reliable fiat on/off-ramps, and lower counterparty risk than unlicensed alternatives. However, licensing may also mean more restricted token availability (some tokens may not be listed due to regulatory concerns), mandatory KYC for all users, and higher fees to cover compliance costs. Balance regulatory protection with your specific needs when choosing platforms.</p></section>
    </LearnPageLayout>
  );
}
