import { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";

export const metadata: Metadata = { title: "Understanding Crypto Market Cycles (2026)", description: "Learn about cryptocurrency market cycles, the four phases of each cycle, historical patterns, and how to position your portfolio for each phase." };

export default function MarketCyclesPage() {
  return (
    <LearnPageLayout title="Understanding Crypto Market Cycles" categoryName="Long-Term" categorySlug="long-term" readTime="8 min"
      intro="Cryptocurrency markets move in distinct cycles of expansion and contraction, typically spanning 3-5 years. Understanding these cycles helps long-term investors set expectations, manage emotions, and make better decisions about accumulation, holding, and taking profits. While no cycle is identical, recognizable patterns have repeated across multiple cycles."
      toc={[{ id: "four-phases", title: "The Four Market Phases", level: 2 }, { id: "historical", title: "Historical Patterns", level: 2 }, { id: "positioning", title: "Positioning for Each Phase", level: 2 }, { id: "mistakes", title: "Common Cycle Mistakes", level: 2 }]}
      faqs={[
        { question: "How long do crypto market cycles last?", answer: "Historically, crypto cycles have lasted approximately 4 years, loosely correlated with Bitcoin's halving schedule. The bull phase typically lasts 12-18 months, followed by a 12-18 month bear market, with accumulation and early recovery phases filling the remaining time. However, as the market matures, cycles may evolve in duration and intensity." },
        { question: "Are we in a bull or bear market?", answer: "Market phase determination is easier in hindsight. Current indicators to consider include: price relative to the previous all-time high, on-chain metrics like active addresses and exchange flows, Bitcoin dominance trends, and macro economic conditions. Our analysis section covers current market phase indicators in detail." },
        { question: "Should I try to time crypto cycles?", answer: "While understanding cycles is valuable for setting expectations, actively timing cycles is extremely difficult and most investors who try underperform simple buy-and-hold strategies. A better approach is to use cycle awareness for gradual allocation adjustments: slightly increase DCA during deep bear markets and consider taking partial profits during euphoric bull peaks." },
      ]}
      relatedArticles={[{ title: "HODL Strategy Guide", href: "/long-term/learn/hodl-strategy", category: "Long-Term" }, { title: "Risk Management", href: "/long-term/learn/risk-management", category: "Long-Term" }]}
    >
      <h2 id="four-phases">The Four Market Phases</h2>
      <p>Crypto markets cycle through four distinct phases. The accumulation phase follows a major bear market bottom, characterized by low prices, low volatility, minimal public interest, and smart money quietly accumulating positions. This phase can last 6-12 months and feels boring. The markup phase (early bull market) sees prices begin to rise with increasing volume and public awareness. Institutional interest grows and positive news narratives develop. This is when most long-term investors see their positions move into profit. The distribution phase (late bull market) features euphoric sentiment, parabolic price movements, mainstream media coverage, and inexperienced investors flooding in. Smart money and early investors begin taking profits. The markdown phase (bear market) involves a dramatic price decline, often 70-85% from the peak, accompanied by capitulation, negative sentiment, and many participants exiting the market entirely. Understanding which phase the market is in helps calibrate your expectations and behavior.</p>

      <h2 id="historical">Historical Patterns</h2>
      <p>Bitcoin has completed several full market cycles since its inception. The 2013 cycle saw Bitcoin rise from under $15 to over $1,100 before crashing 85% to around $170 in 2015. The 2017 cycle took Bitcoin from $1,000 to nearly $20,000 before a 84% crash to $3,200 in late 2018. The 2021 cycle saw Bitcoin reach $69,000 before declining approximately 77% to $15,500 in late 2022. Each cycle has featured higher highs and higher lows, suggesting a long-term upward trend despite devastating drawdowns. Altcoin cycles tend to amplify Bitcoin's movements: altcoins underperform during early bull markets (Bitcoin dominance rises), then outperform dramatically in late bull markets (altcoin season), before crashing even harder in bear markets. Many altcoins from previous cycles never recover their highs, reinforcing the importance of focusing long-term holdings on the highest-quality assets.</p>

      <h2 id="positioning">Positioning for Each Phase</h2>
      <p>During the accumulation phase, this is the optimal time to build long-term positions through aggressive DCA. Fear is maximum, prices are depressed, and most participants have given up. Increase your regular DCA amounts if possible. During the markup phase, continue your DCA but at normal levels. Resist the urge to chase pumps or FOMO into new positions. This is the time to simply hold and let your accumulated positions appreciate. During the distribution phase, consider taking partial profits (10-30% of positions) to lock in gains. Do not try to sell the exact top, as it is impossible to identify in real-time. Set predetermined profit-taking levels based on portfolio multiples rather than price predictions. During the markdown phase, resist panic selling. If you have taken partial profits, redeploy that capital gradually as prices decline. Increase DCA amounts to take advantage of lower prices. This is where long-term wealth is built.</p>

      <h2 id="mistakes">Common Cycle Mistakes</h2>
      <p>The most costly cycle mistake is selling during the markup phase and failing to repurchase before the bull market peaks. Many investors sell early after recovering from bear market losses, missing the majority of the upside. The second most common mistake is failing to take any profits during the distribution phase, watching unrealized gains evaporate in the subsequent bear market. Third is panic selling during the markdown phase, crystallizing losses at the worst possible time. Fourth is over-investing during euphoria and under-investing during fear, the exact opposite of optimal behavior. Fifth is holding altcoins from previous cycles that never recover instead of rotating into higher-quality assets. The antidote to all these mistakes is having a written plan created during calm market conditions that specifies your DCA amounts, profit-taking levels, and rebalancing rules for each phase. Following a plan removes emotional decision-making during the most emotionally charged market moments.</p>
    </LearnPageLayout>
  );
}
