import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Head and Shoulders Pattern in Crypto Trading (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Master the head and shoulders pattern for crypto. Learn to identify, confirm, and trade this powerful reversal pattern including inverse head and shoulders setups." };

export default function Page() {
  return (<LearnPageLayout title="Head and Shoulders Pattern" categoryName="Crypto Trading" categorySlug="trading" readTime="8 min" intro="The head and shoulders pattern is considered one of the most reliable reversal patterns in technical analysis. It signals the end of an uptrend and the beginning of a downtrend (or vice versa for the inverse pattern). Learning to identify and trade this pattern accurately can significantly improve your trading results." toc={[{id:"anatomy",title:"Pattern Anatomy",level:2},{id:"identification",title:"Identifying the Pattern",level:2},{id:"trading-strategy",title:"Trading Strategy",level:2},{id:"inverse",title:"Inverse Head and Shoulders",level:2},{id:"tips",title:"Tips and Variations",level:2}]} faqs={[{question:"How reliable is the head and shoulders pattern?",answer:"Research suggests the head and shoulders pattern has a success rate of roughly 70-80% on daily timeframes when properly identified with volume confirmation. However, reliability decreases on lower timeframes and in choppy markets."},{question:"Can the right shoulder be higher than the left?",answer:"Ideally, the right shoulder is at a similar height or slightly lower than the left shoulder. A right shoulder higher than the left weakens the pattern. If the right shoulder exceeds the head, the pattern is invalidated."},{question:"What happens if the neckline is sloping?",answer:"Upward-sloping necklines make the bearish pattern less reliable because the overall structure still shows higher lows. Downward-sloping necklines make the pattern more bearish. Flat necklines are the most textbook and reliable configuration."}]} relatedArticles={[{title:"Chart Patterns Guide",href:"/trading/learn/chart-patterns-guide",category:"Trading"},{title:"Double Top Bottom Pattern",href:"/trading/learn/double-top-bottom-pattern",category:"Trading"},{title:"Support and Resistance Levels",href:"/trading/learn/support-resistance-levels",category:"Trading"}]}>
    <section id="anatomy"><h2>Pattern Anatomy</h2><p>The bearish head and shoulders consists of three peaks. The left shoulder forms as price rallies to a high point, then pulls back. The head forms as price rallies again to a higher peak, then pulls back roughly to the same level as the previous trough. The right shoulder forms as price rallies a third time but fails to reach the head's height, then declines. The neckline is drawn connecting the two troughs between the three peaks. This neckline serves as the critical support level — a break below it confirms the pattern and triggers the reversal signal. Volume typically decreases from left shoulder to head to right shoulder, showing diminishing buying interest. This declining volume is a key confirmation that the uptrend is losing momentum.</p></section>
    <section id="identification"><h2>Identifying the Pattern</h2><p>Look for the pattern after an established uptrend — it needs a preceding trend to reverse. The head must be the highest point, with both shoulders at roughly similar heights. The troughs between the peaks should be at approximately the same level to form a clear neckline. Volume should progressively decrease across the three peaks. A volume spike on the left shoulder, lower volume on the head, and even lower on the right shoulder is the ideal volume signature. The pattern can take weeks to months to form on daily charts. Do not try to identify the pattern too early — wait for the right shoulder to form and price to start declining toward the neckline before anticipating the break. Premature identification leads to many false pattern identifications.</p></section>
    <section id="trading-strategy"><h2>Trading Strategy</h2><p>The conservative entry waits for a close below the neckline with above-average volume, then enters short (or sells) on the next candle. The aggressive entry anticipates the neckline break by entering short as the right shoulder begins to decline, placing a stop above the right shoulder. After the neckline breaks, a common retest occurs where price rallies back to the neckline (now resistance) before continuing lower — this retest offers the best risk-reward entry. The measured move target equals the vertical distance from the head to the neckline, projected downward from the neckline break point. Stop-loss should be placed above the right shoulder for conservative entries or above the neckline for post-break entries. The risk-reward ratio of properly traded head and shoulders patterns is typically 2:1 or better.</p></section>
    <section id="inverse"><h2>Inverse Head and Shoulders</h2><p>The inverse (or reverse) head and shoulders is the bullish counterpart, forming at market bottoms. It consists of three troughs where the middle trough (head) is the lowest, flanked by two higher troughs (shoulders). The neckline connects the peaks between the troughs. A breakout above the neckline confirms the bullish reversal. Volume ideally increases on the breakout above the neckline, confirming buying interest. The measured move target and trading approach mirror the bearish version but inverted. Inverse head and shoulders patterns are particularly powerful signals in crypto because they often form after extended bear markets or corrections, marking the beginning of significant uptrends. They can also form on intraday charts as accumulation patterns before strong rallies.</p></section>
    <section id="tips"><h2>Tips and Variations</h2><p>The pattern does not need to be perfectly symmetrical — slight variations in shoulder height, neckline slope, and timing are normal. Complex head and shoulders patterns feature multiple left shoulders, multiple right shoulders, or multiple heads — these are less common but can be equally valid. The longer the pattern takes to form, the more significant the expected move. A head and shoulders forming over three months is a more powerful signal than one forming over three days. Failed head and shoulders (where the neckline holds and price rallies above the right shoulder) can be powerful continuation signals in the original trend direction. Always use volume and other indicators for confirmation — the pattern alone is not sufficient for high-probability trading.</p></section>
  </LearnPageLayout>);
}
