import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Bull and Bear Flag Patterns for Crypto Trading (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Learn to identify and trade bull flags and bear flags in crypto. Understand flagpoles, consolidation patterns, breakout entries, and measured move targets." };

export default function Page() {
  return (<LearnPageLayout title="Bull and Bear Flag Patterns" categoryName="Crypto Trading" categorySlug="trading" readTime="7 min" intro="Bull and bear flags are among the most reliable continuation patterns in crypto trading. They represent brief pauses in strong trends before the move resumes. Their clear structure makes them easy to identify and trade with well-defined entries, stops, and targets." toc={[
        { id: "anatomy", title: "anatomy", level: 2 },
        { id: "flag-pattern-anatomy", title: "Flag Pattern Anatomy", level: 2 },
        { id: "bull-flags", title: "bull-flags", level: 2 },
        { id: "bull-flag-patterns", title: "Bull Flag Patterns", level: 2 },
        { id: "bear-flags", title: "bear-flags", level: 2 },
        { id: "bear-flag-patterns", title: "Bear Flag Patterns", level: 2 },
        { id: "trading", title: "trading", level: 2 },
        { id: "how-to-trade-flags", title: "How to Trade Flags", level: 2 },
        { id: "pennants", title: "pennants", level: 2 },
        { id: "pennants-flag-variations", title: "Pennants: Flag Variations", level: 2 }
      ]} faqs={[{question:"What is the difference between a flag and a pennant?",answer:"Flags have parallel boundaries forming a rectangular channel during consolidation. Pennants have converging boundaries forming a small symmetrical triangle. Both are continuation patterns with similar trading approaches and measured move targets."},{question:"How long should the flag consolidation last?",answer:"Flag consolidations typically last 1-4 weeks on daily charts. The consolidation should be significantly shorter than the flagpole move. Very brief consolidations (1-2 days) may not have sufficient pattern development, while very long ones may indicate the trend is weakening."},{question:"Do flags work in crypto as well as in stocks?",answer:"Flags work exceptionally well in crypto because crypto trends tend to be strong and impulsive, creating ideal flagpole moves. The 24/7 market and high volatility produce frequent flag formations across all timeframes."}]} relatedArticles={[{title:"Chart Patterns Guide",href:"/trading/learn/chart-patterns-guide",category:"Trading"},{title:"Breakout Trading Guide",href:"/trading/learn/breakout-trading-guide",category:"Trading"},{title:"Momentum Trading Guide",href:"/trading/learn/momentum-trading-guide",category:"Trading"}]}>
    <section id="anatomy"><h2>Flag Pattern Anatomy</h2><p>Every flag pattern has two components: the flagpole and the flag. The flagpole is the strong, impulsive move that precedes the consolidation — a sharp rally for bull flags or a sharp decline for bear flags. The flag is the consolidation period where price drifts counter to the flagpole direction in a rectangular channel. In a bull flag, the flagpole is a strong upward move and the flag slopes slightly downward. In a bear flag, the flagpole is a strong downward move and the flag slopes slightly upward. Volume should be high during the flagpole and decline during the flag formation, then increase again on the breakout. The flag typically retraces 20-50% of the flagpole move. A retracement deeper than 50% weakens the pattern.</p></section>
    <section id="bull-flags"><h2>Bull Flag Patterns</h2><p>A bull flag begins with a strong upward move (flagpole) driven by significant buying volume. This is followed by a period of consolidation where price drifts lower or sideways within a slightly downward-sloping channel. The downward drift represents profit-taking by short-term traders, not a trend reversal. Volume decreases during the flag, showing that selling pressure is light. The pattern completes when price breaks above the upper boundary of the flag channel on increasing volume, resuming the upward trend. Bull flags in crypto are particularly common during the early and middle stages of bull markets, as prices advance in a series of impulsive rallies followed by shallow pullbacks. They frequently appear on altcoins after initial breakout moves.</p></section>
    <section id="bear-flags"><h2>Bear Flag Patterns</h2><p>A bear flag is the mirror image of a bull flag. It starts with a sharp downward move (flagpole) on high volume, followed by a slight upward drift in a rectangular channel. The upward drift represents short covering and tentative buying that ultimately fails. Volume decreases during the consolidation. The pattern completes when price breaks below the lower boundary of the flag channel, continuing the downtrend. Bear flags in crypto are common during market corrections and bear markets. They often form after significant news-driven selloffs when the market attempts a weak bounce before continued selling. Bear flags are generally resolved more quickly than bull flags because fear is a stronger emotion than greed, driving faster resolution of bearish patterns.</p></section>
    <section id="trading"><h2>How to Trade Flags</h2><p>Enter on the breakout from the flag — a decisive close beyond the flag boundary with above-average volume. For bull flags, buy when price closes above the upper flag boundary. For bear flags, sell or short when price closes below the lower flag boundary. Place your stop-loss at the opposite side of the flag. For a bull flag, stop below the flag's lowest point. For a bear flag, stop above the flag's highest point. The measured move target equals the flagpole length projected from the breakout point. If a bull flag's flagpole was a $5,000 move, target $5,000 above the breakout level. Take partial profits at the measured move target and trail the remainder. Alert on the flag boundaries rather than constantly watching — this allows you to set entries in advance and maintain discipline.</p></section>
    <section id="pennants"><h2>Pennants: Flag Variations</h2><p>Pennants form when the consolidation after the flagpole creates a small symmetrical triangle instead of a rectangular channel. The converging trend lines show price range compressing before the breakout. Trading approach is identical to flags — enter on the breakout with stops beyond the pennant and target the flagpole-measured move. High-tight flags are a particularly bullish variation where the flagpole gains 100%+ in a short period and the flag retraces less than 20%. These are rare but extremely powerful continuation signals in crypto, often appearing on small-cap tokens during discovery phases. Multiple flags in sequence create a staircase pattern of strong moves and consolidations — entering on each successive flag breakout while trailing stops on earlier positions can capture the full extent of a major trend move.</p></section>
  </LearnPageLayout>);
}
