import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Basis Trading Explained for Crypto (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Learn basis trading in crypto markets. Understand the cash-and-carry trade, contango, backwardation, and how to profit from the spread between spot and futures prices." };

export default function Page() {
  return (<LearnPageLayout title="Basis Trading Explained" categoryName="Crypto Trading" categorySlug="trading" readTime="8 min" intro="Basis trading exploits the price difference between spot and futures markets. When futures trade at a premium to spot (contango), the basis trade captures this premium through a market-neutral strategy. It is one of the most established arbitrage strategies in crypto and a core strategy for institutional participants." toc={[{id:"what-is-basis",title:"What Is the Basis?",level:2},{id:"cash-and-carry",title:"The Cash-and-Carry Trade",level:2},{id:"contango-backwardation",title:"Contango and Backwardation",level:2},{id:"execution",title:"Executing Basis Trades",level:2},{id:"risks",title:"Risks and Considerations",level:2}]} faqs={[{question:"What is a typical basis in crypto?",answer:"During bullish periods, the quarterly futures basis can be 5-15% annualized. During extreme euphoria, it has exceeded 30% annualized. During bearish periods, the basis compresses to near zero or turns negative (backwardation). The basis is the market's implied cost of carry and risk premium."},{question:"Is basis trading the same as funding rate arbitrage?",answer:"They are related but different. Basis trading uses quarterly futures (fixed expiration) and captures a defined premium. Funding rate arbitrage uses perpetual futures and captures variable ongoing payments. Basis trading has more predictable returns but less flexibility."},{question:"Who does basis trading?",answer:"Institutional investors, hedge funds, market makers, and sophisticated retail traders. The strategy requires significant capital for meaningful returns and understanding of futures mechanics. It is one of the most common institutional strategies in crypto markets."}]} relatedArticles={[{title:"Funding Rate Arbitrage",href:"/trading/learn/funding-rate-arbitrage",category:"Trading"},{title:"Delta Neutral Strategy",href:"/trading/learn/delta-neutral-strategy",category:"Trading"},{title:"Perpetual Futures Explained",href:"/exchanges/learn/perpetual-futures-explained",category:"Exchanges"}]}>
    <section id="what-is-basis"><h2>What Is the Basis?</h2><p>The basis is the difference between the futures price and the spot price. Basis = Futures Price - Spot Price. When futures trade above spot (positive basis), the market is in contango. When futures trade below spot (negative basis), the market is in backwardation. The basis reflects the market's expectations for future price, the cost of carry (opportunity cost of holding the asset), and the supply-demand dynamics of the futures market. In crypto, the basis is often positive during bullish periods because leveraged traders are willing to pay a premium for futures exposure. This premium represents a yield opportunity for traders willing to sell futures and buy spot. The basis converges to zero at futures expiration — this guaranteed convergence is what makes basis trading a defined-return strategy.</p></section>
    <section id="cash-and-carry"><h2>The Cash-and-Carry Trade</h2><p>The cash-and-carry trade is the classic basis trading strategy. When futures trade at a premium to spot, you buy the spot asset and simultaneously sell (short) the futures contract for the same quantity. At futures expiration, the basis converges to zero, and you close both positions. Your profit is the initial basis minus trading costs. For example, if Bitcoin spot is $50,000 and the quarterly futures price is $52,000 (4% premium), you buy 1 BTC spot and short 1 BTC quarterly futures. At expiration, regardless of where Bitcoin's price is, the futures and spot will converge. You lock in the $2,000 (4%) spread minus fees. If the quarterly expiration is 3 months away, this represents approximately 16% annualized return. The beauty of this trade is that it is market-neutral — you profit the same whether Bitcoin goes to $30,000 or $70,000.</p></section>
    <section id="contango-backwardation"><h2>Contango and Backwardation</h2><p>Contango (futures above spot) is the normal state during bullish markets. The premium reflects the cost of leveraged exposure that futures buyers are willing to pay. Higher contango = more bullish sentiment = more profitable basis trades. Contango tends to increase as expiration dates extend further into the future. Backwardation (futures below spot) occurs during bearish markets or extreme selling events. It means the market expects prices to decline or there is extreme demand for short-term spot relative to futures. In backwardation, the basis trade is reversed — you sell spot and buy futures, profiting from the negative basis converging to zero. Monitoring the term structure (the basis across different expiration dates) provides insight into market sentiment. A steepening contango curve indicates increasing bullish expectations; flattening suggests moderating sentiment.</p></section>
    <section id="execution"><h2>Executing Basis Trades</h2><p>Identify quarterly futures with meaningful basis — typically 3% or more to justify the capital deployment and trading costs. Execute both legs as simultaneously as possible to lock in the basis. Use limit orders and split execution across exchanges if necessary for better fills. Monitor the margin requirements on your short futures position throughout the trade. Some traders roll their basis trades — rather than waiting for expiration, they close the current quarter's position and open the next quarter when the new basis is attractive. This requires calculating whether the roll cost justifies the continuation. Track basis using Coinglass, Laevitas, or exchange-native analytics. Compare the annualized basis return across different assets and expiration dates to find the best opportunities. Factor in all costs: trading fees, potential margin interest, and the opportunity cost of locked capital.</p></section>
    <section id="risks"><h2>Risks and Considerations</h2><p>Margin management is critical — a sharp price increase requires additional margin on your short futures position. If you cannot meet margin calls, the short leg is liquidated, leaving you with an unhedged long spot position. Maintain sufficient margin reserves (at least 30-50% additional buffer). Counterparty risk is present on both the exchange holding your spot and the exchange hosting your futures position. Early expiration or contract changes by the exchange can disrupt the trade. Execution risk during entry and exit — if you cannot execute both legs simultaneously, temporary directional exposure exists. Basis compression — if the basis shrinks faster than expected (for example, during a sudden market downturn), your potential profit decreases, though it does not create a loss as long as you hold to expiration. Capital efficiency is low, requiring full capital for both the spot purchase and futures margin.</p></section>
  </LearnPageLayout>);
}
