import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Crypto Market Cycles Explained (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Understand crypto market cycles including accumulation, markup, distribution, and markdown phases. Learn to identify where we are in the cycle and trade accordingly." };

export default function Page() {
  return (<LearnPageLayout title="Crypto Market Cycles" categoryName="Crypto Trading" categorySlug="trading" readTime="9 min" intro="Crypto markets move in cyclical patterns driven by Bitcoin halvings, market psychology, and macroeconomic conditions. Understanding these cycles helps you position your portfolio appropriately and avoid the emotional extremes that cause most retail traders to buy tops and sell bottoms." toc={[
        { id: "four-phases", title: "four-phases", level: 2 },
        { id: "the-four-market-phases", title: "The Four Market Phases", level: 2 },
        { id: "bitcoin-halving", title: "bitcoin-halving", level: 2 },
        { id: "bitcoin-halving-cycles", title: "Bitcoin Halving Cycles", level: 2 },
        { id: "psychology", title: "psychology", level: 2 },
        { id: "market-psychology-in-each-phase", title: "Market Psychology in Each Phase", level: 2 },
        { id: "identifying-phase", title: "identifying-phase", level: 2 },
        { id: "identifying-the-current-phase", title: "Identifying the Current Phase", level: 2 },
        { id: "strategies", title: "strategies", level: 2 },
        { id: "strategies-for-each-phase", title: "Strategies for Each Phase", level: 2 }
      ]} faqs={[{question:"How long do crypto market cycles last?",answer:"Historical crypto cycles have lasted roughly 4 years, coinciding with the Bitcoin halving schedule. Bull phases typically last 12-18 months, bear phases 12-18 months, with accumulation and distribution transitions in between. However, past cycle timing does not guarantee future timing."},{question:"Are we always in one phase?",answer:"Different assets can be in different phases simultaneously. Bitcoin might be in a markup phase while a specific altcoin is in distribution. However, the overall market tends to move together, with Bitcoin leading the cycle direction."},{question:"Will crypto market cycles continue?",answer:"As the market matures and institutional participation grows, cycles may become less extreme. However, human psychology (fear and greed) drives cycles in all markets, so cyclical behavior is likely to persist, potentially with less dramatic amplitude."}]} relatedArticles={[{title:"Bull Market Strategies",href:"/trading/learn/bull-market-strategies",category:"Trading"},{title:"Bear Market Strategies",href:"/trading/learn/bear-market-strategies",category:"Trading"},{title:"Fear Greed Index Guide",href:"/trading/learn/fear-greed-index-guide",category:"Trading"}]}>
    <section id="four-phases"><h2>The Four Market Phases</h2><p>Accumulation occurs after a bear market bottom. Prices are depressed, media coverage is negative, and most retail investors have given up or are too afraid to buy. Smart money and long-term believers are quietly building positions. Prices consolidate in a range with low volatility. Markup (bull market) begins when accumulation is complete and buying pressure exceeds supply. Prices begin rising, media coverage turns positive, retail investors return, and momentum attracts more buyers in a virtuous cycle. This phase features the strongest price appreciation. Distribution occurs near market tops. Early investors and whales begin selling their positions to new buyers who are entering due to FOMO and euphoria. Prices may hit new highs but internal metrics weaken. Markdown (bear market) follows distribution as selling overwhelms buying. Prices decline, often sharply, as panic sets in and weak holders capitulate.</p></section>
    <section id="bitcoin-halving"><h2>Bitcoin Halving Cycles</h2><p>Bitcoin's supply issuance halves approximately every four years. This halving reduces the selling pressure from miners and has historically preceded major bull runs. The 2012 halving preceded a rally from $12 to $1,100. The 2016 halving preceded a rally to $20,000. The 2020 halving preceded a rally to $69,000. Each cycle has shown diminishing percentage returns but increasing absolute dollar gains. Bull markets have typically peaked 12-18 months after the halving. Bear markets have typically bottomed 12-18 months after the bull market peak. While past cycles do not guarantee future patterns, the halving cycle remains the most watched macro-level framework for predicting crypto market direction. Institutional awareness of halving cycles may front-run the traditional timing, potentially altering future cycle dynamics.</p></section>
    <section id="psychology"><h2>Market Psychology in Each Phase</h2><p>During accumulation, the dominant emotions are disbelief, apathy, and lingering fear. Headlines declare crypto dead. Social media engagement is at lows. This is when the best buying opportunities exist but few have the conviction to act. During markup, emotions shift from hope to optimism to excitement to euphoria. Each new high generates more media attention and new buyers. Social media turns overwhelmingly bullish. During distribution, greed peaks. Newcomers flood in, driven by stories of overnight wealth. Experienced traders note warning signs but the crowd dismisses bearish analysis. During markdown, emotions shift from anxiety to denial to panic to capitulation. Each bounce is sold, and eventually even the strongest believers lose hope. Understanding where market psychology is helps you position against the crowd at extremes and with the crowd during the middle of trends.</p></section>
    <section id="identifying-phase"><h2>Identifying the Current Phase</h2><p>On-chain metrics help identify the phase. MVRV ratio (market value to realized value) above 3.5 suggests overvaluation (distribution). Below 1.0 suggests undervaluation (accumulation). The Bitcoin Fear and Greed Index at extremes (above 80 or below 20) for sustained periods indicates potential phase transitions. NUPL (net unrealized profit/loss) shows what percentage of the market is in profit — extreme profit suggests distribution, extreme loss suggests accumulation. Social metrics like Google Trends for Bitcoin, social media engagement, and new exchange signups correlate with cycle phases. Technical indicators on high timeframes — Bitcoin below the 200-week moving average has historically marked accumulation phases. No single metric is definitive, but when multiple metrics align, they provide a reliable picture of the current cycle phase.</p></section>
    <section id="strategies"><h2>Strategies for Each Phase</h2><p>During accumulation, dollar-cost average into high-conviction assets. Build positions gradually as most retail investors are too afraid to buy. Focus on Bitcoin and established large-caps. During markup, hold your accumulated positions and consider rotating into higher-beta altcoins that tend to outperform during bull markets. Take partial profits at historical resistance levels and predetermined targets. During distribution, reduce exposure systematically. Take profits on altcoins first (they typically decline more in bear markets). Increase stablecoin allocation. Set trailing stops on remaining positions. During markdown, preserve capital. Avoid catching falling knives. Begin accumulating only after major capitulation events with extreme fear indicators. Hold stablecoins or earn yield on them. Each phase requires a different mindset and strategy — the mistake most traders make is using a bull market strategy in a bear market or vice versa.</p></section>
  </LearnPageLayout>);
}
