import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `MEV Explained: Maximal Extractable Value in Crypto (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Understand Maximal Extractable Value (MEV) in blockchain. Learn how MEV affects your trades, common MEV strategies, and how to protect yourself from MEV extraction." };

export default function Page() {
  return (<LearnPageLayout title="MEV Explained: Maximal Extractable Value" categoryName="Crypto Exchanges" categorySlug="exchanges" readTime="10 min" intro="Maximal Extractable Value (MEV) is the profit that can be extracted by reordering, including, or excluding transactions within a block. MEV has become a multi-billion-dollar phenomenon that directly impacts every DeFi user. Understanding MEV helps you protect your trades and make informed decisions about which networks and tools to use." toc={[{id:"what-is-mev",title:"What Is MEV?",level:2},{id:"mev-types",title:"Types of MEV",level:2},{id:"mev-supply-chain",title:"The MEV Supply Chain",level:2},{id:"impact-on-users",title:"Impact on Regular Users",level:2},{id:"protecting-yourself",title:"Protecting Yourself from MEV",level:2}]} faqs={[{question:"Does MEV only affect Ethereum?",answer:"No. MEV exists on any blockchain where transaction ordering matters and can be influenced. Ethereum has the most MEV activity, but Solana, BSC, Polygon, and other chains all have MEV extraction. The specific mechanics differ by chain."},{question:"Is MEV theft?",answer:"MEV is controversial. Some forms, like sandwich attacks, are widely considered predatory as they extract value from regular users. Other forms, like arbitrage, actually improve market efficiency by correcting price discrepancies across DEXs."},{question:"How much MEV is extracted daily?",answer:"MEV extraction on Ethereum alone has historically ranged from millions to tens of millions of dollars daily during active market periods. Cumulative MEV extraction across all chains has exceeded several billion dollars since DeFi's growth in 2020."}]} relatedArticles={[{title:"Front-Running Explained",href:"/exchanges/learn/front-running-explained",category:"Exchanges"},{title:"Sandwich Attacks Explained",href:"/exchanges/learn/sandwich-attacks-explained",category:"Exchanges"},{title:"Decentralized Exchange Guide",href:"/exchanges/learn/decentralized-exchange-guide",category:"Exchanges"}]}>
    <section id="what-is-mev"><h2>What Is MEV?</h2><p>Maximal Extractable Value (originally Miner Extractable Value) refers to the maximum profit that block producers (validators on proof-of-stake, miners on proof-of-work) can capture by manipulating the order of transactions within a block. When you submit a transaction on a blockchain, it enters the mempool — a waiting area visible to everyone. Before your transaction is included in a block, sophisticated actors (searchers) can see it and create profitable opportunities by strategically ordering their transactions around yours. This might mean front-running your large DEX trade, back-running a new pool listing, or sandwiching your swap between a buy and sell to extract value from your slippage tolerance. MEV is not a bug — it is an inherent property of any system where transaction ordering can be influenced.</p></section>
    <section id="mev-types"><h2>Types of MEV</h2><p>Arbitrage is the simplest form: when a token price differs across two DEXs, searchers submit transactions to buy on the cheaper DEX and sell on the more expensive one, profiting from the discrepancy. This form is generally considered beneficial as it improves price consistency. Liquidations occur when DeFi lending positions become undercollateralized and searchers race to liquidate them for a reward — this keeps lending protocols healthy. Front-running happens when a searcher sees your pending buy order and places their own buy before yours, profiting from the price increase your order creates. Sandwich attacks combine front-running and back-running: the attacker buys before your swap (pushing the price up), your swap executes at a worse price, then the attacker sells immediately after (pushing the price back down). Just-in-time liquidity provides concentrated liquidity to a pool right before a large swap to capture more fees.</p></section>
    <section id="mev-supply-chain"><h2>The MEV Supply Chain</h2><p>The MEV ecosystem has evolved into a sophisticated supply chain. Searchers are bots that monitor the mempool for profitable opportunities. When they find one, they construct transaction bundles — groups of transactions that must be executed in a specific order. These bundles are submitted to block builders, who assemble the most profitable possible block from available transactions and bundles. Block builders then bid to have their blocks included by validators through a mechanism called MEV-Boost on Ethereum. Validators select the highest-paying block, earning a portion of the MEV as their reward. This system, known as Proposer-Builder Separation (PBS), has centralized block building among a few sophisticated entities while distributing MEV revenue more broadly to validators. Flashbots pioneered this infrastructure and remains a key player in the MEV ecosystem.</p></section>
    <section id="impact-on-users"><h2>Impact on Regular Users</h2><p>MEV extraction costs regular DeFi users real money. Every sandwich attack results in worse execution for the victim — they receive fewer tokens from their swap than they would have without the attack. Estimates suggest that MEV extraction has cost DeFi users billions of dollars cumulatively. Front-running on popular token launches means regular buyers pay inflated prices while searchers capture the initial value. The competition for MEV also drives up gas prices during high-activity periods, making all transactions more expensive. On the positive side, MEV-driven arbitrage keeps prices consistent across DEXs, and MEV-driven liquidations prevent bad debt from accumulating in lending protocols. The net impact depends on the type of MEV — arbitrage and liquidations are generally positive externalities, while sandwich attacks and front-running are clearly harmful to users.</p></section>
    <section id="protecting-yourself"><h2>Protecting Yourself from MEV</h2><p>Use private transaction relays that bypass the public mempool. Flashbots Protect sends your transaction directly to block builders, hiding it from sandwich bots. Many wallets and DEX interfaces now integrate private transaction options by default. Set tighter slippage tolerances on your swaps — a lower slippage setting means sandwich attacks become unprofitable because the attacker cannot push the price far enough. Split large trades into smaller chunks to reduce the profit incentive for MEV extraction. Use DEX aggregators like 1inch or CoW Swap that include MEV protection features. CoW Swap specifically uses batch auctions that are resistant to sandwich attacks. On Solana, Jito's block engine creates similar MEV infrastructure. Consider timing your trades during lower-activity periods when MEV searchers are less active and gas costs are lower.</p></section>
  </LearnPageLayout>);
}
