import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Perpetual Futures Explained: Crypto's Most Traded Instrument (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Learn how perpetual futures work in crypto. Understand funding rates, mark price, leverage, and why perps are the most traded crypto derivatives." };

export default function Page() {
  return (<LearnPageLayout title="Perpetual Futures Explained" categoryName="Crypto Exchanges" categorySlug="exchanges" readTime="10 min" intro="Perpetual futures (perps) are the most heavily traded instruments in crypto, with daily volume often exceeding spot markets several times over. Unlike traditional futures, perps have no expiration date. They use a funding rate mechanism to keep prices aligned with spot markets. Understanding perps is essential for anyone interested in crypto derivatives." toc={[{id:"what-are-perps",title:"What Are Perpetual Futures?",level:2},{id:"funding-rates",title:"How Funding Rates Work",level:2},{id:"mark-vs-last",title:"Mark Price vs Last Price",level:2},{id:"trading-perps",title:"How to Trade Perps",level:2},{id:"perp-strategies",title:"Common Perp Strategies",level:2},{id:"risks",title:"Risks of Trading Perps",level:2}]} faqs={[{question:"What is the difference between perps and spot trading?",answer:"Spot trading involves buying and owning actual crypto. Perps are contracts that track crypto prices without ownership. Perps offer leverage, can be shorted easily, and have funding rates. Spot trading involves actual token custody and no funding costs."},{question:"Do I need to pay funding rates?",answer:"Funding rates are exchanged between long and short positions every 8 hours (on most exchanges). You pay funding if you're on the majority side and receive it if you're on the minority side. The rate varies based on market sentiment."},{question:"Can I hold perp positions indefinitely?",answer:"Yes, there is no expiration. However, you will accumulate funding rate costs or earnings over time. High funding rates can make long-term positions expensive. Always factor in cumulative funding costs when planning trade duration."}]} relatedArticles={[{title:"How to Use Leverage",href:"/exchanges/learn/how-to-use-leverage",category:"Exchanges"},{title:"Funding Rates Explained",href:"/exchanges/learn/funding-rates-explained",category:"Exchanges"},{title:"Crypto Derivatives Guide",href:"/exchanges/learn/crypto-derivatives-guide",category:"Exchanges"}]}>
    <section id="what-are-perps"><h2>What Are Perpetual Futures?</h2><p>Perpetual futures are derivative contracts that track the price of an underlying asset (like Bitcoin or Ethereum) without an expiration date. Invented by BitMEX in 2016, they have become the dominant trading instrument in crypto. Unlike traditional futures that expire monthly or quarterly, perps can be held indefinitely. They allow traders to go long (profit from price increases) or short (profit from price decreases) with leverage. Because perps are derivatives, you never own the underlying asset — you are simply speculating on its price movement. Settlement is in the collateral currency, typically USDT or the underlying crypto itself (coin-margined).</p></section>
    <section id="funding-rates"><h2>How Funding Rates Work</h2><p>The funding rate is the mechanism that keeps perpetual futures prices aligned with spot market prices. Every 8 hours (on most exchanges), a payment is exchanged between long and short holders. When the perp price trades above the spot price (indicating bullish sentiment), longs pay shorts. When it trades below spot, shorts pay longs. This incentivizes traders to take the opposite side when the perp deviates from spot, naturally correcting the price. Funding rates typically range from -0.1% to 0.1% per period but can spike to 0.5% or higher during extreme market conditions. Annualized, even a steady 0.01% every 8 hours compounds to roughly 10.95% per year — a significant cost for long-term position holders.</p></section>
    <section id="mark-vs-last"><h2>Mark Price vs Last Price</h2><p>Exchanges use two price references for perpetual futures. The last price is the most recent trade price on that exchange. The mark price is a composite price derived from multiple spot exchanges, designed to be manipulation-resistant. Liquidations are triggered based on the mark price, not the last price. This prevents market manipulation through flash crashes on a single exchange from triggering mass liquidations. When placing orders, you see the last price, but your liquidation calculation uses the mark price. Understanding this distinction is important because temporary wicks in the last price that do not affect the mark price will not liquidate your position, even if they briefly cross your liquidation level.</p></section>
    <section id="trading-perps"><h2>How to Trade Perps</h2><p>To trade perpetual futures, first deposit collateral into your futures account — most exchanges separate spot and futures balances. Select the trading pair (BTC/USDT Perp, for example), choose your leverage level, and decide on cross or isolated margin mode. Place a long order if you expect prices to rise or a short order for price declines. Once your position is open, monitor your unrealized PnL, margin ratio, and liquidation price. Set take-profit and stop-loss orders to manage risk. Pay attention to the funding rate countdown — if you are on the paying side, consider whether the expected move justifies the funding cost. Close your position by placing an opposite order of the same size.</p></section>
    <section id="perp-strategies"><h2>Common Perp Strategies</h2><p>Directional trading is the simplest approach — go long in an uptrend, short in a downtrend. Funding rate arbitrage involves going long on spot and short on perps (or vice versa) to capture the funding rate differential while remaining market-neutral. Basis trading exploits the difference between perp and spot prices. Hedging allows spot holders to protect their portfolio by opening short perp positions during uncertain periods without selling their actual tokens. Scalping on perps is popular due to low fees and high liquidity on major pairs. Many quantitative traders use perps for pairs trading, statistical arbitrage, and momentum strategies because of the easy shorting capability and leverage.</p></section>
    <section id="risks"><h2>Risks of Trading Perps</h2><p>Leverage amplifies losses as much as gains, and liquidation can wipe out your entire margin instantly. Funding rate costs can accumulate significantly, especially during sustained bull or bear trends when rates stay elevated. In extreme market conditions, liquidation cascades can cause rapid price drops as forced selling triggers more liquidations. Exchange risk is present — if the platform has technical issues during high volatility, you may be unable to close positions. Slippage during high-volatility events can result in fills far from your expected price. The ease of trading and leverage access can encourage overtrading and excessive risk-taking. Approach perpetual futures with strict risk management rules and position sizing discipline.</p></section>
  </LearnPageLayout>);
}
