import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `How to Recover a Crypto Wallet (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Step-by-step guide to recovering your crypto wallet using seed phrases, hardware wallet backups, and social recovery methods.",
  keywords: ["wallet recovery", "seed phrase recovery", "crypto wallet restore", "lost wallet"],
};

export default function Page() {
  return (
    <LearnPageLayout title="How to Recover a Crypto Wallet" categoryName="Crypto Wallets" categorySlug="wallets" readTime="8 min" intro="Losing access to your crypto wallet is stressful but often recoverable. Whether you lost your device, forgot your password, or need to migrate to new hardware, this guide walks you through every recovery method available for different wallet types." toc={[{id:"seed-phrase",title:"Recovery via Seed Phrase",level:2},{id:"hardware",title:"Hardware Wallet Recovery",level:2},{id:"social",title:"Social Recovery Methods",level:2},{id:"no-backup",title:"Recovery Without a Backup",level:2}]} faqs={[{question:"Can I recover my wallet without a seed phrase?",answer:"If you have no seed phrase and no access to the original device, recovery is almost always impossible for non-custodial wallets. Some wallets offer cloud backup options, and social recovery wallets like Argent allow guardian-based recovery. For custodial wallets, contact customer support for account recovery."},{question:"Is it safe to enter my seed phrase into a new wallet?",answer:"Only enter your seed phrase into the official app or website of a trusted wallet provider. Never enter it into a website you reached through an email link, search ad, or DM. Phishing sites designed to steal seed phrases are the number one cause of crypto theft."},{question:"What if I wrote my seed phrase incorrectly?",answer:"If one or two words are wrong, specialized recovery tools can sometimes brute-force the correct words since the BIP39 word list is only 2,048 words. However, these tools require technical knowledge. If many words are incorrect or the order is wrong, recovery becomes exponentially harder or impossible."}]} relatedArticles={[{title:"Seed Phrase Guide",href:"/wallets/learn/seed-phrase-guide",category:"Wallets"},{title:"Social Recovery Wallets",href:"/wallets/learn/social-recovery-wallets",category:"Wallets"},{title:"Best Hardware Wallets",href:"/wallets/best/hardware",category:"Best Of"}]}>
      <section id="seed-phrase"><h2>Recovery via Seed Phrase</h2><p>The most common recovery method uses your 12 or 24-word seed phrase. To recover, download the wallet application you want to use (it does not have to be the same wallet you originally used — any BIP39-compatible wallet works). During setup, choose the restore or import option instead of creating a new wallet. Enter your seed phrase words in the exact order they were given. The wallet will derive all your accounts and display your balances. This process works because the seed phrase is a universal standard — any wallet following BIP39 and BIP44 specifications will derive the same keys from the same phrase. After recovery, verify your addresses and balances match before using the wallet for transactions.</p></section>
      <section id="hardware"><h2>Hardware Wallet Recovery</h2><p>If your hardware wallet is lost, stolen, or damaged, you can recover using your seed phrase on a new device. Purchase a new hardware wallet from the same or different manufacturer, and during setup choose the recovery option. Enter your seed phrase, and the new device will have identical keys to the old one. For Tangem card wallets, recovery uses your backup cards rather than a seed phrase. Some hardware wallets like Trezor allow recovery through Shamir backup, where you need a minimum number of recovery shares rather than a single seed phrase. Always buy replacement hardware wallets from official sources to avoid supply chain attacks where devices arrive with pre-compromised firmware.</p></section>
      <section id="social"><h2>Social Recovery Methods</h2><p>Social recovery wallets like Argent use a different approach where designated guardians can help you regain access. If you lose your device, a majority of your chosen guardians (trusted friends, family members, or services) approve a recovery request that transfers wallet control to your new device. This eliminates seed phrase dependency entirely. The guardians cannot access your funds — they can only authorize account recovery. To initiate social recovery, install the wallet on your new device, start the recovery process, and contact your guardians to approve the request. The recovery typically involves a time delay for security, preventing instant unauthorized recovery attempts.</p></section>
      <section id="no-backup"><h2>Recovery Without a Backup</h2><p>If you have no seed phrase and no access to your wallet device, options are extremely limited. For software wallets, the encrypted key file may still exist on your device — check backup folders, old hard drives, or device backups. Some wallets store encrypted data that can be unlocked with your wallet password. For custodial wallets on exchanges, contact customer support with identity verification. Professional recovery services exist for situations like forgotten passwords with known seed phrases, but be extremely cautious of scammers posing as recovery services. No legitimate service can recover funds without either your seed phrase, encrypted key file, or device access. Anyone claiming otherwise is attempting to scam you.</p></section>
    </LearnPageLayout>
  );
}
