import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `How to Use Layer 2 Networks (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Practical guide to using Ethereum Layer 2 networks including Arbitrum, Optimism, Base, and zkSync for cheaper and faster transactions.",
  keywords: ["Layer 2", "how to use L2", "Arbitrum tutorial", "Base tutorial", "Optimism guide", "L2 DeFi"],
};

export default function HowToUseLayer2Page() {
  return (
    <LearnPageLayout title="How to Use Layer 2 Networks" categoryName="Crypto Education" categorySlug="learn" readTime="7 min" intro="Layer 2 networks extend Ethereum by processing transactions off-chain while inheriting Ethereum's security. They offer the same DeFi applications you know from mainnet but at a fraction of the cost and with faster confirmation times. This guide walks you through getting started with L2 networks."
      toc={[{ id: "overview", title: "L2 Overview", level: 2 },{ id: "getting-started", title: "Getting Started", level: 2 },{ id: "popular-l2s", title: "Popular L2 Networks", level: 2 },{ id: "bridging", title: "Bridging to L2", level: 2 },{ id: "defi-on-l2", title: "DeFi on L2", level: 2 }]}
      faqs={[
        { question: "Are Layer 2 networks safe?", answer: "Layer 2 networks inherit security from Ethereum through different mechanisms. Optimistic rollups (Arbitrum, Optimism, Base) use fraud proofs, while zk-rollups (zkSync, Starknet) use validity proofs. Both approaches ensure that L2 transactions are ultimately secured by Ethereum's consensus. The technology is well-tested with billions in value secured." },
        { question: "Which Layer 2 should I use?", answer: "Arbitrum has the largest DeFi ecosystem, Base is growing rapidly with strong Coinbase integration, and Optimism has a well-developed governance ecosystem. For most users, any of these provide a great experience. Choose based on the specific DeFi applications and liquidity available on each." },
        { question: "Can I withdraw from L2 to Ethereum?", answer: "Yes, you can always withdraw back to Ethereum mainnet. Official bridges for optimistic rollups have a 7-day withdrawal period for security. Third-party bridges offer instant withdrawals for a small fee. Zk-rollup withdrawals can be faster due to validity proofs rather than fraud proofs." },
      ]}
      relatedArticles={[
        { title: "What Is Layer 2?", href: "/learn/what-is-layer-2", category: "Learn" },
        { title: "How to Bridge Crypto", href: "/learn/how-to-bridge-crypto", category: "Learn" },
        { title: "How to Avoid Gas Fees", href: "/learn/how-to-avoid-gas-fees", category: "Learn" },
        { title: "Arbitrum Ecosystem Guide", href: "/learn/arbitrum-ecosystem-guide", category: "Learn" },
      ]}
    >
      <section id="overview"><h2>L2 Overview</h2><p>Layer 2 networks process transactions in batches off-chain and post compressed transaction data back to Ethereum. This dramatically reduces per-transaction costs while maintaining the security guarantees of Ethereum's base layer. For users, L2s feel identical to Ethereum mainnet — the same wallet addresses, the same token standards, and familiar DeFi protocols — just faster and cheaper.</p><p>The L2 ecosystem has matured significantly, with combined TVL exceeding that of many alternative L1 blockchains. Major DeFi protocols like Uniswap, Aave, and Curve are deployed across multiple L2s. The trend toward L2-centric Ethereum means that most user activity is expected to occur on L2s, with Ethereum mainnet serving primarily as a settlement and data availability layer.</p></section>
      <section id="getting-started"><h2>Getting Started</h2><p>Your existing Ethereum wallet (MetaMask, Rabby, etc.) works on all EVM-compatible L2 networks. Simply add the L2 network to your wallet — most wallets now include popular L2s by default or offer one-click addition. Your wallet address is the same across all networks, but balances are network-specific. You need to bridge assets to an L2 before using DeFi applications on that network.</p><p>The fastest way to start: many exchanges (Coinbase, Binance, Kraken) support direct withdrawals to L2 networks. Withdraw ETH directly to Arbitrum, Base, or Optimism from the exchange, skipping the Ethereum mainnet bridging step entirely. This saves time and gas fees. Once you have ETH on the L2 for gas, you can interact with any DeFi protocol on that network.</p></section>
      <section id="popular-l2s"><h2>Popular L2 Networks</h2><p>Arbitrum is the largest L2 by TVL, offering a deep DeFi ecosystem with protocols like GMX, Camelot, and Pendle in addition to established protocols like Uniswap and Aave. Optimism powers the OP Stack used by multiple chains and has a strong governance ecosystem with OP token incentives. Base, built by Coinbase using the OP Stack, has grown rapidly with a focus on consumer applications and strong on-ramp integration.</p><p>zkSync Era uses zero-knowledge proofs for faster finality and native account abstraction features. Starknet uses a different zk-proof system (STARKs) with its own programming language (Cairo). Polygon zkEVM provides another zk-rollup option. Each L2 has its own character, ecosystem, and community. Exploring multiple L2s lets you access the best opportunities across the ecosystem.</p></section>
      <section id="bridging"><h2>Bridging to L2</h2><p>To bridge from Ethereum mainnet to an L2: use the official bridge (bridge.arbitrum.io, app.optimism.io/bridge, bridge.base.org) for maximum security, or use third-party bridges (Across, Stargate, Hop) for faster processing. Connect your wallet, select the amount of ETH or tokens to bridge, and confirm the transaction. Official bridges deposit funds within minutes for L1 to L2 direction.</p><p>For bridging between L2 networks (e.g., Arbitrum to Base), third-party bridges or bridge aggregators like Jumper Exchange are necessary since official bridges only connect to Ethereum mainnet. These cross-L2 bridges typically complete within minutes and charge small fees. Always verify bridge URLs and use well-established bridging services to minimize smart contract risk.</p></section>
      <section id="defi-on-l2"><h2>DeFi on L2</h2><p>DeFi on L2 networks is functionally identical to mainnet DeFi — swapping tokens, providing liquidity, lending, borrowing, and staking all work the same way. The key difference is cost: operations that cost $20-$100 on mainnet typically cost $0.01-$0.50 on L2s. This makes strategies involving frequent transactions (compounding, active management, small trades) economically viable for the first time.</p><p>Explore the L2's native DeFi ecosystem alongside multi-chain deployments of established protocols. Each L2 has unique DeFi applications that may not be available elsewhere. Use DeFi Llama to discover protocols and compare yields across L2s. The lower transaction costs on L2s also make it practical to experiment with new protocols using small amounts, reducing the cost of learning and discovery.</p></section>
    </LearnPageLayout>
  );
}
