import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Risk Management Guide for Crypto Trading (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Master risk management for crypto trading. Learn position sizing, the 1% rule, risk-reward ratios, portfolio risk limits, and how to protect your trading capital." };

export default function Page() {
  return (<LearnPageLayout title="Risk Management Guide" categoryName="Crypto Trading" categorySlug="trading" readTime="10 min" intro="Risk management is the single most important skill in trading. It does not matter how good your analysis is — without proper risk management, a string of losses will destroy your account. This guide covers the essential risk management techniques that professional traders use to protect and grow their capital." toc={[{id:"why-risk-management",title:"Why Risk Management Matters",level:2},{id:"one-percent-rule",title:"The 1% Rule",level:2},{id:"risk-reward",title:"Risk-Reward Ratios",level:2},{id:"portfolio-risk",title:"Portfolio Risk Management",level:2},{id:"advanced",title:"Advanced Risk Techniques",level:2}]} faqs={[{question:"What percentage should I risk per trade?",answer:"Most professional traders risk 0.5-2% of their account per trade. Beginners should start at 0.5-1%. This ensures that even a string of 10 consecutive losses only draws down your account 5-10%, which is recoverable."},{question:"Is a 1:1 risk-reward ratio acceptable?",answer:"A 1:1 ratio requires a win rate above 50% to be profitable after fees. Most professional traders target at least 2:1, meaning the potential profit is twice the potential loss. This allows profitability even with a win rate below 50%."},{question:"How do I calculate my position size?",answer:"Position size = (Account Risk Amount) / (Distance to Stop Loss). If you have $10,000, risk 1% ($100), and your stop loss is 5% from entry, your position size is $100 / 0.05 = $2,000."}]} relatedArticles={[{title:"Position Sizing Guide",href:"/trading/learn/position-sizing-guide",category:"Trading"},{title:"Stop Loss Strategies",href:"/trading/learn/stop-loss-strategies",category:"Trading"},{title:"Crypto Trading Psychology",href:"/trading/learn/crypto-trading-psychology",category:"Trading"}]}>
    <section id="why-risk-management"><h2>Why Risk Management Matters</h2><p>A trader with a mediocre strategy but excellent risk management will outperform a trader with a great strategy but poor risk management over time. This is because trading is a probability game — no strategy wins every trade. Risk management ensures that inevitable losses remain small enough to survive while letting winners compound. Consider: a 50% loss requires a 100% gain just to break even. A 20% drawdown requires a 25% gain to recover. Keeping losses small and recoverable is the mathematical foundation of long-term profitability. The crypto market's extreme volatility makes risk management even more critical than in traditional markets. Moves of 10-20% in a single day are common, and without proper position sizing, these moves can devastate an unprotected portfolio.</p></section>
    <section id="one-percent-rule"><h2>The 1% Rule</h2><p>The 1% rule states that you should never risk more than 1% of your total trading capital on any single trade. With a $10,000 account, your maximum risk per trade is $100. This does not mean your position size is $100 — it means the maximum amount you can lose if the trade hits your stop-loss is $100. If your stop-loss is 5% away from entry, you can have a $2,000 position. If your stop-loss is 2% away, you can have a $5,000 position. The 1% rule ensures that even 10 consecutive losing trades only draw down your account 10% — uncomfortable but recoverable. More aggressive traders may use 2%, but exceeding 2% per trade significantly increases the risk of catastrophic drawdowns from losing streaks that are statistically inevitable over time.</p></section>
    <section id="risk-reward"><h2>Risk-Reward Ratios</h2><p>The risk-reward ratio compares your potential loss to your potential profit. A 2:1 ratio means you expect to make $2 for every $1 you risk. If your stop-loss is $100 from entry, your target should be at least $200 from entry. Higher ratios (3:1, 4:1) allow profitability with lower win rates. At 2:1, you only need to win 34% of trades to break even (before fees). At 3:1, you need just 25%. This is why chasing high win rates is less important than maintaining favorable risk-reward ratios. Always calculate your risk-reward before entering a trade. If the nearest support is $100 away (your stop) but the nearest resistance is only $80 away (your target), the risk-reward is 0.8:1 — not favorable. Wait for setups where the structure provides at least 2:1 in your favor.</p></section>
    <section id="portfolio-risk"><h2>Portfolio Risk Management</h2><p>Beyond individual trade risk, manage your total portfolio exposure. Limit the number of simultaneous positions so that if all trades hit their stops, the total loss is bearable — most professionals cap total risk at 5-10% at any given time. Diversify across uncorrelated assets — holding five positions that are all highly correlated to Bitcoin provides no diversification benefit. Set maximum daily and weekly loss limits. If you lose 3% in a day, stop trading for the day. If you lose 6% in a week, reduce position sizes or stop for the week. Never add risk to protect existing losses — this is the path to account destruction. Regularly review your overall portfolio heat (total risk across all open positions) and reduce exposure when it exceeds your predetermined limits.</p></section>
    <section id="advanced"><h2>Advanced Risk Techniques</h2><p>Scaling in and out allows you to build positions gradually, reducing timing risk. Enter with one-third of your planned position size, add another third if price confirms your thesis, and add the final third at a pullback within the trend. Take profits similarly in stages. Correlation management involves tracking the correlation between your positions — during market stress, correlations typically increase, so positions you thought were diversified may all move against you simultaneously. Use portfolio stress testing — model what happens to your total portfolio if the market drops 20%, 40%, or 60% and ensure you can survive each scenario. Risk budgeting allocates a fixed risk budget across strategies or asset classes, ensuring that one over-allocated strategy cannot damage the entire portfolio. Volatility-adjusted position sizing reduces positions in volatile markets and increases them in calm markets, maintaining consistent risk despite changing market conditions.</p></section>
  </LearnPageLayout>);
}
