import { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Impermanent Loss Explained: The Hidden DeFi Risk (${CURRENT_YEAR}) | CryptoDegen`,
  description:
    "Understand impermanent loss in DeFi liquidity pools: what causes it, how to calculate it, when it becomes permanent, and strategies to minimize its impact on your returns.",
};

export default function ImpermanentLossPage() {
  return (
    <LearnPageLayout
      title="Impermanent Loss Explained: The Hidden DeFi Risk"
      categoryName="Learn Crypto"
      categorySlug="learn"
      readTime="8 min read"
      intro="Impermanent loss is the difference in value between holding tokens in a liquidity pool versus simply holding them in your wallet. It occurs when the price ratio of the tokens in a pool changes after you deposit, causing the AMM to rebalance your position through arbitrage. Despite being called 'impermanent,' this loss can become permanent if you withdraw at a different price ratio than when you deposited. Understanding impermanent loss is essential for anyone providing liquidity in DeFi."
      toc={[
        { id: "what-is-il", title: "What Is Impermanent Loss?", level: 2 },
        { id: "how-it-happens", title: "How Impermanent Loss Happens", level: 2 },
        { id: "calculating-il", title: "Calculating Impermanent Loss", level: 2 },
        { id: "mitigation", title: "Strategies to Mitigate Impermanent Loss", level: 2 },
      ]}
      faqs={[
        {
          question: "Why is it called 'impermanent' loss?",
          answer:
            "The loss is called impermanent because if the token prices return to the exact ratio they were at when you deposited, the loss disappears. However, if you withdraw while prices are at a different ratio, the loss becomes permanent. In practice, prices rarely return to the exact original ratio, so some degree of loss is common.",
        },
        {
          question: "Can trading fees offset impermanent loss?",
          answer:
            "Yes, in many cases. Liquidity providers earn a share of all trading fees generated by the pool. For pairs with high trading volume relative to their liquidity, the accumulated fees can exceed the impermanent loss, making liquidity provision profitable overall. However, for low-volume or highly volatile pairs, impermanent loss may exceed fees earned.",
        },
        {
          question: "Which pools have the highest impermanent loss?",
          answer:
            "Pools with highly volatile, uncorrelated assets experience the most impermanent loss. For example, a pool pairing a small-cap altcoin with ETH will suffer greater impermanent loss than a stablecoin/stablecoin pool. The greater the price divergence between the two tokens, the higher the impermanent loss.",
        },
      ]}
      relatedArticles={[
        { title: "AMMs Explained", href: "/learn/amm-explained", category: "Learn" },
        { title: "What Is a DEX?", href: "/learn/what-is-a-dex", category: "Learn" },
        { title: "What Is Yield Farming?", href: "/learn/what-is-yield-farming", category: "Learn" },
        { title: "DeFi Yield Strategies", href: "/learn/defi-yield-strategies", category: "Learn" },
      ]}
    >
      <section id="what-is-il">
        <h2>What Is Impermanent Loss?</h2>
        <p>
          When you provide liquidity to an AMM pool, you deposit two tokens in a specific ratio. The AMM's pricing formula maintains a mathematical relationship between the quantities of these tokens. When external market prices change, arbitrageurs trade against the pool to bring its price in line with the market, which changes the ratio of tokens in the pool. The net effect is that you end up with more of the token that decreased in value and less of the token that increased in value.
        </p>
        <p>
          Impermanent loss measures how much less your liquidity position is worth compared to what it would have been if you had simply held the same tokens in your wallet without providing liquidity. It is a direct consequence of the AMM's constant rebalancing mechanism. The loss is purely opportunity cost — you have not actually lost money in absolute terms (assuming both token prices are higher or equal), but you would have made more by not providing liquidity.
        </p>
      </section>

      <section id="how-it-happens">
        <h2>How Impermanent Loss Happens</h2>
        <p>
          Consider a practical example: you deposit 1 ETH and 3,000 USDC into a pool when ETH is priced at $3,000. Your total deposit is worth $6,000. Now suppose ETH's price doubles to $6,000. Arbitrageurs will buy ETH from the pool (where it is cheaper) until the pool price matches the market price. After rebalancing, you might have approximately 0.707 ETH and 4,243 USDC, worth about $8,485 total.
        </p>
        <p>
          If you had simply held your original 1 ETH and 3,000 USDC, they would now be worth $9,000 (1 ETH at $6,000 plus 3,000 USDC). The difference of $515 (approximately 5.7% of the hold value) is your impermanent loss. You still made money compared to your initial deposit ($8,485 vs $6,000), but you made less than you would have by simply holding. This loss grows larger as the price divergence increases, reaching significant levels for extreme price movements.
        </p>
      </section>

      <section id="calculating-il">
        <h2>Calculating Impermanent Loss</h2>
        <p>
          For a standard constant product AMM (x * y = k), impermanent loss depends solely on the price ratio change, not the direction. A 2x price increase in either direction results in approximately 5.7% impermanent loss. A 3x change results in about 13.4%. A 5x change causes about 25.5% loss, and a 10x change causes about 42.5% loss. These percentages represent how much less your liquidity position is worth compared to a simple hold strategy.
        </p>
        <p>
          For concentrated liquidity positions, impermanent loss is amplified because the same capital is exposed to a narrower price range. A concentrated position with 10x capital efficiency experiences impermanent loss as if the capital were 10 times larger in a full-range position. This is the fundamental trade-off of concentrated liquidity: higher fee earnings in exchange for greater impermanent loss exposure. Many DeFi dashboards and calculators exist to help LPs estimate potential impermanent loss based on different price scenarios.
        </p>
      </section>

      <section id="mitigation">
        <h2>Strategies to Mitigate Impermanent Loss</h2>
        <p>
          The most effective mitigation is choosing pools where impermanent loss is naturally low. Stablecoin pools (USDC/USDT) experience minimal impermanent loss because the token prices rarely diverge significantly. Pools of correlated assets (stETH/ETH, WBTC/renBTC) similarly experience low impermanent loss. These pools offer lower yields but much more predictable returns for liquidity providers.
        </p>
        <p>
          For volatile pairs, look for pools with high trading volume relative to TVL, as this generates more fees to offset impermanent loss. Using wider ranges in concentrated liquidity positions reduces impermanent loss at the cost of lower capital efficiency. Some protocols offer impermanent loss protection through insurance mechanisms or token incentives that compensate LPs for losses. Active management — adjusting your position as prices move — can also help, though it requires more time and gas costs. Always model potential impermanent loss scenarios before committing significant capital to liquidity provision.
        </p>
      </section>
    </LearnPageLayout>
  );
}
