import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Gas Fees Explained (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Complete guide to understanding gas fees on Ethereum and EVM blockchains. Learn how gas works, EIP-1559, and strategies to pay less.",
  keywords: ["gas fees", "Ethereum gas", "EIP-1559", "gwei", "transaction fees"],
};

export default function Page() {
  return (
    <LearnPageLayout title="Gas Fees Explained" categoryName="Crypto Wallets" categorySlug="wallets" readTime="8 min" intro="Gas fees are the transaction costs paid to blockchain validators for processing and confirming your transactions. On Ethereum and EVM-compatible chains, gas is a unit measuring the computational effort required to execute operations. Understanding gas mechanics helps you optimize costs and avoid failed transactions." toc={[{id:"what-is",title:"What Is Gas?",level:2},{id:"eip1559",title:"How EIP-1559 Changed Gas Pricing",level:2},{id:"factors",title:"Factors Affecting Gas Costs",level:2},{id:"save",title:"Strategies to Save on Gas",level:2}]} faqs={[{question:"Why did my transaction fail but I still paid gas?",answer:"Gas is consumed by the computational work performed, regardless of whether the transaction succeeds. If your transaction fails due to a smart contract revert, slippage error, or insufficient token balance, the validators still performed work processing it. The gas cost for the attempted execution is non-refundable. Setting appropriate slippage tolerance and verifying balances before transacting helps prevent wasted gas."},{question:"What is gwei?",answer:"Gwei is a denomination of ETH used to express gas prices. One gwei equals 0.000000001 ETH (one billionth). Gas prices are quoted in gwei per gas unit — for example, 20 gwei means each unit of gas costs 0.00000002 ETH. A standard ETH transfer uses 21,000 gas units, so at 20 gwei it would cost 0.00042 ETH."},{question:"Are gas fees burned or paid to validators?",answer:"Since EIP-1559, gas fees have two components: a base fee that is burned (permanently removed from circulation) and a priority tip paid to validators. The burning mechanism makes ETH deflationary during high-usage periods. Validators earn the priority tip plus block rewards, while the base fee reduction benefits all ETH holders."}]} relatedArticles={[{title:"Wallet Transaction Fees",href:"/wallets/learn/wallet-transaction-fees",category:"Wallets"},{title:"How to Bridge Tokens",href:"/wallets/learn/how-to-bridge-tokens",category:"Wallets"},{title:"ERC-20 Tokens Wallet Guide",href:"/wallets/learn/erc20-tokens-wallet-guide",category:"Wallets"}]}>
      <section id="what-is"><h2>What Is Gas?</h2><p>Gas is a unit of measurement for the computational effort required to execute operations on Ethereum and EVM-compatible blockchains. Every operation — from a simple ETH transfer to a complex smart contract interaction — requires a specific amount of gas. A basic ETH transfer costs exactly 21,000 gas units, while a Uniswap swap might cost 150,000-300,000 gas units depending on complexity. The gas cost of a transaction is calculated by multiplying the gas units consumed by the gas price in gwei. Validators prioritize transactions with higher gas prices, creating a competitive market for block space. When the network is busy, gas prices rise as users bid higher to get their transactions included quickly. When demand is low, gas prices drop. This dynamic pricing mechanism ensures the network allocates its limited processing capacity to users who value it most, preventing spam while remaining accessible during quiet periods.</p></section>
      <section id="eip1559"><h2>How EIP-1559 Changed Gas Pricing</h2><p>Ethereum Improvement Proposal 1559, implemented in August 2021, fundamentally restructured Ethereum&apos;s fee market. Before EIP-1559, users submitted a single gas price as a blind bid, leading to overpayment and unpredictable costs. EIP-1559 introduced a base fee — an algorithmically determined minimum price that adjusts up or down based on block utilization. Users also set a priority fee (tip) paid to validators for faster inclusion and a max fee representing the absolute maximum they are willing to pay. If the base fee plus priority fee is less than the max fee, the user pays only the actual cost and the difference is refunded. The base fee is burned rather than paid to validators, creating a deflationary mechanism for ETH supply. This system provides better fee estimation, more predictable costs, and faster transaction inclusion. Most wallets now implement EIP-1559 by default, showing estimated fees based on current network conditions and allowing users to choose between slow, normal, and fast transaction speeds.</p></section>
      <section id="factors"><h2>Factors Affecting Gas Costs</h2><p>Several factors determine your actual transaction cost. Network congestion is the primary driver — during NFT drops, DeFi yield farming events, or market volatility, gas prices can spike tenfold within minutes. Transaction complexity matters significantly: a simple transfer costs far less than a multi-hop swap or a contract deployment. The smart contract&apos;s code efficiency also affects gas — well-optimized contracts consume less gas than poorly written ones. Token approvals add gas overhead before you can interact with a new protocol for the first time. Time of day correlates with gas costs due to global usage patterns, with US business hours typically seeing higher demand. Layer 2 networks dramatically reduce costs by batching many transactions into single mainnet submissions. The gas limit you set determines the maximum gas units your transaction can consume — setting it too low causes failures, while setting it appropriately based on transaction type prevents both failures and unexpected costs. Advanced users monitor gas patterns and time their non-urgent transactions for optimal pricing.</p></section>
      <section id="save"><h2>Strategies to Save on Gas</h2><p>The most effective gas-saving strategy is migrating activity to Layer 2 networks. Arbitrum, Optimism, Base, and zkSync offer the same smart contract functionality with fees typically 10-50 times lower than mainnet. For mainnet transactions, timing is crucial — use gas trackers like Etherscan&apos;s gas tracker, ETH Gas Station, or Blocknative to identify low-fee windows, typically on weekends or during Asian and European off-hours. Batch operations when possible: some protocols and wallets allow bundling multiple actions into a single transaction. Set reasonable max fees using EIP-1559 parameters rather than overpaying with aggressive gas settings for non-urgent transactions. For DeFi users, some protocols offer gasless transactions through meta-transactions or relayers that allow signing off-chain messages instead of paying gas directly. Avoid interacting with unoptimized contracts that waste gas — established protocols like Uniswap, Aave, and Curve are well-optimized, while newer or forked protocols may consume significantly more gas for equivalent operations. Cancel stuck transactions by sending a zero-value transaction with the same nonce and higher gas price rather than waiting indefinitely.</p></section>
    </LearnPageLayout>
  );
}
