import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Position Sizing Guide for Crypto Trading (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Learn proper position sizing for crypto trading. Master fixed-risk, percentage-based, and volatility-adjusted methods to protect your capital and maximize returns." };

export default function Page() {
  return (<LearnPageLayout title="Position Sizing Guide" categoryName="Crypto Trading" categorySlug="trading" readTime="8 min" intro="Position sizing determines how much capital to allocate to each trade and is the bridge between your trading strategy and risk management. Correct position sizing ensures that no single trade can significantly damage your account while allowing winning trades to meaningfully grow your capital." toc={[{id:"why-it-matters",title:"Why Position Sizing Matters",level:2},{id:"fixed-risk",title:"Fixed Risk Method",level:2},{id:"percentage-method",title:"Percentage-Based Method",level:2},{id:"volatility-adjusted",title:"Volatility-Adjusted Sizing",level:2},{id:"practical-examples",title:"Practical Examples",level:2}]} faqs={[{question:"Should I use the same position size for every trade?",answer:"No. Your position size should vary based on how far your stop-loss is from your entry. A wider stop requires a smaller position to maintain the same dollar risk. This keeps your risk consistent even when trade setups have different stop distances."},{question:"How do I size positions for leveraged trades?",answer:"Calculate position size based on your actual risk (margin at stake), not the total leveraged position size. If you use 10x leverage on a $1,000 margin for a $10,000 position, your risk is the $1,000 margin, which should not exceed 1-2% of your total account."},{question:"Should I increase position size after winning streaks?",answer:"Some traders use progressive sizing (increasing after wins), but this is risky. A simpler approach is to recalculate your position size based on your current account balance each time, naturally increasing sizes as your account grows and decreasing as it shrinks."}]} relatedArticles={[{title:"Risk Management Guide",href:"/trading/learn/risk-management-guide",category:"Trading"},{title:"Stop Loss Strategies",href:"/trading/learn/stop-loss-strategies",category:"Trading"},{title:"Take Profit Strategies",href:"/trading/learn/take-profit-strategies",category:"Trading"}]}>
    <section id="why-it-matters"><h2>Why Position Sizing Matters</h2><p>Position sizing is arguably more important than your entry strategy. Two traders can enter the same trades at the same prices — one makes money and the other goes broke, entirely because of how much they risked on each trade. Oversized positions amplify losses beyond what your account can sustain. Undersized positions fail to grow your account meaningfully when you are right. The goal is to find the optimal size that maximizes long-term growth while keeping drawdowns within tolerable limits. Professional traders spend far more time on position sizing than on finding the perfect entry. The Kelly Criterion, a mathematical formula for optimal bet sizing, suggests that most traders should risk even less than the mathematically optimal amount, as the psychological burden of large drawdowns causes them to deviate from their strategy.</p></section>
    <section id="fixed-risk"><h2>Fixed Risk Method</h2><p>The fixed risk method is the most straightforward and widely recommended approach. You risk a fixed percentage of your current account equity on every trade (typically 1%). The formula is: Position Size = (Account Equity x Risk Percentage) / (Entry Price - Stop Loss Price). With a $10,000 account risking 1% ($100) and a stop-loss 5% below your entry, your position size equals $100 / 0.05 = $2,000. If your next trade has a stop 2% away, the position size is $100 / 0.02 = $5,000. The beauty of this method is that it automatically adjusts position sizes based on trade setup — tighter stops allow larger positions, wider stops force smaller positions, keeping risk constant. As your account grows, absolute position sizes grow proportionally.</p></section>
    <section id="percentage-method"><h2>Percentage-Based Method</h2><p>The percentage-based method allocates a fixed percentage of your portfolio to each trade regardless of stop distance. For example, you might allocate 5% of your portfolio per position, with a maximum of 10 positions for 50% total deployment. This is simpler than the fixed risk method but does not account for the distance to your stop-loss, meaning your actual risk per trade varies. A 5% allocation with a 10% stop-loss risks 0.5% of your account. The same 5% allocation with a 50% stop-loss risks 2.5% — a significant difference. This method works better for longer-term investing where stop-losses are wider and position management is less active. For active trading, the fixed risk method is superior because it normalizes your risk across all trades.</p></section>
    <section id="volatility-adjusted"><h2>Volatility-Adjusted Sizing</h2><p>Volatility-adjusted position sizing accounts for how volatile each asset is, ensuring equal risk exposure regardless of the asset's volatility. Use the Average True Range (ATR) to measure volatility. Position Size = (Account Risk) / (ATR x Multiplier). If Bitcoin's daily ATR is $1,500 and Ethereum's is $150, an equal-risk position in Bitcoin would be much smaller than in Ethereum. The ATR multiplier determines how many ATRs away your stop-loss is — a common approach is 2x ATR. This method is particularly valuable in crypto where volatility varies enormously between assets. A small-cap altcoin might have 10x the volatility of Bitcoin, requiring 10x smaller position size to maintain equivalent risk.</p></section>
    <section id="practical-examples"><h2>Practical Examples</h2><p>Example 1: $10,000 account, 1% risk, buying ETH at $3,000 with stop at $2,850 (5% away). Risk amount: $100. Stop distance: $150 per ETH. Position size: $100 / $150 = 0.667 ETH ($2,000). Example 2: Same account, buying a small-cap token at $1.00 with stop at $0.80 (20% away). Risk amount: $100. Stop distance: $0.20 per token. Position size: $100 / $0.20 = 500 tokens ($500). Notice how the wider stop on the volatile small-cap results in a much smaller position. Example 3: With 5x leverage, $10,000 account, 1% risk, trading BTC/USDT perpetual at $50,000 with stop at $49,000 (2%). Risk amount: $100. Stop distance on margin: at 5x leverage, a 2% move means 10% of your margin. Position: $100 / 0.10 = $1,000 margin, controlling $5,000 in BTC. Always calculate your position size before entering any trade.</p></section>
  </LearnPageLayout>);
}
