import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `RSI Indicator Guide for Crypto Trading (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Master the RSI indicator for crypto trading. Learn how to use overbought/oversold levels, RSI divergences, and advanced RSI strategies for better trade timing." };

export default function Page() {
  return (<LearnPageLayout title="RSI Indicator Guide" categoryName="Crypto Trading" categorySlug="trading" readTime="9 min" intro="The Relative Strength Index (RSI) is one of the most versatile and widely used momentum indicators in crypto trading. It measures the speed and magnitude of price changes to identify overbought and oversold conditions, divergences, and trend strength. This guide covers everything from basic RSI reading to advanced trading strategies." toc={[
        { id: "what-is-rsi", title: "what-is-rsi", level: 2 },
        { id: "what-is-rsi", title: "What Is RSI?", level: 2 },
        { id: "overbought-oversold", title: "overbought-oversold", level: 2 },
        { id: "overbought-and-oversold", title: "Overbought and Oversold", level: 2 },
        { id: "divergences", title: "divergences", level: 2 },
        { id: "rsi-divergences", title: "RSI Divergences", level: 2 },
        { id: "advanced-techniques", title: "advanced-techniques", level: 2 },
        { id: "advanced-rsi-techniques", title: "Advanced RSI Techniques", level: 2 },
        { id: "strategies", title: "strategies", level: 2 },
        { id: "rsi-trading-strategies", title: "RSI Trading Strategies", level: 2 }
      ]} faqs={[{question:"What RSI setting should I use?",answer:"The default 14-period RSI works well for most timeframes. Shorter periods (7 or 9) are more sensitive and better for scalping. Longer periods (21 or 25) are smoother and better for swing trading. Stick with the default until you have a specific reason to change."},{question:"Is RSI above 70 always a sell signal?",answer:"No. In strong uptrends, RSI can remain above 70 for extended periods while price continues to rise. RSI above 70 indicates strong momentum, not necessarily a reversal. Use RSI divergence and context rather than fixed levels for reversal signals."},{question:"Can RSI predict price direction?",answer:"RSI does not predict direction; it measures momentum. However, RSI divergences (price making new highs while RSI makes lower highs) are among the most reliable reversal signals in technical analysis when combined with other confirmation."}]} relatedArticles={[{title:"MACD Indicator Guide",href:"/trading/learn/macd-indicator-guide",category:"Trading"},{title:"Bollinger Bands Guide",href:"/trading/learn/bollinger-bands-guide",category:"Trading"},{title:"Technical Analysis Basics",href:"/trading/learn/technical-analysis-basics",category:"Trading"}]}>
    <section id="what-is-rsi"><h2>What Is RSI?</h2><p>The Relative Strength Index, developed by J. Welles Wilder in 1978, measures the speed and change of price movements on a scale from 0 to 100. It compares the magnitude of recent gains to recent losses over a specified period (default 14 periods). The formula calculates the average gain and average loss over the lookback period, then transforms this ratio into the 0-100 scale. RSI above 50 indicates that average gains exceed average losses — bullish momentum. RSI below 50 indicates bearish momentum. The farther RSI moves from 50 in either direction, the stronger the momentum. RSI is classified as a momentum oscillator, meaning it oscillates between fixed boundaries and measures the velocity of price change rather than the price itself.</p></section>
    <section id="overbought-oversold"><h2>Overbought and Oversold</h2><p>Traditional interpretation defines RSI above 70 as overbought and below 30 as oversold. However, in crypto's volatile markets, these levels require nuanced interpretation. During strong trends, RSI can remain in overbought or oversold territory for extended periods — this is called embedded RSI and indicates a powerful trend. Rather than automatically selling when RSI hits 70, look for RSI to peak above 70 and then drop below it — the cross back below 70 is a more reliable sell signal. Similarly, buying when RSI crosses back above 30 (rather than at 30) confirms that selling momentum is actually fading. In strong bull markets, consider using 80/40 instead of 70/30, as RSI tends to oscillate between 40 and 80 in uptrends and 60 and 20 in downtrends.</p></section>
    <section id="divergences"><h2>RSI Divergences</h2><p>Divergences are the most powerful RSI signal. Bearish divergence occurs when price makes a higher high but RSI makes a lower high — momentum is weakening despite rising prices. This warns of a potential reversal or correction. Bullish divergence occurs when price makes a lower low but RSI makes a higher low — selling pressure is fading despite lower prices, suggesting a potential bottom. Hidden divergence confirms trend continuation: in an uptrend, price makes a higher low while RSI makes a lower low (bullish continuation). In a downtrend, price makes a lower high while RSI makes a higher high (bearish continuation). Divergences on higher timeframes (daily, weekly) are more reliable than those on lower timeframes. Always wait for price confirmation of the divergence before entering a trade — divergences can persist for extended periods before resolving.</p></section>
    <section id="advanced-techniques"><h2>Advanced RSI Techniques</h2><p>RSI support and resistance: RSI itself forms trends, support, and resistance lines. Drawing trend lines on the RSI indicator can reveal breakdowns or breakouts before they appear on the price chart. RSI failure swings are reversal patterns that form entirely within the RSI indicator. A bullish failure swing occurs when RSI drops below 30, bounces, pulls back without going below 30, then breaks above its recent high. The range shift concept recognizes that RSI operates in different ranges depending on the trend. During bull markets, RSI typically stays between 40 and 90. During bear markets, it stays between 10 and 60. Recognizing these range shifts helps identify major trend changes early. Multi-timeframe RSI analysis checks RSI alignment across timeframes — when daily, 4-hour, and 1-hour RSI all align in the same direction, the signal is more powerful.</p></section>
    <section id="strategies"><h2>RSI Trading Strategies</h2><p>The RSI bounce strategy buys when RSI crosses above 30 from below at a price support level and sells when RSI crosses below 70 from above at price resistance. Combine with candlestick patterns for entry confirmation. The RSI divergence strategy waits for a clear divergence on the daily chart, then uses a lower timeframe for precise entry timing. Place stops beyond the recent swing point that formed the divergence. The RSI trend strategy uses RSI to confirm trend direction: only take long trades when RSI is above 50 and short trades when RSI is below 50 on your primary trading timeframe. This simple filter eliminates many false signals. The RSI centerline crossover strategy treats the 50 level as a trend signal — RSI crossing above 50 is bullish, below 50 is bearish. This is less common but effective when combined with moving average alignment on the price chart.</p></section>
  </LearnPageLayout>);
}
