import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `What Is Proof of Reserves? (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Learn what proof of reserves is, how it works, why it matters after FTX, and which exchanges publish regular proof of reserves attestations." };

export default function Page() {
  return (
    <LearnPageLayout title="What Is Proof of Reserves?" categoryName="Crypto Exchanges" categorySlug="exchanges" readTime="8 min" intro="Proof of reserves (PoR) has become a critical trust indicator for crypto exchanges following the FTX collapse. It is a method for exchanges to demonstrate cryptographically that they hold sufficient assets to cover all customer deposits. Understanding PoR helps you evaluate exchange trustworthiness."
      toc={[{id:"what-is-por",title:"What Is Proof of Reserves",level:2},{id:"how-it-works",title:"How Proof of Reserves Works",level:2},{id:"why-ftx",title:"Why FTX Made PoR Essential",level:2},{id:"limitations",title:"Limitations of PoR",level:2},{id:"which-exchanges",title:"Which Exchanges Publish PoR",level:2}]}
      faqs={[{question:"Does proof of reserves mean an exchange is safe?",answer:"PoR demonstrates that assets exist to cover deposits at a point in time. It does not guarantee ongoing solvency, prevent mismanagement, or prove that liabilities are fully accounted for. It is one important indicator among many."},{question:"How can I verify my own account in a PoR?",answer:"Merkle tree-based PoR systems let you verify your account balance is included in the proof using a verification tool on the exchange's website. Your specific holdings are hashed for privacy."},{question:"How often should exchanges publish PoR?",answer:"Monthly PoR attestations are the emerging standard. Some exchanges publish more frequently. Less frequent than quarterly should raise questions."}]}
      relatedArticles={[{title:"Exchange Security Checklist",href:"/exchanges/learn/exchange-security-checklist",category:"Exchanges"},{title:"Exchange Insurance Funds",href:"/exchanges/learn/exchange-insurance-funds",category:"Exchanges"},{title:"Exchange Hacks History",href:"/exchanges/learn/exchange-hacks-history",category:"Exchanges"}]}
    >
      <section id="what-is-por"><h2>What Is Proof of Reserves</h2><p>Proof of reserves is a verification method that demonstrates a crypto exchange holds enough assets to back all customer deposits. In its simplest form, PoR involves showing that the total value of assets in the exchange's wallets equals or exceeds the total value of customer deposits. More sophisticated implementations use cryptographic techniques like Merkle trees to allow individual users to verify their account is included in the proof without revealing other users' information.</p></section>
      <section id="how-it-works"><h2>How Proof of Reserves Works</h2><p>A typical PoR process involves three steps. First, the exchange takes a snapshot of all customer balances and creates a Merkle tree data structure that cryptographically summarizes every account. Second, on-chain wallet addresses controlled by the exchange are identified and their balances are verified on the blockchain. Third, an independent auditor or the exchange itself publishes a report comparing total liabilities (customer balances) against total assets (wallet balances). The Merkle tree allows individual users to verify their account's inclusion using a verification tool without seeing other accounts.</p></section>
      <section id="why-ftx"><h2>Why FTX Made PoR Essential</h2><p>The FTX collapse in November 2022 revealed that the exchange had been misusing billions of dollars of customer funds for risky investments through its sister company Alameda Research. Customer deposits were not backed by corresponding assets, and when users tried to withdraw, FTX could not fulfill the requests. This catastrophic failure demonstrated the critical need for regular, verifiable proof that exchanges actually hold what they claim. In the aftermath, major exchanges rushed to implement and publish PoR attestations.</p></section>
      <section id="limitations"><h2>Limitations of PoR</h2><p>PoR has important limitations. It is a point-in-time snapshot — an exchange could be solvent during the attestation and insolvent the next day. PoR does not account for liabilities beyond customer deposits (loans, derivatives positions). Some implementations only prove assets without proving matching liabilities. Exchanges could temporarily borrow assets to inflate their reserves during attestation. A full proof of solvency requires both proof of reserves (assets) and proof of liabilities, ideally verified by independent third-party auditors.</p></section>
      <section id="which-exchanges"><h2>Which Exchanges Publish PoR</h2><p>Major exchanges that publish regular PoR include Binance, OKX, Bybit, Kraken, KuCoin, Gate.io, and Bitget. Coinbase, as a publicly traded company, provides financial audits instead of traditional PoR. The quality and frequency of PoR varies between exchanges. Look for third-party audited PoR with both asset and liability verification, published at least monthly, with individual account verification available to users.</p></section>
    </LearnPageLayout>
  );
}
