import { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";

export const metadata: Metadata = {
  title: "How to Earn Yield in DeFi: Complete Guide (2026)",
  description: "Learn the best ways to earn yield in DeFi including lending, staking, liquidity provision, and yield farming. Step-by-step guide for beginners and intermediate users.",
};

export default function HowToEarnYieldPage() {
  return (
    <LearnPageLayout
      title="How to Earn Yield in DeFi"
      categoryName="DeFi Lending"
      categorySlug="defi-lending"
      readTime="10 min"
      intro="DeFi offers multiple ways to earn yield on your crypto assets, from simple lending to sophisticated farming strategies. This guide covers the main yield-earning methods, their risk profiles, expected returns, and how to get started with each approach."
      toc={[
        { id: "lending", title: "lending", level: 2 },
        { id: "lending-on-protocols", title: "Lending on Protocols", level: 2 },
        { id: "liquid-staking", title: "liquid-staking", level: 2 },
        { id: "liquid-staking", title: "Liquid Staking", level: 2 },
        { id: "liquidity-provision", title: "liquidity-provision", level: 2 },
        { id: "liquidity-provision", title: "Liquidity Provision", level: 2 },
        { id: "yield-farming", title: "yield-farming", level: 2 },
        { id: "yield-farming", title: "Yield Farming", level: 2 },
        { id: "risk-comparison", title: "risk-comparison", level: 2 },
        { id: "risk-comparison", title: "Risk Comparison", level: 2 }
      ]}
      faqs={[
        { question: "What is the safest way to earn yield in DeFi?", answer: "Lending stablecoins on established protocols like Aave or Compound, or staking ETH through liquid staking protocols like Lido, are generally considered the safest DeFi yield strategies. They carry the lowest complexity and impermanent loss risk." },
        { question: "How much yield can I earn in DeFi?", answer: "Returns vary widely: lending yields 2-8% APY, liquid staking yields 3-5% APY, stablecoin LP pools yield 2-10% APY, and more aggressive farming strategies can yield 20-100%+ but with significantly higher risk." },
        { question: "Are DeFi yields sustainable?", answer: "Base yields from lending and staking come from real economic activity (borrower interest and validator rewards) and are sustainable. Token incentive yields are often temporary and decline over time as emission schedules reduce." },
      ]}
      relatedArticles={[
        { title: "What Is DeFi Lending?", href: "/defi-lending/learn/what-is-defi-lending", category: "DeFi Lending" },
        { title: "Yield Farming Guide", href: "/defi-lending/learn/yield-farming-guide", category: "DeFi Lending" },
        { title: "APY vs APR", href: "/defi-lending/learn/apy-vs-apr", category: "DeFi Lending" },
      ]}
    >
      <h2 id="lending">Lending on Protocols</h2>
      <p>The simplest way to earn yield in DeFi is lending your assets on a protocol like Aave, Compound, or Spark. You deposit assets into a lending pool and earn interest from borrowers. Yields are variable and depend on borrowing demand, but typically range from 2-8% APY for major assets. This is the lowest-risk DeFi yield strategy because there is no impermanent loss, and your principal remains intact (subject to smart contract risk).</p>

      <h2 id="liquid-staking">Liquid Staking</h2>
      <p>Liquid staking protocols like Lido and Rocket Pool let you stake ETH (or other PoS assets) and receive liquid tokens (stETH, rETH) that earn staking rewards while remaining usable in DeFi. The current ETH staking yield is approximately 3.5-4.5% APR. You can then use these liquid staking tokens as collateral on lending protocols to earn additional yield, creating a compounding strategy.</p>

      <h2 id="liquidity-provision">Liquidity Provision</h2>
      <p>Providing liquidity to DEX pools earns you a share of trading fees generated by swaps. Stablecoin pools on Curve offer 2-10% APY with minimal impermanent loss. Volatile pair pools on Uniswap V3 can generate higher returns but carry significant impermanent loss risk. Concentrated liquidity positions require active management for optimal performance.</p>

      <h2 id="yield-farming">Yield Farming</h2>
      <p>Yield farming involves chasing the highest yields by depositing into protocols that distribute governance token incentives. While advertised APYs can be extremely high (50-1000%+), these returns are often unsustainable and decline as more capital enters. Yield aggregators like Yearn automate this process, but farming still carries higher risk than simple lending or staking.</p>

      <h2 id="risk-comparison">Risk Comparison</h2>
      <p>Each yield strategy carries different risk levels. Lending is the lowest risk but offers modest returns. Liquid staking adds protocol risk but provides consistent yields. Liquidity provision adds impermanent loss risk. Yield farming adds complexity and token price risk. Always match your strategy to your risk tolerance, and diversify across multiple approaches and protocols when possible.</p>
    </LearnPageLayout>
  );
}
