import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Crypto Liquidation Explained (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Understand how liquidation works in crypto trading. Learn about liquidation prices, partial liquidation, insurance funds, and how to protect your leveraged positions." };

export default function Page() {
  return (<LearnPageLayout title="Liquidation Explained" categoryName="Crypto Trading" categorySlug="trading" readTime="7 min" intro="Liquidation occurs when a leveraged position loses enough value that the remaining margin no longer meets the maintenance requirement. The exchange forcefully closes your position to prevent further losses. Understanding liquidation mechanics is essential for anyone trading with leverage in crypto markets." toc={[
        { id: "mechanics", title: "mechanics", level: 2 },
        { id: "how-liquidation-works", title: "How Liquidation Works", level: 2 },
        { id: "calculation", title: "calculation", level: 2 },
        { id: "liquidation-price-calculation", title: "Liquidation Price Calculation", level: 2 },
        { id: "partial-full", title: "partial-full", level: 2 },
        { id: "partial-vs-full-liquidation", title: "Partial vs Full Liquidation", level: 2 },
        { id: "prevention", title: "prevention", level: 2 },
        { id: "preventing-liquidation", title: "Preventing Liquidation", level: 2 },
        { id: "after-liquidation", title: "after-liquidation", level: 2 },
        { id: "what-happens-after-liquidation", title: "What Happens After Liquidation", level: 2 }
      ]} faqs={[{question:"Can I get liquidated on spot trading?",answer:"No. Spot trading without margin or borrowing cannot be liquidated because you own the asset outright. Only margin trades, futures positions, and borrowed positions are subject to liquidation."},{question:"Do I lose everything when liquidated?",answer:"You lose the margin allocated to that position. With isolated margin, this is only the margin for that specific trade. With cross margin, your entire futures account balance is at risk. Some exchanges return a small residual amount after liquidation."},{question:"Can I add margin to avoid liquidation?",answer:"Yes. Adding margin increases your collateral, moving your liquidation price further away. However, this increases your total capital at risk. It should be a conscious risk management decision, not a panic response."}]} relatedArticles={[{title:"Margin Call Explained",href:"/exchanges/learn/margin-call-explained",category:"Exchanges"},{title:"How to Use Leverage",href:"/exchanges/learn/how-to-use-leverage",category:"Exchanges"},{title:"Leverage Trading Risks",href:"/trading/learn/leverage-trading-risks",category:"Trading"}]}>
    <section id="mechanics"><h2>How Liquidation Works</h2><p>When you open a leveraged position, you deposit margin as collateral. The exchange monitors your margin ratio — the relationship between your equity (margin plus unrealized PnL) and the maintenance margin requirement. When unrealized losses push your equity below the maintenance margin, the liquidation engine activates. The engine takes over your position and attempts to close it at the best available market price. The exchange charges a liquidation fee (typically 0.5-1.5% of position value) which goes to the insurance fund. If the position can be closed at a price better than the bankruptcy price (where your margin is exactly zero), the excess goes to the insurance fund. If the closure price is worse than the bankruptcy price, the insurance fund covers the deficit. The entire process is automated and typically completes within seconds once triggered.</p></section>
    <section id="calculation"><h2>Liquidation Price Calculation</h2><p>For a simplified long position on isolated margin: Liquidation Price = Entry Price x (1 - Initial Margin Rate + Maintenance Margin Rate). At 10x leverage (10% initial margin) with 0.5% maintenance margin: Liquidation Price = Entry x (1 - 0.10 + 0.005) = Entry x 0.905. For a $50,000 entry, liquidation occurs at approximately $45,250 — a 9.5% drop. At 50x leverage: Entry x (1 - 0.02 + 0.005) = Entry x 0.985, or approximately $49,250 — just 1.5% away. These calculations are simplified — actual liquidation prices vary by exchange due to different fee structures, funding rates, and maintenance margin tiers. Most exchanges display your exact liquidation price on the position dashboard. Always note this number before entering a trade.</p></section>
    <section id="partial-full"><h2>Partial vs Full Liquidation</h2><p>Well-designed exchanges use partial (or progressive) liquidation. Rather than closing your entire position at once, the engine reduces your position size in stages. If your margin ratio deteriorates, the engine closes a portion of the position to bring the ratio back above the maintenance level. If price continues moving against you, additional portions are closed. This approach gives traders more time to react, reduces the market impact of liquidation selling, and often preserves some of the position. Binance, Bybit, and OKX all implement progressive liquidation. Some smaller exchanges use full liquidation — closing the entire position immediately when the maintenance threshold is breached. This is more common with smaller insurance funds. Check your exchange's liquidation mechanism before trading.</p></section>
    <section id="prevention"><h2>Preventing Liquidation</h2><p>The most effective prevention is using lower leverage. At 3x leverage, you need a 30%+ adverse move before liquidation. At 10x, only 9%. Use isolated margin to limit each position's risk to its allocated margin. Set stop-loss orders well above your liquidation price — a stop at 5% loss is much better than a forced liquidation at 10% loss, especially considering liquidation fees and potential slippage. Monitor your margin ratio actively and add margin if necessary (though this increases total risk). Avoid holding positions through highly uncertain events. Reduce position size as volatility increases. Some exchanges offer auto-margin top-up features that automatically transfer balance from your spot account to prevent liquidation — use this as a safety net rather than a primary strategy. Consider using options instead of leveraged futures — buying options has defined, limited risk without liquidation possibility.</p></section>
    <section id="after-liquidation"><h2>What Happens After Liquidation</h2><p>After liquidation, your position is closed and the remaining margin (after losses and liquidation fees) may be returned to your account. With isolated margin, only the allocated margin is affected. With cross margin, your entire futures account balance may be consumed. Some exchanges implement ADL (auto-deleveraging) if the insurance fund cannot cover the deficit — profitable traders on the winning side have their positions partially reduced. Review what happened: was your stop-loss hit before liquidation? Did a sudden market move gap past your stop? Was your leverage too high for the asset's volatility? Use the liquidation as a learning experience. Adjust your risk management — lower leverage, wider stops, smaller positions. Do not immediately re-enter the market seeking revenge. Take time to analyze and improve your approach before trading again. Many successful traders have experienced liquidation early in their career and used it as the catalyst for developing proper risk management.</p></section>
  </LearnPageLayout>);
}
