import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `How to Recover Lost Crypto (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Guide to recovering lost cryptocurrency including wallet recovery, forgotten passwords, exchange recovery, and when professional help may be needed.",
  keywords: ["recover lost crypto", "wallet recovery", "lost Bitcoin", "forgotten password crypto", "crypto recovery", "seed phrase recovery"],
};

export default function HowToRecoverLostCryptoPage() {
  return (
    <LearnPageLayout title="How to Recover Lost Crypto" categoryName="Crypto Education" categorySlug="learn" readTime="7 min" intro="Losing access to cryptocurrency is unfortunately common — whether from forgotten passwords, lost seed phrases, corrupted wallet files, or exchange account issues. While not all situations are recoverable, understanding your options and acting methodically can maximize your chances of regaining access to lost funds."
      toc={[{ id: "assess", title: "Assessing Your Situation", level: 2 },{ id: "seed-phrase", title: "Seed Phrase Recovery", level: 2 },{ id: "password", title: "Password Recovery", level: 2 },{ id: "exchange", title: "Exchange Account Recovery", level: 2 },{ id: "prevention", title: "Prevention Strategies", level: 2 }]}
      faqs={[
        { question: "Can lost Bitcoin be recovered?", answer: "It depends on the situation. If you have a seed phrase or wallet backup, recovery is straightforward. If you have partial information (some seed phrase words, password hints), specialized services may help. If all key material is completely lost, recovery is typically impossible. An estimated 20% of all Bitcoin is believed to be lost permanently." },
        { question: "Should I use a crypto recovery service?", answer: "Be extremely cautious. While legitimate data recovery firms exist, the space is rife with scams targeting desperate people. Never share your complete seed phrase with anyone. Legitimate services work with encrypted wallet files or partial information — they should never need your full seed phrase." },
        { question: "Can I recover crypto sent to the wrong address?", answer: "If you sent crypto to a wrong but valid address that you do not control, recovery is generally impossible due to blockchain's irreversible nature. If you sent to a smart contract that supports recovery, the contract owner might be able to help. If you sent to the wrong network (e.g., ETH to a BSC address), recovery may be possible with technical steps." },
      ]}
      relatedArticles={[
        { title: "Self-Custody Guide", href: "/learn/self-custody-guide", category: "Learn" },
        { title: "Crypto Recovery Scams", href: "/learn/crypto-recovery-scams", category: "Learn" },
        { title: "How to Use a Hardware Wallet", href: "/learn/how-to-use-hardware-wallet", category: "Learn" },
        { title: "How to Create a Wallet", href: "/learn/how-to-create-wallet", category: "Learn" },
      ]}
    >
      <section id="assess"><h2>Assessing Your Situation</h2><p>First, determine exactly what you have lost access to and what recovery materials you still possess. Do you have: a seed phrase (partial or complete), a wallet file (encrypted or not), exchange account credentials, hardware wallet device, or any written notes about your wallet? Each piece of information opens different recovery paths. Document everything you have before attempting recovery.</p><p>Common loss scenarios include: forgotten wallet password (but have the seed phrase — easy recovery), lost seed phrase (but wallet still accessible — immediately transfer to a new wallet and create a proper backup), corrupted wallet file (data recovery services may help), lost hardware wallet (use seed phrase on a new device), and exchange account lockout (contact exchange support with identity documents).</p></section>
      <section id="seed-phrase"><h2>Seed Phrase Recovery</h2><p>If you have your complete seed phrase, recovery is straightforward: download the same wallet application (or any compatible wallet), select "Restore wallet," enter your seed phrase, and your accounts and balances will reappear. Seed phrases follow the BIP-39 standard, so any compatible wallet can restore accounts from any other compatible wallet's seed phrase.</p><p>If you have a partial seed phrase (some words missing or uncertain), the situation is more complex. For one or two missing words, brute-force recovery may be feasible — there are 2,048 possible BIP-39 words, so a few missing words can be computationally searched. Tools like BTCRecover and specialized services can attempt this. For many missing words, recovery becomes practically impossible due to the exponential growth in combinations.</p></section>
      <section id="password"><h2>Password Recovery</h2><p>If you have an encrypted wallet file but forgot the password, recovery depends on the encryption strength and any information you remember about the password. Password cracking tools (like hashcat or John the Ripper) can attempt to recover passwords, especially if you remember partial information (approximate length, characters used, patterns). The success probability depends on the wallet's encryption method and your password's complexity.</p><p>Some wallet applications have weaker encryption than others, making password recovery more feasible. Bitcoin Core wallets, Electrum wallets, and various mobile wallet backups each have different recovery approaches. If you remember anything about the password (length, characters, language, pattern), provide this information to narrow the search space. Professional services specializing in wallet password recovery (KeychainX, Wallet Recovery Services) may help but always verify their legitimacy thoroughly first.</p></section>
      <section id="exchange"><h2>Exchange Account Recovery</h2><p>If you have lost access to an exchange account, contact the exchange's support team with identity verification documents. Most regulated exchanges have account recovery procedures that involve verifying your identity through KYC documents, email verification, and sometimes video verification. This process can take days to weeks depending on the exchange and the complexity of your case.</p><p>If the exchange no longer exists (shutdown, bankruptcy), your options are limited. In some cases (like Mt. Gox or FTX), bankruptcy proceedings may eventually return some portion of funds to creditors. Monitor official communications from bankruptcy trustees. Register as a creditor if applicable. For exchanges that simply disappeared (exit scams), recovery is unlikely, and you should report the incident to law enforcement.</p></section>
      <section id="prevention"><h2>Prevention Strategies</h2><p>The best recovery strategy is prevention: create multiple secure backups of your seed phrase on durable physical media, store them in separate secure locations, test your recovery process before it matters, and maintain updated records of all wallets and their associated recovery materials. Use a password manager for exchange and wallet passwords, with its own secure backup.</p><p>Consider creating a recovery document that lists all your crypto accounts, wallet types, and where backups are stored — without including the actual seed phrases or passwords. Store this document securely as a guide for recovery. For significant holdings, establish a dead man's switch or inheritance plan that ensures trusted individuals can access your crypto in an emergency while preventing unauthorized access during normal circumstances.</p></section>
    </LearnPageLayout>
  );
}
