import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Covered Call Strategy for Crypto (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Learn the covered call strategy for crypto. Generate income from your holdings by selling call options while understanding the tradeoffs and optimal conditions." };

export default function Page() {
  return (<LearnPageLayout title="Covered Call Strategy" categoryName="Crypto Trading" categorySlug="trading" readTime="7 min" intro="The covered call is one of the most popular options strategies for crypto holders. It generates income from assets you already own by selling call options against your position. While it limits upside potential, it provides a consistent yield that can significantly boost returns over time." toc={[
        { id: "how-it-works", title: "how-it-works", level: 2 },
        { id: "how-covered-calls-work", title: "How Covered Calls Work", level: 2 },
        { id: "strike-selection", title: "strike-selection", level: 2 },
        { id: "choosing-the-strike-price", title: "Choosing the Strike Price", level: 2 },
        { id: "returns", title: "returns", level: 2 },
        { id: "expected-returns", title: "Expected Returns", level: 2 },
        { id: "when-to-use", title: "when-to-use", level: 2 },
        { id: "when-to-use-covered-calls", title: "When to Use Covered Calls", level: 2 },
        { id: "risks", title: "risks", level: 2 },
        { id: "risks-and-tradeoffs", title: "Risks and Tradeoffs", level: 2 }
      ]} faqs={[{question:"Can I lose money with covered calls?",answer:"You cannot lose money on the option itself since you own the underlying. However, if the asset's price declines, your loss on the spot position can exceed the premium earned. The covered call reduces your breakeven by the premium received but does not eliminate downside risk."},{question:"What happens if the price exceeds my strike?",answer:"If the price exceeds your strike at expiration, your asset will be called away (sold at the strike price). You keep the premium plus the profit from entry to the strike price. You miss any gains above the strike. This is the main tradeoff of covered calls."},{question:"How often should I sell covered calls?",answer:"Most crypto covered call traders sell weekly or monthly options. Weekly options generate more total premium due to faster time decay but require more active management. Monthly options are less work and provide smoother income."}]} relatedArticles={[{title:"Crypto Options Basics",href:"/trading/learn/crypto-options-basics",category:"Trading"},{title:"Straddle Strategy Crypto",href:"/trading/learn/straddle-strategy-crypto",category:"Trading"},{title:"Delta Neutral Strategy",href:"/trading/learn/delta-neutral-strategy",category:"Trading"}]}>
    <section id="how-it-works"><h2>How Covered Calls Work</h2><p>A covered call combines two positions: holding the underlying crypto asset (long spot) and selling (writing) a call option against it. When you sell the call, you receive the premium immediately. If the price stays below the strike at expiration, the option expires worthless and you keep both the asset and the premium — pure income. If the price rises above the strike, the option buyer exercises their right and you sell your asset at the strike price. You keep the premium but miss gains above the strike. The premium you receive effectively lowers your cost basis and provides a buffer against small declines. This makes covered calls attractive for holders who want to generate yield from their positions during periods of sideways or moderately bullish price action.</p></section>
    <section id="strike-selection"><h2>Choosing the Strike Price</h2><p>Higher strikes (further out-of-the-money) have lower premiums but less probability of being called away. You retain more upside potential. This is conservative — you earn less income but are less likely to have to sell your asset. Lower strikes (closer to the current price) have higher premiums but greater probability of being called away. This is aggressive — you earn more income but accept a higher chance of selling your asset. A common approach is selling calls 10-20% above the current price with 2-4 weeks to expiration. This balances premium income with a reasonable probability of keeping your asset. Use the delta of the option as a guide — an option with 0.20 delta has approximately a 20% chance of expiring in-the-money. Most covered call strategies target 0.15-0.30 delta strikes.</p></section>
    <section id="returns"><h2>Expected Returns</h2><p>The premium collected depends on implied volatility, time to expiration, and how far the strike is from the current price. In crypto, elevated implied volatility means covered call premiums are significantly higher than in traditional markets. A 10% out-of-the-money monthly BTC call might generate 2-5% in premium, annualizing to 24-60%. During periods of very high IV, premiums can be even larger. These returns are additive to any appreciation in the underlying asset (up to the strike). Over a full year of consistent covered call writing, the cumulative premium can significantly boost total returns. However, in strong bull markets, the opportunity cost of capped upside may exceed the premium earned. The strategy performs best when markets are flat to moderately bullish.</p></section>
    <section id="when-to-use"><h2>When to Use Covered Calls</h2><p>Covered calls work best when you are neutral to moderately bullish on the asset, not expecting a massive upside move. They excel during periods of high implied volatility (you collect more premium) and low realized volatility (price is less likely to exceed your strike). They are ideal for long-term holders who want to generate income from their position. Use them during distribution phases of market cycles when upside is limited. Avoid selling covered calls just before known catalysts (protocol upgrades, ETF decisions) that could cause large moves, as the risk of being called away increases dramatically. Consider selling calls after a significant rally when IV spikes and the probability of continued sharp upside decreases.</p></section>
    <section id="risks"><h2>Risks and Tradeoffs</h2><p>The primary tradeoff is capped upside. If Bitcoin rallies 50% and your call is at a 10% strike, you miss 40% of the move while earning perhaps 3% in premium. This opportunity cost is the biggest drawback. Downside risk is not eliminated — the premium provides a small buffer, but if the asset declines significantly, you still suffer the loss (reduced by the premium received). Assignment risk means you might have to sell your asset unexpectedly if it reaches the strike before you planned to exit. If you have to sell, you may face tax implications on the capital gain. In crypto, rapid overnight moves can push price well past your strike between monitoring sessions. If you do not want to sell your underlying position, be prepared to roll the option (buy back the current call and sell a new one at a higher strike or later date) if price approaches your strike. Rolling has a cost that reduces net premium earned.</p></section>
  </LearnPageLayout>);
}
