import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `What Is OTC Crypto Trading? (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Learn about OTC (over-the-counter) crypto trading. Understand how large block trades work, OTC desk services, pricing, and when to use OTC instead of exchanges." };

export default function Page() {
  return (<LearnPageLayout title="What Is OTC Crypto Trading?" categoryName="Crypto Exchanges" categorySlug="exchanges" readTime="8 min" intro="OTC (over-the-counter) trading allows large cryptocurrency transactions to be executed privately, off the public order book. OTC desks serve institutional investors, high-net-worth individuals, and companies that need to buy or sell significant amounts of crypto without causing market impact." toc={[
        { id: "otc-basics", title: "otc-basics", level: 2 },
        { id: "otc-trading-basics", title: "OTC Trading Basics", level: 2 },
        { id: "how-it-works", title: "how-it-works", level: 2 },
        { id: "how-otc-trading-works", title: "How OTC Trading Works", level: 2 },
        { id: "otc-vs-exchange", title: "otc-vs-exchange", level: 2 },
        { id: "otc-vs-exchange-trading", title: "OTC vs Exchange Trading", level: 2 },
        { id: "who-uses-otc", title: "who-uses-otc", level: 2 },
        { id: "who-uses-otc-desks", title: "Who Uses OTC Desks", level: 2 },
        { id: "finding-otc", title: "finding-otc", level: 2 },
        { id: "finding-an-otc-desk", title: "Finding an OTC Desk", level: 2 }
      ]} faqs={[{question:"What is the minimum trade size for OTC?",answer:"Most OTC desks have minimum trade sizes between $50,000 and $100,000, though some serve trades as low as $10,000. Institutional desks may require $1 million minimum. The specific minimum depends on the desk and the asset."},{question:"Are OTC prices better than exchange prices?",answer:"For large orders, yes. OTC desks provide a single price for the entire block trade, avoiding the slippage you would face executing a large order on an exchange. The OTC spread is typically competitive with or better than the effective spread of a large exchange order."},{question:"Is OTC trading safe?",answer:"OTC trading through reputable desks attached to major exchanges (Coinbase Prime, Kraken OTC, Binance OTC) is generally safe. However, peer-to-peer OTC carries counterparty risk. Always use established, regulated OTC providers for significant transactions."}]} relatedArticles={[{title:"Liquidity Explained",href:"/exchanges/learn/liquidity-explained",category:"Exchanges"},{title:"Dark Pools in Crypto",href:"/exchanges/learn/dark-pools-crypto",category:"Exchanges"},{title:"Slippage Explained",href:"/exchanges/learn/slippage-explained",category:"Exchanges"}]}>
    <section id="otc-basics"><h2>OTC Trading Basics</h2><p>Over-the-counter trading refers to buying or selling cryptocurrency directly between two parties, outside of public exchange order books. In traditional finance, OTC markets have existed for decades, handling large block trades of stocks and bonds. In crypto, OTC desks serve a similar function — facilitating large transactions that would be impractical or too costly to execute on exchanges. The key advantage of OTC is price certainty for large orders. If you need to buy $10 million in Bitcoin, placing that order on an exchange would push the price up significantly (slippage). An OTC desk quotes you a fixed price for the entire amount, executing the trade as a single block at an agreed-upon rate.</p></section>
    <section id="how-it-works"><h2>How OTC Trading Works</h2><p>The OTC process typically follows these steps. The client contacts an OTC desk and requests a quote for a specific amount and direction (buy or sell). The desk provides a two-sided quote with a bid and ask spread — typically tighter than what you would get executing the equivalent order on an exchange. If the client accepts, the trade is locked in at the quoted price. Settlement can be immediate (on exchange OTC portals) or follow a T+1 or T+2 schedule for larger trades. Some desks offer streaming prices via API for clients who trade frequently. The desk manages the risk by sourcing liquidity from multiple venues, market making, and hedging. Larger desks can handle trades of $100 million or more without significant market impact.</p></section>
    <section id="otc-vs-exchange"><h2>OTC vs Exchange Trading</h2><p>Exchange trading is public, transparent, and self-service, but large orders suffer from slippage and market impact. A $5 million market buy of BTC on an exchange might push the price up 0.5-1%, resulting in an average fill price well above the current market. OTC trades are private, negotiated, and settled at a single agreed price. The OTC spread (typically 0.1-0.5% for major assets) compensates the desk for providing this service. OTC is preferable for trades above $50,000-$100,000 where exchange slippage would exceed the OTC spread. For smaller trades, exchanges are more convenient and cost-effective. OTC trades also do not create visible market activity on exchanges, which is important for traders who do not want to signal their intentions to the market.</p></section>
    <section id="who-uses-otc"><h2>Who Uses OTC Desks</h2><p>Institutional investors (hedge funds, family offices, pension funds) use OTC to enter and exit large positions without market impact. Crypto-native funds and trading firms use OTC for portfolio rebalancing and large directional trades. Corporations buying Bitcoin for treasury (like MicroStrategy) use OTC to accumulate billions without moving the market. Mining companies use OTC to sell mined Bitcoin in large blocks. High-net-worth individuals converting significant fiat to crypto prefer OTC for both execution quality and privacy. Even smaller traders use OTC for large stablecoin conversions or for buying tokens not well-listed on exchanges. Some OTC desks also facilitate token sales and unlock events for crypto projects.</p></section>
    <section id="finding-otc"><h2>Finding an OTC Desk</h2><p>Major exchanges offer integrated OTC services: Coinbase Prime, Kraken OTC, Binance OTC Portal, and Gemini OTC. These are the safest options as they operate within regulated frameworks. Independent OTC desks like Cumberland (a DRW subsidiary), Circle Trade, and Galaxy Digital serve institutional clients with dedicated relationship managers and custom execution strategies. For smaller OTC trades ($10,000-$100,000), some platforms like Kraken offer OTC-like functionality through dark pool order types. When choosing an OTC desk, evaluate their spread competitiveness, settlement speed, supported assets, regulatory status, and counterparty risk. Always verify the reputation and track record of any OTC provider before transacting significant amounts.</p></section>
  </LearnPageLayout>);
}
