import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `How to Add Custom Tokens to Your Wallet (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Step-by-step guide to adding custom ERC-20, SPL, and other tokens to crypto wallets. Learn how to find contract addresses and avoid scam tokens.",
  keywords: ["add custom token", "import token", "contract address", "ERC-20 token"],
};

export default function Page() {
  return (
    <LearnPageLayout title="How to Add Custom Tokens to Your Wallet" categoryName="Crypto Wallets" categorySlug="wallets" readTime="6 min" intro="Most wallets automatically detect popular tokens, but newer or less common tokens may not appear in your balance. Adding custom tokens requires the token contract address and a few simple steps. This guide covers the process for major wallets and teaches you how to verify legitimate tokens." toc={[
        { id: "why-add", title: "why-add", level: 2 },
        { id: "why-you-need-to-add-tokens-manually", title: "Why You Need to Add Tokens Manually", level: 2 },
        { id: "find-address", title: "find-address", level: 2 },
        { id: "finding-the-contract-address", title: "Finding the Contract Address", level: 2 },
        { id: "add-evm", title: "add-evm", level: 2 },
        { id: "adding-tokens-on-evm-wallets", title: "Adding Tokens on EVM Wallets", level: 2 },
        { id: "verify", title: "verify", level: 2 },
        { id: "verifying-legitimate-tokens", title: "Verifying Legitimate Tokens", level: 2 }
      ]} faqs={[{question:"Why does my token not show up automatically?",answer:"Wallets maintain curated token lists of popular assets. New, low-cap, or niche tokens may not be on these lists yet. Your tokens are still in your wallet — they just need to be added to the display. Adding the contract address tells the wallet to look for and show that specific token."},{question:"Is it safe to add any token contract?",answer:"Adding a token to your display is safe — it only tells your wallet to show the balance. However, interacting with scam tokens (trying to sell or approve them) can be dangerous. Scam tokens may contain malicious smart contract code that triggers wallet draining when you attempt to swap them. Never interact with tokens you did not expect to receive."},{question:"Do I need to add tokens on every chain separately?",answer:"Yes. Tokens on different chains have different contract addresses. USDC on Ethereum has a different contract than USDC on Polygon or Arbitrum. You need to add the correct contract address for each chain where you hold the token."}]} relatedArticles={[{title:"ERC-20 Tokens Wallet Guide",href:"/wallets/learn/erc20-tokens-wallet-guide",category:"Wallets"},{title:"Wallet Drainer Scams",href:"/wallets/learn/wallet-drainer-scams",category:"Wallets"},{title:"Gas Fees Explained",href:"/wallets/learn/gas-fees-explained",category:"Wallets"}]}>
      <section id="why-add"><h2>Why You Need to Add Tokens Manually</h2><p>When you receive tokens that are not on your wallet&apos;s default token list, they exist in your address on the blockchain but your wallet does not display them. This is a display issue, not a security issue — the tokens are safely in your address regardless of whether the wallet shows them. Wallets maintain curated lists of established tokens to avoid cluttering your interface with thousands of obscure assets or spam tokens. To see unlisted tokens, you manually add them using the token&apos;s smart contract address. This tells the wallet exactly which contract to query for your balance. The process is simple and reversible — you can remove manually added tokens from your display at any time without affecting the actual token balance on-chain.</p></section>
      <section id="find-address"><h2>Finding the Contract Address</h2><p>The safest way to find a token&apos;s contract address is through the project&apos;s official documentation or verified sources. CoinGecko and CoinMarketCap list contract addresses for thousands of tokens across multiple chains. Block explorers like Etherscan, Arbiscan, and Polygonscan provide verified contract information with checkmarks for legitimate projects. Always cross-reference the contract address from multiple sources before adding it. Never use contract addresses from social media posts, direct messages, or unverified websites — scammers create fake tokens with identical names and symbols that redirect transactions to their own contracts. The contract address is the definitive identifier, not the token name or symbol, since multiple tokens can share the same name.</p></section>
      <section id="add-evm"><h2>Adding Tokens on EVM Wallets</h2><p>In MetaMask, click Import Tokens at the bottom of the token list, paste the contract address, and MetaMask will auto-fill the token symbol and decimals. Click Add Custom Token to confirm. In Trust Wallet, tap the toggle icon on the main screen, search for the token, or tap Add Custom Token and enter the contract address along with the network. In Rabby, tokens are often auto-detected, but you can manually add them through the token management settings. For Coinbase Wallet, tap Receive, search for the token, and if it does not appear, use the custom token option with the contract address. The process is similar across most EVM wallets — paste the contract address, verify the auto-filled details match your expectations, and confirm the addition.</p></section>
      <section id="verify"><h2>Verifying Legitimate Tokens</h2><p>Before adding or interacting with any token, verify its legitimacy. Check that the contract address matches what the project&apos;s official website lists. Look for the verified checkmark on block explorers like Etherscan. Examine the token&apos;s holder distribution — legitimate tokens have thousands of holders, while scam tokens may have very few. Check if the contract is verified on the block explorer, meaning the source code has been published for public review. Be extremely cautious with tokens that appear in your wallet unexpectedly — airdropped tokens are frequently used as bait in wallet drainer scams. If you did not buy or earn a token, do not try to sell or interact with it. Simply hide it in your wallet display and ignore it.</p></section>
    </LearnPageLayout>
  );
}
