import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Market Making Explained for Crypto (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Understand how market making works in crypto. Learn about bid-ask spreads, inventory management, automated market making, and the risks of providing liquidity." };

export default function Page() {
  return (<LearnPageLayout title="Market Making Explained" categoryName="Crypto Trading" categorySlug="trading" readTime="8 min" intro="Market makers provide liquidity by simultaneously quoting buy and sell prices, profiting from the bid-ask spread. They are essential to functioning markets, enabling other traders to buy and sell at any time. Understanding market making reveals how exchanges work and provides insight into a strategy used by some of the most successful participants in crypto." toc={[
        { id: "what-is-mm", title: "what-is-mm", level: 2 },
        { id: "what-is-market-making", title: "What Is Market Making?", level: 2 },
        { id: "how-it-works", title: "how-it-works", level: 2 },
        { id: "how-market-making-works", title: "How Market Making Works", level: 2 },
        { id: "inventory-management", title: "inventory-management", level: 2 },
        { id: "inventory-management", title: "Inventory Management", level: 2 },
        { id: "amm-vs-traditional", title: "amm-vs-traditional", level: 2 },
        { id: "amm-vs-traditional-market-making", title: "AMM vs Traditional Market Making", level: 2 },
        { id: "retail-approaches", title: "retail-approaches", level: 2 },
        { id: "approaches-for-retail-traders", title: "Approaches for Retail Traders", level: 2 }
      ]} faqs={[{question:"Can individual traders be market makers?",answer:"Technically yes, but competing with professional market-making firms is extremely difficult. They have faster infrastructure, better pricing models, and more capital. Individual traders can participate in AMM-based market making on DEXs more easily, though impermanent loss is a consideration."},{question:"How much do market makers earn?",answer:"Professional market makers on major crypto exchanges earn from the bid-ask spread, which can be 0.01-0.1% per trade on liquid pairs. With billions in daily volume, even tiny spreads generate substantial revenue. They also benefit from exchange rebates for providing liquidity."},{question:"Is market making risky?",answer:"Yes. The primary risk is adverse selection — trading against informed traders who know the price is about to move. Market makers can accumulate inventory in a losing direction. Managing this inventory risk is the central challenge of market making."}]} relatedArticles={[{title:"Liquidity Explained",href:"/exchanges/learn/liquidity-explained",category:"Exchanges"},{title:"How to Read Order Book",href:"/exchanges/learn/how-to-read-order-book",category:"Exchanges"},{title:"AMM Explained",href:"/exchanges/learn/amm-explained",category:"Exchanges"}]}>
    <section id="what-is-mm"><h2>What Is Market Making?</h2><p>Market making is the practice of continuously providing buy and sell orders on an exchange, earning the bid-ask spread as compensation for providing liquidity. A market maker simultaneously posts a bid (offer to buy) at a slightly lower price and an ask (offer to sell) at a slightly higher price. When both sides of the quote fill, the market maker profits the difference. For example, posting a bid at $49,990 and an ask at $50,010 for Bitcoin yields $20 per BTC when both sides execute. Market makers serve a crucial function — without them, traders would face wider spreads, less liquidity, and more difficulty executing at fair prices. In return, market makers earn the spread and often receive reduced fees or rebates from exchanges.</p></section>
    <section id="how-it-works"><h2>How Market Making Works</h2><p>Professional market makers use algorithms that continuously calculate fair value based on multiple data sources and adjust their quotes accordingly. The algorithm considers the current mid-market price across multiple venues, recent order flow and trade direction, order book depth and imbalance, correlation with other assets, and volatility. Quotes are updated multiple times per second. When conditions change (a large trade shifts the price, volatility increases, or correlated assets move), the market maker widens the spread to compensate for increased risk or temporarily withdraws from the market entirely. The profit per trade is tiny — often a few basis points — but across thousands of trades per day, it accumulates into substantial revenue. The key skill is managing the risk of accumulating inventory in a direction that turns unprofitable.</p></section>
    <section id="inventory-management"><h2>Inventory Management</h2><p>The biggest challenge in market making is inventory risk. When a market maker buys more than they sell, they accumulate long inventory. If the price drops, this inventory loses value. Conversely, selling more than buying creates short inventory that loses value if the price rises. Professional market makers use several techniques to manage inventory: skewing quotes (adjusting bid and ask prices to encourage trades that reduce inventory), hedging on other exchanges (offsetting accumulated positions), imposing position limits that trigger more aggressive inventory reduction, and using correlation-based hedging (offsetting Bitcoin inventory with Ethereum positions, for example). The goal is to end each day with minimal directional exposure while having earned spread income throughout the day.</p></section>
    <section id="amm-vs-traditional"><h2>AMM vs Traditional Market Making</h2><p>Automated Market Makers on DEXs democratized market making by allowing anyone to provide liquidity through simple deposits. Traditional market makers actively manage quotes, adjust spreads, and control inventory. AMM liquidity providers passively deposit assets and earn fees based on their pool share. Traditional market makers earn the spread they set. AMMs have a mathematically determined spread based on the pool's constant product formula. Traditional market makers can withdraw from the market during extreme conditions. AMM liquidity is always available. The tradeoff for AMM simplicity is impermanent loss — the automatic rebalancing that occurs as prices move. Traditional market makers can avoid this through active management. For most individual participants, providing liquidity on AMMs is more accessible than running a traditional market-making operation.</p></section>
    <section id="retail-approaches"><h2>Approaches for Retail Traders</h2><p>While competing with professional market makers on order books is impractical, retail traders can participate through DEX liquidity provision. Choose pools with high volume and fee tiers that compensate for impermanent loss risk. Concentrated liquidity on Uniswap v3 allows tighter ranges for higher fee capture but requires more active management. Hummingbot is an open-source market-making bot that individual traders can configure for order book market making, though profitability on major pairs competing against professionals is challenging. Grid trading is essentially a simplified form of market making — placing orders at regular intervals on both sides of the market. Some exchanges offer market maker programs with fee rebates for qualified participants who maintain quote obligations. Understanding market making principles improves all trading by deepening your understanding of order flow, liquidity, and market microstructure.</p></section>
  </LearnPageLayout>);
}
