import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Account Abstraction Wallets Explained (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Learn how account abstraction (ERC-4337) transforms crypto wallets with gas sponsorship, batched transactions, session keys, and social recovery.",
  keywords: ["account abstraction", "ERC-4337", "smart account", "gas sponsorship", "session keys"],
};

export default function Page() {
  return (
    <LearnPageLayout title="Account Abstraction Wallets Explained" categoryName="Crypto Wallets" categorySlug="wallets" readTime="9 min" intro="Account abstraction is a fundamental upgrade to how Ethereum wallets work, replacing rigid externally owned accounts with programmable smart accounts. This enables features previously impossible: gas sponsorship, batched transactions, social recovery, spending limits, and session keys. It represents the biggest leap in wallet usability since MetaMask." toc={[{id:"what-is",title:"What Is Account Abstraction?",level:2},{id:"erc4337",title:"ERC-4337 Standard",level:2},{id:"features",title:"Key Features Enabled",level:2},{id:"wallets",title:"Wallets Using Account Abstraction",level:2}]} faqs={[{question:"Do I need ETH for gas with account abstraction?",answer:"Not necessarily. Account abstraction enables gas sponsorship where dApps or paymasters can cover gas fees on your behalf. You could also pay gas fees in stablecoins like USDC instead of ETH. This removes one of the biggest onboarding barriers for new crypto users."},{question:"Is account abstraction available now?",answer:"Yes. ERC-4337 is live on Ethereum mainnet and most Layer 2 networks. Wallets like Argent, Safe, and several others already implement account abstraction features. Adoption is growing rapidly as more dApps integrate paymaster support and wallet providers build on the standard."},{question:"Are smart accounts less secure than regular wallets?",answer:"Smart accounts can actually be more secure because they support programmable security rules — spending limits, guardian recovery, and multi-signature requirements. The trade-off is smart contract risk and higher gas costs for basic transactions. Well-audited smart accounts from established providers like Safe and Argent have strong security track records."}]} relatedArticles={[{title:"Smart Contract Wallets",href:"/wallets/learn/smart-contract-wallets",category:"Wallets"},{title:"Social Recovery Wallets",href:"/wallets/learn/social-recovery-wallets",category:"Wallets"},{title:"Argent Wallet Review",href:"/wallets/reviews/argent",category:"Review"}]}>
      <section id="what-is"><h2>What Is Account Abstraction?</h2><p>Traditional Ethereum accounts (externally owned accounts or EOAs) are controlled by a single private key with fixed, rigid rules — every transaction must be signed by that key, gas must be paid in ETH, and transactions execute one at a time. Account abstraction replaces this model with smart contract accounts that can define custom validation logic. Instead of a single key being the gatekeeper, the smart contract can implement any security model: multi-signature, social recovery, biometric authentication, spending limits, or any combination. This programmability transforms wallets from static key holders into flexible, upgradeable security systems that can adapt to each user&apos;s needs. The result is wallets that can offer experiences comparable to traditional fintech apps while maintaining self-custody.</p></section>
      <section id="erc4337"><h2>ERC-4337 Standard</h2><p>ERC-4337 is the Ethereum standard that enables account abstraction without requiring changes to the core Ethereum protocol. It introduces several new concepts: UserOperations (user intents that replace traditional transactions), Bundlers (services that package UserOperations into regular transactions for inclusion in blocks), Paymasters (contracts that can sponsor gas fees for users), and EntryPoint (a singleton contract that validates and executes UserOperations). The standard was deployed on Ethereum mainnet in March 2023 and has since been adopted across major Layer 2 networks. ERC-4337 enables developers to build wallet experiences that abstract away blockchain complexity while preserving the security and decentralization properties that make crypto valuable.</p></section>
      <section id="features"><h2>Key Features Enabled</h2><p>Gas sponsorship allows dApps to pay transaction fees so users never need to hold ETH for gas — critical for mainstream onboarding. Batched transactions combine multiple operations into a single transaction — approve a token and swap it in one step instead of two separate transactions. Session keys grant temporary, limited-scope signing permissions to dApps, enabling experiences like gaming sessions without constant signature popups. Spending limits cap the value that can be transferred without additional authorization, protecting against key compromise. Social recovery through guardian designation replaces seed phrase dependency. Programmable security enables time-locked transfers, whitelisted addresses, and custom rules that traditional wallets cannot implement. Together, these features make crypto wallets dramatically more user-friendly and secure.</p></section>
      <section id="wallets"><h2>Wallets Using Account Abstraction</h2><p>Argent is a pioneer in account abstraction, implementing smart accounts on both Ethereum mainnet and Starknet with social recovery and spending limits. Safe has evolved from a multisig wallet into a full account abstraction platform with modular plugins. Biconomy, ZeroDev, and Alchemy offer developer SDKs for building account abstraction features into new wallets and dApps. Coinbase has integrated smart accounts into Coinbase Wallet. As the ERC-4337 ecosystem matures, expect most new wallets to be built on smart accounts by default, and existing wallets to offer migration paths from EOAs to smart accounts. The transition represents a fundamental shift in how users interact with blockchain technology.</p></section>
    </LearnPageLayout>
  );
}
