import { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `What Is Gods Unchained (GODS)? Price, Guide & How to Buy (${CURRENT_YEAR}) | CryptoDegen`,
  description: "Learn about Gods Unchained (GODS), the blockchain trading card game. Discover GODS tokenomics and how to buy.",
};

export default function GodsPage() {
  return (
    <LearnPageLayout title="What Is Gods Unchained (GODS)? Price, Guide & How to Buy" categoryName="Investing" categorySlug="investing" readTime="8 min read" intro="Gods Unchained (GODS) is a free-to-play, play-to-earn digital trading card game built on Immutable X, an Ethereum Layer 2 scaling solution. Inspired by games like Hearthstone and Magic: The Gathering, Gods Unchained enables true ownership of in-game cards as NFTs that can be traded or sold on open marketplaces." toc={[{id:"what-is",title:"What Is Gods Unchained?",level:2},{id:"how-it-works",title:"How Does Gods Unchained Work?",level:2},{id:"tokenomics",title:"GODS Tokenomics",level:2},{id:"use-cases",title:"Key Use Cases",level:2},{id:"how-to-buy",title:"How to Buy GODS",level:2},{id:"risks",title:"Risks and Considerations",level:2}]} faqs={[{question:"What is Gods Unchained?",answer:"Gods Unchained is a blockchain trading card game on Immutable X where players truly own their cards as NFTs. GODS is the utility token used for card forging, rewards, and governance."},{question:"Where can I buy GODS?",answer:"GODS is available on Coinbase, KuCoin, and other exchanges. It can also be earned through gameplay."},{question:"Is Gods Unchained a good investment?",answer:"Gods Unchained has quality gameplay and blockchain card ownership. Its value depends on player retention and the broader adoption of blockchain gaming."}]} relatedArticles={[{title:"Best Cryptos to Buy",href:"/investing/best/cryptos-to-buy",category:"Investing"},{title:"How to Invest in Crypto",href:"/investing/learn/how-to-invest-in-crypto",category:"Investing"}]}>
      <section id="what-is"><h2>What Is Gods Unchained?</h2><p>Gods Unchained is a competitive trading card game developed by Immutable, the company behind the Immutable X scaling solution. The game features strategic card battles where players build decks, compete against other players, and earn rewards. Unlike traditional digital card games where cards exist only within a single platform, Gods Unchained cards are NFTs that players can freely trade, sell, or transfer. The game is free-to-play with core card packs available at no cost.</p><p>Built on Immutable X, the game benefits from gasless NFT minting and trading, making the blockchain aspects seamless for players. The game has attracted both traditional card game enthusiasts and crypto gamers, positioning itself as one of the most polished blockchain games available.</p></section>
      <section id="how-it-works"><h2>How Does Gods Unchained Work?</h2><p>Players compete in ranked matches to earn Flux, an in-game resource that combines with GODS tokens to forge (upgrade) cards from plain to higher-quality meteorite, shadow, gold, or diamond versions. Higher quality cards are rarer and more valuable on the marketplace. Card packs can be purchased with GODS or ETH, and individual cards trade on the Immutable X marketplace and other NFT platforms. Weekly ranked rewards distribute card packs and GODS tokens to active players.</p></section>
      <section id="tokenomics"><h2>GODS Tokenomics</h2><p>GODS has a total supply of 500 million tokens. Distribution includes play-to-earn rewards, ecosystem development, team, and token sale allocations. GODS is burned through the card forging process, creating deflationary pressure tied to gameplay activity. The token's value proposition depends on the game maintaining an active player base that demands cards and participates in forging and trading.</p></section>
      <section id="use-cases"><h2>Key Use Cases</h2><p>GODS is used for card forging (upgrading card quality), purchasing card packs, earning through gameplay, and governance over game development. The game economy revolves around card collection, competitive play, and marketplace trading. GODS connects the gameplay experience to the on-chain economy.</p></section>
      <section id="how-to-buy"><h2>How to Buy GODS</h2><p>GODS is available on Coinbase, KuCoin, and other exchanges. It can also be earned through competitive play. Store in MetaMask or any Ethereum-compatible wallet with Immutable X support.</p></section>
      <section id="risks"><h2>Risks and Considerations</h2><p>Blockchain gaming has struggled to achieve mainstream adoption. Player retention in card games depends on constant content updates and meta balancing. Competition from established card games like Hearthstone and Magic Arena is fierce. The NFT card market depends on sufficient player demand; declining players mean declining card values. GODS token emissions from play-to-earn rewards create sell pressure if not matched by demand. The broader crypto gaming narrative has cooled since its 2021-2022 peak.</p></section>
    </LearnPageLayout>
  );
}
