import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `How to Evaluate an ICO or Token Sale (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Guide to evaluating ICOs, IDOs, and token sales including due diligence checklist, valuation methods, red flags, and participation best practices.",
  keywords: ["ICO evaluation", "token sale", "IDO guide", "crypto presale", "token launch evaluation", "ICO due diligence"],
};

export default function HowToEvaluateIcoPage() {
  return (
    <LearnPageLayout title="How to Evaluate an ICO or Token Sale" categoryName="Crypto Education" categorySlug="learn" readTime="7 min" intro="Token launches — whether called ICOs, IDOs, IEOs, or presales — represent opportunities to invest in projects at early stages. However, they also carry significant risk, including high rates of project failure and outright fraud. Rigorous evaluation is essential before participating in any token sale."
      toc={[{ id: "types", title: "Types of Token Sales", level: 2 },{ id: "evaluation", title: "Evaluation Checklist", level: 2 },{ id: "valuation", title: "Valuation Considerations", level: 2 },{ id: "red-flags", title: "Red Flags", level: 2 },{ id: "participation", title: "Participation Best Practices", level: 2 }]}
      faqs={[
        { question: "What percentage of ICOs succeed?", answer: "Historical data shows that the majority of ICO-funded projects fail to deliver on their promises. Studies of the 2017-2018 ICO boom found that over 80% of ICOs were scams or failed projects. The success rate has improved with better infrastructure and investor sophistication, but token sales remain high-risk investments." },
        { question: "What is an IDO vs ICO?", answer: "An ICO (Initial Coin Offering) is a direct token sale by the project. An IDO (Initial DEX Offering) launches the token on a decentralized exchange launchpad, providing immediate liquidity. IEOs (Initial Exchange Offerings) are conducted through centralized exchanges that perform some vetting. Each format has different risk profiles and accessibility." },
        { question: "Should I invest in presales?", answer: "Presales offer the lowest prices but the highest risk — the project may have no working product. Only invest in presales after thorough due diligence on the team, technology, and tokenomics. Never invest more than you can afford to lose completely, and treat presale investments as high-risk speculative bets." },
      ]}
      relatedArticles={[
        { title: "How to Research Crypto", href: "/learn/how-to-research-crypto", category: "Learn" },
        { title: "How to Spot Rug Pulls", href: "/learn/how-to-spot-rug-pulls", category: "Learn" },
        { title: "What Is Tokenomics?", href: "/learn/what-is-tokenomics", category: "Learn" },
        { title: "Crypto Scams Guide", href: "/learn/crypto-scams-guide", category: "Learn" },
      ]}
    >
      <section id="types"><h2>Types of Token Sales</h2><p>ICOs involve projects selling tokens directly to investors, often through a website with smart contract interaction. IDOs launch tokens on decentralized exchange platforms (like launchpads on Ethereum, Solana, or BSC) that provide immediate trading liquidity. IEOs are conducted through centralized exchanges that perform basic vetting of the project before hosting the sale on their platform.</p><p>Presales offer tokens at discounted prices to early investors before the public sale. Seed and private rounds target institutional and accredited investors at the earliest stages with the deepest discounts. Each stage involves different price points, lock-up periods, and risk levels. Earlier stages offer lower prices but higher risk and longer lock-ups, while later stages are more expensive but offer quicker liquidity.</p></section>
      <section id="evaluation"><h2>Evaluation Checklist</h2><p>Evaluate systematically: team backgrounds and track records (verifiable and relevant), technology viability (working prototype preferred, whitepaper minimum), market opportunity (real problem with a large addressable market), competitive advantage (what is unique about this approach), tokenomics (fair distribution, clear utility, reasonable valuation), legal structure (proper incorporation, regulatory compliance), and community engagement (organic growth, not bought followers).</p><p>Review the smart contracts that will handle the token sale — are they audited? Check for vesting schedules on team tokens (immediate unlock is a red flag). Verify any claimed partnerships or endorsements independently. Assess the project's funding needs versus the amount being raised — excessive raises relative to the project scope suggest misaligned incentives. Look for transparency about fund allocation and milestone-based development plans.</p></section>
      <section id="valuation"><h2>Valuation Considerations</h2><p>Evaluate the fully diluted valuation (FDV) — the total token supply multiplied by the sale price. Compare this to comparable projects that have launched and are currently trading. If the FDV at sale price is higher than established competitors, the valuation may be too aggressive. Consider the initial market cap (circulating supply at launch times price) versus FDV to understand dilution risk from future token unlocks.</p><p>Model potential outcomes: what does the project need to achieve for the investment to be profitable at different multiples? Are those milestones realistic given the team and market conditions? Factor in lock-up periods — even if the token appreciates, you cannot realize gains until your tokens unlock. Consider the opportunity cost of capital locked in vesting schedules versus liquid investments.</p></section>
      <section id="red-flags"><h2>Red Flags</h2><p>Avoid token sales with: anonymous teams raising large amounts, no working product and vague roadmaps, unrealistic return promises, heavy emphasis on referral bonuses (pyramid-like structure), no code repository or audit, majority token allocation to team with short or no vesting, no clear explanation of how the token captures value, and aggressive marketing that prioritizes FOMO over substance.</p><p>Additional warnings: projects that frequently change their narrative to match current trends, teams with multiple failed past projects, copying another project's whitepaper or code without attribution, artificial social media engagement (bought followers, bot comments), and resistance to legitimate criticism or technical questions. If the team cannot convincingly explain why their token is necessary for their protocol to function, the token may have no fundamental value proposition.</p></section>
      <section id="participation"><h2>Participation Best Practices</h2><p>If you decide to participate in a token sale after thorough due diligence: invest only what you can afford to lose entirely, use a dedicated wallet for the purchase (not your main holdings wallet), verify the sale contract address through multiple official sources, and understand the exact terms (price, vesting, lock-up, network). Never send funds to an address received through DM or unofficial channels.</p><p>After participation: record the transaction for tax purposes, note vesting schedules and unlock dates, monitor project development against their stated milestones, and be prepared to adjust your thesis if execution deviates significantly from promises. Diversify across multiple early-stage investments rather than concentrating on a single token sale — the high failure rate makes concentration extremely risky in early-stage crypto investments.</p></section>
    </LearnPageLayout>
  );
}
