import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Crypto Phishing Protection Guide (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Protect yourself from crypto phishing attacks. Learn to identify fake websites, malicious links, social engineering tactics, and secure your wallet.",
  keywords: ["crypto phishing", "phishing protection", "wallet security", "fake websites", "social engineering"],
};

export default function Page() {
  return (
    <LearnPageLayout title="Crypto Phishing Protection Guide" categoryName="Crypto Wallets" categorySlug="wallets" readTime="7 min" intro="Phishing remains the most common attack vector in crypto, responsible for more individual losses than any other type of exploit. Attackers create convincing replicas of legitimate websites, send deceptive messages, and exploit social media platforms to trick users into revealing credentials or signing malicious transactions. This guide arms you with the knowledge to recognize and avoid these threats." toc={[{id:"types",title:"Types of Crypto Phishing Attacks",level:2},{id:"identify",title:"How to Identify Phishing Attempts",level:2},{id:"tools",title:"Anti-Phishing Tools and Extensions",level:2},{id:"respond",title:"What to Do If You Fall Victim",level:2}]} faqs={[{question:"Can I get phished just by clicking a link?",answer:"Simply clicking a link typically does not compromise your wallet. Phishing sites need you to actively connect your wallet and sign transactions. However, malicious links can install malware on compromised systems, redirect you to convincing fake sites, or exploit browser vulnerabilities. Practice caution with all links, especially from unsolicited messages."},{question:"How do attackers create such convincing fake sites?",answer:"Modern phishing kits clone entire website frontends automatically, replicating every visual element of legitimate dApps. Attackers register domains with subtle variations — extra characters, different TLDs, or homoglyph substitutions using similar-looking unicode characters. They often promote these sites through compromised social media accounts, paid ads, and direct messages."},{question:"Are hardware wallets safe from phishing?",answer:"Hardware wallets protect against malware but not against phishing-induced signatures. If you connect your hardware wallet to a phishing site and approve a malicious transaction on the device, your assets can be stolen. Always verify transaction details on the hardware wallet screen match your intended action."}]} relatedArticles={[{title:"Wallet Drainer Scams",href:"/wallets/learn/wallet-drainer-scams",category:"Wallets"},{title:"Wallet Security Best Practices",href:"/wallets/learn/wallet-security-best-practices",category:"Wallets"},{title:"Private Key Management",href:"/wallets/learn/private-key-management",category:"Wallets"}]}>
      <section id="types"><h2>Types of Crypto Phishing Attacks</h2><p>Website phishing involves creating pixel-perfect replicas of popular DeFi protocols, NFT marketplaces, or wallet interfaces to capture wallet connections and signatures. Search engine phishing places malicious ads above legitimate results for popular crypto terms. Social media phishing operates through fake accounts impersonating projects or influencers, posting fake mint links and airdrop claims. Discord and Telegram phishing targets community members with fake announcements, bot messages, and compromised admin accounts posting malicious links. Email phishing sends fake notifications from exchanges, wallets, or protocols requesting urgent action. DNS hijacking redirects legitimate domain traffic to attacker-controlled servers — even typing the correct URL leads to a fake site. Address poisoning sends tiny transactions from addresses designed to look similar to your frequent contacts, hoping you copy the wrong address from transaction history. Each attack type requires different defensive strategies, but the common thread is always verifying before acting.</p></section>
      <section id="identify"><h2>How to Identify Phishing Attempts</h2><p>URL verification is your first line of defense — always check the exact domain before connecting your wallet. Look for subtle misspellings, extra characters, or unusual subdomains. Bookmark legitimate sites and use bookmarks rather than search results or clicked links. Legitimate projects almost never ask you to urgently connect your wallet through direct messages or social media posts. Be suspicious of any unsolicited communication requesting wallet interaction, regardless of how official it appears. Check for HTTPS encryption but understand that phishing sites also use SSL certificates — HTTPS alone does not guarantee legitimacy. Verify announcements through multiple official channels before acting — if an airdrop or mint is real, it will be announced on the project&apos;s verified website, not just through a random link. Unexpected approval or signature requests from sites you trust may indicate the site has been compromised — verify the contract addresses match known legitimate contracts before signing anything.</p></section>
      <section id="tools"><h2>Anti-Phishing Tools and Extensions</h2><p>Wallet Guard is a browser extension that warns about known phishing domains and simulates transactions to show their true intent before you sign. Pocket Universe provides real-time transaction simulation showing exactly what assets will leave your wallet. Blockaid, integrated into MetaMask, scans transactions against a database of known attack patterns and flags suspicious requests. Rabby wallet includes built-in phishing detection and transaction simulation as core features. Scam Sniffer monitors blockchain activity for drainer contracts and maintains a database of malicious sites. Fire extension provides human-readable transaction descriptions, translating complex contract calls into understandable language. Using multiple layers of protection is recommended — a phishing detection extension combined with a wallet that simulates transactions provides robust defense. Keep all extensions and wallets updated, as phishing techniques evolve rapidly and protection tools update their databases frequently to counter new threats.</p></section>
      <section id="respond"><h2>What to Do If You Fall Victim</h2><p>Speed is critical if you realize you have interacted with a phishing site. Immediately revoke any approvals you granted to the malicious contract using Revoke.cash — connect from a clean device if possible. Transfer remaining assets to a new wallet address that has never interacted with the compromised site. If you entered your seed phrase on a phishing site, every account derived from that seed is compromised — create an entirely new wallet and transfer assets from all compromised accounts immediately. Change passwords for any exchange accounts if you entered credentials on a phishing site. Report the phishing URL to PhishFort, browser safe browsing databases, and the impersonated project&apos;s team. Document everything including transaction hashes, the phishing URL, and timestamps for potential law enforcement reports. While recovering stolen crypto is difficult, reporting helps protect others and builds cases against serial attackers. Learn from the experience and implement stronger protections — phishing awareness dramatically reduces future risk.</p></section>
    </LearnPageLayout>
  );
}
