import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Rug Pull Guide: How to Spot and Avoid Them (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Learn how crypto rug pulls work, the warning signs to look for, and how to protect your investments from liquidity pulls and exit scams.",
  keywords: ["rug pull", "crypto rug pull", "liquidity pull", "exit scam", "honeypot token"],
};

export default function Page() {
  return (
    <LearnPageLayout title="Rug Pull Guide: How to Spot and Avoid Them" categoryName="Crypto Investing" categorySlug="investing" readTime="7 min" intro="A rug pull is a type of crypto scam where developers abandon a project and run away with investors' funds. Named after the expression 'pulling the rug out,' these scams account for a significant portion of crypto fraud. Understanding the mechanics and warning signs helps you avoid becoming a victim." toc={[
        { id: "types", title: "types", level: 2 },
        { id: "types-of-rug-pulls", title: "Types of Rug Pulls", level: 2 },
        { id: "mechanics", title: "mechanics", level: 2 },
        { id: "how-rug-pulls-work", title: "How Rug Pulls Work", level: 2 },
        { id: "warning-signs", title: "warning-signs", level: 2 },
        { id: "warning-signs-to-watch-for", title: "Warning Signs to Watch For", level: 2 },
        { id: "protect", title: "protect", level: 2 },
        { id: "how-to-protect-yourself", title: "How to Protect Yourself", level: 2 }
      ]} faqs={[{question:"Can a rug pull happen with established projects?",answer:"While classic rug pulls are most common with new, unvetted tokens, established projects can experience slow rug pulls where the team gradually sells holdings and reduces development effort over months. Even well-known projects have had team members exit with treasury funds. The risk decreases with time, community size, and transparent governance."},{question:"Are all meme coins rug pulls?",answer:"Not all meme coins are rug pulls, but meme coins have a significantly higher rug pull rate than utility tokens because they often lack fundamental value, have anonymous creators, and attract impulsive investors who do less research. Some meme coins like Dogecoin have survived for years, but the vast majority of new meme tokens are created specifically for scamming."},{question:"Can you get your money back after a rug pull?",answer:"Recovery from rug pulls is extremely rare. Blockchain transactions are irreversible, and scammers typically use mixing services or chain-hopping to obscure stolen funds. Some victims have recovered partial funds when scammers used centralized exchanges that cooperated with law enforcement, but this is the exception."}]} relatedArticles={[{title:"Crypto Scam Protection",href:"/investing/learn/crypto-scam-protection",category:"Investing"},{title:"Pump and Dump Explained",href:"/investing/learn/pump-and-dump-explained",category:"Investing"},{title:"What Are Meme Coins",href:"/investing/learn/what-are-meme-coins",category:"Investing"}]}>
      <section id="types"><h2>Types of Rug Pulls</h2><p>Hard rug pulls are sudden, dramatic exits where developers withdraw all liquidity from a trading pool, making the token instantly untradeable and worthless. This is the classic rug pull — one moment the token has value, the next moment it cannot be sold at any price. Soft rug pulls are gradual — developers slowly sell their token holdings over time, suppressing the price while making excuses about development delays and market conditions. The project slowly dies rather than collapsing overnight. Honeypot tokens are programmed so that only the developer can sell — buyers can purchase but the smart contract prevents anyone else from selling. This creates the illusion of a rising token with active buying but zero selling, until the developer extracts all value. Malicious mint rug pulls exploit hidden functions in the smart contract that allow the developer to mint unlimited new tokens, which they then sell to drain the liquidity pool. Each type requires different detection methods, but all share the common outcome of investors losing their money while developers profit.</p></section>
      <section id="mechanics"><h2>How Rug Pulls Work</h2><p>A typical rug pull follows a predictable playbook. The developers create a new token with an appealing narrative — a revolutionary DeFi protocol, the next big meme coin, or a celebrity-endorsed project. They create a liquidity pool on a decentralized exchange like Uniswap, pairing their token with ETH or a stablecoin. They generate artificial hype through paid social media promotion, influencer partnerships, fake partnerships, and manufactured community excitement. As investors buy in, the token price rises, attracting more buyers in a self-reinforcing cycle. The developers typically hold a large portion of the token supply or maintain admin control over the liquidity pool. Once they have attracted sufficient investment, they execute the rug pull — withdrawing liquidity, selling massive token holdings, or using contract backdoors to drain funds. The entire lifecycle can be as short as a few hours for blatant scams or extend over weeks or months for more sophisticated operations that build community trust before pulling.</p></section>
      <section id="warning-signs"><h2>Warning Signs to Watch For</h2><p>Anonymous or pseudonymous development teams with no verifiable track record significantly increase rug pull risk. Unlocked liquidity — where the developer can withdraw pool assets at any time — is a critical red flag checkable through tools like DeFi Safety and RugDoc. Concentrated token ownership where few wallets hold most of the supply creates dump risk. Unaudited or unverified smart contracts may contain hidden functions like mint, pause, or blacklist that enable rug pulls. Extremely aggressive marketing with paid influencers, coordinated social media campaigns, and unrealistic promises often accompanies fraudulent projects. No clear use case or technology beyond token speculation suggests the project exists solely to extract value. Copying code from other projects without meaningful innovation indicates low effort and potential dishonesty. Suspiciously high initial yields designed to attract liquidity before the rug pull. Disabled selling functionality or unusual transfer taxes that only appear after initial purchases. Projects that launched within the last few days or weeks carry the highest risk, as most rug pulls occur within the first month of a token&apos;s existence.</p></section>
      <section id="protect"><h2>How to Protect Yourself</h2><p>Use token analysis tools like Token Sniffer, GoPlusLabs, and RugDoc to scan smart contracts for known rug pull patterns before investing. These tools check for honeypot mechanics, hidden minting functions, suspicious ownership concentration, and other red flags automatically. Verify that liquidity is locked through time-locked contracts — services like Unicrypt and Team Finance provide verifiable liquidity locks that prevent developers from withdrawing pool assets. Check the contract on block explorers like Etherscan to see if it is verified and review the source code for suspicious functions. Only invest amounts you can afford to lose completely in new, unvetted tokens. Wait for initial euphoria to settle before investing — most rug pulls happen within the first few days of launch, and waiting even a week eliminates many scam tokens. Look for genuine community development including active GitHub repositories, regular development updates, and engaged community discussions beyond price speculation. If a project seems too good to be true — guaranteed returns, celebrity endorsements, revolutionary claims with no technical substance — assume it is a scam until proven otherwise through thorough independent verification.</p></section>
    </LearnPageLayout>
  );
}
