import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Liquidity Explained: Why It Matters in Crypto (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Understand what liquidity means in crypto markets, how it affects your trades, and how to evaluate exchange and token liquidity.",
};

export default function LiquidityExplainedPage() {
  return (
    <LearnPageLayout title="Liquidity Explained: Why It Matters in Crypto" categoryName="Crypto Exchanges" categorySlug="exchanges" readTime="8 min"
      intro="Liquidity is one of the most important yet misunderstood concepts in crypto trading. It directly affects the prices you get, how quickly you can trade, and the overall health of a market. Understanding liquidity helps you choose better exchanges, trade more efficiently, and avoid costly mistakes."
      toc={[{id:"what-is-liquidity",title:"What Is Liquidity",level:2},{id:"measuring",title:"Measuring Liquidity",level:2},{id:"why-it-matters",title:"Why Liquidity Matters for Traders",level:2},{id:"exchange-liquidity",title:"Comparing Exchange Liquidity",level:2},{id:"defi-liquidity",title:"Liquidity in DeFi",level:2}]}
      faqs={[{question:"Which crypto exchange has the most liquidity?",answer:"Binance has the deepest liquidity globally across the most trading pairs. For US traders, Coinbase and Kraken offer the best liquidity on USD pairs."},{question:"Is high volume the same as high liquidity?",answer:"Volume and liquidity are related but distinct. Volume measures total trading activity over a period. Liquidity measures how much can be traded right now without impacting price. An exchange can have high volume but poor liquidity if most trades are small."},{question:"Can liquidity change quickly?",answer:"Yes. Liquidity can evaporate during market panics as market makers withdraw orders. This is why spreads widen and slippage increases during volatile events."}]}
      relatedArticles={[{title:"Slippage Explained",href:"/exchanges/learn/slippage-explained",category:"Exchanges"},{title:"How to Read the Order Book",href:"/exchanges/learn/how-to-read-order-book",category:"Exchanges"},{title:"AMM Explained",href:"/exchanges/learn/amm-explained",category:"Exchanges"}]}
    >
      <section id="what-is-liquidity"><h2>What Is Liquidity</h2><p>Liquidity refers to how easily and quickly an asset can be bought or sold without significantly affecting its price. A highly liquid market has many buyers and sellers, tight bid-ask spreads, and the ability to absorb large orders with minimal price impact. An illiquid market has few participants, wide spreads, and even small orders can cause significant price movements. Bitcoin on Binance is extremely liquid. A newly launched memecoin on a small DEX pool is extremely illiquid.</p></section>
      <section id="measuring"><h2>Measuring Liquidity</h2><p>Several metrics help assess liquidity. Bid-ask spread measures the gap between the best buy and sell prices — tighter is better. Order book depth shows the volume available at different price levels. Trading volume indicates overall market activity. Market depth percentage measures how much price would move for a given order size. On DEXs, total value locked (TVL) in a liquidity pool indicates available liquidity. For practical purposes, try placing a simulated large order and observe the estimated slippage to assess real-world liquidity for your trading size.</p></section>
      <section id="why-it-matters"><h2>Why Liquidity Matters for Traders</h2><p>Low liquidity directly costs you money through wider spreads and higher slippage. For a day trader executing $100,000 in daily volume, the difference between a 0.05% spread (liquid market) and a 0.5% spread (illiquid market) is $450 per day or over $100,000 per year. Beyond cost, low liquidity makes it difficult to enter and exit positions at desired prices, increases the risk of getting trapped in positions during market downturns, and makes stop-loss orders less reliable as prices can gap through stop levels.</p></section>
      <section id="exchange-liquidity"><h2>Comparing Exchange Liquidity</h2><p>Binance dominates global crypto liquidity, particularly for BTC/USDT and ETH/USDT. OKX, Bybit, and Coinbase follow. Liquidity varies significantly by trading pair — an exchange might have excellent BTC liquidity but thin order books for mid-cap altcoins. Always check the specific pairs you plan to trade, not just headline liquidity numbers. Crypto market data aggregators provide comparative liquidity metrics across exchanges.</p></section>
      <section id="defi-liquidity"><h2>Liquidity in DeFi</h2><p>DeFi protocols use liquidity pools instead of order books. Liquidity providers deposit token pairs into smart contracts, and traders swap against these pools. The pool size directly determines available liquidity and slippage. Larger pools handle bigger trades with less price impact. DEX aggregators like Jupiter and 1inch improve liquidity by routing trades across multiple pools and protocols. Concentrated liquidity (Uniswap v3) allows LPs to focus their capital in specific price ranges, improving capital efficiency and reducing slippage within those ranges.</p></section>
    </LearnPageLayout>
  );
}
