import { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `What Is Yield Guild Games (YGG)? Price, Guide & How to Buy (${CURRENT_YEAR}) | CryptoDegen`,
  description: "Learn about Yield Guild Games (YGG), the blockchain gaming guild and Web3 community. Discover YGG tokenomics and how to buy.",
};

export default function YieldGuildPage() {
  return (
    <LearnPageLayout title="What Is Yield Guild Games (YGG)? Price, Guide & How to Buy" categoryName="Investing" categorySlug="investing" readTime="8 min read" intro="Yield Guild Games (YGG) is a decentralized autonomous organization (DAO) that invests in NFTs used in blockchain games and facilitates a community of players who earn through play-to-earn gaming. YGG pioneered the gaming guild model during the Axie Infinity boom, lending NFT game assets to players (scholars) who could not afford the upfront cost, with earnings split between the guild and players." toc={[{id:"what-is",title:"What Is Yield Guild Games?",level:2},{id:"how-it-works",title:"How Does Yield Guild Games Work?",level:2},{id:"tokenomics",title:"YGG Tokenomics",level:2},{id:"use-cases",title:"Key Use Cases",level:2},{id:"how-to-buy",title:"How to Buy YGG",level:2},{id:"risks",title:"Risks and Considerations",level:2}]} faqs={[{question:"What is Yield Guild Games?",answer:"YGG is a blockchain gaming guild and DAO that invests in gaming NFTs and builds a community of play-to-earn gamers. YGG tokens represent membership and governance in the guild."},{question:"Where can I buy YGG?",answer:"YGG is available on Coinbase, Binance, Bybit, and other major exchanges."},{question:"Is Yield Guild Games a good investment?",answer:"YGG has evolved from Axie-focused scholarships to a broader web3 gaming community. Its value depends on the overall health of blockchain gaming and the guild's ability to identify winning games early."}]} relatedArticles={[{title:"Best Cryptos to Buy",href:"/investing/best/cryptos-to-buy",category:"Investing"},{title:"How to Invest in Crypto",href:"/investing/learn/how-to-invest-in-crypto",category:"Investing"}]}>
      <section id="what-is"><h2>What Is Yield Guild Games?</h2><p>Yield Guild Games was founded in 2020 in the Philippines during the Axie Infinity boom, when the scholarship model allowed players from developing countries to earn income through play-to-earn gaming. YGG became the largest gaming guild, managing thousands of scholars playing Axie Infinity and other blockchain games. The DAO's treasury holds a diverse portfolio of gaming NFTs across dozens of blockchain games.</p><p>As the play-to-earn model evolved, YGG pivoted from a purely scholarship-based model to a broader web3 gaming community platform. The guild now focuses on identifying promising blockchain games early, building player communities, and providing services to game studios seeking player acquisition and engagement. YGG has expanded globally with sub-DAOs in multiple countries.</p></section>
      <section id="how-it-works"><h2>How Does Yield Guild Games Work?</h2><p>YGG operates through a guild structure where the DAO treasury acquires gaming NFTs and in-game assets that are deployed across blockchain games. Guild members participate in quests, tournaments, and community activities to earn rewards. The Guild Advancement Program (GAP) tracks player contributions and rewards engagement. YGG also partners with game studios to provide early player feedback, beta testing, and community building services. Sub-DAOs operate in specific regions or game communities with localized management.</p></section>
      <section id="tokenomics"><h2>YGG Tokenomics</h2><p>YGG has a total supply of 1 billion tokens distributed across community rewards, treasury, team, investors, and advisors. The token provides governance over DAO decisions including treasury management and game partnerships. YGG staking enables participation in guild governance and access to premium features. The token's value is influenced by the performance of the gaming NFT treasury and the guild's ability to generate yield from its gaming assets.</p></section>
      <section id="use-cases"><h2>Key Use Cases</h2><p>YGG is used for DAO governance, staking for guild benefits, access to gaming quests and rewards, and representation of economic interest in the guild's NFT treasury. The token connects the guild community with the DAO's gaming investments and services.</p></section>
      <section id="how-to-buy"><h2>How to Buy YGG</h2><p>YGG is available on Coinbase, Binance, Bybit, and other exchanges. After purchasing, YGG can be staked for governance participation and guild rewards. Store in MetaMask or any Ethereum-compatible wallet.</p></section>
      <section id="risks"><h2>Risks and Considerations</h2><p>The original scholarship model that drove YGG's growth has declined as Axie Infinity earnings dropped. The guild's NFT treasury has depreciated significantly from peak valuations alongside the broader NFT market downturn. YGG's pivot to community and services is still being validated. Gaming guild competition has increased with many similar organizations emerging. The DAO's success depends on consistently identifying winning blockchain games, which is inherently difficult. Token unlocks from team and investor vesting can create sell pressure. The broader play-to-earn sector has matured beyond the initial hype, requiring sustainable economic models.</p></section>
    </LearnPageLayout>
  );
}
