import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Wallet Transaction Fees Explained (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Understand the different types of transaction fees in crypto wallets including network fees, swap fees, and bridge fees. Learn how to minimize costs.",
  keywords: ["wallet fees", "transaction fees", "crypto fees", "network fees", "gas fees"],
};

export default function Page() {
  return (
    <LearnPageLayout title="Wallet Transaction Fees Explained" categoryName="Crypto Wallets" categorySlug="wallets" readTime="6 min" intro="Every crypto transaction involves fees, but the types and amounts vary dramatically between networks, wallets, and transaction types. Understanding fee structures helps you choose the most cost-effective wallet and timing for your transactions, potentially saving hundreds of dollars over time." toc={[{id:"types",title:"Types of Wallet Fees",level:2},{id:"network-fees",title:"Network Fees by Blockchain",level:2},{id:"wallet-markup",title:"Wallet Swap and Service Fees",level:2},{id:"minimize",title:"How to Minimize Transaction Costs",level:2}]} faqs={[{question:"Do all wallets charge the same fees?",answer:"No. Network fees (gas) are the same regardless of which wallet you use, but many wallets add their own service fees on top for built-in swaps and bridges. MetaMask charges approximately 0.875% on swaps, while some wallets offer fee-free swaps by routing through DEX aggregators directly. Always compare the total cost including both network and wallet fees."},{question:"Why are my Ethereum fees so high?",answer:"Ethereum mainnet fees are determined by network demand. During peak usage, gas prices can spike to make simple transfers cost $20-50 or more. Layer 2 networks like Arbitrum, Optimism, and Base offer the same security with fees typically under $0.50. Consider moving your activity to Layer 2 for significant savings."},{question:"Can I set my own transaction fee?",answer:"Most wallets allow you to customize gas settings. You can lower the gas price for slower confirmation or increase it for priority processing. However, setting fees too low may cause transactions to get stuck in the mempool. Advanced users can use EIP-1559 priority fee settings for more precise control on Ethereum."}]} relatedArticles={[{title:"Gas Fees Explained",href:"/wallets/learn/gas-fees-explained",category:"Wallets"},{title:"How to Bridge Tokens",href:"/wallets/learn/how-to-bridge-tokens",category:"Wallets"},{title:"Wallet for DeFi Guide",href:"/wallets/learn/wallet-for-defi-guide",category:"Wallets"}]}>
      <section id="types"><h2>Types of Wallet Fees</h2><p>Crypto wallet fees fall into several distinct categories. Network fees (gas fees) are paid to blockchain validators or miners for processing your transaction — these are unavoidable and go directly to the network, not to your wallet provider. Swap fees are charged by wallets that offer built-in token exchange features, typically as a percentage markup on the exchange rate or as a separate service fee. Bridge fees apply when transferring assets between different blockchain networks and include both the bridge protocol&apos;s fee and destination chain gas costs. Some wallets charge withdrawal fees for converting crypto to fiat currency or transferring to external addresses. Approval fees are one-time costs to authorize smart contracts to spend your tokens before you can interact with DeFi protocols. Understanding which fees are network-inherent versus wallet-imposed helps you make informed choices about which wallet and which network to use for different types of transactions.</p></section>
      <section id="network-fees"><h2>Network Fees by Blockchain</h2><p>Network fees vary enormously between blockchains. Ethereum mainnet remains the most expensive, with simple ETH transfers costing a few dollars and complex smart contract interactions costing $10-100 or more during peak demand. Bitcoin transaction fees fluctuate with network congestion, typically ranging from $1-20. Solana offers extremely low fees, usually under $0.01 per transaction regardless of complexity. Layer 2 networks like Arbitrum, Optimism, Base, and zkSync provide Ethereum-level security with fees typically under $0.50 for most operations. BNB Chain and Polygon offer low fees under $0.10 but with different security trade-offs than Ethereum Layer 2s. Avalanche C-Chain fees are moderate, usually under $1. These fee differences significantly impact which chains are practical for different use cases — frequent trading or gaming activity is impractical on expensive networks but works well on Layer 2s or alternative chains.</p></section>
      <section id="wallet-markup"><h2>Wallet Swap and Service Fees</h2><p>Many wallets generate revenue by adding fees to built-in swap features. MetaMask&apos;s swap aggregator charges approximately 0.875% on each swap, which can add up significantly for larger trades. Trust Wallet charges a variable fee on its built-in DEX feature. Coinbase Wallet includes a spread on swaps executed through its interface. Exodus charges a markup embedded in swap exchange rates that is not displayed as a separate fee line item, making true costs harder to evaluate. Some wallets like Rabby route trades through DEX aggregators like 1inch or Paraswap without additional markup, passing savings directly to users. For large trades, executing swaps directly on a DEX through your wallet&apos;s browser rather than using the built-in swap feature can save significant money. Compare the quoted output amount between the wallet&apos;s built-in swap and a direct DEX visit to see the actual markup you are paying.</p></section>
      <section id="minimize"><h2>How to Minimize Transaction Costs</h2><p>The most impactful strategy for reducing fees is choosing the right network. Move routine activity to Layer 2 networks where fees are a fraction of mainnet costs. Time your mainnet transactions for low-demand periods — weekends and late nights in US time zones typically have lower gas prices. Use gas tracking tools like Etherscan&apos;s gas tracker or GasNow to identify optimal transaction timing. For swaps, compare your wallet&apos;s built-in feature against direct DEX usage to find the cheaper option. Batch transactions when possible — some wallets with account abstraction support let you combine multiple operations into a single transaction. Set appropriate gas limits rather than accepting wallet defaults, which often overestimate. Use EIP-1559 priority fees strategically, setting a reasonable max fee with a lower priority tip during non-urgent transactions. Consider accumulating small transactions and executing them together during low-fee periods rather than making many individual transfers throughout the day.</p></section>
    </LearnPageLayout>
  );
}
