import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Exchange vs Wallet: Where Should You Keep Crypto? (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Understand the differences between keeping crypto on an exchange vs a personal wallet. Learn about custody, security, convenience, and when to use each." };

export default function Page() {
  return (<LearnPageLayout title="Exchange vs Wallet: Where Should You Keep Your Crypto?" categoryName="Crypto Exchanges" categorySlug="exchanges" readTime="8 min" intro="One of the most important decisions for any crypto holder is where to store their assets. Exchanges offer convenience for trading, while personal wallets offer self-custody and greater security. Understanding the tradeoffs helps you develop the right storage strategy." toc={[{id:"exchange-storage",title:"Keeping Crypto on an Exchange",level:2},{id:"wallet-storage",title:"Keeping Crypto in a Wallet",level:2},{id:"security-comparison",title:"Security Comparison",level:2},{id:"when-to-use",title:"When to Use Each",level:2},{id:"best-strategy",title:"The Best Strategy",level:2}]} faqs={[{question:"Is it safe to keep crypto on an exchange?",answer:"Major regulated exchanges are reasonably safe for active trading. However, you do not control the private keys, and exchanges can be hacked, go bankrupt, or freeze accounts. For long-term holdings, a personal wallet is safer."},{question:"What is self-custody?",answer:"Self-custody means you hold the private keys that control your crypto. With a personal wallet, only you can access and move your funds. This eliminates counterparty risk but makes you solely responsible for security."},{question:"What is the best hardware wallet?",answer:"Ledger and Trezor are the two most popular hardware wallet brands. Both offer strong security for long-term crypto storage. Choose based on supported cryptocurrencies, interface preference, and budget."}]} relatedArticles={[{title:"Exchange Security Checklist",href:"/exchanges/learn/exchange-security-checklist",category:"Exchanges"},{title:"How to Transfer Between Exchanges",href:"/exchanges/learn/how-to-transfer-between-exchanges",category:"Exchanges"}]}>
      <section id="exchange-storage"><h2>Keeping Crypto on an Exchange</h2><p>When you hold crypto on an exchange, the exchange controls the private keys. This is called custodial storage. The advantage is convenience — you can trade instantly, access your portfolio from any device, and recover your account if you forget your password. The risk is counterparty risk: if the exchange gets hacked, goes bankrupt, or freezes your account, you may lose access to your funds. The phrase "not your keys, not your coins" reflects this fundamental risk.</p></section>
      <section id="wallet-storage"><h2>Keeping Crypto in a Wallet</h2><p>A personal wallet gives you direct control over your private keys. Hardware wallets (Ledger, Trezor) store keys offline in a physical device. Software wallets (MetaMask, Phantom) store keys on your device. The advantage is that no third party can freeze, seize, or lose your funds. The risk is entirely on you — lose your seed phrase and your funds are gone forever with no recovery possible. Self-custody requires careful security practices and backup procedures.</p></section>
      <section id="security-comparison"><h2>Security Comparison</h2><p>Exchange storage protects against personal mistakes (password recovery exists) but exposes you to exchange-level risks (hacks, insolvency, account freezes). Self-custody protects against exchange-level risks but exposes you to personal risks (lost keys, stolen devices, phishing attacks). Neither is universally safer — the best approach depends on your technical comfort level, the amount at stake, and how actively you trade.</p></section>
      <section id="when-to-use"><h2>When to Use Each</h2><p>Keep crypto on exchanges when you are actively trading and need quick access to buy and sell. Use exchanges for smaller amounts that you are comfortable having exposed to counterparty risk. Use personal wallets for long-term holdings (HODL positions), amounts that represent a significant portion of your net worth, assets you want to use in DeFi, and any time you want maximum security and control.</p></section>
      <section id="best-strategy"><h2>The Best Strategy</h2><p>Most experienced crypto users employ a split strategy: keep trading capital on exchanges for active positions, and transfer long-term holdings to a hardware wallet. A common rule of thumb is to not keep more on an exchange than you would be willing to lose entirely. For significant holdings, use a hardware wallet with a properly secured seed phrase backup stored in a physically separate, secure location.</p></section>
    </LearnPageLayout>);
}
