import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Crypto Options Basics: A Beginner's Guide (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Learn the basics of crypto options trading. Understand calls, puts, premiums, strike prices, and simple strategies for getting started with cryptocurrency options." };

export default function Page() {
  return (<LearnPageLayout title="Crypto Options Basics" categoryName="Crypto Trading" categorySlug="trading" readTime="10 min" intro="Options give you the right, but not the obligation, to buy or sell crypto at a specific price before a certain date. They provide powerful tools for hedging, income generation, and leveraged speculation with defined risk. This guide covers the fundamental concepts you need to understand before trading crypto options." toc={[{id:"calls-and-puts",title:"Calls and Puts",level:2},{id:"key-terms",title:"Key Options Terms",level:2},{id:"pricing",title:"How Options Are Priced",level:2},{id:"basic-strategies",title:"Basic Options Strategies",level:2},{id:"getting-started",title:"Getting Started",level:2}]} faqs={[{question:"Are options risky?",answer:"Buying options has limited, defined risk — you can only lose the premium paid. Selling options has potentially unlimited risk. Options are versatile tools that can be used conservatively (hedging, income) or aggressively (leveraged speculation). Risk depends on how you use them."},{question:"Do I need to hold options until expiration?",answer:"No. You can close an options position at any time before expiration by selling (if you bought) or buying back (if you sold). Most active options traders close positions before expiration rather than exercising them."},{question:"What is the minimum investment for crypto options?",answer:"On Deribit, options on Bitcoin require a minimum of 0.1 BTC as the contract unit. Some platforms offer smaller contract sizes. The premium cost depends on the specific option — out-of-the-money options can be very inexpensive while in-the-money options require more capital."}]} relatedArticles={[{title:"Covered Call Strategy",href:"/trading/learn/covered-call-strategy",category:"Trading"},{title:"Straddle Strategy Crypto",href:"/trading/learn/straddle-strategy-crypto",category:"Trading"},{title:"Best for Options Trading",href:"/trading/best/options-trading",category:"Trading"}]}>
    <section id="calls-and-puts"><h2>Calls and Puts</h2><p>A call option gives you the right to buy an asset at a specific price (the strike price) before the expiration date. You buy a call when you expect prices to rise. If Bitcoin is at $50,000 and you buy a $55,000 call, you profit if Bitcoin rises above $55,000 plus the premium you paid. A put option gives you the right to sell at the strike price. You buy a put when you expect prices to fall or want to protect an existing position. If you hold Bitcoin and buy a $45,000 put, you are protected against any decline below $45,000. For every buyer there is a seller (writer). The option seller receives the premium in exchange for taking on the obligation. Call sellers are obligated to sell at the strike if exercised. Put sellers are obligated to buy at the strike if exercised.</p></section>
    <section id="key-terms"><h2>Key Options Terms</h2><p>The strike price is the price at which the option can be exercised. The premium is the price paid for the option — this is your maximum loss as a buyer. The expiration date is when the option expires. In-the-money (ITM) means the option has intrinsic value — a call with a $45,000 strike when Bitcoin is $50,000. Out-of-the-money (OTM) means the option has no intrinsic value — a call with a $55,000 strike when Bitcoin is $50,000. At-the-money (ATM) is when the strike equals the current price. Intrinsic value is the real value if exercised now. Time value is the premium above intrinsic value — it decreases as expiration approaches (time decay or theta). Implied volatility (IV) is the market's expectation of future volatility, directly affecting premium prices — higher IV means more expensive options.</p></section>
    <section id="pricing"><h2>How Options Are Priced</h2><p>An option's premium consists of intrinsic value plus time value. Intrinsic value is straightforward — for a call, it is the amount by which the current price exceeds the strike (zero if the strike is above current price). Time value reflects the probability that the option will become profitable before expiration and is influenced by time to expiration (more time = more value), implied volatility (more volatility = more value), the distance between strike and current price, and interest rates. The Black-Scholes model is the standard for options pricing, though adjustments are made for crypto's unique characteristics. In crypto, implied volatility is significantly higher than in traditional markets, making options relatively expensive. This creates opportunities for both buyers (who need protection or want leveraged exposure) and sellers (who want to capture elevated premiums).</p></section>
    <section id="basic-strategies"><h2>Basic Options Strategies</h2><p>Long call: Buy a call when bullish. Maximum loss is the premium paid. Profit is unlimited above the breakeven (strike + premium). Best when you expect a significant upward move. Long put: Buy a put when bearish or for portfolio protection. Maximum loss is the premium. Profit increases as price falls below the breakeven (strike - premium). Covered call: Own the asset and sell a call against it. You earn premium income but cap your upside at the strike price. Best for generating income on holdings you are willing to sell. Protective put: Own the asset and buy a put for downside protection. Like insurance — you pay a premium for protection against a decline. Best for protecting profits during uncertain periods without selling the underlying asset.</p></section>
    <section id="getting-started"><h2>Getting Started</h2><p>Start by studying options on Deribit's testnet (paper trading) to understand mechanics without risking real money. Learn to read an options chain — the table showing all available strikes and expirations with their bid/ask prices and Greeks. Begin with simple strategies — buying calls and puts — before progressing to selling options or multi-leg strategies. Understand that buying options has a defined, limited loss (the premium) while selling options has potentially unlimited loss. Start with options on Bitcoin and Ethereum, which have the deepest liquidity and tightest spreads. Use longer-dated options (1-3 months) rather than very short-dated ones, as short-dated options suffer from rapid time decay. Track your options PnL separately from other trading — options performance should be evaluated differently from spot or futures trading due to their non-linear payoff structure.</p></section>
  </LearnPageLayout>);
}
