'use client';
import Link from "next/link";
import TradingViewChart from "@/components/TradingViewChart";
const S={bg:"#0d1117",surface:"#161b22",surface2:"#1c2330",border:"#30363d",text:"#e6edf3",text2:"#8b949e",blue:"#58a6ff",green:"#3fb950",orange:"#f0883e",yellow:"#d29922",purple:"#bc8cff"};
const C="#3fcfcf";
export default function PendleGuidePage(){return(<main style={{backgroundColor:S.bg,color:S.text,minHeight:"100vh",fontFamily:"-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif"}}>
<div style={{borderBottom:`1px solid ${S.border}`,padding:"16px 24px",display:"flex",gap:8,fontSize:13,color:S.text2}}><Link href="/" style={{color:S.text2,textDecoration:"none"}}>Home</Link><span>/</span><Link href="/ecosystem" style={{color:S.text2,textDecoration:"none"}}>Ecosystem</Link><span>/</span><span style={{color:S.text}}>Pendle</span></div>
<article style={{maxWidth:860,margin:"0 auto",padding:"48px 24px 80px"}}>
<div style={{display:"flex",alignItems:"center",gap:20,marginBottom:32}}>
<div style={{width:64,height:64,background:`${C}20`,borderRadius:16,display:"flex",alignItems:"center",justifyContent:"center",fontSize:36,border:`1px solid ${C}40`}}>⏳</div>
<div>
<div style={{display:"flex",gap:8,marginBottom:8,flexWrap:"wrap"}}>
<span style={{fontSize:11,fontWeight:700,padding:"2px 8px",borderRadius:20,background:`${C}20`,color:C,border:`1px solid ${C}40`}}>Yield Trading</span>
<span style={{fontSize:11,fontWeight:700,padding:"2px 8px",borderRadius:20,background:`${S.blue}20`,color:S.blue}}>DeFi</span>
</div>
<h1 style={{fontSize:"2rem",fontWeight:900,lineHeight:1.2,margin:0}}>Pendle Finance: Yield Trading Protocol Guide 2026</h1>
<p style={{margin:"8px 0 0",color:S.text2,fontSize:14}}>Tokenize and trade future yield · +150 XP · 13 min read · Updated March 2026</p>
</div>
</div>

<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill, minmax(160px, 1fr))",gap:12,marginBottom:40}}>
{[["TVL","$4.1B",C],["Markets","60+",S.blue],["Token","$PENDLE",S.purple],["Chains","Ethereum, Arb, BNB",S.green],["Fixed Yield","Available",S.orange],["Rating","⭐ 4.7",S.yellow]].map(([l,v,c])=>(
<div key={String(l)} style={{background:S.surface,border:`1px solid ${S.border}`,borderRadius:10,padding:"14px 16px"}}>
<div style={{fontSize:11,color:S.text2,textTransform:"uppercase"}}>{l}</div>
<div style={{fontSize:16,fontWeight:800,color:String(c),marginTop:4}}>{v}</div>
</div>
))}
</div>

<section style={{marginBottom:36}}>
<h2 style={{fontSize:"1.5rem",fontWeight:800,marginBottom:12,color:C}}>What is Pendle?</h2>
<p style={{color:S.text2,lineHeight:1.8,marginBottom:14}}>Pendle Finance is a yield trading protocol that splits yield-bearing tokens (stETH, aUSDC, wstETH, GLP, etc.) into two components: <strong style={{color:S.text}}>PT (Principal Token)</strong> and <strong style={{color:S.text}}>YT (Yield Token)</strong>. These can then be traded independently, allowing users to lock in fixed yields, speculate on yield rates, or maximize yield exposure.</p>
<p style={{color:S.text2,lineHeight:1.8}}>Think of it like the DeFi equivalent of interest rate derivatives — a financial primitive that has traditionally only existed in TradFi (bonds, interest rate swaps).</p>
</section>

<section style={{marginBottom:36}}>
<h2 style={{fontSize:"1.5rem",fontWeight:800,marginBottom:16,color:C}}>PT vs YT: Core Mechanics</h2>
{[
["PT (Principal Token)","Redeems for 1 unit of the underlying asset at maturity. Trading at a discount before maturity — this discount represents the fixed yield. Example: buy PT-stETH for 0.95 ETH, redeem for 1 ETH at maturity → ~5% fixed APY regardless of future stETH rates."],
["YT (Yield Token)","Entitles the holder to all yield generated by the underlying asset until maturity. If yield rates rise, YT becomes more valuable. High risk, high reward — YT can go to near-zero if yields collapse."],
].map(([t,d])=>(
<div key={String(t)} style={{background:S.surface,border:`1px solid ${S.border}`,borderRadius:10,padding:"14px 16px",marginBottom:10}}>
<div style={{fontWeight:700,color:C,fontSize:13,marginBottom:4}}>{t}</div>
<div style={{color:S.text2,fontSize:13,lineHeight:1.6}}>{d}</div>
</div>
))}
</section>

<section style={{marginBottom:36}}>
<h2 style={{fontSize:"1.5rem",fontWeight:800,marginBottom:12,color:C}}>Strategies</h2>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(200px,1fr))",gap:10}}>
{[["🔒 Lock Fixed Yield","Buy PT to guarantee a fixed APY regardless of market conditions. Great for risk-averse yield seekers.","Conservative"],["📈 Long Yield","Buy YT to speculate that yields will increase. Leveraged yield exposure — high risk.","Aggressive"],["💧 Provide Liquidity","Add to PT/SY AMM pools to earn swap fees + PENDLE incentives. More complex IL profile.","Intermediate"],["🔄 Arbitrage","Trade between PT and spot when implied fixed yield diverges from market rates.","Advanced"]].map(([e,d,lv])=>(
<div key={String(e)} style={{background:S.surface,border:`1px solid ${S.border}`,borderRadius:10,padding:"14px 16px"}}>
<div style={{fontSize:18,marginBottom:6}}>{String(e).split(" ")[0]}</div>
<div style={{fontWeight:700,fontSize:13,marginBottom:4,color:C}}>{String(e).replace(/^[^\s]+\s/,"")}</div>
<div style={{fontSize:12,color:S.text2,lineHeight:1.5,marginBottom:6}}>{d}</div>
<div style={{fontSize:10,fontWeight:700,color:S.yellow}}>Level: {lv}</div>
</div>
))}
</div>
</section>

<div style={{background:`linear-gradient(135deg,${C}15,${S.purple}10)`,border:`1px solid ${C}30`,borderRadius:14,padding:"20px 24px",display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:16}}>
<div><div style={{fontWeight:800,fontSize:16,marginBottom:4}}>Trade yield on Pendle</div><div style={{color:S.text2,fontSize:13}}>Complete the Pendle quiz and earn +150 XP</div></div>
<div style={{display:"flex",gap:10}}>
<a href="https://app.pendle.finance" target="_blank" rel="noopener noreferrer" style={{padding:"10px 20px",background:C,color:"#000",borderRadius:8,fontWeight:700,fontSize:13,textDecoration:"none"}}>Open Pendle ↗</a>
<Link href="/quiz" style={{padding:"10px 20px",background:`${S.purple}20`,color:S.purple,border:`1px solid ${S.purple}40`,borderRadius:8,fontWeight:700,fontSize:13,textDecoration:"none"}}>Take Quiz +150 XP</Link>
</div>
</div>

        {/* Live Price Chart */}
        <section style={{ marginBottom: 40 }}>
          <h2 style={{ fontSize: "1.4rem", fontWeight: 800, marginBottom: 16 }}>Live Price Chart</h2>
          <TradingViewChart symbol="BINANCE:PENDLEUSDT" height={420} />
        </section>

      </article>
</main>);}
