import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `What Is a Consensus Mechanism? (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Learn what consensus mechanisms are, how Proof of Work and Proof of Stake differ, and why consensus is fundamental to blockchain security and decentralization.",
  keywords: ["consensus mechanism", "proof of work", "proof of stake", "blockchain consensus", "distributed consensus"],
};

export default function ConsensusMechanismPage() {
  return (
    <LearnPageLayout title="What Is a Consensus Mechanism?" categoryName="Glossary" categorySlug="learn/glossary" readTime="5 min" intro="A consensus mechanism is the process by which a distributed network of nodes agrees on the current state of the blockchain. Since there is no central authority in a decentralized network, consensus mechanisms provide the rules that determine which transactions are valid and which blocks are added to the chain. The two most prominent consensus mechanisms are Proof of Work (PoW) and Proof of Stake (PoS), each with distinct trade-offs in security, energy consumption, and decentralization."
      toc={[{ id: "definition", title: "Definition", level: 2 },{ id: "proof-of-work", title: "Proof of Work", level: 2 },{ id: "proof-of-stake", title: "Proof of Stake", level: 2 },{ id: "other-mechanisms", title: "Other Mechanisms", level: 2 },{ id: "comparison", title: "Comparison", level: 2 }]}
      faqs={[
        { question: "Why do blockchains need consensus mechanisms?", answer: "Without a central authority, distributed networks face the challenge of agreeing on which transactions are valid and in what order they occurred. Consensus mechanisms solve this by creating economic incentives for honest behavior and making it prohibitively expensive to attack the network. Without consensus, anyone could double-spend tokens or create conflicting versions of the blockchain." },
        { question: "Which consensus mechanism is best?", answer: "There is no universally best consensus mechanism — each involves trade-offs. Proof of Work provides battle-tested security but consumes significant energy. Proof of Stake is energy-efficient but concentrates power among large holders. Newer mechanisms like Delegated Proof of Stake offer high throughput but sacrifice some decentralization. The best choice depends on a network's specific priorities." },
        { question: "Can a blockchain change its consensus mechanism?", answer: "Yes, but it is a major undertaking. Ethereum successfully transitioned from Proof of Work to Proof of Stake in September 2022 during 'The Merge.' Such transitions require extensive testing, community consensus, and careful coordination to avoid chain splits or security vulnerabilities during the transition period." },
      ]}
      relatedArticles={[
        { title: "Decentralization", href: "/learn/glossary/decentralization", category: "Glossary" },
        { title: "Hash Rate", href: "/learn/glossary/hash-rate", category: "Glossary" },
        { title: "What Is Staking?", href: "/learn/what-is-staking", category: "Learn" },
        { title: "Finality", href: "/learn/glossary/finality", category: "Glossary" },
      ]}
    >
      <section id="definition"><h2>Definition</h2><p>A consensus mechanism is a fault-tolerant protocol used by blockchain networks to achieve agreement among distributed nodes on the state of the ledger. In computer science, this relates to the Byzantine Generals Problem — how can distributed actors coordinate when some may be dishonest or unreliable? Blockchain consensus mechanisms solve this by creating rules where following the protocol honestly is more profitable than cheating, typically through economic incentives (block rewards) and economic penalties (wasted energy or slashed stake). The mechanism must ensure that all honest nodes eventually agree on the same transaction history, even in the presence of malicious actors.</p></section>
      <section id="proof-of-work"><h2>Proof of Work</h2><p>Proof of Work (PoW) requires miners to expend computational energy solving cryptographic puzzles to propose new blocks. The first miner to find a valid solution earns the right to add the next block and receives a block reward. The difficulty of these puzzles adjusts automatically to maintain a consistent block time. PoW security comes from the massive energy investment required — attacking the network requires controlling over 50% of the total computational power, which becomes prohibitively expensive as the network grows. Bitcoin, Litecoin, and Dogecoin use Proof of Work, with Bitcoin's network consuming more energy than many small countries.</p></section>
      <section id="proof-of-stake"><h2>Proof of Stake</h2><p>Proof of Stake (PoS) selects block validators based on the amount of cryptocurrency they have staked (locked) as collateral. Validators are chosen pseudorandomly, weighted by their stake size, and they earn rewards for proposing and attesting to valid blocks. If a validator acts dishonestly — such as trying to approve conflicting transactions — their staked tokens are slashed (partially or fully destroyed). Ethereum, Cardano, Solana, and most modern blockchains use variations of Proof of Stake, which requires approximately 99.95% less energy than Proof of Work while maintaining strong security guarantees.</p></section>
      <section id="other-mechanisms"><h2>Other Mechanisms</h2><p>Beyond PoW and PoS, numerous alternative consensus mechanisms exist. Delegated Proof of Stake (DPoS), used by EOS and Tron, allows token holders to vote for a limited set of validators, increasing throughput at some cost to decentralization. Proof of Authority (PoA) relies on a set of pre-approved validators, suitable for private or consortium blockchains. Proof of History (PoH), pioneered by Solana, creates a verifiable timestamp for events to improve ordering efficiency. Byzantine Fault Tolerance (BFT) variants like Tendermint, used by Cosmos, achieve fast finality through multi-round voting among validators.</p></section>
      <section id="comparison"><h2>Comparison</h2><p>The choice of consensus mechanism fundamentally shapes a blockchain's characteristics. Proof of Work maximizes security and decentralization but limits throughput to roughly 7-30 transactions per second and requires enormous energy expenditure. Proof of Stake dramatically reduces energy usage and can support higher throughput, but may lead to wealth concentration as larger stakers earn proportionally more rewards. BFT-based systems offer instant finality and high throughput but typically require a known, limited validator set. The blockchain trilemma — the difficulty of simultaneously optimizing security, decentralization, and scalability — means every consensus mechanism involves inherent trade-offs that protocol designers must navigate.</p></section>
    </LearnPageLayout>
  );
}
