import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `How to Participate in Crypto Governance (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Guide to participating in cryptocurrency governance including voting on proposals, delegating, forums, and governance platforms like Snapshot and Tally.",
  keywords: ["crypto governance", "DAO voting", "governance tokens", "Snapshot voting", "on-chain governance", "governance participation"],
};

export default function HowToParticipateInGovernancePage() {
  return (
    <LearnPageLayout title="How to Participate in Governance" categoryName="Crypto Education" categorySlug="learn" readTime="7 min" intro="Cryptocurrency governance allows token holders to shape protocol development, treasury spending, and parameter changes through voting. Participation in governance is a fundamental right of token ownership and a responsibility that strengthens the decentralized ecosystem. This guide explains how governance works and how to participate effectively."
      toc={[{ id: "overview", title: "How Governance Works", level: 2 },{ id: "platforms", title: "Governance Platforms", level: 2 },{ id: "voting", title: "Voting on Proposals", level: 2 },{ id: "delegation", title: "Delegation", level: 2 },{ id: "getting-involved", title: "Getting More Involved", level: 2 }]}
      faqs={[
        { question: "Do I need to lock my tokens to vote?", answer: "It depends on the protocol. Some governance systems use snapshot voting where tokens stay in your wallet. Others require locking or staking tokens in a governance contract. Some use vote-escrow models (veTokens) where longer lock periods give more voting power." },
        { question: "What is governance delegation?", answer: "Delegation allows you to assign your voting power to another address (a delegate) who votes on your behalf. You retain ownership of your tokens and can undelegate at any time. This is useful if you want to participate indirectly without following every proposal." },
        { question: "Can small holders make a difference?", answer: "Yes. Many governance decisions pass with low participation rates, meaning even small holdings can be impactful. Active participation in forum discussions, supporting quality delegates, and voting consistently amplifies your influence beyond raw token weight." },
      ]}
      relatedArticles={[
        { title: "What Is a DAO?", href: "/learn/what-is-a-dao", category: "Learn" },
        { title: "How to Use Multisig", href: "/learn/how-to-use-multisig", category: "Learn" },
        { title: "What Is Tokenomics?", href: "/learn/what-is-tokenomics", category: "Learn" },
        { title: "Cardano Ecosystem Guide", href: "/learn/cardano-ecosystem-guide", category: "Learn" },
      ]}
    >
      <section id="overview"><h2>How Governance Works</h2><p>Most DeFi protocols use token-based governance where holding governance tokens (UNI, AAVE, COMP, etc.) grants voting rights on protocol decisions. Proposals typically go through a multi-stage process: informal discussion on forums, formal proposal submission, a voting period, and if approved, execution (either automatically through on-chain governance or through multisig implementation).</p><p>Governance decisions can include protocol parameter changes (fee adjustments, collateral requirements), treasury spending (grants, partnerships, development funding), protocol upgrades and new features, and emergency actions in response to security events. The scope of governance varies by protocol — some have broad governance over all aspects, while others limit governance to specific parameters.</p></section>
      <section id="platforms"><h2>Governance Platforms</h2><p>Snapshot is the most popular off-chain governance platform, allowing gasless voting through signed messages. Tally provides an interface for on-chain governance on protocols using Governor contracts. Commonwealth hosts governance forums and discussions. Each protocol typically specifies which platform it uses for formal voting, with forum discussions happening on platforms like Discourse or Commonwealth.</p><p>On-chain governance (Compound Governor, OpenZeppelin Governor) executes approved proposals automatically through smart contracts, providing trustless execution but requiring gas fees for voting. Off-chain governance (Snapshot) is gasless and more accessible but requires trusted execution of results. Many protocols use a hybrid approach: off-chain voting for sentiment and direction, on-chain execution for implementation.</p></section>
      <section id="voting"><h2>Voting on Proposals</h2><p>To vote: connect your wallet to the governance platform, browse active proposals, read the proposal details and discussion, and cast your vote (typically For, Against, or Abstain). For Snapshot votes, you sign a message with no gas fee. For on-chain votes, you submit a transaction and pay gas. Your voting power is typically proportional to your token holdings at a specific snapshot block.</p><p>Before voting, read the full proposal and any linked analysis or discussion. Consider the proposer's track record, the technical feasibility of the proposal, its impact on different stakeholders, and whether adequate security review has been conducted for technical changes. Thoughtful voting that considers the protocol's long-term health contributes more than reflexive voting on every proposal.</p></section>
      <section id="delegation"><h2>Delegation</h2><p>If you cannot follow every proposal, delegate your voting power to a trusted representative. Visit the protocol's governance interface, find the delegation section, enter the delegate's address, and confirm the transaction. Your tokens remain in your wallet — only your voting power is assigned. You can change your delegate or reclaim your voting power at any time.</p><p>Choose delegates who are active, knowledgeable about the protocol, transparent about their voting rationale, and aligned with your values for the protocol's direction. Many governance platforms display delegate profiles with their voting history, proposals they have supported, and their stated governance philosophy. Delegation improves governance participation by allowing informed specialists to vote on behalf of passive token holders.</p></section>
      <section id="getting-involved"><h2>Getting More Involved</h2><p>Beyond voting, you can contribute to governance by participating in forum discussions, providing analysis on proposals, writing your own proposals, and joining governance working groups or committees. Many protocols offer governance incentives (compensation for active delegates, grants for governance contributors) that reward meaningful participation.</p><p>Start by reading through recent proposals and discussions to understand the current priorities and dynamics of the protocol's governance. Join the governance Discord or Telegram channels. Contribute constructive feedback on proposals. As you build expertise and reputation, you may be able to submit your own proposals or become a recognized delegate. Active governance participation is one of the most impactful ways to contribute to the protocols you use.</p></section>
    </LearnPageLayout>
  );
}
