import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Hardware Wallet Setup Guide (${CURRENT_YEAR}) - Step by Step | ${SITE_NAME}`,
  description: `Complete hardware wallet setup guide for ${CURRENT_YEAR}. Step-by-step instructions for Ledger, Trezor, and other hardware wallets. Secure your crypto with cold storage.`,
  alternates: { canonical: "/wallets/learn/hardware-wallet-setup-guide" },
};

const toc = [
  { id: "before-setup", title: "Before You Start", level: 2 },
  { id: "initial-setup", title: "Initial Device Setup", level: 2 },
  { id: "seed-phrase-backup", title: "Backing Up Your Seed Phrase", level: 2 },
  { id: "connecting-apps", title: "Connecting to Wallet Apps", level: 2 },
  { id: "first-transaction", title: "Your First Transaction", level: 2 },
];

const faqs = [
  { question: "Should I buy a Ledger or Trezor?", answer: "Both are excellent and secure. Ledger uses a secure element chip (similar to credit cards) and supports more cryptocurrencies and chains. Trezor uses an open-source design that the community can audit. Ledger Nano X and Trezor Model T / Safe 3 are the most popular models. Choose based on your chain requirements and preference for closed vs open-source security models." },
  { question: "Is it safe to buy a hardware wallet from Amazon?", answer: "We recommend buying only from the manufacturer's official website or authorized retailers. Third-party marketplaces like Amazon carry the risk of tampered devices where the seed phrase has been pre-generated by the attacker. If you do buy from Amazon, verify the seller is the official brand store, check for any signs of tampering, and ensure the device generates a new seed phrase during setup." },
  { question: "How do I know if my hardware wallet has been tampered with?", answer: "Check for intact packaging seals and holographic stickers. The device should require initialization when first powered on, generating a fresh seed phrase. If a device comes with a pre-filled seed phrase card or asks you to use specific recovery words, it has been tampered with and should not be used. Contact the manufacturer immediately." },
  { question: "Can I use a hardware wallet with DeFi?", answer: "Yes. Hardware wallets can connect to DeFi through browser extension wallets like MetaMask or Rabby. Your keys stay on the hardware device while you use the software wallet's interface to interact with dApps. Each transaction must be physically confirmed on the hardware wallet, adding a security layer to DeFi interactions." },
  { question: "What happens if my hardware wallet breaks?", answer: "Your funds are safe. A hardware wallet is just a key; your crypto exists on the blockchain. If your device breaks, buy a replacement hardware wallet and restore it using your seed phrase. This is why seed phrase backup is the most critical step in the setup process. The physical device is replaceable; your seed phrase is not." },
];

const relatedArticles = [
  { title: "Hot vs Cold Wallets", href: "/wallets/learn/hot-vs-cold-wallets", category: "Wallets" },
  { title: "Passphrase vs Seed Phrase", href: "/wallets/learn/passphrase-vs-seed-phrase", category: "Wallets" },
  { title: "Wallet Recovery Guide", href: "/wallets/learn/wallet-recovery-guide", category: "Wallets" },
  { title: "Best Hardware Wallets", href: "/wallets/best/hardware", category: "Wallets" },
];

export default function HardwareWalletSetupGuidePage() {
  return (
    <LearnPageLayout
      title="Hardware Wallet Setup Guide: Secure Your Crypto Step by Step"
      categoryName="Crypto Wallets"
      categorySlug="wallets"
      readTime="10 min"
      intro="Setting up a hardware wallet is the most important security step you can take as a crypto holder. A hardware wallet stores your private keys on a dedicated offline device, protecting your assets from malware, phishing, and remote attacks. This step-by-step guide walks you through the entire setup process, from unboxing to making your first secure transaction."
      toc={toc}
      faqs={faqs}
      relatedArticles={relatedArticles}
    >
      <h2 id="before-setup">Before You Start</h2>
      <p>
        Purchase your hardware wallet directly from the manufacturer&apos;s official website. Ledger
        (ledger.com) and Trezor (trezor.io) are the two most trusted brands. Avoid third-party
        sellers where devices could be tampered with. When your device arrives, inspect the packaging
        for signs of tampering: broken seals, missing holographic stickers, or pre-opened packaging.
        The device should be completely blank and require initialization when first powered on.
      </p>
      <p>
        Prepare your setup environment. Choose a private, secure location. Do not set up your
        hardware wallet in public or where someone could observe your screen or seed phrase. Have
        a pen ready to write down your seed phrase (the device will display it during setup). Better
        yet, have a metal seed phrase backup plate ready for permanent storage. Ensure your computer
        or phone is free of malware and up to date before connecting the device.
      </p>

      <h2 id="initial-setup">Initial Device Setup</h2>
      <p>
        Connect your hardware wallet to your computer or phone using the provided cable (or
        Bluetooth for wireless models). Follow the on-screen instructions to initialize the
        device. You will be asked to choose a PIN code. Select a strong PIN that you will
        remember but that others cannot guess. Avoid simple sequences like 1234 or your birthday.
        The PIN protects against physical access to the device.
      </p>
      <p>
        The device will then generate your seed phrase. This is the most critical moment of
        setup. The screen will display 12 or 24 words one at a time. Write down every word
        carefully and in exact order. Double-check each word. Most devices will ask you to
        confirm specific words to verify you recorded them correctly. Never skip this verification
        step. Never take a photo of your seed phrase or enter it into any digital device.
      </p>

      <h2 id="seed-phrase-backup">Backing Up Your Seed Phrase</h2>
      <p>
        After recording your seed phrase on paper, transfer it to a more durable medium as soon
        as possible. Metal backup plates from companies like Cryptosteel, Billfodl, or CryptoTag
        allow you to stamp or engrave your seed words onto stainless steel that survives fire,
        water, and physical damage. This one-time investment protects your seed phrase from the
        physical risks that can destroy paper.
      </p>
      <p>
        Store your seed phrase backup in a physically secure location: a fireproof safe at home,
        a bank safety deposit box, or with a trusted family member. Consider creating two backups
        in separate locations to protect against localized disasters. Never store your seed phrase
        and hardware wallet in the same location. If a thief takes both, they have everything they
        need to access your funds (assuming they can bypass or brute-force the device PIN).
      </p>

      <h2 id="connecting-apps">Connecting to Wallet Apps</h2>
      <p>
        Install the manufacturer&apos;s official companion app: Ledger Live for Ledger devices or
        Trezor Suite for Trezor devices. These apps manage your accounts, display balances, and
        facilitate sending and receiving crypto. Install the blockchain apps you need on the
        hardware wallet (Bitcoin app, Ethereum app, etc.) through the companion software. Each
        blockchain requires its own app on the device.
      </p>
      <p>
        For DeFi and dApp access, connect your hardware wallet to a browser extension wallet
        like MetaMask or Rabby. In MetaMask, choose &quot;Connect Hardware Wallet&quot; and follow
        the prompts. This lets you use MetaMask&apos;s familiar interface while all transaction
        signing happens on the hardware wallet. You get the convenience of a software wallet with
        the security of hardware signing. Always verify transaction details on the hardware
        wallet&apos;s screen before confirming.
      </p>

      <h2 id="first-transaction">Your First Transaction</h2>
      <p>
        Start with a small test transaction. Send a small amount of crypto to your hardware
        wallet address. Verify the address on the hardware wallet&apos;s screen matches what is shown
        on your computer. After the transaction confirms on the blockchain, verify the balance
        appears in your companion app. This test confirms everything is working correctly before
        you transfer larger amounts.
      </p>
      <p>
        Once your test succeeds, you can transfer your main holdings to the hardware wallet.
        Always verify the receiving address on the hardware wallet&apos;s physical screen, not just
        on your computer screen (which could be manipulated by malware). For large transfers,
        consider sending in multiple smaller transactions rather than one large one. After all
        transfers are complete, verify your total balance and test sending a small amount from
        the hardware wallet to confirm outgoing transactions also work properly.
      </p>
    </LearnPageLayout>
  );
}
