import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Tokenomics Explained (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Understand crypto tokenomics including supply mechanics, token distribution, vesting schedules, inflation, burns, and utility. Essential for investment analysis.",
  keywords: ["tokenomics", "token supply", "token distribution", "vesting schedule", "token burns"],
};

export default function Page() {
  return (
    <LearnPageLayout title="Tokenomics Explained" categoryName="Crypto Investing" categorySlug="investing" readTime="8 min" intro="Tokenomics — the economics of a token — determines the supply and demand dynamics that ultimately drive price. Understanding tokenomics is essential for evaluating any crypto investment because even the best technology with poor token design can underperform. This guide breaks down the key tokenomic factors that separate good investments from value traps." toc={[
        { id: "supply", title: "supply", level: 2 },
        { id: "supply-mechanics", title: "Supply Mechanics", level: 2 },
        { id: "distribution", title: "distribution", level: 2 },
        { id: "token-distribution-and-vesting", title: "Token Distribution and Vesting", level: 2 },
        { id: "utility", title: "utility", level: 2 },
        { id: "token-utility-and-demand-drivers", title: "Token Utility and Demand Drivers", level: 2 },
        { id: "red-flags", title: "red-flags", level: 2 },
        { id: "tokenomics-red-flags", title: "Tokenomics Red Flags", level: 2 }
      ]} faqs={[{question:"What makes good tokenomics?",answer:"Good tokenomics align incentives between the project and token holders. Key characteristics include reasonable supply inflation, fair distribution between team and community, meaningful token utility that drives demand, transparent vesting schedules, and sustainable value accrual mechanisms. The best tokenomics create positive feedback loops where protocol growth increases token demand."},{question:"Should I invest in deflationary tokens?",answer:"Deflationary mechanics (burning tokens) reduce supply over time, which is generally positive for price if demand remains constant. However, deflation alone does not make a good investment. A token can be deflationary and still decline if demand drops faster than supply. Evaluate burn mechanisms alongside utility, adoption metrics, and competitive positioning."},{question:"How important are vesting schedules?",answer:"Very important. Large upcoming unlocks can create significant selling pressure. If 30% of a token's supply unlocks over the next year, early investors and team members receiving these tokens often sell at least a portion. Check Token Unlocks and similar platforms to understand the unlock schedule before investing."}]} relatedArticles={[{title:"Crypto Valuation Methods",href:"/investing/learn/crypto-valuation-methods",category:"Investing"},{title:"What Is Market Cap",href:"/investing/learn/what-is-market-cap",category:"Investing"},{title:"Crypto Whitepaper Guide",href:"/investing/learn/crypto-whitepaper-guide",category:"Investing"}]}>
      <section id="supply"><h2>Supply Mechanics</h2><p>Token supply determines the scarcity equation that influences price. Fixed supply tokens like Bitcoin (21 million cap) have predetermined scarcity that increases over time as adoption grows against a finite supply. Inflationary tokens like Ethereum pre-merge continuously create new tokens, though Ethereum&apos;s EIP-1559 burn mechanism can make it deflationary during high usage. Understanding the difference between circulating supply, total supply, and maximum supply is crucial. Circulating supply represents tokens currently tradeable. Total supply includes minted tokens that may be locked or vesting. Maximum supply is the theoretical cap if one exists. The inflation rate — the speed at which new tokens enter circulation — directly impacts holding returns. A token appreciating 20% annually while inflating at 15% provides only 5% real returns. Emission schedules determine how quickly new tokens are created, with many projects following declining emission curves that reduce inflation over time. Bitcoin&apos;s halving every four years is the most well-known emission reduction mechanism, but most proof-of-stake networks also have their own supply dynamics that investors must understand.</p></section>
      <section id="distribution"><h2>Token Distribution and Vesting</h2><p>How tokens are distributed at launch and over time reveals the project&apos;s priorities and creates structural supply dynamics. Typical distribution includes team and advisor allocations (10-25%), venture capital investors (10-30%), ecosystem and community incentives (20-40%), treasury reserves (5-15%), and public sale (5-20%). Heavy allocation to insiders (team plus investors exceeding 50%) creates concentration risk and substantial future selling pressure. Vesting schedules dictate when these locked tokens become tradeable. Standard vesting includes a cliff period (typically 6-12 months of no unlocking) followed by linear or milestone-based vesting over 2-4 years. Monitor upcoming unlocks carefully — large vesting events where millions of dollars worth of tokens become liquid often coincide with price declines as recipients take profits. Token Unlocks and similar platforms track vesting schedules across projects. Fair launch projects that distributed tokens primarily through community participation rather than venture capital funding often have more distributed ownership and less concentrated selling pressure.</p></section>
      <section id="utility"><h2>Token Utility and Demand Drivers</h2><p>Token utility creates the demand side of the supply-demand equation. Governance tokens grant voting rights over protocol parameters and treasury allocation — their value depends on the importance of governance decisions and treasury size. Fee tokens must be used to access protocol services, creating demand proportional to protocol usage. Staking tokens secure the network and earn rewards, creating a yield incentive to hold. Collateral tokens serve as backing for other assets, locking supply and creating structured demand. Work tokens grant operators the right to perform services and earn fees within the protocol. The strongest tokenomics create multiple demand drivers simultaneously. Ethereum, for example, serves as gas payment, staking collateral, DeFi collateral, and an ecosystem store of value. Value accrual mechanisms determine how protocol success translates to token value — fee distribution to stakers, buyback and burn programs, and governance over growing treasuries are common mechanisms. Without clear value accrual, a token can function as a donation to the protocol rather than an investment.</p></section>
      <section id="red-flags"><h2>Tokenomics Red Flags</h2><p>Several tokenomic patterns consistently precede poor investment outcomes. Extreme insider allocation where team and investors hold over 50% of supply concentrates control and creates massive selling pressure during vesting unlocks. Very low initial circulating supply (under 10% of total) combined with high FDV suggests the current price is artificially inflated by scarcity that will diminish as tokens unlock. No clear token utility beyond speculation means demand depends entirely on greater-fool dynamics. Unlimited supply with no burn mechanism or decreasing inflation leads to perpetual dilution. Hidden or opaque token allocations suggest the team is concealing unfavorable distribution. Frequent tokenomics changes through governance indicate instability and potential manipulation. Unusually high staking yields (above 20% annually) often signal unsustainable inflation-funded rewards that dilute non-stakers. Complex rebasing or elastic supply mechanisms can obscure real returns and confuse investors. Always read the full token documentation and cross-reference with on-chain data before investing based on tokenomics claims.</p></section>
    </LearnPageLayout>
  );
}
