import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Crypto Portfolio Strategies (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Build a winning crypto portfolio with proven strategies. Core-satellite, barbell, and thematic approaches for different risk profiles and goals.",
  keywords: ["crypto portfolio", "portfolio strategy", "crypto allocation", "portfolio management"],
};

export default function Page() {
  return (
    <LearnPageLayout title="Crypto Portfolio Strategies" categoryName="Crypto Investing" categorySlug="investing" readTime="8 min" intro="A well-structured crypto portfolio balances growth potential with risk management. Rather than randomly accumulating tokens, applying deliberate portfolio strategies helps you align your crypto holdings with your financial goals, risk tolerance, and investment timeline. This guide covers proven frameworks adapted for the crypto market." toc={[
        { id: "core-satellite", title: "core-satellite", level: 2 },
        { id: "core-satellite-strategy", title: "Core-Satellite Strategy", level: 2 },
        { id: "barbell", title: "barbell", level: 2 },
        { id: "barbell-strategy", title: "Barbell Strategy", level: 2 },
        { id: "thematic", title: "thematic", level: 2 },
        { id: "thematic-investing", title: "Thematic Investing", level: 2 },
        { id: "management", title: "management", level: 2 },
        { id: "ongoing-portfolio-management", title: "Ongoing Portfolio Management", level: 2 }
      ]} faqs={[{question:"How many different cryptocurrencies should I hold?",answer:"Most experts recommend 5-15 positions for adequate diversification without over-dilution. Holding too few concentrates risk, while holding too many makes it difficult to monitor positions and dilutes the impact of winners. Your core holdings (Bitcoin, Ethereum) should represent 50-70% of the portfolio, with the remainder in carefully selected altcoins."},{question:"Should I invest in Bitcoin only?",answer:"A Bitcoin-only strategy is a valid, lower-risk approach to crypto investing. Bitcoin has the longest track record, deepest liquidity, and strongest institutional adoption. However, diversifying into other quality projects like Ethereum and select altcoins offers higher growth potential with increased risk. Your approach should match your risk tolerance."},{question:"How often should I rebalance my crypto portfolio?",answer:"Quarterly rebalancing works well for most investors, restoring target allocations without excessive trading costs. Threshold-based rebalancing — adjusting when positions deviate more than 5-10% from targets — is more responsive to market moves. Avoid daily or weekly rebalancing as frequent trading increases tax events and transaction costs."}]} relatedArticles={[{title:"Crypto Diversification Guide",href:"/investing/learn/crypto-diversification-guide",category:"Investing"},{title:"Rebalancing Crypto Portfolio",href:"/investing/learn/rebalancing-crypto-portfolio",category:"Investing"},{title:"Crypto Investment Risks",href:"/investing/learn/crypto-investment-risks",category:"Investing"}]}>
      <section id="core-satellite"><h2>Core-Satellite Strategy</h2><p>The core-satellite approach divides your portfolio into a stable core and speculative satellites. The core, typically 60-80% of your portfolio, consists of large-cap, established assets — primarily Bitcoin and Ethereum. These assets provide relative stability, deep liquidity, and proven staying power through multiple market cycles. The satellite portion, 20-40% of the portfolio, holds higher-risk, higher-potential positions in emerging projects, newer Layer 1s, DeFi tokens, or sector-specific bets. This structure ensures your overall portfolio is anchored by assets most likely to survive long-term while giving you upside exposure to potential breakout projects. The core positions require less active management, while satellite positions demand more research and monitoring. When satellite positions perform exceptionally well, trim them back to target allocation, effectively converting speculative gains into core holdings. This disciplined approach prevents the common mistake of having an entire portfolio in high-risk altcoins that may not survive bear markets.</p></section>
      <section id="barbell"><h2>Barbell Strategy</h2><p>The barbell strategy, borrowed from Nassim Taleb&apos;s risk framework, concentrates holdings at two extremes while avoiding the middle. In crypto, this means holding the most conservative assets (Bitcoin, stablecoins earning yield) alongside small positions in high-risk, high-reward opportunities (early-stage tokens, new protocol tokens, meme coins with community momentum). The middle ground — mid-cap altcoins with moderate risk and moderate potential — is deliberately avoided. The logic is that mid-cap altcoins offer neither the safety of Bitcoin nor the explosive upside of small-cap discoveries. A typical barbell might be 70% Bitcoin and stablecoin yield positions with 30% split across 10-15 small speculative bets. Most speculative positions will fail, but the few that succeed can deliver outsized returns that more than compensate. The conservative side protects your capital base while the speculative side captures tail-risk upside. This approach requires strict position sizing on the speculative side — no single bet should exceed 3-5% of total portfolio value.</p></section>
      <section id="thematic"><h2>Thematic Investing</h2><p>Thematic portfolios concentrate on specific crypto sectors you believe will outperform. Common themes include DeFi infrastructure (Aave, Uniswap, Lido, Maker), Layer 2 scaling (ARB, OP, MATIC, zkSync), real-world asset tokenization (Ondo, Centrifuge, Maple), decentralized physical infrastructure or DePIN (Helium, Render, Filecoin), gaming and metaverse (IMX, GALA, AXS), and AI-crypto convergence (FET, RNDR, OCEAN). Thematic investing works best when you have deep conviction and knowledge in a specific area, allowing you to identify winners within that theme. The risk is theme-level failure — if the narrative shifts away from your chosen sector, the entire portfolio suffers. Mitigate this by spreading across 2-3 themes and maintaining a core Bitcoin and Ethereum position alongside thematic bets. Research each theme thoroughly, understanding the technology, competitive landscape, and adoption metrics. Monitor theme-specific developments and be willing to rotate themes as the market evolves and new narratives emerge.</p></section>
      <section id="management"><h2>Ongoing Portfolio Management</h2><p>Portfolio strategy does not end at initial allocation — ongoing management determines long-term success. Set specific allocation targets for each position and rebalance quarterly or when positions deviate significantly from targets. Use portfolio tracking tools like CoinGecko, CoinMarketCap portfolios, or dedicated apps like Delta and CoinStats to monitor positions across exchanges and wallets. Document your investment thesis for each position — why you bought it, what success looks like, and what would make you sell. Review these theses periodically and sell positions where the thesis has been invalidated regardless of whether you are at a profit or loss. Track your portfolio performance against benchmarks — at minimum, compare against a simple Bitcoin-only strategy to ensure your active management is adding value. Consider tax implications when rebalancing, as each sale is a taxable event. Use tax-loss harvesting strategically during downturns to offset gains. Keep a cash or stablecoin reserve for buying opportunities during market corrections rather than being fully invested at all times.</p></section>
    </LearnPageLayout>
  );
}
