import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `What Are Crypto Trading Pairs? (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Learn what trading pairs are, how to read them, and how they affect your trading. Understand base currencies, quote currencies, and cross pairs." };

export default function Page() {
  return (<LearnPageLayout title="What Are Crypto Trading Pairs?" categoryName="Crypto Exchanges" categorySlug="exchanges" readTime="7 min" intro="Trading pairs are the foundation of every crypto exchange. They define what you are buying and what you are paying with. Understanding how pairs work, how to read them, and how they affect liquidity and pricing is fundamental to effective trading." toc={[{id:"basics",title:"Trading Pair Basics",level:2},{id:"reading-pairs",title:"How to Read Trading Pairs",level:2},{id:"types",title:"Types of Trading Pairs",level:2},{id:"liquidity-impact",title:"How Pairs Affect Liquidity",level:2},{id:"choosing-pairs",title:"Choosing the Right Pair",level:2}]} faqs={[{question:"What does BTC/USDT mean?",answer:"BTC/USDT means you are trading Bitcoin against Tether (USDT). BTC is the base currency (what you buy/sell) and USDT is the quote currency (what you pay with). A price of 50,000 means 1 BTC costs 50,000 USDT."},{question:"Why are there multiple pairs for the same coin?",answer:"Different pairs exist for different quote currencies. BTC/USDT, BTC/USD, BTC/EUR, and BTC/ETH all let you trade Bitcoin but against different currencies. Liquidity and fees may differ between pairs."},{question:"Should I trade against USDT or USD?",answer:"USDT pairs typically have higher liquidity on most exchanges. USD pairs are available on US exchanges and provide direct fiat settlement. Both work well — choose based on your exchange and liquidity needs."}]} relatedArticles={[{title:"Liquidity Explained",href:"/exchanges/learn/liquidity-explained",category:"Exchanges"},{title:"Order Types Explained",href:"/exchanges/learn/order-types-explained",category:"Exchanges"}]}>
      <section id="basics"><h2>Trading Pair Basics</h2><p>A trading pair consists of two currencies: the base currency and the quote currency. The base currency is listed first and is what you are buying or selling. The quote currency is listed second and is what you are paying with or receiving. In the pair ETH/USDT, ETH is the base and USDT is the quote. When you buy this pair, you spend USDT to receive ETH. When you sell, you give up ETH and receive USDT. The price shown for a pair represents how much of the quote currency is needed to buy one unit of the base currency.</p></section>
      <section id="reading-pairs"><h2>How to Read Trading Pairs</h2><p>If BTC/USDT is priced at 50,000, it means 1 Bitcoin costs 50,000 USDT. If ETH/BTC is priced at 0.05, it means 1 ETH costs 0.05 BTC. Cross pairs like ETH/BTC allow you to trade directly between two cryptocurrencies without converting to a stablecoin or fiat first. This can be more efficient when you want to rotate between crypto assets.</p></section>
      <section id="types"><h2>Types of Trading Pairs</h2><p>Stablecoin pairs (BTC/USDT, ETH/USDC) are the most liquid and commonly traded. Fiat pairs (BTC/USD, ETH/EUR) provide direct fiat settlement. Crypto-to-crypto pairs (ETH/BTC, SOL/ETH) allow direct swaps between assets. Some exchanges also offer pairs against their native tokens (BTC/BNB on Binance). The most liquid pairs on any exchange are typically BTC/USDT and ETH/USDT.</p></section>
      <section id="liquidity-impact"><h2>How Pairs Affect Liquidity</h2><p>Different pairs for the same asset can have dramatically different liquidity. BTC/USDT might have $100 million in 24-hour volume on an exchange, while BTC/EUR might have only $5 million. Trading on less liquid pairs results in wider spreads and more slippage. Always check the order book depth and 24-hour volume for your specific pair before trading significant amounts.</p></section>
      <section id="choosing-pairs"><h2>Choosing the Right Pair</h2><p>Choose pairs based on liquidity, fees, and your end goal. If you want to cash out to USD, trading against a USD pair eliminates an extra conversion step. If you want maximum liquidity, trade against USDT. If you want to rebalance between crypto assets, use cross pairs. Some exchanges offer fee discounts on specific pairs, so check the fee schedule for your chosen pairs.</p></section>
    </LearnPageLayout>);
}
