import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `How to Claim a Crypto Airdrop (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Guide to claiming cryptocurrency airdrops safely including eligibility checks, claim process, tax implications, and how to avoid airdrop scams.",
  keywords: ["crypto airdrop", "claim airdrop", "how to claim airdrop", "airdrop guide", "token airdrop", "airdrop eligibility"],
};

export default function HowToClaimAirdropPage() {
  return (
    <LearnPageLayout title="How to Claim an Airdrop" categoryName="Crypto Education" categorySlug="learn" readTime="7 min" intro="Airdrops distribute free tokens to wallet addresses that meet certain eligibility criteria — typically based on past protocol usage, governance participation, or community involvement. While legitimate airdrops can provide significant value, the space is also rife with scams. This guide covers how to safely check eligibility and claim airdrops."
      toc={[{ id: "what-are-airdrops", title: "What Are Airdrops?", level: 2 },{ id: "eligibility", title: "Checking Eligibility", level: 2 },{ id: "claiming", title: "How to Claim", level: 2 },{ id: "safety", title: "Airdrop Safety", level: 2 },{ id: "taxes", title: "Tax Implications", level: 2 }]}
      faqs={[
        { question: "How do I become eligible for airdrops?", answer: "Use protocols actively — bridge assets, swap tokens, provide liquidity, participate in governance, and engage with testnet deployments. Many airdrops reward early adopters and active users. There is no guaranteed formula, but genuine protocol usage across multiple chains increases your chances." },
        { question: "Are airdrops taxable?", answer: "In most jurisdictions, airdropped tokens are taxable as income at their fair market value when received. Subsequent gains or losses from selling are subject to capital gains tax. Keep records of claim dates and token values at the time of receipt. Consult a tax professional for your specific situation." },
        { question: "How do I know if an airdrop is legitimate?", answer: "Legitimate airdrops are announced through official project channels (verified Twitter, official Discord, project website). They never ask for your seed phrase. Claim pages are hosted on official project domains. Be extremely suspicious of airdrop notifications from unknown sources." },
      ]}
      relatedArticles={[
        { title: "Crypto Scams Guide", href: "/learn/crypto-scams-guide", category: "Learn" },
        { title: "How to Do Crypto Taxes", href: "/learn/how-to-do-crypto-taxes", category: "Learn" },
        { title: "How to Use DeFi", href: "/learn/how-to-use-defi", category: "Learn" },
        { title: "Phishing Attacks in Crypto", href: "/learn/phishing-attacks-crypto", category: "Learn" },
      ]}
    >
      <section id="what-are-airdrops"><h2>What Are Airdrops?</h2><p>Airdrops are token distributions from projects to community members, typically used to decentralize token ownership, reward early adopters, and bootstrap governance participation. Major airdrops like Uniswap's UNI, Arbitrum's ARB, and Optimism's OP distributed significant value to users who had interacted with these protocols before the token launch.</p><p>Projects determine eligibility based on on-chain activity: protocol usage, transaction history, governance participation, liquidity provision, and other verifiable on-chain actions. Some airdrops also reward social contributions, testnet participation, or holding specific NFTs. Eligibility criteria are usually announced retroactively, meaning the activities that qualify were performed before the airdrop was announced.</p></section>
      <section id="eligibility"><h2>Checking Eligibility</h2><p>When a project announces an airdrop, they typically provide an eligibility checker on their official website. Enter your wallet address to see if you qualify and how many tokens you can claim. Only use eligibility checkers on official project domains — phishing sites frequently create fake checkers that steal wallet credentials. Verify the URL through official social media announcements.</p><p>To maximize future airdrop eligibility: use protocols genuinely (not just for farming), interact across multiple chains, participate in governance, provide liquidity, use protocols during their early stages, and engage with testnet deployments. Sybil detection systems are increasingly sophisticated at identifying and excluding addresses that engage in inauthentic activity solely for airdrop farming.</p></section>
      <section id="claiming"><h2>How to Claim</h2><p>The claim process typically involves: navigating to the official claim page, connecting your eligible wallet, reviewing the claim amount, approving the claim transaction, and paying gas fees. Some airdrops require claiming within a specific time window — unclaimed tokens may be returned to the protocol treasury or redistributed after the deadline.</p><p>After claiming, tokens will appear in your wallet. You can hold them for governance participation and potential appreciation, sell them on exchanges or DEXs, or use them in DeFi protocols. Consider the tax implications of your decision — selling immediately establishes a clear cost basis, while holding defers capital gains tax but introduces price risk.</p></section>
      <section id="safety"><h2>Airdrop Safety</h2><p>Airdrop scams are extremely common. Red flags include: unsolicited airdrop notifications (real airdrops do not DM you), claim pages asking for seed phrases (never legitimate), unknown tokens appearing in your wallet with instructions to visit a website (phishing bait), and claim pages on unofficial domains. Always verify through official channels before interacting with any claim page.</p><p>Use a separate wallet with minimal funds for claiming airdrops from less established projects. Do not interact with random tokens that appear in your wallet — some are designed to steal funds when you try to sell or transfer them. Before claiming, verify the claim contract address against official announcements. If something feels suspicious, wait and watch for community confirmation before claiming.</p></section>
      <section id="taxes"><h2>Tax Implications</h2><p>Airdropped tokens are generally treated as income in most tax jurisdictions. The taxable amount is the fair market value at the time of receipt (when you claim, not when the airdrop is announced). Record the date of claim, the number of tokens received, and their market value at that time. This establishes your cost basis for future capital gains calculations when you sell.</p><p>Some jurisdictions may treat airdrops differently depending on whether you actively claimed them versus receiving them automatically. Tax treatment of airdrops is an evolving area of tax law. Maintain detailed records and consider consulting a crypto-knowledgeable tax professional, especially for large airdrops that could result in significant tax liability.</p></section>
    </LearnPageLayout>
  );
}
