import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Self-Repaying Crypto Loans (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Learn about self-repaying loans in DeFi. Understand how protocols like Alchemix use yield to automatically repay your debt over time.",
  keywords: ["self repaying loans", "alchemix", "auto repaying crypto loan", "yield backed loans"],
};

export default function SelfRepayingLoansPage() {
  return (
    <LearnPageLayout
      title="Self-Repaying Crypto Loans"
      categoryName="Crypto Loans"
      categorySlug="crypto-loans"
      readTime="8 min"
      intro="Self-repaying loans are a DeFi innovation where your deposited collateral earns yield that automatically pays down your loan over time. Instead of making manual repayments, the yield generated by your collateral gradually reduces your debt until it reaches zero. This concept, pioneered by Alchemix, represents one of the most creative applications of DeFi composability."
      toc={[
        { id: "how-they-work", title: "how-they-work", level: 2 },
        { id: "how-self-repaying-loans-work", title: "How Self-Repaying Loans Work", level: 2 },
        { id: "alchemix", title: "alchemix", level: 2 },
        { id: "alchemix-protocol", title: "Alchemix Protocol", level: 2 },
        { id: "pros-cons", title: "pros-cons", level: 2 },
        { id: "advantages-and-limitations", title: "Advantages and Limitations", level: 2 },
        { id: "alternatives", title: "alternatives", level: 2 },
        { id: "alternatives-and-variations", title: "Alternatives and Variations", level: 2 }
      ]}
      faqs={[
        { question: "Can I really never be liquidated?", answer: "On Alchemix specifically, there is no liquidation risk because the maximum LTV is 50% and your collateral yield only reduces debt. Since your debt can never exceed your collateral value at the 50% ratio, liquidation is unnecessary. However, smart contract risk and yield source risk still apply." },
        { question: "How long does it take for the loan to repay itself?", answer: "The repayment timeline depends on the yield rate. At 5% yield on a 50% LTV loan, the loan would take approximately 10 years to fully self-repay. Higher yields speed this up. You can also make additional manual payments to accelerate repayment." },
      ]}
      relatedArticles={[
        { title: "Crypto Loan Strategies", href: "/crypto-loans/learn/crypto-loan-strategies", category: "Crypto Loans" },
        { title: "How Crypto Loans Work", href: "/crypto-loans/learn/how-crypto-loans-work", category: "Crypto Loans" },
      ]}
    >
      <section id="how-they-work">
        <h2>How Self-Repaying Loans Work</h2>
        <p>Self-repaying loans deposit your collateral into yield-generating strategies and use the earned yield to automatically reduce your outstanding debt. You deposit an asset like ETH or DAI, receive an advance of up to 50% of the deposited value as a synthetic asset, and the remaining collateral earns yield that pays down the loan. No manual repayment is required. The loan gradually pays itself off as yield accrues. There is no liquidation risk because the maximum LTV is designed to ensure collateral always exceeds debt. The tradeoff is lower capital efficiency compared to traditional lending, since you can only borrow up to 50% of your deposit and the yield that would normally go to you instead services the debt.</p>
      </section>
      <section id="alchemix">
        <h2>Alchemix Protocol</h2>
        <p>Alchemix is the pioneer and most prominent self-repaying loan protocol. When you deposit ETH, it goes into a yield-generating vault (like Yearn or Aave) and you receive alETH, a synthetic asset pegged to ETH. You can borrow up to 50% of your deposit as alETH, which can be exchanged for regular ETH. As the vault generates yield, your debt decreases automatically. Alchemix V2 supports multiple collateral types including DAI, USDC, ETH, and WSTETH, each with their own yield strategies and synthetic token. The protocol has been audited and operates on Ethereum and Optimism. Alchemix's design eliminates liquidation risk entirely, making it one of the safest borrowing options in DeFi from a position management perspective, though smart contract and yield source risks remain.</p>
      </section>
      <section id="pros-cons">
        <h2>Advantages and Limitations</h2>
        <p>The primary advantage is eliminating liquidation risk and manual repayment requirements. This makes self-repaying loans ideal for long-term borrowers who want set-and-forget positions. The psychological benefit of never worrying about margin calls or market volatility affecting your loan is significant. However, limitations are meaningful. The 50% maximum LTV is lower than most traditional lending protocols that offer 65-80% or more. You forfeit the yield on your collateral since it services the debt, meaning the effective borrowing cost equals the forgone yield. Synthetic assets like alETH may not be as liquid or widely accepted as regular ETH or stablecoins. Repayment timelines can be very long at current yield rates. Smart contract risk from both Alchemix and the underlying yield strategies creates layered exposure.</p>
      </section>
      <section id="alternatives">
        <h2>Alternatives and Variations</h2>
        <p>While Alchemix pioneered the concept, other protocols offer variations on self-repaying mechanics. Some lending protocols allow you to manually route collateral yield to debt repayment, creating a DIY self-repaying loan. Depositing yield-bearing collateral like stETH on Aave and using the staking yield to periodically repay debt achieves a similar outcome with more flexibility. Abracadabra allows borrowing against yield-bearing tokens, where collateral yield effectively reduces your net borrowing cost even though repayment is not automatic. These alternatives typically offer higher LTV and more flexibility but require active management and carry liquidation risk. The choice between true self-repaying loans and yield-enhanced traditional borrowing depends on your priorities: convenience and safety versus capital efficiency and flexibility.</p>
      </section>
    </LearnPageLayout>
  );
}
