import { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `What Is GameFi (GAFI)? Price, Guide & How to Buy (${CURRENT_YEAR}) | CryptoDegen`,
  description: "Learn about GameFi (GAFI), the blockchain gaming aggregator and launchpad. Discover GAFI tokenomics and how to buy.",
};

export default function GamefiPage() {
  return (
    <LearnPageLayout title="What Is GameFi (GAFI)? Price, Guide & How to Buy" categoryName="Investing" categorySlug="investing" readTime="8 min read" intro="GameFi (GAFI) is a blockchain gaming hub that combines a launchpad, game aggregator, marketplace, and yield farming into a single platform. The project aims to serve as a one-stop destination for blockchain gaming discovery, investment, and participation. GAFI is the utility token that powers the platform's launchpad tiers, staking, and governance." toc={[{id:"what-is",title:"What Is GameFi?",level:2},{id:"how-it-works",title:"How Does GameFi Work?",level:2},{id:"tokenomics",title:"GAFI Tokenomics",level:2},{id:"use-cases",title:"Key Use Cases",level:2},{id:"how-to-buy",title:"How to Buy GAFI",level:2},{id:"risks",title:"Risks and Considerations",level:2}]} faqs={[{question:"What is GameFi?",answer:"GameFi is a blockchain gaming hub with a launchpad, game aggregator, and marketplace. GAFI is the utility token for launchpad access, staking, and governance."},{question:"Where can I buy GAFI?",answer:"GAFI is available on Gate.io, KuCoin, and PancakeSwap."},{question:"Is GameFi a good investment?",answer:"GameFi provides access to blockchain gaming launches and discovery. Its value depends on deal flow quality and the platform maintaining relevance in a competitive launchpad space."}]} relatedArticles={[{title:"Best Cryptos to Buy",href:"/investing/best/cryptos-to-buy",category:"Investing"},{title:"How to Invest in Crypto",href:"/investing/learn/how-to-invest-in-crypto",category:"Investing"}]}>
      <section id="what-is"><h2>What Is GameFi?</h2><p>GameFi (not to be confused with the broader GameFi sector) is a platform that aggregates blockchain gaming opportunities including token launches, NFT drops, and gaming yield opportunities. The platform features a curated game hub where users can discover and track blockchain games, a launchpad for new game token sales, and a marketplace for gaming assets. The name "GameFi" captures the intersection of gaming and DeFi that the platform aims to serve.</p><p>The platform operates primarily on BNB Chain and Ethereum, supporting games across multiple blockchain networks. GameFi has hosted multiple token launches and NFT sales, establishing itself within the blockchain gaming launchpad ecosystem alongside competitors like Seedify and Enjinstarter.</p></section>
      <section id="how-it-works"><h2>How Does GameFi Work?</h2><p>GameFi operates a tiered staking system where GAFI stakers receive allocations to participate in Initial NFT Offerings (INOs) and token launches. The game aggregator provides data, reviews, and metrics for blockchain games across chains. The marketplace enables cross-game NFT trading. The platform also features yield farming opportunities where users can stake gaming tokens for rewards. GameFi conducts research and vetting on projects before listing them for launches, providing a curation layer for quality control.</p></section>
      <section id="tokenomics"><h2>GAFI Tokenomics</h2><p>GAFI has a total supply of 24 million tokens, a relatively small supply designed to drive value through scarcity. Distribution includes ecosystem development, team, investors, and community. GAFI staking for launchpad tiers locks significant supply, reducing circulation during active launch periods. Platform fees from marketplace transactions and launches are used for token buybacks and burns. The small supply means even modest demand from launchpad participation can significantly impact circulating tokens.</p></section>
      <section id="use-cases"><h2>Key Use Cases</h2><p>GAFI is used for launchpad tier staking, governance over platform decisions, marketplace fee discounts, premium game hub features, and yield farming participation. The token connects the various GameFi platform services under a unified access and governance model.</p></section>
      <section id="how-to-buy"><h2>How to Buy GAFI</h2><p>GAFI is available on Gate.io, KuCoin, and PancakeSwap. After purchasing, GAFI can be staked on the platform for launchpad access. Store in MetaMask configured for BNB Chain or Ethereum.</p></section>
      <section id="risks"><h2>Risks and Considerations</h2><p>The gaming launchpad space is crowded with multiple platforms competing for the same projects and users. GameFi shares its name with the broader blockchain gaming sector, which can cause brand confusion. The platform's deal flow depends on the pipeline of new blockchain games, which is cyclical. Post-launch token performance for launchpad projects varies widely, and poor outcomes erode user trust. The aggregator model requires constant content updates and curation to remain useful. Low trading volume for GAFI creates liquidity risk for larger positions. The platform must differentiate through deal quality and user experience to survive market consolidation.</p></section>
    </LearnPageLayout>
  );
}
