import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Air-Gapped Wallets Guide (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Learn how air-gapped crypto wallets work, why they offer maximum security, and which devices support fully offline transaction signing via QR codes.",
  keywords: ["air-gapped wallet", "offline signing", "QR code wallet", "cold storage"],
};

export default function Page() {
  return (
    <LearnPageLayout title="Air-Gapped Wallets Guide" categoryName="Crypto Wallets" categorySlug="wallets" readTime="8 min" intro="Air-gapped wallets represent the highest level of hardware wallet security by never connecting to a computer or phone through any wired or wireless channel. Instead, they communicate entirely through QR codes or microSD cards, eliminating entire categories of attack vectors." toc={[
        { id: "what-is", title: "what-is", level: 2 },
        { id: "what-is-an-air-gapped-wallet", title: "What Is an Air-Gapped Wallet?", level: 2 },
        { id: "how-works", title: "how-works", level: 2 },
        { id: "how-air-gapped-signing-works", title: "How Air-Gapped Signing Works", level: 2 },
        { id: "devices", title: "devices", level: 2 },
        { id: "top-air-gapped-devices", title: "Top Air-Gapped Devices", level: 2 },
        { id: "tradeoffs", title: "tradeoffs", level: 2 },
        { id: "trade-offs-and-limitations", title: "Trade-offs and Limitations", level: 2 }
      ]} faqs={[{question:"Is air-gapped signing really more secure?",answer:"Yes. By eliminating USB, Bluetooth, and Wi-Fi connections, air-gapped wallets remove entire categories of attack vectors including malicious USB firmware attacks, Bluetooth exploits, and network-based key extraction. The only communication channel is visual QR codes, which are human-verifiable."},{question:"Which wallets support air-gapped mode?",answer:"Keystone, Coldcard, Blockstream Jade, Foundation Passport, and NGRAVE ZERO all support air-gapped operation. Keystone and Jade use QR codes via built-in cameras, while Coldcard uses microSD cards for transaction transfer."},{question:"Can I use an air-gapped wallet for DeFi?",answer:"Yes, though the process is slower. You create transactions in a companion app, transfer them to the air-gapped device via QR code, sign on the device, and transfer the signed transaction back. This works for any transaction type but adds several seconds to each interaction."}]} relatedArticles={[{title:"Best Security Wallets",href:"/wallets/best/security",category:"Best Of"},{title:"Hardware Wallet Firmware Updates",href:"/wallets/learn/hardware-wallet-firmware-updates",category:"Wallets"},{title:"Jade Wallet Review",href:"/wallets/reviews/jade-wallet",category:"Review"}]}>
      <section id="what-is"><h2>What Is an Air-Gapped Wallet?</h2><p>An air-gapped wallet is a hardware wallet that operates completely disconnected from any network or direct device connection. Unlike standard hardware wallets that connect via USB or Bluetooth, air-gapped wallets communicate with companion apps exclusively through QR codes displayed on screen and scanned by camera, or through microSD card transfer. This physical isolation — the air gap — means there is no electronic pathway for malware to reach the device or for keys to leak out through a compromised connection. Even the most sophisticated remote attacks cannot extract keys from a device that has no electronic communication channel. This makes air-gapped wallets the most paranoia-justified security solution for cryptocurrency storage.</p></section>
      <section id="how-works"><h2>How Air-Gapped Signing Works</h2><p>The air-gapped signing workflow involves several steps. First, you create an unsigned transaction in a companion app on your phone or computer. This app displays the transaction as a QR code. You then use the air-gapped wallet&apos;s camera to scan this QR code, which transfers the transaction data to the device optically. The wallet displays the transaction details on its own screen for verification — recipient address, amount, and fees. After you confirm, the wallet signs the transaction using the private key stored in its secure element and displays the signed transaction as a new QR code on its screen. You scan this QR code with your phone camera, and the companion app broadcasts the signed transaction to the blockchain. At no point do the private keys leave the air-gapped device through any channel.</p></section>
      <section id="devices"><h2>Top Air-Gapped Devices</h2><p>Keystone is a premium air-gapped wallet with a large touchscreen and camera that supports Bitcoin and many altcoins through QR code signing. It integrates with MetaMask, Rabby, and other software wallets. Coldcard supports air-gapped operation via microSD card for Bitcoin transactions, offering the most paranoid Bitcoin security with features like anti-duress PINs and brick-me PINs. Blockstream Jade provides budget-friendly air-gapped Bitcoin signing through its built-in camera and color display. Foundation Passport offers a premium air-gapped Bitcoin experience with open-source firmware and a distinctive design. NGRAVE ZERO uses a proprietary key generation process and QR communication for maximum security. Each device targets slightly different user profiles but shares the fundamental air-gapped security model.</p></section>
      <section id="tradeoffs"><h2>Trade-offs and Limitations</h2><p>Air-gapped wallets add friction to every transaction. The QR code scanning process takes additional time compared to USB-connected signing, making rapid-fire DeFi interactions slower. Complex transactions may require multiple QR code scans due to data size limitations. Initial setup and firmware updates also require the QR or microSD workflow, which is more involved than USB-based updates. Some users find the multiple-step signing process tedious for frequent transactions. The ideal use case for air-gapped wallets is long-term cold storage where transactions are infrequent and security is paramount. For daily DeFi trading, a standard hardware wallet connected via USB to a browser extension provides a better balance of security and convenience.</p></section>
    </LearnPageLayout>
  );
}
