import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `How to Use a Hardware Wallet (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Complete guide to using hardware wallets including Ledger and Trezor setup, sending and receiving, DeFi integration, and security best practices.",
  keywords: ["hardware wallet", "Ledger tutorial", "Trezor guide", "cold wallet", "hardware wallet setup", "crypto hardware wallet"],
};

export default function HowToUseHardwareWalletPage() {
  return (
    <LearnPageLayout title="How to Use a Hardware Wallet" categoryName="Crypto Education" categorySlug="learn" readTime="8 min" intro="Hardware wallets are the gold standard for cryptocurrency security, keeping your private keys isolated from internet-connected devices. By storing keys on a dedicated device, hardware wallets protect against malware, phishing, and remote attacks. This guide covers setup, daily use, and best practices for Ledger, Trezor, and other hardware wallets."
      toc={[{ id: "choosing", title: "Choosing a Hardware Wallet", level: 2 },{ id: "setup", title: "Initial Setup", level: 2 },{ id: "daily-use", title: "Daily Use", level: 2 },{ id: "defi-integration", title: "DeFi Integration", level: 2 },{ id: "best-practices", title: "Security Best Practices", level: 2 }]}
      faqs={[
        { question: "Ledger vs Trezor — which is better?", answer: "Both are excellent choices. Ledger uses a secure element chip and supports more assets natively. Trezor is fully open-source and has a larger touchscreen on premium models. Both have strong security track records. Choose based on your priorities: Ledger for broad asset support, Trezor for open-source transparency." },
        { question: "What if my hardware wallet is lost or broken?", answer: "Your funds are safe as long as you have your seed phrase. Purchase a new hardware wallet (same or different brand) and restore it using your seed phrase. All your wallets and funds will be recovered. This is why secure seed phrase backup is the most critical aspect of hardware wallet ownership." },
        { question: "Can I use a hardware wallet with DeFi?", answer: "Yes, hardware wallets integrate with software wallets like MetaMask and Rabby. You get the convenience of a software wallet interface with the security of hardware key signing. Every transaction must be confirmed on the hardware device, providing a physical verification layer against malicious software." },
      ]}
      relatedArticles={[
        { title: "Self-Custody Guide", href: "/learn/self-custody-guide", category: "Learn" },
        { title: "How to Create a Wallet", href: "/learn/how-to-create-wallet", category: "Learn" },
        { title: "How to Use MetaMask", href: "/learn/how-to-use-metamask", category: "Learn" },
        { title: "Operational Security for Crypto", href: "/learn/operational-security-crypto", category: "Learn" },
      ]}
    >
      <section id="choosing"><h2>Choosing a Hardware Wallet</h2><p>Ledger offers the Nano S Plus (budget-friendly) and Nano X (Bluetooth-enabled) and Stax (touchscreen). All use a secure element chip that is certified for cryptographic operations. Trezor offers the Model One (basic), Model T (touchscreen), and Safe series with improved designs. Both brands support hundreds of cryptocurrencies across multiple blockchains.</p><p>Purchase only from the manufacturer's official website or authorized retailers. Never buy used or third-party hardware wallets — they may have been tampered with to steal funds. Verify the device is sealed and shows no signs of tampering upon arrival. Third-party wallets like Keystone (air-gapped QR code-based) and GridPlus Lattice1 (smartcard-based) offer alternative approaches to hardware security.</p></section>
      <section id="setup"><h2>Initial Setup</h2><p>Connect the device to your computer and install the companion software (Ledger Live for Ledger, Trezor Suite for Trezor). Choose "Set up as new device." The device will generate a random seed phrase and display it on its own screen — never on the computer. Write down every word carefully on the provided recovery sheet. Verify the seed phrase by re-entering it when prompted.</p><p>Set a strong PIN code on the device. Install blockchain apps (Bitcoin, Ethereum, etc.) through the companion software. Your device is now ready to receive and manage cryptocurrency. Before depositing significant funds, test the entire workflow: receive a small amount, verify it appears correctly, and test the recovery process by resetting the device and restoring from your seed phrase.</p></section>
      <section id="daily-use"><h2>Daily Use</h2><p>To receive crypto: open the relevant app on your hardware wallet, navigate to the receive section in the companion software, and verify that the address shown on the computer matches the address displayed on the hardware wallet screen. This verification protects against address-swapping malware. Share the verified address with the sender.</p><p>To send crypto: initiate the transaction in the companion software, verify the recipient address and amount on the hardware wallet's screen (the only trusted display), and confirm the transaction by pressing the hardware wallet's physical buttons. This two-step verification ensures that even if your computer is compromised, the hardware wallet shows the actual transaction details for your review.</p></section>
      <section id="defi-integration"><h2>DeFi Integration</h2><p>Connect your hardware wallet to MetaMask or Rabby for DeFi access: in the software wallet, select "Connect Hardware Wallet" and follow the connection steps. Your hardware wallet address will appear in the software wallet interface. When you interact with DeFi protocols, every transaction must be confirmed on the hardware wallet's physical screen, providing security verification for all DeFi operations.</p><p>This combination gives you the convenience of a browser-based wallet with the security of hardware signing. Review every transaction on the hardware wallet screen before confirming — the device shows the actual contract address, function being called, and values being transferred. Blind signing (confirming without reviewing) defeats the purpose of a hardware wallet. Take time to verify each transaction, especially token approvals and large transfers.</p></section>
      <section id="best-practices"><h2>Security Best Practices</h2><p>Store your seed phrase on metal backup plates in multiple secure, separate locations. Never store it digitally. Keep your hardware wallet firmware updated to receive security patches. Use a strong, unique PIN. Consider setting up a passphrase (25th word) for an additional security layer that creates separate wallets inaccessible without the passphrase.</p><p>Keep your hardware wallet in a secure location when not in use. Be wary of phishing attempts specific to hardware wallet users — fake firmware updates, counterfeit customer support, and malicious companion software are all attack vectors. Only download software from official websites. If you receive unexpected prompts to update firmware or enter your seed phrase, verify through official channels before proceeding.</p></section>
    </LearnPageLayout>
  );
}
