import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `How to Track Your Crypto Portfolio (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Guide to tracking cryptocurrency portfolios including tools, DeFi position tracking, performance metrics, tax preparation, and best practices.",
  keywords: ["crypto portfolio tracker", "track crypto", "portfolio management", "DeFi tracker", "crypto performance", "portfolio tools"],
};

export default function HowToTrackPortfolioPage() {
  return (
    <LearnPageLayout title="How to Track Your Crypto Portfolio" categoryName="Crypto Education" categorySlug="learn" readTime="6 min" intro="As your crypto holdings grow across multiple wallets, chains, exchanges, and DeFi protocols, tracking your portfolio becomes essential. Portfolio trackers aggregate your positions, show real-time values, calculate performance, and help prepare for tax reporting. This guide covers the tools and practices for effective portfolio management."
      toc={[{ id: "why-track", title: "Why Track Your Portfolio?", level: 2 },{ id: "tools", title: "Portfolio Tracking Tools", level: 2 },{ id: "defi-tracking", title: "DeFi Position Tracking", level: 2 },{ id: "metrics", title: "Key Metrics", level: 2 },{ id: "best-practices", title: "Best Practices", level: 2 }]}
      faqs={[
        { question: "What is the best crypto portfolio tracker?", answer: "Popular options include CoinGecko and CoinMarketCap for manual tracking, DeBank and Zapper for on-chain DeFi positions, and Koinly or CoinTracker for tax-focused tracking. The best choice depends on whether you prioritize DeFi visibility, tax preparation, or simple price tracking." },
        { question: "Is it safe to connect my wallet to a tracker?", answer: "Read-only wallet connections (providing your public address) are safe — trackers only need your public address to view holdings, not your private keys. Never connect through wallet signing prompts for portfolio tracking. Some trackers offer manual address input without wallet connection for additional security." },
        { question: "How do I track DeFi positions?", answer: "On-chain portfolio trackers like DeBank, Zapper, and Zerion automatically detect DeFi positions (LP tokens, lending deposits, staked tokens) by reading smart contract data. They show the underlying value of complex positions that may not appear in simple wallet views." },
      ]}
      relatedArticles={[
        { title: "How to Do Crypto Taxes", href: "/learn/how-to-do-crypto-taxes", category: "Learn" },
        { title: "How to Dollar Cost Average", href: "/learn/how-to-dollar-cost-average", category: "Learn" },
        { title: "How to Research Crypto", href: "/learn/how-to-research-crypto", category: "Learn" },
        { title: "What Is TVL?", href: "/learn/what-is-tvl", category: "Learn" },
      ]}
    >
      <section id="why-track"><h2>Why Track Your Portfolio?</h2><p>Portfolio tracking provides clarity on your total crypto exposure, asset allocation, and performance over time. Without tracking, it is easy to lose track of positions across multiple chains, wallets, and protocols — leading to forgotten assets, unbalanced allocations, and difficulty during tax season. A clear portfolio view enables informed decision-making about rebalancing, taking profits, and managing risk.</p><p>Tax preparation is another critical reason: most jurisdictions require reporting crypto gains and losses, which means tracking every acquisition cost, disposal proceeds, and holding period. Manual tracking becomes impractical with frequent trading and DeFi activity. Automated portfolio tracking tools significantly simplify tax compliance by importing transaction history and calculating gains automatically.</p></section>
      <section id="tools"><h2>Portfolio Tracking Tools</h2><p>CoinGecko and CoinMarketCap offer free portfolio tracking with manual entry of holdings and price alerts. DeBank and Zapper automatically detect on-chain holdings and DeFi positions across multiple chains by scanning your wallet addresses. Zerion provides a comprehensive dashboard combining wallet tracking with swap and DeFi functionality.</p><p>Tax-focused trackers like Koinly, CoinTracker, and TokenTax import exchange and wallet transaction history, calculate capital gains, and generate tax reports. These are essential if you have significant trading activity. Most support direct API connections to major exchanges and on-chain transaction import. Choose a tracker based on your primary need: DeFi visibility, tax preparation, or simple portfolio overview.</p></section>
      <section id="defi-tracking"><h2>DeFi Position Tracking</h2><p>DeFi positions are more complex than simple token holdings — LP positions, lending deposits, staked tokens, and farming rewards all need to be tracked. On-chain trackers like DeBank excel at decomposing these positions: showing the underlying tokens in an LP position, accumulated but unclaimed rewards, and the current value of yield-bearing tokens.</p><p>Cross-chain tracking is important as DeFi activity often spans multiple networks. Ensure your tracker supports all chains where you have positions. Some positions may require manual tracking if they use non-standard contracts that automated tools do not recognize. Regularly cross-reference tracker data with actual wallet balances to catch any discrepancies.</p></section>
      <section id="metrics"><h2>Key Metrics</h2><p>Track these portfolio metrics: total portfolio value, asset allocation percentages, profit and loss (unrealized and realized), cost basis per asset, and performance against benchmarks (BTC, ETH, or total market). Understanding whether your portfolio is outperforming or underperforming simple benchmarks helps evaluate your strategy's effectiveness.</p><p>For DeFi positions, monitor: APY and actual returns versus projected, impermanent loss on LP positions, health factors on lending positions, and reward token accumulation. Set alerts for significant portfolio changes, liquidation risk thresholds, and large price movements. Regular monitoring helps you identify and respond to opportunities and risks in a timely manner.</p></section>
      <section id="best-practices"><h2>Best Practices</h2><p>Maintain a consistent tracking system from the beginning of your crypto activity — retroactively reconstructing transaction history is time-consuming and error-prone. Use a single primary tracker supplemented by specialized tools as needed. Record the purpose and strategy behind positions to help future decision-making. Review your portfolio allocation regularly (monthly or quarterly) to assess whether rebalancing is needed.</p><p>Back up important tracking data and export transaction records periodically. If using exchange API connections, use read-only API keys that cannot execute trades. For privacy, be aware that on-chain trackers make your portfolio visible to anyone who knows your addresses. Consider the trade-off between tracking convenience and address privacy when deciding which wallets to track publicly.</p></section>
    </LearnPageLayout>
  );
}
