import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Crypto Trading Journal: Why and How to Keep One (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Learn how to keep an effective crypto trading journal. Track trades, analyze performance, identify patterns, and improve your trading through systematic record-keeping." };

export default function Page() {
  return (<LearnPageLayout title="Crypto Trading Journal" categoryName="Crypto Trading" categorySlug="trading" readTime="7 min" intro="A trading journal is the most underutilized tool for improving trading performance. It transforms trading from random guessing into a systematic, improvable process. By recording every trade and the reasoning behind it, you create a personal database that reveals your strengths, weaknesses, and patterns over time." toc={[
        { id: "why-journal", title: "why-journal", level: 2 },
        { id: "why-keep-a-trading-journal", title: "Why Keep a Trading Journal", level: 2 },
        { id: "what-to-track", title: "what-to-track", level: 2 },
        { id: "what-to-track", title: "What to Track", level: 2 },
        { id: "tools", title: "tools", level: 2 },
        { id: "journal-tools-and-templates", title: "Journal Tools and Templates", level: 2 },
        { id: "review-process", title: "review-process", level: 2 },
        { id: "the-review-process", title: "The Review Process", level: 2 },
        { id: "improving", title: "improving", level: 2 },
        { id: "using-your-journal-to-improve", title: "Using Your Journal to Improve", level: 2 }
      ]} faqs={[{question:"How often should I review my journal?",answer:"Review individual trades daily (or after each session). Do a comprehensive analysis weekly — look at overall statistics, patterns, and emotional trends. Do a deep strategy review monthly, examining win rates and performance by setup type."},{question:"What is the most important thing to journal?",answer:"Your emotional state and reasoning. The trade details (entry, exit, PnL) are important but trackable automatically. The why — your reasoning for entering, how you felt during the trade, and why you exited — is the information only you can capture and is most valuable for improvement."},{question:"Can I just use my exchange trade history instead?",answer:"Exchange history shows what happened but not why. A trading journal adds context: your thesis, emotional state, what you saw on the chart, and lessons learned. This context is what makes a journal valuable for improvement. Use both — exchange data for accuracy, journal for context."}]} relatedArticles={[{title:"Crypto Trading Psychology",href:"/trading/learn/crypto-trading-psychology",category:"Trading"},{title:"Backtesting Strategies",href:"/trading/learn/backtesting-strategies",category:"Trading"},{title:"Crypto Trading Mistakes",href:"/trading/learn/crypto-trading-mistakes",category:"Trading"}]}>
    <section id="why-journal"><h2>Why Keep a Trading Journal</h2><p>Without a journal, you are relying on memory — which is biased, selective, and unreliable. You will remember big wins and big losses but forget the patterns that led to them. A journal provides objective data about your trading performance that memory cannot. It reveals which strategies actually work for you versus which you think work. It shows whether your win rate is improving or declining, which market conditions favor your approach, and whether emotional trading is costing you money. Professional traders at prop firms are required to journal. The traders who improve fastest are consistently those who review their journals most diligently. The habit of journaling also forces you to think critically about each trade, which naturally improves decision-making quality.</p></section>
    <section id="what-to-track"><h2>What to Track</h2><p>Record every trade with the following: date and time, asset and direction (long/short), entry price and reason, stop-loss and take-profit levels, position size and risk amount, exit price and reason, profit or loss in both dollar and percentage terms, timeframe and strategy used, chart screenshot at entry and exit, emotional state before and during the trade, and what you would do differently. Additionally, track daily statistics: number of trades, win rate, total PnL, largest win, largest loss, and whether you followed your trading plan. Tag each trade with the strategy type so you can filter and analyze performance by strategy. Note market conditions: trending, ranging, volatile, calm, news-driven. This lets you identify which conditions are most favorable for your approach.</p></section>
    <section id="tools"><h2>Journal Tools and Templates</h2><p>Spreadsheets (Google Sheets, Excel) offer maximum flexibility and are free. Create columns for each data point and use formulas to calculate running statistics like cumulative PnL, win rate, average R-multiple, and profit factor. Dedicated trading journal platforms like Edgewonk, TraderSync, and Tradervue import trade data automatically from exchanges, calculate advanced statistics, and provide visual analytics. Notion and Obsidian offer a middle ground — flexible note-taking with database capabilities. For chart screenshots, TradingView allows you to annotate and save charts with your analysis. The best journal is the one you will actually use consistently. A simple spreadsheet used daily beats a sophisticated platform used sporadically. Start simple and add complexity as journaling becomes habitual.</p></section>
    <section id="review-process"><h2>The Review Process</h2><p>Daily review (5-10 minutes): Record all trades from the session. Note your emotional state and whether you followed your plan. Identify any rule violations. Weekly review (30-60 minutes): Calculate statistics for the week — win rate, total PnL, average trade, largest winner and loser. Compare to previous weeks. Identify which strategies worked and which did not. Look for emotional patterns that preceded losing trades. Monthly review (1-2 hours): Deep analysis of performance by strategy, asset, timeframe, and market condition. Identify your best-performing setups and your worst. Compare your actual results to your trading plan expectations. Adjust your plan based on data. Quarterly review: Evaluate whether your overall approach is working. Consider major strategic adjustments. The key is consistency — the value of a journal compounds over time as your dataset grows and patterns become clearer.</p></section>
    <section id="improving"><h2>Using Your Journal to Improve</h2><p>After accumulating 50-100 trades, you will have enough data to draw meaningful conclusions. Filter trades by strategy — which setups have the highest win rate and best average R? Focus on those. Filter by market condition — do you perform better in trending or ranging markets? Trade more in favorable conditions and less in unfavorable ones. Filter by time of day or day of week — many traders have systematic time-based patterns in their performance. Look for emotional patterns: does revenge trading follow specific triggers? Does FOMO buying consistently lose money? Quantify these patterns so they become undeniable rather than vague feelings. The most powerful insight often comes from comparing your best and worst trades — what did they have in common? Your journal will reveal your personal edge and your personal weaknesses, allowing you to amplify the former and mitigate the latter.</p></section>
  </LearnPageLayout>);
}
