import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Social Recovery Wallets Explained (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Learn how social recovery wallets use trusted guardians to recover your crypto without seed phrases. How Argent and other smart wallets implement this feature.",
  keywords: ["social recovery", "guardian recovery", "smart wallet", "seedless wallet", "Argent"],
};

export default function Page() {
  return (
    <LearnPageLayout title="Social Recovery Wallets Explained" categoryName="Crypto Wallets" categorySlug="wallets" readTime="7 min" intro="Social recovery wallets replace traditional seed phrases with a guardian-based system. Instead of memorizing words, you designate trusted people or services who can collectively help you regain access to your wallet. This approach eliminates the most common cause of permanent fund loss — lost or destroyed seed phrases." toc={[
        { id: "concept", title: "concept", level: 2 },
        { id: "the-social-recovery-concept", title: "The Social Recovery Concept", level: 2 },
        { id: "guardians", title: "guardians", level: 2 },
        { id: "how-guardians-work", title: "How Guardians Work", level: 2 },
        { id: "wallets", title: "wallets", level: 2 },
        { id: "wallets-that-support-social-recovery", title: "Wallets That Support Social Recovery", level: 2 },
        { id: "best-practices", title: "best-practices", level: 2 },
        { id: "setup-best-practices", title: "Setup Best Practices", level: 2 }
      ]} faqs={[{question:"Can guardians steal my funds?",answer:"No. Guardians can only authorize account recovery to a new device. They cannot initiate transactions, view your balance, or access your funds in any way. The guardian role is strictly limited to approving recovery requests."},{question:"How many guardians should I set up?",answer:"At least three guardians with a majority threshold (2-of-3). More guardians provide more redundancy — a 3-of-5 setup means you can lose contact with two guardians and still recover. Choose guardians who are reliable, technically capable, and unlikely to all become unavailable simultaneously."},{question:"What happens if a guardian loses their device?",answer:"A single guardian losing access does not affect your wallet. You only need a majority to recover. While you still have wallet access, remove the compromised guardian and add a replacement to maintain your recovery threshold."}]} relatedArticles={[{title:"Account Abstraction Wallets",href:"/wallets/learn/account-abstraction-wallets",category:"Wallets"},{title:"Argent Wallet Review",href:"/wallets/reviews/argent",category:"Review"},{title:"Smart Contract Wallets",href:"/wallets/learn/smart-contract-wallets",category:"Wallets"}]}>
      <section id="concept"><h2>The Social Recovery Concept</h2><p>Social recovery addresses the fundamental challenge of self-custody: humans are unreliable at protecting static secrets over long time periods. Seed phrases written on paper get lost, damaged, or stolen. Metal backups can be forgotten in old locations. Social recovery replaces this static secret model with a dynamic trust network. You choose trusted contacts — friends, family, other devices you own, or dedicated recovery services — as guardians. If you lose wallet access, a threshold majority of these guardians can authorize recovery to your new device. The approach leverages the reliability of human relationships rather than depending on physical media preservation. Vitalik Buterin has advocated for social recovery as the preferred wallet security model for mainstream adoption.</p></section>
      <section id="guardians"><h2>How Guardians Work</h2><p>Each guardian is registered on the blockchain through a smart contract that defines the recovery rules. When you need to recover, you initiate a recovery request from your new device. This request is visible to your guardians through their own wallets or through notifications. Each guardian reviews the request and approves it by signing a transaction from their own wallet. Once the required threshold of guardian approvals is reached, the smart contract executes the recovery — transferring wallet control to your new device. Most implementations include a time delay between approval and execution, giving you a window to cancel if someone fraudulently initiates recovery. Guardians never have access to your funds — the smart contract strictly limits their capabilities to the recovery function.</p></section>
      <section id="wallets"><h2>Wallets That Support Social Recovery</h2><p>Argent is the most prominent social recovery wallet, supporting guardians on both its Ethereum mainnet and Starknet wallets. Guardians can be other Argent users, additional devices you own, or Argent&apos;s own recovery service as a backup guardian. Safe (Gnosis Safe) supports social recovery through optional recovery modules that add guardian functionality to multisig wallets. Loopring wallet also implements guardian-based recovery on its Layer 2 network. As account abstraction becomes more widespread through ERC-4337, more wallets are expected to adopt social recovery as a standard feature. The trend is clearly moving toward eliminating seed phrase dependency for mainstream users while maintaining self-custody properties.</p></section>
      <section id="best-practices"><h2>Setup Best Practices</h2><p>Choose guardians who are geographically distributed, technologically competent, and trustworthy. Avoid choosing guardians who might collude (such as business partners with financial incentives). Include at least one institutional guardian — like a dedicated recovery service — as insurance against all personal guardians becoming unavailable. Test the recovery process periodically to ensure guardians remember their role and can complete the approval workflow. Update your guardian list proactively when relationships change — do not wait until you need recovery to discover a guardian is unreachable. Consider including a hardware wallet as one guardian for additional security. Document your guardian list and recovery instructions in your estate plan so heirs can initiate recovery if needed.</p></section>
    </LearnPageLayout>
  );
}
