import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Crypto Scam Protection Guide (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Protect yourself from cryptocurrency scams including rug pulls, Ponzi schemes, fake exchanges, romance scams, and phishing. Learn the warning signs.",
  keywords: ["crypto scams", "scam protection", "rug pull", "Ponzi scheme", "fake exchange"],
};

export default function Page() {
  return (
    <LearnPageLayout title="Crypto Scam Protection Guide" categoryName="Crypto Investing" categorySlug="investing" readTime="8 min" intro="Cryptocurrency scams cost investors billions of dollars annually. The irreversible nature of blockchain transactions, combined with the novelty and complexity of the technology, creates fertile ground for fraudsters. Learning to identify common scam patterns is the most effective protection — most scams follow recognizable templates that become obvious once you know what to look for." toc={[{id:"types",title:"Common Crypto Scam Types",level:2},{id:"warning-signs",title:"Universal Warning Signs",level:2},{id:"due-diligence",title:"Due Diligence Checklist",level:2},{id:"recovery",title:"What to Do If Scammed",level:2}]} faqs={[{question:"Can stolen crypto be recovered?",answer:"In most cases, stolen crypto is extremely difficult to recover. Blockchain transactions are irreversible by design. Some victims have recovered funds through law enforcement working with exchanges to freeze stolen assets, but this requires the scammer to use a regulated exchange and cooperation across jurisdictions. Prevention is far more effective than recovery."},{question:"Are all new crypto projects scams?",answer:"No, but new projects carry inherently higher risk. Many legitimate innovations start as new projects. The key is thorough due diligence — verified team identities, audited smart contracts, transparent tokenomics, and real technology. Scams typically fail multiple due diligence criteria simultaneously."},{question:"How do I report a crypto scam?",answer:"Report to local law enforcement and relevant financial regulatory authorities (SEC, FTC, or equivalent in your country). File reports with the FBI IC3 (US) or Action Fraud (UK). Report phishing sites to Google Safe Browsing and browser vendors. Alert the community through crypto forums and social media to prevent additional victims."}]} relatedArticles={[{title:"Rug Pull Guide",href:"/investing/learn/rug-pull-guide",category:"Investing"},{title:"Pump and Dump Explained",href:"/investing/learn/pump-and-dump-explained",category:"Investing"},{title:"Crypto Investment Risks",href:"/investing/learn/crypto-investment-risks",category:"Investing"}]}>
      <section id="types"><h2>Common Crypto Scam Types</h2><p>Rug pulls occur when developers create a token, build hype, attract investment, then withdraw liquidity and abandon the project with investors&apos; money. Ponzi schemes promise guaranteed high returns funded by new investor deposits rather than legitimate revenue — they collapse when new investment slows. Fake exchange scams create professional-looking trading platforms that accept deposits but never allow withdrawals. Romance scams build emotional relationships to manipulate victims into sending crypto to fraudulent investment platforms. Pig butchering scams combine romance and investment fraud, gradually escalating requests after building trust. Impersonation scams use fake social media profiles of celebrities, influencers, or support staff to solicit payments or seed phrases. Advance fee scams claim you have won or are owed crypto but must pay a fee or tax to receive it. Fake ICO and token sales collect investment for projects that never intend to deliver. Clone phishing creates identical copies of legitimate protocol websites to steal wallet credentials and approvals. Each scam type exploits different psychological vulnerabilities — greed, trust, urgency, fear of missing out, or the desire for easy returns.</p></section>
      <section id="warning-signs"><h2>Universal Warning Signs</h2><p>Guaranteed returns are the single most reliable scam indicator — no legitimate investment guarantees profits, and anyone claiming otherwise is either lying or running an unsustainable scheme. Pressure to invest urgently using artificial deadlines, limited spots, or claims that prices will skyrocket imminently exploits fear of missing out. Requests for your seed phrase or private key are always scams with zero exceptions — no legitimate service, support agent, or airdrop ever needs your seed phrase. Unrealistic annual percentage yields exceeding 100% are almost certainly unsustainable and likely fraudulent. Anonymous or unverifiable team members increase the probability of exit scams. Lack of audited smart contracts for DeFi protocols suggests either negligence or intentional avoidance of scrutiny. Aggressive social media marketing with paid influencers, bot followers, and manufactured engagement often accompanies low-quality or fraudulent projects. Requirements to recruit others to earn returns structure the scheme as a pyramid. Professional-looking websites and documentation do not validate legitimacy — scammers invest in presentation specifically to build false trust.</p></section>
      <section id="due-diligence"><h2>Due Diligence Checklist</h2><p>Before investing in any crypto project, systematically verify these elements. Confirm the team&apos;s identities through LinkedIn, previous projects, and public records — anonymous teams are higher risk. Check for smart contract audits from reputable firms and read the actual audit findings, not just the claim of being audited. Review the token distribution for insider concentration — if the top wallets hold a disproportionate share, large sell-offs can crash the price. Examine the liquidity lock status — legitimate projects lock liquidity for extended periods to prevent rug pulls. Search for the project name combined with scam or warning to find community reports. Verify the project has a functional product or clear development progress, not just promises. Check trading volume on CoinGecko or CoinMarketCap for signs of wash trading (suspiciously consistent volume patterns). Review community channels for genuine organic discussion versus bot activity and paid shilling. Test small transactions before committing significant amounts. Cross-reference project claims with independent sources rather than relying on project-provided information alone.</p></section>
      <section id="recovery"><h2>What to Do If Scammed</h2><p>If you discover you have been scammed, act immediately to limit further damage. Disconnect your wallet from any malicious dApps and revoke all token approvals granted to suspicious contracts. Transfer remaining assets to a new wallet address if your current wallet may be compromised. Document everything — transaction hashes, wallet addresses involved, screenshots of the scam website and communications, and a timeline of events. File reports with law enforcement, your country&apos;s financial regulatory authority, and the FBI&apos;s Internet Crime Complaint Center (IC3) if in the US. Report the scam to the platforms where you encountered it — exchanges, social media companies, and domain registrars can take action against fraudulent operations. Contact blockchain analysis firms like Chainalysis or Crystal if significant amounts are involved — they can sometimes trace funds to exchanges where they may be frozen. Be extremely wary of recovery scam services that promise to retrieve your stolen crypto for a fee — many of these are secondary scams targeting victims who are desperate to recover losses. Share your experience in crypto communities to warn others and prevent additional victims.</p></section>
    </LearnPageLayout>
  );
}
