import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Candlestick Patterns Guide for Crypto Trading (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Master essential candlestick patterns for crypto trading. Learn to read hammers, dojis, engulfing patterns, and multi-candle formations for better trade entries." };

export default function Page() {
  return (<LearnPageLayout title="Candlestick Patterns Guide" categoryName="Crypto Trading" categorySlug="trading" readTime="10 min" intro="Candlestick patterns are one of the oldest and most reliable tools in technical analysis. They reveal the psychology of buyers and sellers within each time period. Learning to recognize key patterns gives you an edge in timing entries and exits across any crypto market." toc={[
        { id: "single-candle", title: "single-candle", level: 2 },
        { id: "single-candle-patterns", title: "Single Candle Patterns", level: 2 },
        { id: "dual-candle", title: "dual-candle", level: 2 },
        { id: "two-candle-patterns", title: "Two-Candle Patterns", level: 2 },
        { id: "triple-candle", title: "triple-candle", level: 2 },
        { id: "three-candle-patterns", title: "Three-Candle Patterns", level: 2 },
        { id: "context", title: "context", level: 2 },
        { id: "context-matters", title: "Context Matters", level: 2 },
        { id: "crypto-application", title: "crypto-application", level: 2 },
        { id: "applying-patterns-in-crypto", title: "Applying Patterns in Crypto", level: 2 }
      ]} faqs={[{question:"Do candlestick patterns work in crypto?",answer:"Yes. Candlestick patterns reflect human psychology, which is consistent across all markets. Crypto's high retail participation often makes patterns even more reliable as traders collectively act on the same recognizable formations."},{question:"What is the most reliable candlestick pattern?",answer:"Engulfing patterns and morning/evening stars tend to be among the most reliable, especially when they form at key support or resistance levels with high volume. No single pattern works in isolation — context and confirmation are essential."},{question:"What timeframe is best for candlestick patterns?",answer:"Higher timeframes (4-hour, daily, weekly) produce more reliable patterns than lower timeframes. On 1-minute charts, patterns are mostly noise. The daily chart is the sweet spot for most swing traders using candlestick analysis."}]} relatedArticles={[{title:"Technical Analysis Basics",href:"/trading/learn/technical-analysis-basics",category:"Trading"},{title:"Chart Patterns Guide",href:"/trading/learn/chart-patterns-guide",category:"Trading"},{title:"Support and Resistance Levels",href:"/trading/learn/support-resistance-levels",category:"Trading"}]}>
    <section id="single-candle"><h2>Single Candle Patterns</h2><p>The hammer has a small body at the top with a long lower wick — at least twice the body length. It signals potential reversal from a downtrend as sellers pushed price down but buyers stepped in strongly. The inverted hammer has a small body at the bottom with a long upper wick, also suggesting bullish reversal potential. The shooting star is the bearish equivalent of the hammer — small body at the bottom with a long upper wick, appearing at the top of an uptrend. Doji candles have nearly equal open and close prices, creating a cross shape. They signal indecision and potential reversal when appearing after a strong trend. The dragonfly doji (long lower wick, no upper wick) is bullish at support, while the gravestone doji (long upper wick, no lower wick) is bearish at resistance. Marubozu candles have large bodies with no wicks, indicating strong conviction in the direction of the candle.</p></section>
    <section id="dual-candle"><h2>Two-Candle Patterns</h2><p>The bullish engulfing pattern occurs when a large green candle completely engulfs the body of the previous red candle — it signals that buyers have overwhelmed sellers. The bearish engulfing is the opposite: a large red candle engulfs the previous green candle. These are among the most reliable reversal patterns. The tweezer bottom features two candles with matching lows at the end of a downtrend, suggesting strong support at that price. Tweezer tops have matching highs at the end of an uptrend. The harami pattern is an inside candle where the second candle's body is completely within the first candle's body — bullish harami at the bottom of downtrends and bearish harami at the top of uptrends signal potential reversals. The piercing line features a bullish candle that opens below and closes above the midpoint of the previous bearish candle.</p></section>
    <section id="triple-candle"><h2>Three-Candle Patterns</h2><p>The morning star is a powerful bullish reversal pattern: a large bearish candle, followed by a small-bodied candle (the star) that gaps lower, followed by a large bullish candle that closes above the midpoint of the first candle. The evening star is the bearish equivalent. Three white soldiers feature three consecutive large bullish candles with each closing near its high and opening within the prior candle's body — a strong bullish continuation signal. Three black crows are the bearish opposite. The three inside up pattern starts with a large bearish candle, followed by a smaller bullish candle within it (harami), followed by a bullish candle that closes above the first candle's open — confirming the reversal. These multi-candle patterns are generally more reliable than single candle patterns because they show a clear shift in market sentiment over multiple periods.</p></section>
    <section id="context"><h2>Context Matters</h2><p>Candlestick patterns are only meaningful in the right context. A hammer pattern is significant at a known support level after a sustained downtrend — the same pattern in the middle of a range is far less meaningful. Always consider where the pattern forms relative to support, resistance, trend lines, and moving averages. Volume should confirm the pattern — a bullish engulfing on high volume is much more significant than one on low volume. The timeframe affects reliability — patterns on daily and weekly charts are more reliable than those on minute charts. The prior trend gives the pattern its meaning — reversal patterns require a preceding trend to reverse. Combine candlestick patterns with other technical tools for higher-probability setups rather than trading patterns in isolation.</p></section>
    <section id="crypto-application"><h2>Applying Patterns in Crypto</h2><p>In crypto markets, candlestick patterns work particularly well because of high retail participation and the self-fulfilling nature of widely watched patterns. Focus on the most reliable patterns first — engulfing patterns, hammers at support, and morning/evening stars. Wait for the pattern to complete before entering. Use the pattern's range for stop-loss placement. For a bullish hammer at support, place your stop below the hammer's low. Target the next resistance level or a measured move based on the pattern's size. Practice identifying patterns in real-time on TradingView by scrolling through historical charts and marking patterns that led to significant moves. Build a catalog of successful pattern examples from your own analysis to develop pattern recognition intuition over time.</p></section>
  </LearnPageLayout>);
}
