import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Impermanent Loss Explained: DeFi's Hidden Cost (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Understand impermanent loss in DeFi liquidity pools. Learn how it works, how to calculate it, and strategies to minimize its impact on your LP returns." };

export default function Page() {
  return (<LearnPageLayout title="Impermanent Loss Explained" categoryName="Crypto Exchanges" categorySlug="exchanges" readTime="9 min" intro="Impermanent loss is one of the most important concepts for anyone providing liquidity on decentralized exchanges. It represents the opportunity cost of holding tokens in a liquidity pool versus simply holding them in your wallet. Understanding it helps you make better decisions about where and when to provide liquidity." toc={[
        { id: "what-is-il", title: "what-is-il", level: 2 },
        { id: "what-is-impermanent-loss", title: "What Is Impermanent Loss?", level: 2 },
        { id: "how-it-works", title: "how-it-works", level: 2 },
        { id: "how-impermanent-loss-works", title: "How Impermanent Loss Works", level: 2 },
        { id: "calculating-il", title: "calculating-il", level: 2 },
        { id: "calculating-impermanent-loss", title: "Calculating Impermanent Loss", level: 2 },
        { id: "real-examples", title: "real-examples", level: 2 },
        { id: "real-world-examples", title: "Real-World Examples", level: 2 },
        { id: "minimizing-il", title: "minimizing-il", level: 2 },
        { id: "strategies-to-minimize-il", title: "Strategies to Minimize IL", level: 2 },
        { id: "when-profitable", title: "when-profitable", level: 2 },
        { id: "when-is-lp-still-profitable", title: "When Is LP Still Profitable?", level: 2 }
      ]} faqs={[{question:"Is impermanent loss permanent?",answer:"It becomes permanent only when you withdraw your liquidity. If token prices return to their original ratio, the loss disappears — hence 'impermanent.' However, prices rarely return to exact original ratios, so some degree of loss is common."},{question:"Can you lose all your money to impermanent loss?",answer:"You cannot lose all your money to impermanent loss alone. In the worst case (one token goes to zero), you lose 100% of that token's value but retain the other token. However, combined with a token price crash, total losses can be severe."},{question:"Do stablecoin pools have impermanent loss?",answer:"Stablecoin pools have minimal impermanent loss because the tokens are designed to maintain similar values. This is why stablecoin LP positions are popular — they earn trading fees with very little IL risk."}]} relatedArticles={[{title:"AMM Explained",href:"/exchanges/learn/amm-explained",category:"Exchanges"},{title:"Decentralized Exchange Guide",href:"/exchanges/learn/decentralized-exchange-guide",category:"Exchanges"},{title:"Liquidity Explained",href:"/exchanges/learn/liquidity-explained",category:"Exchanges"}]}>
    <section id="what-is-il"><h2>What Is Impermanent Loss?</h2><p>Impermanent loss occurs when the price ratio of tokens in a liquidity pool changes compared to when you deposited them. The AMM's constant product formula automatically rebalances your position as prices move, which means you end up with more of the token that decreased in value and less of the token that increased. Compared to simply holding the tokens in your wallet, your pool position is worth less. This difference is the impermanent loss. It is called impermanent because if prices return to their original ratio, the loss reverses. However, if you withdraw while prices are different, the loss is realized and becomes permanent.</p></section>
    <section id="how-it-works"><h2>How Impermanent Loss Works</h2><p>Consider a pool with ETH and USDC. You deposit 1 ETH ($1,000) and 1,000 USDC — total value $2,000. If ETH price doubles to $2,000, arbitrageurs trade against the pool until it reflects the new price. Due to the constant product formula, the pool rebalances so you now have approximately 0.707 ETH and 1,414 USDC — worth $2,828 total. If you had simply held your original 1 ETH and 1,000 USDC, you would have $3,000. The $172 difference is your impermanent loss — about 5.7% in this scenario. The key insight is that the AMM automatically sells your appreciating asset (ETH) as its price rises and buys more of the depreciating asset.</p></section>
    <section id="calculating-il"><h2>Calculating Impermanent Loss</h2><p>Impermanent loss depends solely on the price ratio change, not the direction. The formula is: IL = 2 * sqrt(price_ratio) / (1 + price_ratio) - 1. For a 2x price change (in either direction), IL is approximately 5.7%. For a 3x change, IL is about 13.4%. For a 5x change, IL reaches about 25.5%. For a 10x change, IL is approximately 42.5%. These percentages represent how much less your pool position is worth compared to simply holding. Note that this formula applies to standard 50/50 constant product pools. Concentrated liquidity positions (like Uniswap v3) experience amplified impermanent loss within their specified range.</p></section>
    <section id="real-examples"><h2>Real-World Examples</h2><p>In a bull market where altcoins pump 5-10x, LPs in ETH/altcoin pools can experience 25-42% impermanent loss. If the altcoin then crashes back, the LP now holds mostly the crashed token and less ETH. This is the worst-case scenario: impermanent loss on the way up, then realized value destruction on the way down. Conversely, in stablecoin pools like USDC/USDT, price ratios barely deviate from 1:1, so IL is negligible while trading fees accumulate steadily. This is why experienced LPs often prefer stablecoin pools or pairs where they believe the price ratio will remain relatively stable.</p></section>
    <section id="minimizing-il"><h2>Strategies to Minimize IL</h2><p>Choose correlated pairs where both tokens tend to move together, such as ETH/stETH or USDC/USDT. These pairs experience minimal price ratio changes. Use stable swap AMMs like Curve for stablecoin pairs, as their formula is optimized to minimize IL for pegged assets. With concentrated liquidity, use wider ranges to reduce IL severity, though this decreases fee earnings. Some protocols offer IL protection — Bancor pioneered this concept where the protocol compensates LPs for impermanent loss over time. You can also time your LP entries during periods of low volatility and exit before major market moves if possible. Finally, focus on high-fee pools where trading fee revenue exceeds impermanent loss.</p></section>
    <section id="when-profitable"><h2>When Is LP Still Profitable?</h2><p>Providing liquidity is profitable when trading fee revenue exceeds impermanent loss. High-volume pools with volatile assets generate substantial fees that can more than compensate for IL. The key metric is net APY: fee APY minus IL. A pool generating 50% APY in fees with 10% IL still nets 40% returns. Stablecoin pools typically offer lower fee APY (5-15%) but near-zero IL. Some protocols add token incentives (liquidity mining rewards) that further offset IL. Evaluate each pool holistically: expected price movement of both tokens, historical fee revenue, any additional incentives, and your time horizon. Short-term LP positions during high-volatility periods can be particularly profitable if fees spike.</p></section>
  </LearnPageLayout>);
}
