import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `What Are Crypto Derivatives? (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Learn what crypto derivatives are, how futures, options, and perpetual swaps work, and how derivative markets impact cryptocurrency price discovery.",
  keywords: ["crypto derivatives", "perpetual swap", "crypto futures", "crypto options", "derivative trading"],
};

export default function DerivativesPage() {
  return (
    <LearnPageLayout title="What Are Crypto Derivatives?" categoryName="Glossary" categorySlug="learn/glossary" readTime="5 min" intro="Crypto derivatives are financial contracts whose value is derived from the price of an underlying cryptocurrency. Rather than buying and selling actual tokens, derivatives allow traders to speculate on price movements, hedge existing positions, and access leverage. The crypto derivatives market dwarfs spot trading, with perpetual swap contracts generating trillions of dollars in monthly volume across centralized and decentralized exchanges."
      toc={[{ id: "definition", title: "Definition", level: 2 },{ id: "types", title: "Types of Derivatives", level: 2 },{ id: "perpetual-swaps", title: "Perpetual Swaps", level: 2 },{ id: "defi-derivatives", title: "DeFi Derivatives", level: 2 },{ id: "risks", title: "Risks", level: 2 }]}
      faqs={[
        { question: "What are perpetual swaps?", answer: "Perpetual swaps (perps) are the most popular crypto derivative — they are futures contracts with no expiration date. Traders maintain positions indefinitely, paying or receiving a funding rate every 8 hours that keeps the perpetual price close to the spot price. When most traders are long, longs pay shorts (positive funding rate); when most are short, shorts pay longs. This mechanism ensures the contract price tracks the underlying asset." },
        { question: "How does leverage work in crypto derivatives?", answer: "Leverage allows traders to control a larger position than their deposited capital. With 10x leverage, a $1,000 deposit controls a $10,000 position. This amplifies both gains and losses — a 5% price move creates a 50% gain or loss on the deposited margin. If losses approach the deposited margin, the position is liquidated (forcibly closed), and the trader loses their deposit." },
        { question: "Are crypto derivatives regulated?", answer: "Regulation varies significantly by jurisdiction. In the US, the CFTC oversees crypto derivatives, and most platforms restrict access for US residents. Offshore exchanges like Binance and Bybit offer derivatives globally with less regulatory oversight. DeFi derivatives protocols operate without centralized regulatory compliance, though regulatory frameworks are evolving rapidly worldwide." },
      ]}
      relatedArticles={[
        { title: "What Is DeFi?", href: "/learn/what-is-defi", category: "Learn" },
        { title: "DEX", href: "/learn/glossary/dex", category: "Glossary" },
        { title: "Liquidity Pool", href: "/learn/glossary/liquidity-pool", category: "Glossary" },
        { title: "Oracle", href: "/learn/glossary/oracle", category: "Glossary" },
      ]}
    >
      <section id="definition"><h2>Definition</h2><p>A derivative is a financial instrument whose value depends on (is derived from) the price of an underlying asset. In crypto, the underlying asset is typically a cryptocurrency like Bitcoin or Ethereum. Derivatives allow traders to speculate on price movements without holding the actual asset, access leverage to amplify returns, hedge existing spot positions to reduce risk, and gain exposure to assets that may be difficult to buy directly. The crypto derivatives market has grown to become several times larger than the spot market, heavily influencing price discovery and market dynamics across the entire cryptocurrency ecosystem.</p></section>
      <section id="types"><h2>Types of Derivatives</h2><p>Crypto derivatives include several major categories. Futures contracts obligate parties to buy or sell an asset at a predetermined price on a future date. Options contracts give the holder the right (but not obligation) to buy (call) or sell (put) at a specified price before expiration. Perpetual swaps are futures without expiration dates, maintained through a funding rate mechanism. Structured products combine multiple derivatives into packaged strategies for specific risk-return profiles. Each type serves different purposes — futures for directional bets with defined timeframes, options for asymmetric risk strategies and hedging, and perpetuals for continuous leveraged exposure.</p></section>
      <section id="perpetual-swaps"><h2>Perpetual Swaps</h2><p>Perpetual swaps, invented by BitMEX in 2016, are the dominant crypto derivative by volume. Unlike traditional futures with expiration dates, perps can be held indefinitely. They use a funding rate mechanism — typically calculated every 8 hours — to anchor the contract price to the spot price. When the perp trades above spot (contango), long positions pay short positions, incentivizing selling and pushing the price down. When the perp trades below spot (backwardation), shorts pay longs. Platforms like Binance, Bybit, and dYdX offer perpetuals with leverage up to 100x or more on major pairs, though such extreme leverage makes liquidation almost certain for most traders.</p></section>
      <section id="defi-derivatives"><h2>DeFi Derivatives</h2><p>Decentralized derivatives protocols bring derivative trading on-chain with transparent, non-custodial execution. GMX, dYdX, Synthetix, and Hyperliquid are leading platforms offering perpetual swaps with competitive fees and no KYC requirements. These protocols use various architectures — GMX uses a multi-asset liquidity pool (GLP) as the counterparty to all trades, dYdX uses an off-chain orderbook with on-chain settlement, and Synthetix creates synthetic assets backed by staked SNX tokens. DeFi derivatives solve the counterparty risk inherent in centralized exchanges but introduce smart contract risk and may have lower liquidity for less popular trading pairs.</p></section>
      <section id="risks"><h2>Risks</h2><p>Crypto derivatives carry significant risks beyond standard market risk. Leverage amplifies losses as well as gains — with high leverage, small adverse price movements can liquidate entire positions. Liquidation cascades can create violent price swings when large leveraged positions are forcibly closed, triggering further liquidations in a chain reaction. Funding rates can accumulate to substantial costs for positions held over time. On centralized platforms, traders face counterparty risk if the exchange is hacked or becomes insolvent. On DeFi platforms, smart contract vulnerabilities and oracle manipulation can lead to unexpected losses. The complexity and speed of derivative markets make them unsuitable for inexperienced traders.</p></section>
    </LearnPageLayout>
  );
}
