import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Correlation Trading in Crypto (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Learn correlation trading strategies for crypto. Understand how asset correlations work, how to identify decorrelation opportunities, and how to build diversified portfolios." };

export default function Page() {
  return (<LearnPageLayout title="Correlation Trading" categoryName="Crypto Trading" categorySlug="trading" readTime="8 min" intro="Correlation measures how two assets move relative to each other. Understanding correlations in crypto helps with portfolio diversification, pairs trading, and identifying market regime changes. When correlations break down, they create trading opportunities that technical analysis alone might miss." toc={[
        { id: "understanding", title: "understanding", level: 2 },
        { id: "understanding-correlation", title: "Understanding Correlation", level: 2 },
        { id: "crypto-correlations", title: "crypto-correlations", level: 2 },
        { id: "crypto-correlation-dynamics", title: "Crypto Correlation Dynamics", level: 2 },
        { id: "strategies", title: "strategies", level: 2 },
        { id: "correlation-based-strategies", title: "Correlation-Based Strategies", level: 2 },
        { id: "portfolio", title: "portfolio", level: 2 },
        { id: "portfolio-applications", title: "Portfolio Applications", level: 2 },
        { id: "tools", title: "tools", level: 2 },
        { id: "measuring-correlation", title: "Measuring Correlation", level: 2 }
      ]} faqs={[{question:"Are all cryptos correlated with Bitcoin?",answer:"Most major cryptocurrencies have high correlation with Bitcoin, typically 0.6-0.9 during normal conditions. During market stress, correlations increase further (everything drops together). Some assets (stablecoins, certain DeFi tokens) have lower correlations."},{question:"Do crypto-stock correlations matter?",answer:"Increasingly yes. Since 2020, Bitcoin has shown growing correlation with tech stocks (Nasdaq). This correlation matters for macro-level portfolio construction and for understanding how interest rate decisions and equity market moves might affect crypto."},{question:"Can correlations predict price movements?",answer:"Correlations themselves do not predict price direction. However, changes in correlation can signal regime shifts. When a previously correlated asset starts diverging, it may indicate a change in the fundamental drivers affecting one or both assets."}]} relatedArticles={[{title:"Pairs Trading Crypto",href:"/trading/learn/pairs-trading-crypto",category:"Trading"},{title:"Risk Management Guide",href:"/trading/learn/risk-management-guide",category:"Trading"},{title:"Fundamental Analysis Crypto",href:"/trading/learn/fundamental-analysis-crypto",category:"Trading"}]}>
    <section id="understanding"><h2>Understanding Correlation</h2><p>Correlation is measured on a scale from -1 to +1. A correlation of +1 means two assets move perfectly together. A correlation of -1 means they move perfectly opposite. A correlation of 0 means no relationship. In practice, most crypto assets have positive correlation with each other because they share common market drivers: overall crypto market sentiment, Bitcoin price movements, and macroeconomic factors. Correlation is calculated using historical price data over a specified period — common lookback periods are 30, 60, and 90 days. Short-term correlations can differ significantly from long-term correlations. Importantly, correlation is not causation — two correlated assets may both be responding to a common factor rather than one driving the other. Correlations also change over time, which is both a challenge and an opportunity for traders.</p></section>
    <section id="crypto-correlations"><h2>Crypto Correlation Dynamics</h2><p>Bitcoin acts as the anchor for crypto correlations. During normal markets, most altcoins have 0.5-0.8 correlation with BTC. During market crashes, correlations spike toward 1.0 as all assets sell off together — this is called correlation convergence and is the primary challenge for diversification during market stress. Within the crypto market, sector correlations exist: DeFi tokens tend to correlate highly with each other, Layer-1 tokens move somewhat together, and meme coins cluster. Cross-market correlations between crypto and traditional assets have increased with institutional participation. Bitcoin-Nasdaq correlation has ranged from 0.3 to 0.7 in recent years. Gold-Bitcoin correlation is typically low (0.0-0.3), providing genuine diversification. Stablecoins have near-zero correlation with volatile crypto assets, making them the primary hedge within the crypto ecosystem.</p></section>
    <section id="strategies"><h2>Correlation-Based Strategies</h2><p>Pairs trading identifies two highly correlated assets and trades the spread between them when it deviates from the normal relationship. When the spread widens beyond historical norms, go long the underperformer and short the outperformer, expecting the spread to normalize. Correlation breakdown trading identifies when a previously correlated asset starts diverging — this can signal a fundamental change worth investigating. If ETH suddenly decorrelates from BTC, it may indicate a sector-specific catalyst. Sector rotation uses correlation data to identify which crypto sectors are leading versus lagging, rotating capital toward decorrelating (outperforming) sectors. Risk-on/risk-off trading uses the correlation between crypto and traditional risk assets to anticipate how macro events will affect crypto prices.</p></section>
    <section id="portfolio"><h2>Portfolio Applications</h2><p>Diversification works by combining assets with low or negative correlations. A portfolio of highly correlated assets provides no diversification benefit — when one falls, they all fall together. Seek assets with correlations below 0.5 for meaningful diversification. Include stablecoins (zero correlation), potentially some gold exposure (low correlation), and consider DeFi yield strategies that are partially decorrelated from market direction. Build a correlation matrix for your portfolio and review it monthly. If your portfolio's average pairwise correlation exceeds 0.7, you have concentration risk even if you hold many different tokens. During market stress, remember that correlations spike — what looked diversified in calm markets may behave like a single concentrated position during crashes.</p></section>
    <section id="tools"><h2>Measuring Correlation</h2><p>CoinMetrics provides institutional-grade correlation data across hundreds of crypto assets. IntoTheBlock offers correlation matrices for major cryptocurrencies. TradingView allows you to overlay assets and visually compare their movements, though it does not calculate correlation coefficients directly. For do-it-yourself analysis, export daily closing prices to a spreadsheet and use the CORREL function to calculate pairwise correlations. Python with pandas makes it easy to calculate rolling correlation over any window. Create a heatmap of correlations across your portfolio to visualize relationships. Track how correlations change over time by calculating rolling 30-day and 90-day correlations — when short-term correlations diverge significantly from long-term, it may signal a regime change worth investigating.</p></section>
  </LearnPageLayout>);
}
