import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Self-Custody Guide (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Complete guide to cryptocurrency self-custody including wallet types, seed phrase management, security best practices, and backup strategies.",
  keywords: ["self-custody", "crypto wallet", "seed phrase", "private keys", "hardware wallet", "crypto security"],
};

export default function SelfCustodyGuidePage() {
  return (
    <LearnPageLayout title="Self-Custody Guide" categoryName="Crypto Education" categorySlug="learn" readTime="9 min" intro="Self-custody means holding your own private keys and taking personal responsibility for securing your cryptocurrency. The phrase 'not your keys, not your coins' encapsulates the principle that true ownership in crypto requires controlling your own keys rather than trusting a third party. This guide covers everything you need to know to safely self-custody your digital assets."
      toc={[
        { id: "why-self-custody", title: "Why Self-Custody Matters", level: 2 },
        { id: "wallet-types", title: "Wallet Types", level: 2 },
        { id: "seed-phrases", title: "Seed Phrase Management", level: 2 },
        { id: "security-setup", title: "Security Setup", level: 2 },
        { id: "backup-recovery", title: "Backup & Recovery", level: 2 },
        { id: "common-mistakes", title: "Common Mistakes", level: 2 },
      ]}
      faqs={[
        { question: "What happens if I lose my seed phrase?", answer: "If you lose your seed phrase and your wallet device fails, your funds are permanently inaccessible. No one — not the wallet manufacturer, not blockchain developers, not law enforcement — can recover funds without the seed phrase or private keys. This is why secure backup of your seed phrase is the most critical aspect of self-custody." },
        { question: "Is a hardware wallet necessary?", answer: "For significant holdings, a hardware wallet is strongly recommended. It keeps private keys isolated from internet-connected devices, protecting against malware, phishing, and remote attacks. For small amounts used for everyday DeFi interactions, a software wallet may be sufficient, but hardware wallets provide meaningfully better security." },
        { question: "Can I use multiple wallets?", answer: "Yes, and this is recommended. Use different wallets for different purposes: a hardware wallet for long-term savings, a software wallet for active DeFi use, and a separate hot wallet for interacting with new or unverified protocols. This compartmentalization limits exposure if one wallet is compromised." },
        { question: "What is a passphrase (25th word)?", answer: "A passphrase is an additional word or phrase added to your seed phrase that creates an entirely separate set of wallets. Even if someone finds your seed phrase, they cannot access wallets protected by a passphrase without knowing it. This adds a powerful additional security layer but also increases complexity and risk of self-lockout." },
      ]}
      relatedArticles={[
        { title: "How to Use a Hardware Wallet", href: "/learn/how-to-use-hardware-wallet", category: "Learn" },
        { title: "How to Use MetaMask", href: "/learn/how-to-use-metamask", category: "Learn" },
        { title: "Is Cryptocurrency Safe?", href: "/learn/is-cryptocurrency-safe", category: "Learn" },
        { title: "Operational Security for Crypto", href: "/learn/operational-security-crypto", category: "Learn" },
      ]}
    >
      <section id="why-self-custody"><h2>Why Self-Custody Matters</h2><p>Self-custody eliminates counterparty risk — the risk that a third party holding your assets becomes insolvent, gets hacked, freezes your account, or acts fraudulently. History has repeatedly demonstrated these risks through exchange hacks (Mt. Gox, Bitfinex), exchange fraud (FTX), and account freezes. When you control your own keys, no external party can prevent you from accessing or transferring your assets.</p><p>Self-custody also provides censorship resistance and privacy. No intermediary can block your transactions, freeze your account, or require permission for you to use your funds. This sovereignty over your financial assets is one of the fundamental value propositions of cryptocurrency and is only achieved through self-custody. However, this sovereignty comes with full responsibility — there is no recovery mechanism if you lose access to your keys.</p></section>
      <section id="wallet-types"><h2>Wallet Types</h2><p>Hardware wallets (Ledger, Trezor, Keystone) store private keys on dedicated devices that never expose keys to internet-connected computers. They provide the strongest security for self-custody and are recommended for significant holdings. Software wallets (MetaMask, Rabby, Phantom) run on your computer or phone and are more convenient but expose keys to device-level vulnerabilities like malware.</p><p>Paper wallets involve printing private keys or seed phrases on physical media. While air-gapped, they are fragile and difficult to use for transactions. Metal seed phrase backups (steel plates with stamped or engraved words) provide fire and water resistance for long-term seed phrase storage. Multisig wallets require multiple key holders to approve transactions, suitable for organizations or individuals wanting additional security against single points of failure.</p></section>
      <section id="seed-phrases"><h2>Seed Phrase Management</h2><p>Your seed phrase (typically 12 or 24 words) is the master key to all wallets derived from it. Anyone with your seed phrase has complete control over your funds. Never store seed phrases digitally — not in photos, cloud storage, email, password managers, or text files. Digital storage creates attack vectors through malware, cloud breaches, and device compromise that do not exist with physical storage.</p><p>Write your seed phrase on durable physical media. Metal backup plates that are stamped, engraved, or use letter tiles provide resistance to fire, water, and physical degradation. Store backups in multiple secure locations (safe deposit box, home safe, trusted family member) to protect against single-location disasters. Consider splitting the seed phrase across locations using methods like Shamir Secret Sharing for additional security.</p></section>
      <section id="security-setup"><h2>Security Setup</h2><p>When setting up a hardware wallet, generate the seed phrase on the device itself — never use a pre-generated seed phrase or one provided by a third party. Verify the device is genuine and has not been tampered with (check manufacturer seals and verify firmware). Set a strong PIN on the device and consider adding a passphrase for an additional security layer that creates entirely separate wallet accounts.</p><p>For software wallets, use a dedicated browser profile or device for crypto activities. Install wallet software only from official sources, verify downloads against published checksums when possible, and keep your operating system and wallet software updated. Enable all available security features including password protection, auto-lock timers, and transaction signing confirmations.</p></section>
      <section id="backup-recovery"><h2>Backup & Recovery</h2><p>Test your backup recovery process before depositing significant funds. Set up the wallet, record the seed phrase, send a small amount, then completely reset the device and restore from the seed phrase. Verify the same addresses and balances appear. This test confirms your backup is correct and that you understand the recovery process before it matters.</p><p>Maintain at least two physical copies of your seed phrase in separate secure locations. Document which wallets and derivation paths are associated with each seed phrase (you can do this without recording the seed phrase itself). Consider an inheritance plan — ensure trusted family members or legal representatives can access your crypto in an emergency, while preventing unauthorized access during normal circumstances.</p></section>
      <section id="common-mistakes"><h2>Common Mistakes</h2><p>The most common self-custody mistakes include: storing seed phrases digitally (screenshots, cloud documents, email drafts), using a single backup location that could be destroyed or inaccessible, not testing the recovery process, ignoring firmware updates for hardware wallets, and reusing the same wallet for high-risk DeFi interactions and long-term storage.</p><p>Other critical mistakes include sharing seed phrases with anyone for any reason (legitimate support will never ask), generating wallets on compromised devices, falling for fake hardware wallets sold through unofficial channels, and not understanding that token approvals can drain assets even from a hardware wallet if you signed the approval transaction. Security is not a one-time setup but an ongoing practice requiring vigilance and education.</p></section>
    </LearnPageLayout>
  );
}
