import { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `What Is UNUS SED LEO (LEO)? Price, Guide & How to Buy (${CURRENT_YEAR}) | CryptoDegen`,
  description: "Learn about UNUS SED LEO (LEO), the utility token of Bitfinex and iFinex. Discover LEO tokenomics, burn mechanism, and how to buy.",
};

export default function LeoPage() {
  return (
    <LearnPageLayout title="What Is UNUS SED LEO (LEO)? Price, Guide & How to Buy" categoryName="Investing" categorySlug="investing" readTime="8 min read" intro="UNUS SED LEO (LEO) is the utility token of iFinex, the parent company of the Bitfinex exchange and Tether. LEO was created in 2019 to raise funds after Bitfinex faced liquidity issues. The token provides fee discounts on Bitfinex and benefits from a continuous burn mechanism funded by iFinex revenue, with the stated goal of eventually buying back and burning all LEO tokens." toc={[{id:"what-is",title:"What Is UNUS SED LEO?",level:2},{id:"how-it-works",title:"How Does LEO Work?",level:2},{id:"tokenomics",title:"LEO Tokenomics",level:2},{id:"use-cases",title:"Key Use Cases",level:2},{id:"how-to-buy",title:"How to Buy LEO",level:2},{id:"risks",title:"Risks and Considerations",level:2}]} faqs={[{question:"What is UNUS SED LEO?",answer:"LEO is the utility token of iFinex/Bitfinex. It provides exchange fee discounts and benefits from continuous buyback-and-burn funded by company revenue, with the goal of burning all tokens over time."},{question:"Where can I buy LEO?",answer:"LEO is primarily available on Bitfinex. It also trades on some other exchanges."},{question:"Is UNUS SED LEO a good investment?",answer:"LEO has a unique burn mechanism targeting 100% supply reduction. Its value is tied to Bitfinex and Tether's profitability. Regulatory and counterparty risks associated with iFinex are significant factors."}]} relatedArticles={[{title:"Best Cryptos to Buy",href:"/investing/best/cryptos-to-buy",category:"Investing"},{title:"How to Invest in Crypto",href:"/investing/learn/how-to-invest-in-crypto",category:"Investing"}]}>
      <section id="what-is"><h2>What Is UNUS SED LEO?</h2><p>UNUS SED LEO (from the Latin phrase meaning "One, But a Lion") is the utility and exchange token of iFinex Inc., the corporate entity behind both Bitfinex exchange and Tether stablecoin. LEO was created through a private token sale in May 2019, raising $1 billion. The sale was conducted to cover an $850 million shortfall after funds were seized by authorities from Bitfinex's payment processor, Crypto Capital.</p><p>LEO exists on both Ethereum (ERC-20) and EOS blockchains. The token's most notable feature is its aggressive burn mechanism: iFinex commits to using a minimum of 27% of its gross revenue to buy back and burn LEO tokens each month. Additionally, recovered funds from the Crypto Capital incident are used for additional LEO burns. The stated long-term goal is the complete elimination of LEO from circulation.</p></section>
      <section id="how-it-works"><h2>How Does LEO Work?</h2><p>LEO provides trading fee reductions on Bitfinex for spot, derivatives, and lending markets. The fee discount is proportional to LEO holdings relative to trading volume. The primary value driver is the continuous burn mechanism: iFinex uses a significant portion of its revenue from Bitfinex trading fees, Tether operations, and other business lines to buy LEO from the open market and permanently burn them. Given Tether's enormous profitability (billions in annual revenue from Treasury management), the burn pressure on LEO is substantial.</p></section>
      <section id="tokenomics"><h2>LEO Tokenomics</h2><p>LEO was issued with an initial supply of approximately 1 billion tokens. Continuous monthly burns have reduced the supply significantly. The burn rate is tied to iFinex's gross revenue, which includes Tether's highly profitable treasury management operations. The combination of decreasing supply through burns and the value proposition of trading fee discounts creates a deflationary token model with clear revenue backing. Recovered funds from the Crypto Capital case provide additional one-time burn events.</p></section>
      <section id="use-cases"><h2>Key Use Cases</h2><p>LEO is used for Bitfinex trading fee discounts, as a beneficiary of the iFinex revenue-driven burn mechanism, and as an investment in the continued profitability of iFinex's businesses including Tether. The token's primary appeal is its burn dynamics rather than active utility features.</p></section>
      <section id="how-to-buy"><h2>How to Buy LEO</h2><p>LEO is primarily available on the Bitfinex exchange. It also trades on some other platforms including Gate.io. Purchase on Bitfinex for direct fee discount benefits. Store in any Ethereum-compatible wallet for the ERC-20 version.</p></section>
      <section id="risks"><h2>Risks and Considerations</h2><p>LEO is closely linked to iFinex, Bitfinex, and Tether, all of which have faced regulatory scrutiny and legal challenges. Tether's reserve transparency concerns indirectly affect LEO. Any adverse regulatory action against Tether or Bitfinex could significantly impact LEO's value. The token's concentration on Bitfinex creates platform dependency. Despite the burn mechanism, LEO holders have limited governance rights over iFinex's operations. The company's opaque corporate structure adds uncertainty.</p></section>
    </LearnPageLayout>
  );
}
