import { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `What Is a Liquidity Pool? Definition & Guide (${CURRENT_YEAR}) | CryptoDegen`,
  description:
    "Learn what liquidity pools are, how they power decentralized exchanges, and the risks and rewards of providing liquidity.",
};

export default function LiquidityPoolPage() {
  return (
    <LearnPageLayout
      title="What Is a Liquidity Pool?"
      categoryName="Glossary"
      categorySlug="learn/glossary"
      readTime="5 min"
      intro="A liquidity pool is a collection of funds locked in a smart contract that enables decentralized trading, lending, and other DeFi activities. Instead of matching individual buyers and sellers like a traditional order book, liquidity pools allow anyone to trade against the pooled assets using an automated market maker algorithm. Liquidity providers deposit token pairs and earn fees from every trade."
      toc={[
        { id: "definition", title: "What Is a Liquidity Pool?", level: 2 },
        { id: "how-it-works", title: "How Liquidity Pools Work", level: 2 },
        { id: "providing-liquidity", title: "Providing Liquidity", level: 2 },
        { id: "risks", title: "Risks for Liquidity Providers", level: 2 },
        { id: "why-it-matters", title: "Why Liquidity Pools Matter", level: 2 },
      ]}
      faqs={[
        {
          question: "How do liquidity providers earn money?",
          answer:
            "LPs earn a share of the trading fees generated by the pool, proportional to their share of the total liquidity. Some pools also offer additional token rewards (liquidity mining incentives). However, earnings must be weighed against impermanent loss, which can sometimes exceed fee income, particularly in volatile markets.",
        },
        {
          question: "Can anyone create a liquidity pool?",
          answer:
            "Yes. On permissionless DEXs like Uniswap, anyone can create a new liquidity pool by depositing a pair of tokens. This is how new tokens become tradeable without being listed on a centralized exchange. However, pools with very low liquidity are susceptible to high slippage and price manipulation.",
        },
      ]}
      relatedArticles={[
        { title: "What Is an AMM?", href: "/learn/glossary/amm", category: "Glossary" },
        { title: "What Is Impermanent Loss?", href: "/learn/glossary/impermanent-loss", category: "Glossary" },
        { title: "What Is a DEX?", href: "/learn/glossary/dex", category: "Glossary" },
        { title: "What Is Liquidity?", href: "/learn/glossary/liquidity", category: "Glossary" },
      ]}
    >
      <h2 id="definition">What Is a Liquidity Pool?</h2>
      <p>
        A liquidity pool is a smart contract holding reserves of two or more tokens that traders can swap between. Traditional exchanges require a buyer for every seller. Liquidity pools replace this with a mathematical formula that automatically determines prices based on the ratio of tokens in the pool. This innovation, pioneered by protocols like Uniswap and Balancer, made decentralized trading practical.
      </p>

      <h2 id="how-it-works">How Liquidity Pools Work</h2>
      <p>
        The most common design uses the constant product formula (x * y = k). When a trader buys token A from the pool, they deposit token B, changing the ratio and moving the price. Larger trades relative to pool size cause more price impact (slippage). Arbitrageurs continuously trade against pools to keep prices aligned with external markets, earning profits while improving price accuracy.
      </p>

      <h2 id="providing-liquidity">Providing Liquidity</h2>
      <p>
        To become a liquidity provider, you deposit equal values of both tokens in a pool. In return, you receive LP tokens representing your share of the pool. These LP tokens can be redeemed at any time for your proportional share of the pool&apos;s assets plus accumulated fees. Some protocols allow staking LP tokens for additional reward tokens, a practice known as yield farming.
      </p>

      <h2 id="risks">Risks for Liquidity Providers</h2>
      <p>
        Impermanent loss is the primary risk: if token prices diverge, LPs end up with less value than simply holding. Smart contract risk means bugs could lead to loss of deposited funds. Rug pulls can occur in pools for fraudulent tokens. Additionally, the token rewards offered as liquidity mining incentives can decline in value, reducing the effective yield of providing liquidity.
      </p>

      <h2 id="why-it-matters">Why Liquidity Pools Matter</h2>
      <p>
        Liquidity pools are the foundation of decentralized finance. They enable permissionless trading without order books or intermediaries. They allow anyone to earn yields by providing capital. They make it possible for new tokens to have instant markets. Without liquidity pools, the DeFi ecosystem as we know it would not exist. They represent one of crypto&apos;s most important financial innovations.
      </p>
    </LearnPageLayout>
  );
}
