import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `How to Use the Lightning Network (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Guide to Bitcoin's Lightning Network including wallet setup, sending and receiving payments, channel management, and practical use cases.",
  keywords: ["Lightning Network", "Bitcoin Lightning", "how to use Lightning", "Lightning wallet", "Bitcoin payments", "Lightning Network guide"],
};

export default function HowToUseLightningNetworkPage() {
  return (
    <LearnPageLayout title="How to Use the Lightning Network" categoryName="Crypto Education" categorySlug="learn" readTime="7 min" intro="The Lightning Network is Bitcoin's Layer 2 payment solution enabling instant, near-zero-fee transactions. By conducting transactions off-chain through payment channels, Lightning makes Bitcoin practical for everyday payments, micropayments, and high-frequency transactions that would be too slow or expensive on the Bitcoin base layer."
      toc={[{ id: "overview", title: "Lightning Overview", level: 2 },{ id: "wallets", title: "Lightning Wallets", level: 2 },{ id: "sending-receiving", title: "Sending & Receiving", level: 2 },{ id: "use-cases", title: "Use Cases", level: 2 },{ id: "tips", title: "Tips & Considerations", level: 2 }]}
      faqs={[
        { question: "Is the Lightning Network safe?", answer: "The Lightning Network has a strong security model backed by Bitcoin's base layer. Funds in Lightning channels are secured by on-chain Bitcoin transactions. However, Lightning requires that nodes stay online to monitor for fraud attempts. Custodial Lightning wallets simplify this but introduce counterparty risk." },
        { question: "How cheap are Lightning transactions?", answer: "Lightning fees are typically less than 1 satoshi (a fraction of a cent) for small payments, making it one of the cheapest payment networks in existence. Fees scale with payment amount and routing distance but remain negligible compared to on-chain Bitcoin fees." },
        { question: "Do I need to run a node for Lightning?", answer: "No, you can use Lightning through custodial wallets (Wallet of Satoshi, Strike) or non-custodial wallets (Phoenix, Breez) that manage channel operations automatically. Running your own node gives maximum control but is not required for everyday Lightning use." },
      ]}
      relatedArticles={[
        { title: "Bitcoin Ecosystem Guide", href: "/learn/bitcoin-ecosystem-guide", category: "Learn" },
        { title: "What Is Layer 2?", href: "/learn/what-is-layer-2", category: "Learn" },
        { title: "How to Create a Wallet", href: "/learn/how-to-create-wallet", category: "Learn" },
        { title: "What Is Interoperability?", href: "/learn/what-is-interoperability", category: "Learn" },
      ]}
    >
      <section id="overview"><h2>Lightning Overview</h2><p>The Lightning Network creates payment channels between parties where transactions happen off-chain, settling back to Bitcoin's blockchain only when channels open and close. Payments can route through multiple connected channels to reach any Lightning user without a direct channel between them. This network of channels creates a fast, scalable payment layer on top of Bitcoin.</p><p>Lightning transactions settle in milliseconds and cost fractions of a cent, making Bitcoin viable for small payments like buying coffee, tipping content creators, or paying for digital services. The network has grown significantly, with thousands of nodes, substantial liquidity, and integration by major companies including exchanges, payment processors, and point-of-sale systems worldwide.</p></section>
      <section id="wallets"><h2>Lightning Wallets</h2><p>Custodial wallets (Wallet of Satoshi, Strike) offer the simplest experience — install the app, create an account, and start sending and receiving instantly. The trade-off is that the wallet provider holds your funds, introducing counterparty risk. These are ideal for small amounts and everyday payments where convenience is prioritized over self-custody.</p><p>Non-custodial wallets (Phoenix, Breez, Zeus) give you control of your keys and manage Lightning channels automatically. Phoenix by ACINQ is particularly user-friendly, handling channel management transparently while maintaining self-custody. For advanced users, running a full Lightning node with software like LND, Core Lightning, or Eclair provides maximum control over routing, channels, and fees.</p></section>
      <section id="sending-receiving"><h2>Sending & Receiving</h2><p>To receive Lightning payments, generate an invoice in your wallet specifying the amount (or leave it open for any amount). The invoice is displayed as a QR code or text string. The sender scans the QR code or pastes the invoice in their Lightning wallet and confirms the payment. The transaction completes in seconds.</p><p>To send a payment, scan the recipient's invoice QR code or paste their Lightning address (an email-like format for receiving payments). Confirm the amount and send. Lightning addresses and LNURL provide a simpler user experience than traditional invoices, enabling reusable payment endpoints similar to email addresses. Bolt12 offers is an emerging standard for reusable, privacy-preserving payment requests.</p></section>
      <section id="use-cases"><h2>Use Cases</h2><p>Everyday payments at merchants accepting Lightning through point-of-sale integrations or payment processors like BTCPay Server and Strike. Micropayments and streaming payments for content (podcasting 2.0 with value-for-value), social media tipping (Nostr integration), and pay-per-use digital services. Cross-border remittances with near-instant settlement and minimal fees compared to traditional wire transfers.</p><p>Lightning is also used for gaming (in-game microtransactions), API payments (paying per API call), and as a settlement layer for instant exchange-to-exchange transfers. El Salvador's adoption of Bitcoin as legal tender relies heavily on Lightning for everyday commerce. The network continues to find new use cases as infrastructure and adoption grow.</p></section>
      <section id="tips"><h2>Tips & Considerations</h2><p>Start with a custodial wallet to learn the basics before moving to self-custodial options. Keep Lightning balances appropriate for everyday spending — use on-chain Bitcoin for larger amounts and long-term storage. Inbound liquidity can be a challenge for receiving payments on non-custodial wallets — Phoenix and Breez handle this automatically but charge a small fee for channel creation.</p><p>Privacy on Lightning is generally better than on-chain Bitcoin because individual payments are not recorded on the blockchain. However, routing nodes can observe payment flows. For maximum privacy, run your own node. Channel management (opening, closing, rebalancing) involves on-chain transactions with fees — plan channel operations during low-fee periods to minimize costs.</p></section>
    </LearnPageLayout>
  );
}
