import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Mobile Wallet Security Guide (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Secure your mobile crypto wallet with best practices for iOS and Android. Covers biometrics, app permissions, backup strategies, and threat prevention.",
  keywords: ["mobile wallet security", "crypto phone security", "iOS wallet", "Android wallet security"],
};

export default function Page() {
  return (
    <LearnPageLayout title="Mobile Wallet Security Guide" categoryName="Crypto Wallets" categorySlug="wallets" readTime="7 min" intro="Mobile wallets offer unmatched convenience for everyday crypto use, but phones present unique security challenges. From malware and SIM swaps to physical theft and insecure backups, mobile devices are targeted by attackers who know they hold valuable digital assets. Implementing proper security measures makes your mobile wallet significantly harder to compromise." toc={[{id:"threats",title:"Mobile-Specific Threats",level:2},{id:"device",title:"Device Security Fundamentals",level:2},{id:"app",title:"Wallet App Security Settings",level:2},{id:"advanced",title:"Advanced Mobile Protection",level:2}]} faqs={[{question:"Is it safe to keep crypto on my phone?",answer:"Mobile wallets are safe for moderate amounts with proper security measures. Use biometric authentication, enable full-disk encryption, keep your OS updated, and never store your seed phrase in photos or notes apps. For large holdings, use a hardware wallet as your primary storage and your phone wallet for everyday transactions only."},{question:"What happens if my phone is stolen?",answer:"If you use biometric lock and a strong PIN, a thief cannot immediately access your wallet app. Remotely wipe your phone through Find My iPhone or Google Find My Device. Your crypto remains safe as long as the thief cannot access your wallet app or seed phrase. Restore your wallet on a new device using your seed phrase backup."},{question:"Should I use iCloud or Google backup for my wallet?",answer:"Cloud backups can include wallet data, which creates a risk if your cloud account is compromised. Most security experts recommend against cloud-backing wallet seed phrases. If your wallet offers encrypted cloud backup as a feature, it may be acceptable as a secondary backup, but always maintain a physical seed phrase backup as your primary recovery method."}]} relatedArticles={[{title:"Wallet Security Best Practices",href:"/wallets/learn/wallet-security-best-practices",category:"Wallets"},{title:"Phishing Protection Guide",href:"/wallets/learn/phishing-protection-guide",category:"Wallets"},{title:"Best Mobile Wallets",href:"/wallets/best/mobile",category:"Best Of"}]}>
      <section id="threats"><h2>Mobile-Specific Threats</h2><p>Mobile wallets face a unique threat landscape compared to desktop or hardware wallets. SIM swap attacks allow attackers to take over your phone number, intercepting SMS-based two-factor authentication codes and potentially gaining access to accounts that use phone verification. Malicious apps can include keyloggers, screen recorders, or clipboard hijackers that replace copied wallet addresses with attacker addresses. Physical theft gives an attacker direct access to your device, with time to attempt PIN brute-forcing or exploit device vulnerabilities. Fake wallet apps on app stores mimic legitimate wallets to steal seed phrases entered during the setup process. Public WiFi networks expose your traffic to interception, potentially revealing sensitive data. Shoulder surfing in public places can capture PINs, seed phrases, or transaction details. These threats are real and actively exploited — billions of dollars in crypto have been stolen through mobile-specific attack vectors. Understanding each threat helps you implement targeted defenses.</p></section>
      <section id="device"><h2>Device Security Fundamentals</h2><p>Start with a strong device PIN of at least six digits — avoid obvious patterns, birthdays, or repeated numbers. Enable biometric authentication (Face ID or fingerprint) for your device and wallet apps. Keep your operating system updated to the latest version, as updates include security patches for known vulnerabilities. Enable full-disk encryption, which is default on modern iOS and Android devices. Disable USB debugging and developer options unless actively needed. Use a SIM PIN to protect against SIM swap attacks, and consider switching to an eSIM which is harder to swap without device access. Disable notification previews on your lock screen to prevent sensitive information from being visible without unlocking. Review and minimize app permissions — your wallet app should not need access to your contacts, camera, or location. Uninstall apps you do not use, as each installed app increases your attack surface. Consider using a dedicated phone for crypto activities separate from your daily device if your holdings are significant.</p></section>
      <section id="app"><h2>Wallet App Security Settings</h2><p>Within your wallet app, enable every available security feature. Set up biometric or PIN authentication for opening the app, with auto-lock after a short inactivity period. Enable transaction confirmation requirements so every send operation needs explicit approval. If your wallet supports it, enable a secondary password for high-value transactions. Turn on scam and phishing warnings — most modern wallets include built-in protection against known malicious addresses and contracts. Use the wallet&apos;s built-in address book for frequent recipients to avoid copy-paste address manipulation attacks. Review connected dApps regularly and disconnect sessions you are not actively using. If your wallet offers encrypted cloud backup, consider enabling it as a secondary backup alongside your physical seed phrase — but never rely on cloud backup alone. Set up any available notification features for incoming and outgoing transactions so you are immediately aware of any unauthorized activity on your addresses.</p></section>
      <section id="advanced"><h2>Advanced Mobile Protection</h2><p>For serious mobile security, use a VPN when accessing DeFi protocols or exchanges on mobile data or WiFi networks. Consider using a privacy-focused DNS provider that blocks known malicious domains. Install a reputable mobile security app that scans for malware, keyloggers, and suspicious app behavior. Use a password manager for exchange accounts rather than browser-saved passwords. Enable Google Advanced Protection Program or Apple&apos;s Advanced Data Protection for enhanced account security. For your seed phrase backup, never take screenshots, photos, or store it in any digital format on your phone — note-taking apps, photo galleries, and cloud services are commonly targeted by malware specifically designed to find seed phrases. When entering your seed phrase for wallet recovery, do so in a private location, on a secure network, and verify the app is legitimate before entering any recovery information. Consider using a physical Faraday bag when transporting your phone in high-risk situations to prevent remote tracking and wireless data exfiltration. Regularly audit your wallet&apos;s transaction history and token approvals to detect any unauthorized activity early.</p></section>
    </LearnPageLayout>
  );
}
