import { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `What Is SocialFi? Social Finance Explained (${CURRENT_YEAR}) | CryptoDegen`,
  description:
    "Learn what SocialFi is, how social media meets decentralized finance, key platforms in the space, and how creators are monetizing their social influence on-chain.",
};

export default function WhatIsSocialFiPage() {
  return (
    <LearnPageLayout
      title="What Is SocialFi?"
      categoryName="Learn Crypto"
      categorySlug="learn"
      readTime="8 min read"
      intro="SocialFi is the intersection of social media and decentralized finance, where social influence and community engagement are tokenized and financialized on the blockchain. SocialFi platforms allow creators to monetize their audience directly, let users invest in social capital, and enable decentralized social networks where users own their content and data. It represents a fundamental shift in how online social interactions create and distribute economic value."
      toc={[
        { id: "understanding-socialfi", title: "Understanding SocialFi", level: 2 },
        { id: "key-platforms", title: "Key SocialFi Platforms", level: 2 },
        { id: "socialfi-mechanics", title: "How SocialFi Mechanics Work", level: 2 },
        { id: "risks-and-outlook", title: "Risks and Future Outlook", level: 2 },
      ]}
      faqs={[
        {
          question: "How is SocialFi different from regular social media?",
          answer:
            "Traditional social media platforms capture all the economic value generated by user content and engagement. SocialFi gives that value back to users through token ownership, direct monetization, and decentralized governance. Users own their social graph, content, and the financial value their participation creates.",
        },
        {
          question: "Can you make money with SocialFi?",
          answer:
            "Yes, through several mechanisms: creating content that earns token rewards, investing in creator tokens that appreciate with their popularity, participating in protocol governance tokens, and earning referral rewards. However, like all crypto, returns are speculative and many participants lose money, especially those buying social tokens at inflated prices.",
        },
        {
          question: "What is friend.tech?",
          answer:
            "Friend.tech was a SocialFi app on Base that let users buy and sell keys linked to Twitter profiles. Key prices followed a bonding curve, rising with demand. Holding someone's keys granted access to a private chat. It demonstrated massive SocialFi demand, processing millions in volume, though activity declined after initial hype.",
        },
      ]}
      relatedArticles={[
        { title: "What Is Web3?", href: "/learn/what-is-web3", category: "Learn Crypto" },
        { title: "What Is GameFi?", href: "/learn/what-is-gamefi", category: "Learn Crypto" },
        { title: "What Is a DAO?", href: "/learn/what-is-a-dao", category: "Learn Crypto" },
        { title: "Crypto Narratives", href: "/learn/crypto-narratives", category: "Learn Crypto" },
      ]}
    >
      <section id="understanding-socialfi">
        <h2>Understanding SocialFi</h2>
        <p>
          SocialFi combines the engagement models of social media with the financial primitives of DeFi. At its core, it turns social interactions into economic transactions. When you follow a creator, like a post, or join a community, these actions can have financial implications. Creators can issue tokens tied to their brand, communities can pool resources through DAOs, and engagement can be rewarded with cryptocurrency.
        </p>
        <p>
          The movement is driven by frustration with Web2 social media, where platforms like Facebook and Twitter capture billions in advertising revenue while creators and users receive nothing. SocialFi platforms promise to redistribute this value by giving users ownership of their data, content, and social relationships. Decentralized social protocols like Lens and Farcaster store social graphs on-chain, making them portable across applications.
        </p>
      </section>

      <section id="key-platforms">
        <h2>Key SocialFi Platforms</h2>
        <p>
          Farcaster is a decentralized social protocol built on Ethereum that offers a Twitter-like experience with on-chain identity and composable social features. Lens Protocol provides a decentralized social graph that any application can build on, allowing users to carry their followers and content between apps. Both represent infrastructure-level social platforms rather than single applications.
        </p>
        <p>
          On the application side, platforms like friend.tech popularized social token trading, while Fantasy.top gamified crypto Twitter engagement. Frames on Farcaster enable interactive experiences embedded directly in social feeds. Token-gated communities use NFTs or tokens to control access to exclusive content and groups, creating a direct link between token ownership and social access.
        </p>
      </section>

      <section id="socialfi-mechanics">
        <h2>How SocialFi Mechanics Work</h2>
        <p>
          Creator tokens use bonding curves to price social assets. As more people buy a creator&apos;s token, the price increases algorithmically. Early supporters benefit from price appreciation if the creator becomes more popular. This creates a financial incentive to discover and support talented creators early. However, it also means latecomers pay more and bear greater risk if interest declines.
        </p>
        <p>
          Content monetization in SocialFi goes beyond traditional tipping or subscriptions. Posts can be minted as NFTs, engagement can be rewarded with protocol tokens, and attention metrics can be transparently tracked and compensated. Some platforms implement quadratic funding for content, where popular posts receive matched funding from protocol treasuries, amplifying the rewards for content that the community values most.
        </p>
      </section>

      <section id="risks-and-outlook">
        <h2>Risks and Future Outlook</h2>
        <p>
          SocialFi faces significant challenges including speculative bubbles around creator tokens, potential regulatory scrutiny of social tokens as securities, and the difficulty of competing with established social media platforms for user attention. Many SocialFi projects have experienced boom-and-bust cycles where initial hype drives massive adoption followed by rapid user decline once speculative interest fades.
        </p>
        <p>
          Despite these challenges, the fundamental thesis of user-owned social networks remains compelling. As decentralized social protocols mature and user experiences improve, SocialFi is likely to find sustainable models that balance financial incentives with genuine social utility. The projects most likely to succeed are those that create authentic social value first and layer financial features on top, rather than leading with speculation.
        </p>
      </section>
    </LearnPageLayout>
  );
}
