import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Bollinger Bands Guide for Crypto Trading (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Learn how to use Bollinger Bands in crypto trading. Understand band squeezes, walks, bounces, and strategies for volatility-based trading decisions." };

export default function Page() {
  return (<LearnPageLayout title="Bollinger Bands Guide" categoryName="Crypto Trading" categorySlug="trading" readTime="8 min" intro="Bollinger Bands measure volatility by creating a dynamic envelope around price. They help identify when markets are overextended, when volatility is contracting before a big move, and provide actionable trading signals. Created by John Bollinger, they remain one of the most valuable tools for crypto traders." toc={[{id:"how-they-work",title:"How Bollinger Bands Work",level:2},{id:"squeeze",title:"The Bollinger Squeeze",level:2},{id:"band-walks",title:"Band Walks and Trends",level:2},{id:"bounce-strategy",title:"Bollinger Bounce Strategy",level:2},{id:"advanced",title:"Advanced Techniques",level:2}]} faqs={[{question:"What settings should I use for Bollinger Bands?",answer:"The standard settings are a 20-period SMA with 2 standard deviations. For crypto's higher volatility, some traders use 2.5 standard deviations. For shorter timeframes, a 10-period with 1.5 standard deviations can work. Start with defaults."},{question:"Does price touching the upper band mean it is overbought?",answer:"Not necessarily. In strong uptrends, price can ride the upper band for extended periods — this is called a band walk and indicates strength, not overextension. Context matters — touching the upper band at resistance after a large move is more significant than during a steady uptrend."},{question:"Can Bollinger Bands predict breakouts?",answer:"Bollinger Band squeezes (when bands narrow significantly) predict that a large move is coming but do not predict the direction. Combine squeeze signals with other directional indicators to anticipate which way the breakout will go."}]} relatedArticles={[{title:"RSI Indicator Guide",href:"/trading/learn/rsi-indicator-guide",category:"Trading"},{title:"Moving Averages Explained",href:"/trading/learn/moving-averages-explained",category:"Trading"},{title:"Support and Resistance Levels",href:"/trading/learn/support-resistance-levels",category:"Trading"}]}>
    <section id="how-they-work"><h2>How Bollinger Bands Work</h2><p>Bollinger Bands consist of three lines. The middle band is a 20-period simple moving average (SMA). The upper band is the middle band plus 2 standard deviations. The lower band is the middle band minus 2 standard deviations. Standard deviation is a statistical measure of volatility — when price is volatile, the bands widen; when price is calm, the bands narrow. Approximately 95% of price action occurs within the bands (at 2 standard deviations). When price moves outside the bands, it is a statistically unusual event that often signals a reversal or the start of a strong trend. The bands dynamically adjust to current market conditions, making them more adaptive than fixed-percentage envelopes or channels.</p></section>
    <section id="squeeze"><h2>The Bollinger Squeeze</h2><p>The Bollinger Squeeze is one of the most valuable signals for crypto traders. When the bands contract to an unusually narrow width, it indicates that volatility has compressed — and compressed volatility tends to lead to explosive moves. Think of it as a coiled spring. The squeeze does not tell you which direction the move will go, only that a significant move is building. To determine direction, combine the squeeze with other indicators: if RSI is above 50 and MACD is positive, the breakout is more likely to be bullish. If price is below a major moving average with bearish divergence, the breakdown is more likely. Measure the squeeze by comparing the current band width to its historical average — the tighter the squeeze relative to history, the more significant the expected move.</p></section>
    <section id="band-walks"><h2>Band Walks and Trends</h2><p>During strong trends, price can walk along the upper or lower band for extended periods. A band walk occurs when price closes repeatedly near or outside the upper band in an uptrend (or lower band in a downtrend). This is a sign of strength, not a sell signal. During a band walk, the middle band (20 SMA) acts as support in an uptrend. If price pulls back to the middle band and bounces, the trend is healthy. If price closes below the middle band during an upper band walk, the trend may be weakening. Use the middle band as a trailing stop during band walks — as long as price stays above it, maintain your position. The end of a band walk, marked by price moving from the upper band to the middle band and then through to the lower band, confirms a trend reversal.</p></section>
    <section id="bounce-strategy"><h2>Bollinger Bounce Strategy</h2><p>In ranging markets, price tends to bounce between the upper and lower bands. The Bollinger Bounce strategy buys when price touches the lower band and sells when it touches the upper band. This works best when the bands are relatively flat (no strong trend), the market is in a clear range, and you confirm the bounce with a reversal candlestick pattern or RSI reaching overbought or oversold levels. Place your stop-loss slightly outside the band on the entry side. Target the opposite band or the middle band for a more conservative target. This strategy fails during trending markets where price walks along one band — always check for trend presence using moving average alignment or ADX before employing a bounce strategy.</p></section>
    <section id="advanced"><h2>Advanced Techniques</h2><p>Double Bollinger Bands use two sets of bands — one at 2 standard deviations and another at 1 standard deviation. This creates zones: price between 1 and 2 standard deviations indicates trending; price between the 1-SD bands indicates ranging. Bollinger Band width (BBW) indicator plots the distance between bands as a separate indicator, making squeezes easier to identify and quantify historically. Bollinger %B shows where price is relative to the bands on a 0-1 scale — above 1 is outside the upper band, below 0 is outside the lower band. Combining Bollinger Bands with volume creates powerful signals — a band touch on high volume is more significant than one on low volume. Use Bollinger Bands on multiple timeframes — a squeeze on the daily chart is far more significant than a squeeze on the 15-minute chart.</p></section>
  </LearnPageLayout>);
}
