import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Multisig Wallet Setup Guide (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Step-by-step guide to setting up a multisig wallet for enhanced crypto security. Covers Safe (Gnosis Safe), threshold configurations, and best practices.",
  keywords: ["multisig wallet", "multi-signature", "Safe wallet", "Gnosis Safe", "multisig setup"],
};

export default function Page() {
  return (
    <LearnPageLayout title="Multisig Wallet Setup Guide" categoryName="Crypto Wallets" categorySlug="wallets" readTime="8 min" intro="A multisig (multi-signature) wallet requires approval from multiple private keys before a transaction can be executed. This dramatically improves security by eliminating single points of failure — no single compromised key can result in fund loss. Multisig is the gold standard for securing significant crypto holdings and is used by DAOs, protocols, and security-conscious individuals." toc={[{id:"what-is",title:"What Is a Multisig Wallet?",level:2},{id:"setup",title:"Setting Up Safe Multisig",level:2},{id:"config",title:"Choosing Your Configuration",level:2},{id:"operations",title:"Daily Operations and Management",level:2}]} faqs={[{question:"What threshold should I use for a personal multisig?",answer:"For personal use, 2-of-3 is the most popular configuration. It requires two of three keys to sign, meaning you can lose access to one key and still recover your funds. For higher security, 3-of-5 provides more redundancy. Avoid requiring all keys (3-of-3) as losing any single key would permanently lock your funds."},{question:"Does multisig cost more in gas?",answer:"Yes. Multisig transactions are smart contract interactions that consume more gas than standard transfers. On Ethereum mainnet, this can be significant. On Layer 2 networks, the additional cost is minimal. Many users deploy their Safe on an L2 for cost savings while maintaining the same security model."},{question:"Can I add or remove signers after setup?",answer:"Yes. Safe and other multisig implementations allow you to add signers, remove signers, and change the threshold through governance transactions that themselves require multisig approval. This flexibility means you can evolve your security setup over time as your needs change."}]} relatedArticles={[{title:"Safe Wallet Review",href:"/wallets/reviews/safe-wallet",category:"Review"},{title:"Multisig vs Single Key",href:"/wallets/compare/multisig-vs-single-key",category:"Compare"},{title:"Wallet Security Best Practices",href:"/wallets/learn/wallet-security-best-practices",category:"Wallets"}]}>
      <section id="what-is"><h2>What Is a Multisig Wallet?</h2><p>A multisig wallet is a smart contract that requires M-of-N signatures to authorize any transaction. For example, a 2-of-3 multisig needs two out of three designated signers to approve before funds can move. This is fundamentally different from a standard wallet where a single private key controls everything. If your single-key wallet is compromised, the attacker has full control. With a 2-of-3 multisig, an attacker would need to compromise two separate keys — potentially stored on different devices, in different locations, or controlled by different people. This distributed security model is why virtually every major DeFi protocol, DAO treasury, and institutional custody solution uses multisig. Safe (formerly Gnosis Safe) is the dominant multisig platform, securing over $100 billion in assets across Ethereum and EVM chains. It provides a user-friendly web interface for creating and managing multisig wallets without needing to write smart contract code.</p></section>
      <section id="setup"><h2>Setting Up Safe Multisig</h2><p>To create a Safe multisig, visit app.safe.global and connect one of your existing wallets. Click Create New Safe and select the blockchain network — consider deploying on a Layer 2 like Arbitrum or Base for lower ongoing transaction costs. Name your Safe for easy identification, then add signer addresses. Each signer should be a distinct wallet that you or your designated co-signers control — hardware wallets are recommended for at least some signers. Set your confirmation threshold — the number of signers required to execute transactions. Review the configuration carefully as changing it later requires a multisig transaction itself. Confirm the creation transaction and pay the deployment gas fee. Once deployed, your Safe has its own unique address where you can receive any ERC-20 token or NFT. Share this address with your co-signers so they can add the Safe to their own Safe interface. Each signer interacts with the Safe through the web app using their individual wallet.</p></section>
      <section id="config"><h2>Choosing Your Configuration</h2><p>The right configuration depends on your use case and risk tolerance. For personal security with three devices, 2-of-3 provides strong protection while remaining practical — keep keys on a hardware wallet, a mobile wallet, and a browser extension. For a couple or business partners, 2-of-3 with each person holding one key and a shared backup provides joint control. For DAOs or teams, configurations like 3-of-5 or 4-of-7 balance security with operational efficiency. Higher thresholds increase security but slow down operations since more signers must coordinate. Consider geographic distribution of signers to protect against localized disasters. Use diverse wallet types across signers — combining hardware wallets, mobile wallets, and desktop wallets prevents a single vulnerability from compromising multiple keys. Never store multiple signer keys on the same device or in the same physical location. Label each signer clearly in the Safe interface so all parties understand which key belongs to whom.</p></section>
      <section id="operations"><h2>Daily Operations and Management</h2><p>To send funds from a Safe, one signer initiates the transaction by specifying the recipient, amount, and optional data. The transaction appears in the Safe interface as pending, requiring additional confirmations. Other signers review the transaction details — recipient address, amount, and any contract interaction data — then confirm with their wallet. Once the threshold is met, any signer can execute the transaction, paying the gas fee. Safe supports transaction batching, allowing multiple operations to be bundled and confirmed together. The Safe also supports modules for advanced functionality like spending limits that allow individual signers to make transactions up to a daily cap without additional approvals. Regularly review your signer list and update it when circumstances change — remove signers who should no longer have access and add new ones as needed. Keep your Safe interface bookmarked and verify the URL before connecting to prevent phishing. Monitor your Safe activity through the transaction history and set up notifications for pending transactions.</p></section>
    </LearnPageLayout>
  );
}
