import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `How to Sell Crypto (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Complete guide to selling cryptocurrency. Learn about exchange selling, P2P trading, OTC desks, tax implications, and timing strategies.",
  keywords: ["sell crypto", "cash out crypto", "sell bitcoin", "crypto off-ramp"],
};

export default function Page() {
  return (
    <LearnPageLayout title="How to Sell Crypto" categoryName="Crypto Investing" categorySlug="investing" readTime="7 min" intro="Knowing when and how to sell crypto is just as important as knowing how to buy. Whether you are taking profits, rebalancing your portfolio, or converting to fiat for expenses, understanding the different selling methods, their costs, and tax implications ensures you keep more of your gains." toc={[{id:"methods",title:"Methods for Selling Crypto",level:2},{id:"exchanges",title:"Selling on Exchanges",level:2},{id:"tax",title:"Tax Implications of Selling",level:2},{id:"strategies",title:"Selling Strategies",level:2}]} faqs={[{question:"What is the cheapest way to sell crypto?",answer:"Limit orders on major exchanges like Coinbase Advanced, Kraken, or Binance typically offer the lowest fees at 0.1-0.5%. Avoid instant sell features and simplified buy/sell interfaces that charge 1-3% markups. For large amounts, OTC desks offer competitive rates with minimal market impact."},{question:"Do I pay taxes when I sell crypto?",answer:"In most countries, selling crypto is a taxable event. You owe capital gains tax on the difference between your purchase price and sale price. Short-term gains (held less than one year) are taxed at higher ordinary income rates. Long-term gains benefit from reduced tax rates in many jurisdictions. Keep detailed records of all purchases and sales."},{question:"Should I sell all at once or gradually?",answer:"Selling gradually (dollar-cost averaging out) reduces the risk of selling at a local bottom or top. Just as DCA buying smooths your entry price, DCA selling smooths your exit price. For large positions, selling in tranches over days or weeks also minimizes market impact on price."}]} relatedArticles={[{title:"Tax-Efficient Crypto Investing",href:"/investing/learn/tax-efficient-crypto-investing",category:"Investing"},{title:"Crypto Portfolio Strategies",href:"/investing/learn/crypto-portfolio-strategies",category:"Investing"},{title:"Rebalancing Crypto Portfolio",href:"/investing/learn/rebalancing-crypto-portfolio",category:"Investing"}]}>
      <section id="methods"><h2>Methods for Selling Crypto</h2><p>Centralized exchanges remain the most common method for selling crypto to fiat currency. Major platforms like Coinbase, Kraken, and Binance support direct bank transfers and offer various trading interfaces with different fee structures. Peer-to-peer platforms like Paxful and LocalBitcoins connect buyers and sellers directly, often supporting diverse payment methods including bank transfers, mobile payments, and gift cards. Over-the-counter (OTC) desks handle large volume sales privately without impacting market prices — essential for selling significant amounts that would move prices on open exchanges. Crypto debit cards from providers like Crypto.com and Coinbase allow spending crypto directly without explicitly selling, converting automatically at point of sale. Decentralized exchanges allow selling crypto for stablecoins without KYC requirements, though converting stablecoins to fiat still requires a centralized on-ramp. Each method has different speed, cost, privacy, and regulatory characteristics that make them suitable for different situations.</p></section>
      <section id="exchanges"><h2>Selling on Exchanges</h2><p>For most users, selling on a centralized exchange offers the best balance of convenience, speed, and cost. Use the advanced or pro trading interface rather than the simple buy/sell page — the difference in fees can be significant, often 0.1-0.5% versus 1.5-3%. Place limit orders at your desired price rather than market orders to avoid paying the spread and potentially get better execution. Ensure your exchange account is fully verified before you need to sell, as identity verification can take days during busy periods. Set up your bank account withdrawal method in advance. Be aware of withdrawal limits — most exchanges have daily and monthly fiat withdrawal caps that increase with verification level. For tax purposes, download your full transaction history before selling, as you need purchase records to calculate cost basis and capital gains. Consider using exchanges that support instant ACH or SEPA transfers for faster access to your fiat proceeds rather than wire transfers which may take longer.</p></section>
      <section id="tax"><h2>Tax Implications of Selling</h2><p>Selling crypto triggers capital gains tax in most jurisdictions. Your taxable gain is the difference between the sale price and your cost basis — the original purchase price including fees. In the US, crypto held longer than one year qualifies for long-term capital gains rates of 0%, 15%, or 20% depending on income. Short-term gains are taxed as ordinary income, which can reach 37% at the highest federal bracket. Cost basis methods matter significantly — FIFO (first in, first out), LIFO (last in, first out), and specific identification can produce very different tax outcomes. Crypto-to-crypto trades are also taxable events in most countries, not just crypto-to-fiat sales. Tax-loss harvesting — selling losing positions to offset gains — can reduce your tax burden when done strategically. Keep meticulous records of every transaction including dates, amounts, prices, and fees. Consider using crypto tax software like Koinly, CoinTracker, or TaxBit to automate calculation of gains and losses across all your exchanges and wallets.</p></section>
      <section id="strategies"><h2>Selling Strategies</h2><p>Dollar-cost averaging out mirrors the popular buying strategy — selling fixed amounts at regular intervals smooths your exit price and removes emotional decision-making. Target-based selling sets specific price targets where you sell predetermined percentages of your position, ensuring you capture profits at milestone levels. Rebalancing-driven selling trims positions that have grown beyond your target portfolio allocation, maintaining your desired risk profile while naturally selling winners. Trailing stop strategies use automatic sell orders that follow the price upward and trigger when the price drops by a set percentage from its high, capturing uptrend gains while protecting against reversals. Needs-based selling converts crypto to fiat as life expenses require, treating crypto as a long-term savings vehicle rather than an active trading position. Whichever strategy you choose, having a plan before you need to sell prevents emotional decisions during market volatility and helps you execute consistently over time.</p></section>
    </LearnPageLayout>
  );
}
