import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `MPC Wallets Explained (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Learn how Multi-Party Computation wallets work, their security model, and how they compare to traditional seed phrase and multisig wallets.",
  keywords: ["MPC wallet", "multi-party computation", "threshold signatures", "keyless wallet"],
};

export default function Page() {
  return (
    <LearnPageLayout title="MPC Wallets Explained" categoryName="Crypto Wallets" categorySlug="wallets" readTime="8 min" intro="Multi-Party Computation (MPC) wallets split your private key into multiple shares distributed across different parties. No single party ever possesses the complete key, yet transactions can be signed cooperatively. This eliminates seed phrase management while maintaining self-custody properties." toc={[{id:"what-is",title:"What Is MPC?",level:2},{id:"how-works",title:"How MPC Signing Works",level:2},{id:"vs-multisig",title:"MPC vs Multisig",level:2},{id:"wallets",title:"Popular MPC Wallets",level:2}]} faqs={[{question:"Is MPC truly self-custody?",answer:"MPC provides partial self-custody — you hold one or more key shares, and the provider holds others. No single party can sign transactions alone. Whether this qualifies as full self-custody depends on your definition. It is more self-sovereign than custodial exchange storage but less than holding your own complete seed phrase on a hardware wallet."},{question:"What if the MPC provider shuts down?",answer:"Most MPC wallets provide emergency recovery mechanisms. Binance Web3 Wallet stores shares on your device and in cloud backup, allowing recovery without Binance. However, the specific recovery options vary by provider, so understanding them before committing significant funds is important."},{question:"Are MPC wallets secure?",answer:"MPC cryptography is mathematically proven secure and used by major financial institutions. The practical security depends on the implementation quality and the trust assumptions about key share holders. Well-implemented MPC wallets from reputable providers offer strong security comparable to other wallet types."}]} relatedArticles={[{title:"Binance Web3 Wallet Review",href:"/wallets/reviews/binance-web3-wallet",category:"Review"},{title:"Custodial vs Non-Custodial",href:"/wallets/compare/custodial-vs-non-custodial",category:"Compare"},{title:"Smart Contract Wallets",href:"/wallets/learn/smart-contract-wallets",category:"Wallets"}]}>
      <section id="what-is"><h2>What Is MPC?</h2><p>Multi-Party Computation is a cryptographic technique where multiple parties jointly compute a function over their inputs without revealing those inputs to each other. Applied to crypto wallets, MPC splits the private key generation and signing process across multiple parties — typically your device, a cloud backup, and the wallet provider. Each party holds a key share, and the mathematical protocol allows them to collaboratively produce valid transaction signatures without any party ever reconstructing the complete private key. This is fundamentally different from multisig, where multiple complete keys sign a transaction independently. In MPC, no complete key exists at any point — the key is born distributed and stays distributed throughout its lifetime.</p></section>
      <section id="how-works"><h2>How MPC Signing Works</h2><p>When you initiate a transaction, a distributed signing protocol runs between the key share holders. Your device uses its share to produce a partial signature, and the other share holders do the same with their shares. These partial signatures are combined through the MPC protocol to produce a valid complete signature — mathematically identical to one produced by a standard single-key wallet. The blockchain cannot distinguish an MPC-signed transaction from a regular one, which means MPC wallets work with any blockchain without requiring protocol-level support. The signing protocol uses zero-knowledge proofs and secure communication channels to ensure no party can learn another party&apos;s share during the process. Key shares can also be periodically refreshed — replaced with new shares that are mathematically equivalent but different in value — protecting against past share compromises.</p></section>
      <section id="vs-multisig"><h2>MPC vs Multisig</h2><p>Multisig and MPC both distribute trust across multiple parties but use fundamentally different approaches. Multisig creates multiple complete private keys and requires multiple on-chain signatures, resulting in higher transaction costs and blockchain-specific implementations. MPC splits a single key into shares and produces a single standard signature, keeping costs identical to regular transactions and working across all blockchains natively. Multisig is transparent on-chain — anyone can see the multisig contract and signer structure. MPC is invisible on-chain — transactions look identical to standard single-key transactions. Multisig requires smart contract infrastructure on each chain, while MPC works at the cryptographic level independent of blockchain architecture. For institutional use, both are valid approaches with different trade-offs in transparency, cost, and implementation complexity.</p></section>
      <section id="wallets"><h2>Popular MPC Wallets</h2><p>Binance Web3 Wallet uses three-party MPC with shares on your device, cloud backup, and Binance servers. ZenGo pioneered consumer MPC wallets with a two-share model using your device and ZenGo&apos;s servers, with facial biometric recovery replacing seed phrases. Fireblocks provides institutional-grade MPC custody used by major exchanges and financial institutions. Coinbase has integrated MPC technology into its infrastructure for enhanced security. OKX Wallet uses MPC for its keyless wallet option. The consumer MPC wallet space is growing as providers recognize that eliminating seed phrase management dramatically improves user onboarding and retention while maintaining security properties acceptable for moderate to significant holdings.</p></section>
    </LearnPageLayout>
  );
}
