import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `What Is Market Cap in Crypto? (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Understand cryptocurrency market capitalization, how it's calculated, why it matters for investors, and its limitations as a valuation metric.",
  keywords: ["market cap", "crypto market cap", "market capitalization", "fully diluted valuation"],
};

export default function Page() {
  return (
    <LearnPageLayout title="What Is Market Cap in Crypto?" categoryName="Crypto Investing" categorySlug="investing" readTime="6 min" intro="Market capitalization is the most widely used metric for sizing and comparing cryptocurrencies. It provides a quick snapshot of a project's relative scale in the market. However, market cap has significant limitations in crypto that every investor should understand to avoid making decisions based on misleading data." toc={[
        { id: "definition", title: "definition", level: 2 },
        { id: "market-cap-defined", title: "Market Cap Defined", level: 2 },
        { id: "categories", title: "categories", level: 2 },
        { id: "market-cap-categories", title: "Market Cap Categories", level: 2 },
        { id: "fdv", title: "fdv", level: 2 },
        { id: "fully-diluted-valuation", title: "Fully Diluted Valuation", level: 2 },
        { id: "limitations", title: "limitations", level: 2 },
        { id: "limitations-and-misconceptions", title: "Limitations and Misconceptions", level: 2 }
      ]} faqs={[{question:"Does a lower market cap mean a coin is cheaper?",answer:"No. Market cap reflects total market value, not the price of individual tokens. A token priced at $0.001 with 100 billion supply has the same $100 million market cap as a token priced at $100 with 1 million supply. Comparing prices between different tokens without considering supply is meaningless — always compare market caps for relative size."},{question:"Can market cap predict future price?",answer:"Market cap alone cannot predict price. However, it helps set realistic expectations. For a $1 billion market cap token to 100x, it would need to reach $100 billion — exceeding most major companies. Understanding this math prevents unrealistic return expectations and helps identify tokens with genuine growth room versus those requiring implausible market cap increases."},{question:"What is a good market cap to invest in?",answer:"There is no universally good market cap for investment. Large caps ($10B+) are safer but offer less upside. Mid caps ($1-10B) balance risk and reward. Small caps (under $1B) offer the highest potential returns but carry the most risk. Your ideal market cap range depends on your risk tolerance and investment timeline."}]} relatedArticles={[{title:"Tokenomics Explained",href:"/investing/learn/tokenomics-explained",category:"Investing"},{title:"Crypto Valuation Methods",href:"/investing/learn/crypto-valuation-methods",category:"Investing"},{title:"How to Read Crypto Charts",href:"/investing/learn/how-to-read-crypto-charts",category:"Investing"}]}>
      <section id="definition"><h2>Market Cap Defined</h2><p>Market capitalization in crypto is calculated by multiplying the current price of a token by its circulating supply. If a token trades at $50 and has 20 million tokens in circulation, its market cap is $1 billion. This metric attempts to represent the total value the market assigns to a cryptocurrency project. Market cap allows comparison between projects regardless of their individual token prices, which vary wildly due to different total supply amounts. CoinGecko and CoinMarketCap rank cryptocurrencies by market cap, creating a hierarchy that influences investor perception and institutional consideration. Market cap is used to categorize assets into large-cap, mid-cap, and small-cap tiers, each with different risk and return characteristics. While derived from stock market analysis, crypto market cap carries additional complexity due to uncertain circulating supply calculations, token lock-up schedules, and the distinction between circulating and total supply.</p></section>
      <section id="categories"><h2>Market Cap Categories</h2><p>Large-cap cryptocurrencies, generally those above $10 billion in market cap, include Bitcoin, Ethereum, and a handful of established projects. These offer relative stability, deep liquidity, and the strongest survival probability through bear markets. They are typically the starting point for institutional investors. Mid-cap crypto, roughly $1-10 billion, includes established projects with significant adoption but room for growth — many Layer 1 blockchains, major DeFi protocols, and infrastructure tokens fall here. These offer higher growth potential than large caps with moderate additional risk. Small-cap tokens below $1 billion range from promising early-stage projects to speculative bets. They can deliver extraordinary returns if they succeed but carry high failure risk and lower liquidity, making large positions difficult to enter and exit. Micro-cap tokens below $100 million are the most speculative, often representing new projects with unproven technology and small communities. Position sizing should correspond to market cap tier — larger allocations for large caps and progressively smaller allocations as market cap decreases.</p></section>
      <section id="fdv"><h2>Fully Diluted Valuation</h2><p>Fully diluted valuation (FDV) multiplies the current token price by the maximum total supply, not just the circulating supply. This metric is critical because many crypto projects have significant token supplies that are locked, vesting, or yet to be minted. A token might have a $500 million market cap based on circulating supply but a $5 billion FDV — meaning 90% of tokens are yet to enter circulation. As these locked tokens unlock through vesting schedules, team allocations, ecosystem grants, and mining rewards, they create persistent selling pressure that can suppress price appreciation even as demand grows. Comparing market cap to FDV reveals the dilution risk of an investment. A wide gap between the two suggests significant future supply increases. Projects with FDV many multiples of their market cap at launch often underperform because early investors and team members sell as tokens unlock. Checking FDV alongside market cap provides a more complete picture of valuation and future price dynamics.</p></section>
      <section id="limitations"><h2>Limitations and Misconceptions</h2><p>Market cap does not represent actual money invested in a cryptocurrency. If someone buys $1 million worth of a low-liquidity token, the price may increase enough to add $10 million to market cap. Conversely, $1 million in selling pressure might remove $10 million from market cap. This disconnect between capital flows and market cap changes leads to misleading conclusions about money entering or leaving the crypto market. Circulating supply calculations are often inaccurate or disputed — lost tokens, inaccessible wallets, and tokens locked in bridges inflate apparent supply. Stablecoins and wrapped tokens can create double-counting issues in aggregate market cap figures. Market cap does not capture revenue, usage, or fundamental value — a protocol generating millions in fees and a protocol generating nothing might have identical market caps. It is an imperfect but useful starting point for comparison that should always be supplemented with fundamental analysis of usage metrics, revenue, development activity, and competitive positioning.</p></section>
    </LearnPageLayout>
  );
}
