import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Private Key Management Guide (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Learn how to securely manage your cryptocurrency private keys. Best practices for key generation, storage, rotation, and protection against theft.",
  keywords: ["private key", "key management", "crypto security", "key storage"],
};

export default function Page() {
  return (
    <LearnPageLayout title="Private Key Management Guide" categoryName="Crypto Wallets" categorySlug="wallets" readTime="8 min" intro="Private keys are the cryptographic foundation of cryptocurrency ownership. Whoever controls the private key controls the funds. This guide covers everything you need to know about generating, storing, and protecting your private keys from theft and loss." toc={[{id:"what-are",title:"What Are Private Keys?",level:2},{id:"generation",title:"Key Generation Best Practices",level:2},{id:"storage",title:"Secure Key Storage",level:2},{id:"threats",title:"Common Threats",level:2}]} faqs={[{question:"What happens if my private key is stolen?",answer:"If compromised, the attacker can drain all funds immediately. There is no way to freeze or reverse transactions on decentralized blockchains. Transfer all assets to a new wallet with a freshly generated key immediately if you suspect compromise."},{question:"Is a seed phrase the same as a private key?",answer:"Not exactly. A seed phrase encodes the master seed from which all your private keys are derived. One seed phrase generates multiple private keys for multiple cryptocurrencies. Protecting your seed phrase protects all derived private keys."},{question:"Should I memorize my private key?",answer:"Memorizing as your only backup is extremely risky. Human memory is fallible. Always maintain physical backups. Memorization can serve as an additional redundancy layer, but never as your sole backup method."}]} relatedArticles={[{title:"Seed Phrase Guide",href:"/wallets/learn/seed-phrase-guide",category:"Wallets"},{title:"Wallet Security Best Practices",href:"/wallets/learn/wallet-security-best-practices",category:"Wallets"},{title:"Best Security Wallets",href:"/wallets/best/security",category:"Best Of"}]}>
      <section id="what-are"><h2>What Are Private Keys?</h2><p>A private key is a 256-bit random number that serves as cryptographic proof of ownership for cryptocurrency. In Bitcoin and Ethereum, private keys sign transactions, proving to the network that you are authorized to spend funds associated with a particular address. The private key mathematically generates your public key and wallet address through one-way cryptographic functions. Anyone possessing your private key has complete control over your cryptocurrency — they can send, receive, and manage assets without additional authorization. Unlike passwords, private keys cannot be reset or recovered through customer support. This makes private key security the absolute cornerstone of crypto asset protection.</p></section>
      <section id="generation"><h2>Key Generation Best Practices</h2><p>Private keys should be generated using a cryptographically secure random number generator on a trusted device. Hardware wallets generate keys within their secure element chip, which is the most secure method. If using a software wallet, ensure the device is malware-free and ideally freshly installed. Never generate keys on public computers, shared devices, or untrusted websites. The randomness quality is critical — poor randomness has historically produced exploitable keys. Reputable wallets use well-audited random number generators drawing entropy from hardware sources, operating system noise, and user input to ensure sufficient randomness for secure key creation.</p></section>
      <section id="storage"><h2>Secure Key Storage</h2><p>The golden rule is that keys should never exist in digital form on internet-connected devices longer than necessary. Hardware wallets store keys within tamper-resistant secure element chips that physically resist extraction attempts. For software wallets, keys are encrypted with your password, providing protection only as strong as your password. Seed phrases should be stored on physical media — paper or metal — in secure, geographically distributed locations. Never store private keys or seed phrases in cloud storage, email, messaging apps, screenshots, or any digitally accessible location where hackers or data breaches could expose them.</p></section>
      <section id="threats"><h2>Common Threats to Private Keys</h2><p>The most prevalent threats include phishing attacks tricking you into entering your seed phrase on malicious websites, clipboard-hijacking malware that replaces copied wallet addresses, social engineering where scammers impersonate support staff requesting keys, physical theft of devices containing unencrypted keys, and supply chain attacks where compromised hardware wallets arrive with pre-generated keys known to attackers. Protect yourself by verifying website URLs, purchasing hardware wallets directly from manufacturers, keeping software updated, enabling biometric and PIN protection, and maintaining healthy skepticism toward anyone requesting key access.</p></section>
    </LearnPageLayout>
  );
}
