import { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `What Is Star Atlas (ATLAS)? Price, Guide & How to Buy (${CURRENT_YEAR}) | CryptoDegen`,
  description: "Learn about Star Atlas (ATLAS), the space-themed MMORPG on Solana. Discover ATLAS tokenomics and how to buy.",
};

export default function AtlasPage() {
  return (
    <LearnPageLayout title="What Is Star Atlas (ATLAS)? Price, Guide & How to Buy" categoryName="Investing" categorySlug="investing" readTime="8 min read" intro="Star Atlas (ATLAS) is a space-themed massively multiplayer online game (MMORPG) built on Solana using Unreal Engine 5. The game features a grand strategy and exploration gameplay within a metaverse where players can own ships, land, and other assets as NFTs. ATLAS serves as the in-game currency for trading and daily operations." toc={[{id:"what-is",title:"What Is Star Atlas?",level:2},{id:"how-it-works",title:"How Does Star Atlas Work?",level:2},{id:"tokenomics",title:"ATLAS Tokenomics",level:2},{id:"use-cases",title:"Key Use Cases",level:2},{id:"how-to-buy",title:"How to Buy ATLAS",level:2},{id:"risks",title:"Risks and Considerations",level:2}]} faqs={[{question:"What is Star Atlas?",answer:"Star Atlas is a blockchain-based space MMORPG on Solana using Unreal Engine 5. ATLAS is the in-game currency used for transactions and economic activity within the game."},{question:"Where can I buy ATLAS?",answer:"ATLAS is available on Gate.io, Raydium, Jupiter, and other exchanges."},{question:"Is Star Atlas a good investment?",answer:"Star Atlas has ambitious AAA-game aspirations but is still in development. Investment is speculative and depends on the game's ability to deliver a compelling experience and attract players."}]} relatedArticles={[{title:"Best Cryptos to Buy",href:"/investing/best/cryptos-to-buy",category:"Investing"},{title:"How to Invest in Crypto",href:"/investing/learn/how-to-invest-in-crypto",category:"Investing"}]}>
      <section id="what-is"><h2>What Is Star Atlas?</h2><p>Star Atlas is one of the most ambitious blockchain gaming projects, aiming to create a AAA-quality space exploration and strategy MMORPG powered by Unreal Engine 5 on the Solana blockchain. Set in the year 2620, the game features three factions competing for resources and territory across a procedurally generated universe. Players can explore, mine, trade, fight, and govern through a fully player-driven economy where all assets are represented as NFTs on Solana.</p><p>The project has released several pre-alpha modules including SAGE Labs (a browser-based strategy game), the Showroom (a visual showcase of game assets), and a marketplace for trading ships and components. The full UE5 experience remains in development, representing the long-term vision for the project.</p></section>
      <section id="how-it-works"><h2>How Does Star Atlas Work?</h2><p>Star Atlas uses a dual-token economy. ATLAS is the in-game currency used for all economic transactions including buying supplies, trading between players, and paying for services. POLIS is the governance token used for voting on game development decisions and governing in-game territories. The game's economy is designed to be player-driven, with resource gathering, crafting, and trading forming the core economic loop. All ships, land, and equipment are NFTs tradeable on the Star Atlas marketplace and Solana secondary markets.</p></section>
      <section id="tokenomics"><h2>ATLAS Tokenomics</h2><p>ATLAS has a total supply of 36 billion tokens. The large supply reflects its role as an in-game currency requiring high volume of micro-transactions. Distribution includes play-to-earn rewards, ecosystem development, team allocations, and public sale. ATLAS is designed to be earned and spent within the game, with supply and demand dynamics driven by gameplay activity. The token's value depends on the game's ability to create a vibrant in-game economy.</p></section>
      <section id="use-cases"><h2>Key Use Cases</h2><p>ATLAS is used as the primary in-game currency for purchasing ships, equipment, and resources; paying crew salaries; fueling vehicles; and trading between players. The token facilitates the entire Star Atlas game economy. Outside the game, ATLAS is traded on exchanges and used in DeFi on Solana.</p></section>
      <section id="how-to-buy"><h2>How to Buy ATLAS</h2><p>ATLAS is available on Gate.io, MEXC, and Solana DEXs like Jupiter and Raydium. After purchasing, ATLAS can be used in Star Atlas game modules or held as speculative exposure to the game's development. Store in Phantom or any Solana-compatible wallet.</p></section>
      <section id="risks"><h2>Risks and Considerations</h2><p>Star Atlas is still in early development with the full game years away from completion. Game development is inherently risky with uncertain timelines and quality outcomes. The large token supply requires massive game adoption to support price levels. Blockchain gaming has struggled to attract mainstream gamers. Competition from other crypto games and traditional gaming studios entering Web3 is significant. The project's ambitious scope increases execution risk.</p></section>
    </LearnPageLayout>
  );
}
