import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Crypto Trading Taxes Guide (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Understand cryptocurrency trading taxes. Learn about capital gains, taxable events, record-keeping requirements, and strategies to manage your crypto tax burden." };

export default function Page() {
  return (<LearnPageLayout title="Crypto Trading Taxes" categoryName="Crypto Trading" categorySlug="trading" readTime="9 min" intro="Cryptocurrency trading creates tax obligations in most jurisdictions. Every trade, swap, and disposal may be a taxable event. Understanding your tax responsibilities helps you avoid penalties, plan effectively, and minimize your legitimate tax burden. This guide covers the essential tax concepts for crypto traders." toc={[{id:"taxable-events",title:"Taxable Events",level:2},{id:"calculating-gains",title:"Calculating Gains and Losses",level:2},{id:"record-keeping",title:"Record Keeping",level:2},{id:"tax-tools",title:"Crypto Tax Tools",level:2},{id:"strategies",title:"Tax Optimization Strategies",level:2}]} faqs={[{question:"Is every crypto trade taxable?",answer:"In the US, yes — every trade, swap, and conversion is a taxable event. Selling BTC for USD, swapping ETH for SOL, and even spending crypto are all taxable. Buying crypto with fiat is not taxable, and transfers between your own wallets are not taxable."},{question:"What about DeFi transactions?",answer:"DeFi swaps, liquidity provision, yield farming rewards, and airdrops are all potentially taxable events. The tax treatment varies by jurisdiction and specific transaction type. DeFi makes tax tracking more complex due to the volume and variety of on-chain transactions."},{question:"What happens if I do not report crypto taxes?",answer:"Tax authorities in most countries now receive data from major exchanges. Failure to report can result in penalties, interest on unpaid taxes, and in severe cases, criminal prosecution. The IRS, HMRC, and other agencies have made crypto tax enforcement a priority."}]} relatedArticles={[{title:"Crypto Trading for Beginners",href:"/trading/learn/crypto-trading-for-beginners",category:"Trading"},{title:"Crypto Trading Journal",href:"/trading/learn/crypto-trading-journal",category:"Trading"},{title:"Risk Management Guide",href:"/trading/learn/risk-management-guide",category:"Trading"}]}>
    <section id="taxable-events"><h2>Taxable Events</h2><p>In the US (and similarly in most countries), the following are taxable events: selling crypto for fiat currency, trading one cryptocurrency for another, using crypto to pay for goods or services, receiving crypto as payment for work or services (taxed as income), mining or staking rewards (taxed as income when received), and airdrops (taxed as income at fair market value when received). Not taxable: buying crypto with fiat, transferring between your own wallets, and donating to qualified charities (which may even provide a tax deduction). The classification matters because income from mining, staking, and airdrops is taxed as ordinary income at your marginal rate, while gains from selling or trading are taxed as capital gains — which may have a lower rate if held for more than one year. Active traders with hundreds of transactions per year face significant record-keeping requirements.</p></section>
    <section id="calculating-gains"><h2>Calculating Gains and Losses</h2><p>Capital gain or loss equals the sale price minus the cost basis (what you originally paid including fees). Short-term gains (assets held less than one year) are taxed at your ordinary income rate. Long-term gains (held more than one year) receive preferential tax rates — 0%, 15%, or 20% in the US depending on your income bracket. Cost basis tracking requires knowing when and at what price you acquired each unit. FIFO (First In, First Out) assumes you sell your oldest holdings first. LIFO (Last In, First Out) sells newest first. Specific identification lets you choose which lots to sell. The method you choose can significantly affect your tax bill — FIFO tends to produce more long-term gains (lower tax rate), while specific identification provides the most optimization flexibility.</p></section>
    <section id="record-keeping"><h2>Record Keeping</h2><p>Maintain records of every transaction including date, amount, price, fees, and which assets were involved. Export trade history from every exchange you use. For DeFi transactions, record wallet addresses, transaction hashes, and the fair market value at the time of each transaction. Keep records of cost basis for all holdings, including free tokens received through airdrops or forks. Most exchanges provide transaction history exports, but they do not calculate your gains and losses — that is your responsibility. For active traders with thousands of transactions across multiple exchanges and DeFi protocols, manual record keeping is impractical. Tax software that integrates with exchanges and blockchains is essential. Maintain records for at least seven years as tax authorities can audit back multiple years in most jurisdictions.</p></section>
    <section id="tax-tools"><h2>Crypto Tax Tools</h2><p>Koinly, CoinTracker, and CryptoTaxCalculator are leading crypto tax software platforms that import transactions from exchanges and blockchains, calculate gains and losses using your chosen cost basis method, and generate tax reports compatible with your jurisdiction's requirements. They support DeFi, NFTs, and cross-chain transactions. Prices range from free for basic use to $200+ per year for advanced features. Most integrate directly with major exchanges via API and can read on-chain transactions from Ethereum, Solana, and other blockchains. For US taxpayers, these tools generate IRS Form 8949 and Schedule D. For other jurisdictions, they produce equivalent reports. The investment in tax software pays for itself if you have more than a handful of transactions — manually tracking hundreds of trades across multiple platforms is error-prone and time-consuming.</p></section>
    <section id="strategies"><h2>Tax Optimization Strategies</h2><p>Tax-loss harvesting involves selling positions at a loss to offset gains from profitable trades. Unlike stocks, crypto does not have wash sale rules in the US (as of current law), meaning you can sell at a loss and immediately rebuy. This realizes the tax loss while maintaining your position. Hold for more than one year when possible to qualify for lower long-term capital gains rates. Use specific identification to sell highest-cost-basis lots first, minimizing taxable gains. Consider the timing of trades — realizing gains in years with lower income reduces your tax rate. If you are donating to charity, donate appreciated crypto directly to avoid capital gains tax while still receiving the full deduction. Consult a tax professional familiar with crypto — the tax landscape is complex, evolving, and the cost of professional advice is typically far less than the potential tax savings or penalties from incorrect filing.</p></section>
  </LearnPageLayout>);
}
