import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `WalletConnect Guide (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Learn how to use WalletConnect to connect your crypto wallet to dApps across devices. Setup guide, security tips, and troubleshooting.",
  keywords: ["WalletConnect", "dApp connection", "wallet connect guide", "QR code wallet"],
};

export default function Page() {
  return (
    <LearnPageLayout title="WalletConnect Guide" categoryName="Crypto Wallets" categorySlug="wallets" readTime="6 min" intro="WalletConnect is an open protocol that enables secure communication between crypto wallets and decentralized applications across devices. It allows you to use your mobile wallet to interact with desktop dApps by scanning a QR code, bridging the gap between different platforms." toc={[{id:"what-is",title:"What Is WalletConnect?",level:2},{id:"how-to-use",title:"How to Use WalletConnect",level:2},{id:"security",title:"Security Considerations",level:2},{id:"troubleshooting",title:"Troubleshooting Common Issues",level:2}]} faqs={[{question:"Is WalletConnect safe?",answer:"WalletConnect uses end-to-end encryption for communication between your wallet and the dApp. The protocol itself is secure, but you should always verify the dApp URL before connecting and review transaction details carefully before signing. Disconnect from dApps when you are done using them."},{question:"Which wallets support WalletConnect?",answer:"Most major wallets support WalletConnect including MetaMask, Trust Wallet, Rainbow, Argent, Zerion, Exodus, and many others. Hardware wallets can also use WalletConnect through their companion apps."},{question:"Why does my WalletConnect session disconnect?",answer:"Sessions can timeout due to inactivity, network changes, or app backgrounding on mobile. WalletConnect v2 improved session persistence significantly. If disconnections are frequent, ensure your wallet app has background activity permissions enabled and that you are using the latest version."}]} relatedArticles={[{title:"How to Choose a Crypto Wallet",href:"/wallets/learn/how-to-choose-crypto-wallet",category:"Wallets"},{title:"Best Mobile Wallets",href:"/wallets/best/mobile",category:"Best Of"},{title:"Wallet for DeFi Guide",href:"/wallets/learn/wallet-for-defi-guide",category:"Wallets"}]}>
      <section id="what-is"><h2>What Is WalletConnect?</h2><p>WalletConnect is an open-source protocol that creates encrypted connections between wallets and dApps. When a dApp displays a WalletConnect QR code, scanning it with your wallet app establishes a secure peer-to-peer channel. Through this channel, the dApp can request transaction signatures from your wallet without ever accessing your private keys. WalletConnect v2, the current version, supports multiple simultaneous sessions, persistent connections that survive app restarts, and multi-chain support within a single session. The protocol works across all EVM-compatible chains and is expanding support to non-EVM networks. WalletConnect is particularly valuable for connecting mobile wallets to desktop dApps and for connecting hardware wallets through their mobile companion apps.</p></section>
      <section id="how-to-use"><h2>How to Use WalletConnect</h2><p>The connection process is straightforward. On the dApp website, click the connect wallet button and select WalletConnect. The dApp displays a QR code. Open your mobile wallet, tap the scan or WalletConnect button, and scan the QR code. Your wallet will show a connection request with the dApp name and URL — verify these match the site you intend to connect to, then approve. Once connected, the dApp can propose transactions that appear in your wallet for review and signing. You maintain full control — every transaction requires your explicit approval in the wallet. When finished, disconnect the session from your wallet settings to revoke the dApp&apos;s ability to propose new transactions. Some wallets also support deep linking where clicking a WalletConnect link opens the connection directly without QR scanning.</p></section>
      <section id="security"><h2>Security Considerations</h2><p>Always verify the dApp URL displayed in the connection request matches the website you intended to visit. Phishing attacks can present connection requests that impersonate legitimate protocols. Review every transaction proposed through WalletConnect carefully before signing — check the recipient address, amount, and function being called. Be cautious of unlimited token approvals and use revoke tools periodically to clean up old approvals. Disconnect from dApps when your session is complete rather than leaving persistent connections open. Avoid scanning WalletConnect QR codes from untrusted sources such as social media posts or direct messages. The QR code itself is not dangerous, but connecting to a malicious dApp could lead to deceptive transaction requests designed to drain your wallet.</p></section>
      <section id="troubleshooting"><h2>Troubleshooting Common Issues</h2><p>If connections fail, ensure both your wallet app and the dApp are using WalletConnect v2 — incompatible versions will not connect. Check that your wallet is on the correct blockchain network for the dApp. Clear your wallet&apos;s WalletConnect session cache if you experience persistent connection issues. If transactions fail after connection, verify you have sufficient gas tokens on the target chain. If the dApp does not detect your wallet after scanning, try refreshing the dApp page and scanning a fresh QR code. On mobile browsers, ensure your wallet app is installed and up to date. Network firewalls and VPNs can sometimes interfere with WalletConnect relay servers — try disabling them temporarily if experiencing connection issues.</p></section>
    </LearnPageLayout>
  );
}
