import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `On-Chain Analysis for Crypto Trading (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Learn on-chain analysis for crypto trading. Understand key blockchain metrics, exchange flows, holder behavior, and how to use on-chain data for trading decisions." };

export default function Page() {
  return (<LearnPageLayout title="On-Chain Analysis for Trading" categoryName="Crypto Trading" categorySlug="trading" readTime="9 min" intro="On-chain analysis examines blockchain data to understand market participant behavior and network health. Unlike technical analysis which uses price data, or fundamental analysis which evaluates project quality, on-chain analysis provides a unique window into actual user activity, holder behavior, and capital flows that are publicly recorded on blockchains." toc={[
        { id: "what-is-on-chain", title: "what-is-on-chain", level: 2 },
        { id: "what-is-on-chain-analysis", title: "What Is On-Chain Analysis?", level: 2 },
        { id: "key-metrics", title: "key-metrics", level: 2 },
        { id: "key-on-chain-metrics", title: "Key On-Chain Metrics", level: 2 },
        { id: "exchange-flows", title: "exchange-flows", level: 2 },
        { id: "exchange-flow-analysis", title: "Exchange Flow Analysis", level: 2 },
        { id: "holder-behavior", title: "holder-behavior", level: 2 },
        { id: "holder-behavior-metrics", title: "Holder Behavior Metrics", level: 2 },
        { id: "practical-application", title: "practical-application", level: 2 },
        { id: "practical-application", title: "Practical Application", level: 2 }
      ]} faqs={[{question:"Is on-chain analysis reliable?",answer:"On-chain data is objective and tamper-proof — it comes directly from the blockchain. However, interpretation is subjective. The same data can be read differently by different analysts. On-chain metrics work best as one input alongside technical and fundamental analysis."},{question:"Does on-chain analysis work for all cryptocurrencies?",answer:"It works best for transparent blockchains like Bitcoin and Ethereum where all transaction data is publicly visible. Privacy coins have limited on-chain visibility. Token-specific on-chain metrics depend on the blockchain and available tooling."},{question:"What on-chain tools should I use?",answer:"Glassnode is the industry standard for on-chain analytics. CryptoQuant provides real-time exchange flow data. Santiment combines on-chain with social data. Dune Analytics allows custom on-chain queries. LookIntoBitcoin provides free Bitcoin-specific on-chain indicators."}]} relatedArticles={[{title:"Whale Tracking Guide",href:"/trading/learn/whale-tracking-guide",category:"Trading"},{title:"Fundamental Analysis Crypto",href:"/trading/learn/fundamental-analysis-crypto",category:"Trading"},{title:"Sentiment Analysis Guide",href:"/trading/learn/sentiment-analysis-guide",category:"Trading"}]}>
    <section id="what-is-on-chain"><h2>What Is On-Chain Analysis?</h2><p>On-chain analysis studies the data recorded on public blockchains — transactions, wallet balances, smart contract interactions, and network activity — to derive trading insights. Every Bitcoin transaction, every Ethereum smart contract call, and every wallet balance change is permanently recorded on the blockchain and publicly accessible. On-chain analysts extract meaning from this data by tracking patterns in how different types of participants (long-term holders, short-term traders, exchanges, miners) interact with the network. This analysis is unique to crypto — no other asset class provides such granular, real-time transparency into participant behavior. On-chain data reveals what market participants are actually doing, not just what prices are doing, providing a deeper layer of market intelligence.</p></section>
    <section id="key-metrics"><h2>Key On-Chain Metrics</h2><p>MVRV ratio (Market Value to Realized Value) compares the current market cap to the realized cap (the value of all coins at the price they last moved). MVRV above 3.5 historically indicates overvaluation. Below 1.0 indicates undervaluation. NUPL (Net Unrealized Profit/Loss) shows what portion of the market is in profit. Extreme profit (above 0.75) suggests euphoria. Extreme loss (below 0) suggests capitulation. SOPR (Spent Output Profit Ratio) measures whether coins being moved are being sold at a profit or loss. SOPR above 1 means profitable selling; below 1 means selling at a loss. Active addresses count unique addresses participating in transactions, measuring network adoption and activity. Hash rate for proof-of-work chains indicates miner confidence and network security. Each metric provides a different perspective on market health and participant behavior.</p></section>
    <section id="exchange-flows"><h2>Exchange Flow Analysis</h2><p>Exchange inflows represent crypto moving from personal wallets to exchanges — often a precursor to selling. Sustained high exchange inflows suggest distribution and potential selling pressure. Exchange outflows represent crypto moving from exchanges to personal wallets — often indicating accumulation for long-term holding. When outflows consistently exceed inflows, supply on exchanges decreases, which is bullish for price. Exchange reserves (the total amount of crypto held on exchanges) is a key metric — declining reserves mean less sell pressure available. Stablecoin exchange flows are equally important — large stablecoin inflows to exchanges suggest buying power being positioned. The ratio of stablecoin inflows to crypto inflows indicates whether the market is preparing to buy or sell. Track these metrics using CryptoQuant, Glassnode, or similar platforms that aggregate exchange wallet data across major platforms.</p></section>
    <section id="holder-behavior"><h2>Holder Behavior Metrics</h2><p>Long-term holder supply (coins that have not moved in 155+ days) versus short-term holder supply reveals the balance between conviction holders and active traders. When long-term holders accumulate during price weakness, it is a bullish signal. When they distribute during price strength, it suggests a potential top. Coin age metrics like CDD (Coin Days Destroyed) measure when old coins move — spikes in CDD indicate that long-dormant coins are being spent, often at market extremes. Supply distribution analysis shows the concentration of holdings across different wallet sizes — growing numbers of large wallets suggests institutional or whale accumulation. The supply last active in different time bands (1 day, 1 week, 1 month, 1 year, 5 years) creates an age spectrum that reveals the profile of current market activity versus long-term holding conviction.</p></section>
    <section id="practical-application"><h2>Practical Application</h2><p>Use on-chain analysis for macro timing rather than short-term trade entries. On-chain metrics are most valuable for identifying market cycle phases — accumulation, markup, distribution, and markdown — and positioning accordingly. Combine on-chain metrics with technical analysis: if on-chain data shows accumulation (bullish macro) while price is at a technical support level, the confluence creates a high-conviction buying opportunity. Create a dashboard of 5-7 key on-chain metrics and review them weekly. Look for agreement — when multiple metrics simultaneously signal the same direction, the signal is stronger. Be patient with on-chain signals — they often provide early warnings weeks or months before price confirms the direction. This is both their strength (early signals) and their challenge (waiting for confirmation can be uncomfortable). Document your on-chain analysis alongside your trading journal to build a personal reference of how these metrics correlated with subsequent price action in your experience.</p></section>
  </LearnPageLayout>);
}
