import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Sandwich Attacks in DeFi Explained (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Learn how sandwich attacks work in DeFi trading. Understand the mechanics, how much they cost traders, and practical strategies to protect your DEX swaps." };

export default function Page() {
  return (<LearnPageLayout title="Sandwich Attacks in DeFi Explained" categoryName="Crypto Exchanges" categorySlug="exchanges" readTime="8 min" intro="Sandwich attacks are one of the most common forms of MEV extraction on decentralized exchanges. They cost DeFi users millions of dollars by manipulating the price before and after your swap. This guide explains exactly how sandwich attacks work and how to protect yourself." toc={[
        { id: "what-is-sandwich", title: "what-is-sandwich", level: 2 },
        { id: "what-is-a-sandwich-attack", title: "What Is a Sandwich Attack?", level: 2 },
        { id: "mechanics", title: "mechanics", level: 2 },
        { id: "step-by-step-mechanics", title: "Step-by-Step Mechanics", level: 2 },
        { id: "cost-to-users", title: "cost-to-users", level: 2 },
        { id: "cost-to-users", title: "Cost to Users", level: 2 },
        { id: "detection", title: "detection", level: 2 },
        { id: "how-to-detect-sandwich-attacks", title: "How to Detect Sandwich Attacks", level: 2 },
        { id: "protection", title: "protection", level: 2 },
        { id: "protecting-your-swaps", title: "Protecting Your Swaps", level: 2 }
      ]} faqs={[{question:"Can sandwich attacks happen on centralized exchanges?",answer:"No. Sandwich attacks are specific to on-chain DEXs where transactions are publicly visible in the mempool before execution. Centralized exchanges match orders privately and do not expose pending orders to other traders."},{question:"Is a sandwich attack the same as front-running?",answer:"A sandwich attack includes front-running as one component. It consists of a front-run (buying before the victim), the victim's trade in the middle, and a back-run (selling after the victim). Pure front-running only involves the initial trade ahead of the victim."},{question:"Do sandwich attacks always succeed?",answer:"No. They can fail if the victim's transaction fails (due to slippage exceeding tolerance), if gas prices spike unexpectedly, or if another bot competes for the same opportunity. Failed sandwich attempts still cost the attacker gas fees."}]} relatedArticles={[{title:"MEV Explained",href:"/exchanges/learn/mev-explained",category:"Exchanges"},{title:"Front-Running Explained",href:"/exchanges/learn/front-running-explained",category:"Exchanges"},{title:"Slippage Explained",href:"/exchanges/learn/slippage-explained",category:"Exchanges"}]}>
    <section id="what-is-sandwich"><h2>What Is a Sandwich Attack?</h2><p>A sandwich attack is a form of market manipulation where an attacker places two transactions around a victim's pending DEX swap — one before (front-run) and one after (back-run) — to extract profit from the price impact. The attacker literally sandwiches the victim's transaction between their buy and sell. The result is that the victim gets a worse execution price than they would have without the attack. The attacker profits the difference minus gas costs. Sandwich attacks exploit the transparency of blockchain mempools and the predictable price impact of trades on AMMs. They are automated by sophisticated bots that monitor pending transactions in real time and execute within milliseconds.</p></section>
    <section id="mechanics"><h2>Step-by-Step Mechanics</h2><p>Here is how a sandwich attack works step by step. You submit a swap to buy Token X with 1,000 USDC on Uniswap with 2% slippage tolerance. Your transaction enters the public mempool. A sandwich bot detects your pending transaction and analyzes the expected price impact. The bot submits a buy transaction for Token X with higher gas priority, which executes before yours, pushing the price of Token X up. Your swap then executes at the now-higher price — you receive fewer Token X than you would have without the attack. Immediately after your transaction, the bot submits a sell transaction for Token X, selling the tokens it bought at the inflated price. The price returns roughly to where it started, and the bot pockets the difference. The entire sequence happens within a single block, taking just seconds.</p></section>
    <section id="cost-to-users"><h2>Cost to Users</h2><p>Sandwich attacks represent a substantial hidden cost for DeFi users. Research has shown that millions of dollars are extracted daily through sandwich attacks across major DEXs. The cost per attack depends on the size of the victim's transaction and their slippage tolerance. A swap with 5% slippage tolerance on a $10,000 trade could lose up to $500 to a sandwich attack. High-slippage settings during volatile markets or on illiquid tokens create the most profitable opportunities for attackers. Even with moderate slippage settings, the cumulative cost of partial sandwich attacks (extracting smaller amounts from many transactions) adds up significantly. New token launches and popular meme coin swaps are particularly targeted due to high slippage settings and large transaction volumes.</p></section>
    <section id="detection"><h2>How to Detect Sandwich Attacks</h2><p>After executing a DEX swap, check the blockchain explorer for transactions in the same block. If you see a large buy of the same token immediately before your swap and a large sell immediately after, you have likely been sandwiched. Tools like EigenPhi, Flashbots Explorer, and MEV Blocker dashboards can help identify sandwich attacks on your transactions. On Ethereum, you can check your transaction on sites that specifically track MEV activity. Signs include receiving significantly fewer tokens than the quoted amount, unusual price movement in the block containing your transaction, and the same address buying and selling the same token within the same block surrounding your transaction. Some DEX interfaces now warn users when their slippage settings make them vulnerable to sandwich attacks.</p></section>
    <section id="protection"><h2>Protecting Your Swaps</h2><p>The most effective protection is using private transaction relays. Flashbots Protect, MEV Blocker, and similar services send your transaction through a private channel that bypasses the public mempool. Many wallets now integrate these protections by default — MetaMask offers Flashbots Protect as an RPC option. Reduce your slippage tolerance to the minimum necessary for your trade to succeed — lower slippage means less profit for attackers, making your transaction not worth sandwiching. Use CoW Swap, which uses batch auctions that are inherently resistant to sandwich attacks because trades are matched off-chain and settled as a batch. Split large trades into smaller amounts across multiple transactions. On Solana, use Jupiter with appropriate slippage settings and consider using Jito for MEV-protected submissions. For frequent DeFi users, configuring a private RPC endpoint that routes through MEV protection services is the most convenient long-term solution.</p></section>
  </LearnPageLayout>);
}
