import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `ERC-20 Tokens Wallet Guide (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Complete guide to storing, sending, and managing ERC-20 tokens in crypto wallets. Learn about token approvals, gas costs, and compatible wallets.",
  keywords: ["ERC-20 tokens", "Ethereum tokens", "token wallet", "token approvals"],
};

export default function Page() {
  return (
    <LearnPageLayout title="ERC-20 Tokens Wallet Guide" categoryName="Crypto Wallets" categorySlug="wallets" readTime="7 min" intro="ERC-20 is the most widely used token standard on Ethereum and EVM-compatible blockchains. Understanding how these tokens interact with your wallet is essential for managing a diverse crypto portfolio. This guide covers everything from basic storage to advanced approval management and cross-chain considerations." toc={[{id:"what-are",title:"What Are ERC-20 Tokens?",level:2},{id:"storage",title:"How Wallets Store ERC-20 Tokens",level:2},{id:"approvals",title:"Token Approvals and Risks",level:2},{id:"management",title:"Managing ERC-20 Tokens Effectively",level:2}]} faqs={[{question:"Do ERC-20 tokens need their own wallet?",answer:"No. Any Ethereum-compatible wallet can hold all ERC-20 tokens. They share the same address as your ETH. However, your wallet may not automatically display all tokens — you may need to add custom tokens using their contract addresses to see your full balance."},{question:"Why do I need ETH to send ERC-20 tokens?",answer:"All Ethereum transactions require gas fees paid in ETH, including token transfers. When you send ERC-20 tokens, the transaction is executed on the Ethereum network and miners or validators must be compensated. Without ETH in your wallet, you cannot send or interact with your ERC-20 tokens."},{question:"What happens if I send ERC-20 tokens to the wrong network?",answer:"Sending ERC-20 tokens to a non-EVM address (like a Bitcoin address) will result in permanent loss. However, if you send tokens to the same address on a different EVM chain (like Polygon or Arbitrum), the tokens may be recoverable by switching networks in your wallet, since EVM chains share the same address format."}]} relatedArticles={[{title:"How to Add Custom Tokens",href:"/wallets/learn/how-to-add-custom-tokens",category:"Wallets"},{title:"Gas Fees Explained",href:"/wallets/learn/gas-fees-explained",category:"Wallets"},{title:"Wallet for DeFi Guide",href:"/wallets/learn/wallet-for-defi-guide",category:"Wallets"}]}>
      <section id="what-are"><h2>What Are ERC-20 Tokens?</h2><p>ERC-20 is a technical standard for fungible tokens on the Ethereum blockchain, proposed in 2015 and now the foundation of the Ethereum token ecosystem. The standard defines a common set of rules that all compliant tokens must follow, including functions for transferring tokens, checking balances, and approving third-party spending. This standardization means any wallet or application that supports ERC-20 can work with thousands of different tokens without custom integration. Major tokens like USDC, USDT, LINK, UNI, and AAVE are all ERC-20 tokens. The standard has been replicated across EVM-compatible chains — BEP-20 on BNB Chain and equivalent standards on Polygon, Arbitrum, and Avalanche are functionally identical to ERC-20 with minor naming differences. Understanding this standard is fundamental because the vast majority of tradeable crypto assets beyond native chain currencies are ERC-20 or equivalent tokens.</p></section>
      <section id="storage"><h2>How Wallets Store ERC-20 Tokens</h2><p>Unlike native ETH which exists as a base-layer balance, ERC-20 tokens are tracked by smart contracts on the blockchain. Your wallet does not literally contain tokens — instead, each token has its own smart contract that maintains a ledger of balances mapped to addresses. When your wallet shows a token balance, it is querying that token&apos;s smart contract for your address&apos;s entry. This means all ERC-20 tokens associated with your address use the same private key and address as your ETH. You do not need separate wallets or addresses for different tokens. Wallets display tokens by querying known token contracts, which is why new or obscure tokens may not appear automatically — the wallet needs to know which contracts to check. Adding a custom token tells your wallet to query an additional contract address for balance information. This architecture means your tokens exist on-chain regardless of which wallet software you use to view them.</p></section>
      <section id="approvals"><h2>Token Approvals and Risks</h2><p>Before a decentralized application can spend your ERC-20 tokens, you must grant it an approval — a transaction that authorizes a specific smart contract to transfer up to a specified amount of your tokens. Many dApps request unlimited approvals for convenience, meaning the contract can spend any amount of that token from your wallet indefinitely. This creates significant security risk: if the approved contract is exploited or turns malicious, it can drain all approved tokens without any further authorization from you. Regularly audit and revoke unnecessary approvals using tools like Revoke.cash or Etherscan&apos;s token approval checker. Best practice is to approve only the exact amount needed for each transaction, though this requires a separate approval transaction each time, costing additional gas. Some wallets like Rabby show approval warnings and help you manage permissions. Never approve token spending for contracts you do not trust, and be especially cautious with approval requests from unfamiliar dApps or links received through social media.</p></section>
      <section id="management"><h2>Managing ERC-20 Tokens Effectively</h2><p>Effective token management starts with choosing a wallet that provides comprehensive token support. MetaMask, Rabby, and Zerion automatically detect many popular tokens and allow easy custom token imports. For large portfolios, consider using a portfolio tracker like DeBank or Zapper alongside your wallet for a complete overview across chains. When sending tokens, always verify you are on the correct network — USDC on Ethereum mainnet is different from USDC on Polygon, even though both are ERC-20 compatible tokens at the same address. Double-check recipient addresses before confirming transfers, as token transactions are irreversible. Keep sufficient ETH for gas fees — a common frustration is having tokens you cannot move because you lack ETH for the transfer fee. For long-term holdings, consider moving tokens to a hardware wallet for enhanced security while maintaining full ERC-20 compatibility. Organize your token list by hiding dust amounts and spam tokens that clutter your wallet interface.</p></section>
    </LearnPageLayout>
  );
}
