import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Moving Averages Explained for Crypto Trading (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Learn how to use moving averages in crypto trading. Understand SMA, EMA, golden cross, death cross, and moving average strategies for trend identification." };

export default function Page() {
  return (<LearnPageLayout title="Moving Averages Explained" categoryName="Crypto Trading" categorySlug="trading" readTime="9 min" intro="Moving averages are the most widely used indicators in crypto trading. They smooth out price noise to reveal the underlying trend and serve as dynamic support and resistance levels. Understanding how to use different types of moving averages and their crossovers is fundamental to technical analysis." toc={[{id:"types",title:"Types of Moving Averages",level:2},{id:"key-periods",title:"Key Moving Average Periods",level:2},{id:"crossover-strategies",title:"Crossover Strategies",level:2},{id:"dynamic-sr",title:"Dynamic Support and Resistance",level:2},{id:"trading-strategies",title:"MA Trading Strategies",level:2}]} faqs={[{question:"Should I use SMA or EMA?",answer:"EMAs react faster to recent price changes, making them better for short-term trading. SMAs provide smoother signals with fewer false crossovers, better for swing and position trading. Many traders use EMAs on lower timeframes and SMAs on higher timeframes."},{question:"What are the best moving average periods?",answer:"The 20, 50, 100, and 200 periods are most commonly used. The 9 and 21 EMAs are popular for short-term trading. The 50 and 200 SMAs are the most watched for trend identification and crossover signals."},{question:"Do moving averages work in sideways markets?",answer:"Moving averages perform poorly in ranging, sideways markets because they are lagging, trend-following indicators. In ranges, they produce many false signals (whipsaws). Use oscillators like RSI instead during sideways periods."}]} relatedArticles={[{title:"Technical Analysis Basics",href:"/trading/learn/technical-analysis-basics",category:"Trading"},{title:"RSI Indicator Guide",href:"/trading/learn/rsi-indicator-guide",category:"Trading"},{title:"MACD Indicator Guide",href:"/trading/learn/macd-indicator-guide",category:"Trading"}]}>
    <section id="types"><h2>Types of Moving Averages</h2><p>The Simple Moving Average (SMA) calculates the arithmetic mean of closing prices over a specified number of periods. A 50-day SMA adds the last 50 closing prices and divides by 50. Each data point has equal weight. The Exponential Moving Average (EMA) applies more weight to recent prices, making it more responsive to new information. A 50-day EMA reacts faster to price changes than a 50-day SMA. The Weighted Moving Average (WMA) assigns linearly decreasing weights from most recent to oldest. The Hull Moving Average (HMA) reduces lag while maintaining smoothness by using weighted moving averages of different periods. For most crypto trading, SMA and EMA are sufficient. The choice between them depends on whether you prefer faster signals (EMA) or smoother, more reliable signals with slight delay (SMA).</p></section>
    <section id="key-periods"><h2>Key Moving Average Periods</h2><p>The 200-day MA is the most important long-term trend indicator. Price above the 200 MA indicates a bull market; below indicates a bear market. The 50-day MA tracks the intermediate trend and is widely watched for crossovers with the 200 MA. The 20-day MA reflects the short-term trend and is roughly equivalent to one month of trading. For shorter timeframes, the 9 and 21 EMAs are popular among day traders for identifying intraday trends. On weekly charts, the 20-week and 50-week MAs serve similar roles as the 100-day and 200-day on daily charts. The specific periods matter less than consistency — choose your periods and stick with them to develop intuition for how price interacts with your chosen averages over time.</p></section>
    <section id="crossover-strategies"><h2>Crossover Strategies</h2><p>The golden cross occurs when the 50-day MA crosses above the 200-day MA, signaling bullish momentum. The death cross is the opposite — the 50-day crosses below the 200-day, signaling bearish momentum. These are lagging signals that confirm trend changes rather than predict them, but they are among the most watched indicators in all of crypto. Faster crossovers like the 9/21 EMA cross provide earlier but less reliable signals — useful for shorter-term trading. The price crossing above or below a major MA also generates signals — a daily close above the 200 MA after being below it is a significant bullish event. To reduce false signals from crossovers, require the cross to be confirmed by volume and followed by a close beyond the MA for multiple consecutive days.</p></section>
    <section id="dynamic-sr"><h2>Dynamic Support and Resistance</h2><p>Moving averages act as dynamic (moving) support and resistance levels. In a strong uptrend, price often pulls back to the 20 or 50 MA before bouncing higher. Buying these pullbacks is one of the most effective MA strategies. In a strong downtrend, price often rallies to the 20 or 50 MA before resuming its decline — these become selling opportunities. The 200 MA often acts as a major inflection point where significant buying or selling occurs. When multiple MAs converge at the same price level, that zone becomes particularly strong support or resistance. The angle of the MA matters — a steeply rising MA is stronger support than a flat one, because the strong trend attracts buyers at the MA level.</p></section>
    <section id="trading-strategies"><h2>MA Trading Strategies</h2><p>The MA bounce strategy buys when price pulls back to a rising MA in an uptrend (or sells when price rallies to a falling MA in a downtrend). Enter when price touches the MA and shows a reversal candlestick pattern. Stop-loss below the MA. Target the recent high or next resistance. The MA crossover strategy buys when a faster MA crosses above a slower MA and sells on the opposite cross. Filter signals by only taking crosses in the direction of the higher timeframe trend. The multiple MA strategy uses three or more MAs (e.g., 20, 50, 200) — when all are aligned in order (20 above 50 above 200), the trend is strongly bullish; when all are stacked in reverse, strongly bearish. Only trade when MAs are aligned, avoiding choppy periods when MAs are tangled together. Combine MA strategies with volume and momentum confirmation for higher probability trades.</p></section>
  </LearnPageLayout>);
}
