import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Support and Resistance Levels in Crypto Trading (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Master support and resistance analysis for crypto trading. Learn how to identify key price levels, trade bounces and breakouts, and manage risk at critical zones." };

export default function Page() {
  return (<LearnPageLayout title="Support and Resistance Levels" categoryName="Crypto Trading" categorySlug="trading" readTime="9 min" intro="Support and resistance are the most fundamental concepts in technical analysis. These price levels represent zones where buying or selling pressure has historically been strong enough to reverse or pause price movement. Mastering support and resistance identification is essential for timing entries, exits, and stop-loss placement." toc={[
        { id: "basics", title: "basics", level: 2 },
        { id: "support-and-resistance-basics", title: "Support and Resistance Basics", level: 2 },
        { id: "identification", title: "identification", level: 2 },
        { id: "how-to-identify-key-levels", title: "How to Identify Key Levels", level: 2 },
        { id: "trading-levels", title: "trading-levels", level: 2 },
        { id: "trading-at-support-and-resistance", title: "Trading at Support and Resistance", level: 2 },
        { id: "breakouts", title: "breakouts", level: 2 },
        { id: "trading-breakouts", title: "Trading Breakouts", level: 2 },
        { id: "advanced", title: "advanced", level: 2 },
        { id: "advanced-concepts", title: "Advanced Concepts", level: 2 }
      ]} faqs={[{question:"Why do support and resistance levels work?",answer:"They work because many traders watch the same levels and place orders around them. This concentrated order flow creates real buying pressure at support and selling pressure at resistance. They are partly self-fulfilling prophecies reinforced by market structure."},{question:"How many times should a level be tested to be significant?",answer:"A level tested 2-3 times is considered significant. Each additional test may weaken the level as orders are absorbed. Levels that have held multiple times over longer timeframes are the most significant."},{question:"Do support and resistance work on all timeframes?",answer:"Yes, but higher timeframe levels are stronger. A daily support level carries more weight than a 15-minute support level. When levels from multiple timeframes converge at the same price, that zone becomes particularly significant."}]} relatedArticles={[{title:"Technical Analysis Basics",href:"/trading/learn/technical-analysis-basics",category:"Trading"},{title:"Trend Lines Guide",href:"/trading/learn/trend-lines-guide",category:"Trading"},{title:"Breakout Trading Guide",href:"/trading/learn/breakout-trading-guide",category:"Trading"}]}>
    <section id="basics"><h2>Support and Resistance Basics</h2><p>Support is a price level where a downtrend is expected to pause or reverse due to concentration of buying interest. Think of it as a floor — when price falls to this level, buyers step in and push it back up. Resistance is a price level where an uptrend is expected to pause or reverse due to concentration of selling interest. Think of it as a ceiling — when price rises to this level, sellers push it back down. A key principle is role reversal: once support is broken, it often becomes resistance, and once resistance is broken, it often becomes support. This happens because traders who bought at the former support now have losing positions and sell when price returns to that level to break even. Understanding this dynamic is crucial for identifying high-probability trading opportunities.</p></section>
    <section id="identification"><h2>How to Identify Key Levels</h2><p>Look for price levels where the market has reversed multiple times — the more touches, the more significant the level. Horizontal levels drawn at previous swing highs and swing lows are the most straightforward. Round numbers (like $50,000 for BTC or $3,000 for ETH) often act as psychological support and resistance because traders cluster orders at these round figures. Moving averages, especially the 50-day and 200-day, act as dynamic support and resistance. Volume profile data shows price levels where the most trading has occurred — these become natural support and resistance. Think of support and resistance as zones rather than exact prices. A narrow range of 1-2% around a key level is more realistic than expecting price to reverse at an exact number. Draw your levels on higher timeframes first, then zoom into lower timeframes for precision.</p></section>
    <section id="trading-levels"><h2>Trading at Support and Resistance</h2><p>Buy near support with a stop-loss just below the level. Sell or take profit near resistance with a target just below the level. Wait for confirmation at the level before entering — a bullish candlestick pattern at support or bearish pattern at resistance increases the probability of a successful trade. Never chase price away from a level — if you miss the bounce, wait for the next setup. The risk-reward is best when entering right at the level: your stop is tight (just beyond the level) and your target is the next level in the opposite direction. For example, buy at support with a stop 2% below and target resistance 10% above for a 5:1 risk-reward ratio. Be prepared for false breakouts where price briefly pierces a level before reversing — this is why stops should have a small buffer beyond the level.</p></section>
    <section id="breakouts"><h2>Trading Breakouts</h2><p>When price breaks through support or resistance with conviction, it signals a potential trend continuation or reversal. A valid breakout typically features strong volume (at least 1.5-2x average), a decisive close beyond the level (not just a wick), and follow-through in subsequent candles. After a breakout, watch for a retest of the broken level — this is often the best entry opportunity. For example, when price breaks above resistance and then pulls back to retest that level as new support, buying the retest offers a lower-risk entry than chasing the initial breakout. Failed breakouts are common and are called fakeouts — price breaks a level but quickly reverses back. This is why waiting for confirmation (a close beyond the level on the trading timeframe) before entering reduces false signal trades.</p></section>
    <section id="advanced"><h2>Advanced Concepts</h2><p>Support and resistance confluence occurs when multiple forms align at the same price — a horizontal level that coincides with a trend line, a moving average, and a Fibonacci level becomes extremely significant. Volume-weighted support and resistance use the volume profile to identify levels based on actual trading activity rather than just price history. Order block analysis, popular in smart money concepts, identifies areas where institutional orders are clustered. Supply and demand zones extend beyond traditional support and resistance by focusing on areas where price moved rapidly, suggesting unfilled orders remain. Pivot points calculate mathematical support and resistance levels based on the previous period's high, low, and close — widely used by day traders. Each of these advanced concepts adds depth to basic support and resistance analysis.</p></section>
  </LearnPageLayout>);
}
