import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `MACD Indicator Guide for Crypto Trading (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Master the MACD indicator for crypto. Learn signal line crossovers, histogram analysis, MACD divergences, and effective strategies for trend and momentum trading." };

export default function Page() {
  return (<LearnPageLayout title="MACD Indicator Guide" categoryName="Crypto Trading" categorySlug="trading" readTime="8 min" intro="The Moving Average Convergence Divergence (MACD) is a versatile trend-following momentum indicator that shows the relationship between two moving averages. It helps identify trend direction, momentum shifts, and potential reversal points. MACD is one of the most popular indicators among crypto traders for both trend and momentum analysis." toc={[{id:"how-macd-works",title:"How MACD Works",level:2},{id:"signal-crossovers",title:"Signal Line Crossovers",level:2},{id:"histogram",title:"Reading the Histogram",level:2},{id:"divergences",title:"MACD Divergences",level:2},{id:"strategies",title:"MACD Trading Strategies",level:2}]} faqs={[{question:"What are the best MACD settings for crypto?",answer:"The default settings (12, 26, 9) work well for most timeframes. For faster signals, try (8, 17, 9). For smoother signals on volatile crypto, try (19, 39, 9). Stick with defaults until you understand the indicator well enough to know why you would change them."},{question:"Is MACD a leading or lagging indicator?",answer:"MACD is primarily a lagging indicator since it is based on moving averages. However, MACD divergences can provide early warning signals of trend changes, giving it some leading characteristics. The histogram can also signal momentum shifts before the crossover occurs."},{question:"Can MACD be used alone for trading decisions?",answer:"While MACD provides valuable information, relying on it exclusively is not recommended. Combine MACD with price action, support/resistance levels, and at least one other indicator (like RSI) for more reliable signals."}]} relatedArticles={[{title:"RSI Indicator Guide",href:"/trading/learn/rsi-indicator-guide",category:"Trading"},{title:"Moving Averages Explained",href:"/trading/learn/moving-averages-explained",category:"Trading"},{title:"Bollinger Bands Guide",href:"/trading/learn/bollinger-bands-guide",category:"Trading"}]}>
    <section id="how-macd-works"><h2>How MACD Works</h2><p>MACD consists of three components. The MACD line is calculated by subtracting the 26-period EMA from the 12-period EMA. When the shorter EMA is above the longer EMA, MACD is positive (bullish); when below, negative (bearish). The signal line is a 9-period EMA of the MACD line — it acts as a trigger for buy and sell signals. The histogram displays the difference between the MACD line and signal line, providing a visual representation of the momentum and convergence or divergence between the two. The MACD essentially captures three types of information simultaneously: trend direction (above or below zero), momentum strength (the magnitude of the MACD value), and momentum change (the histogram showing acceleration or deceleration).</p></section>
    <section id="signal-crossovers"><h2>Signal Line Crossovers</h2><p>The most common MACD signal is the crossover between the MACD line and the signal line. A bullish crossover occurs when the MACD line crosses above the signal line — this suggests upward momentum is increasing. A bearish crossover occurs when the MACD line crosses below the signal line — downward momentum is increasing. Crossovers that occur above the zero line are considered stronger bullish signals because they happen within an already bullish trend. Crossovers below the zero line are stronger bearish signals. Zero line crossovers (the MACD line crossing above or below zero) indicate a change in trend direction and are significant but slower-developing signals. In choppy, sideways markets, MACD crossovers produce many false signals, which is why additional confirmation is always recommended.</p></section>
    <section id="histogram"><h2>Reading the Histogram</h2><p>The MACD histogram provides the earliest momentum signals. When the histogram is growing (bars getting taller), momentum is increasing in the current direction. When the histogram is shrinking (bars getting shorter), momentum is fading — even if the trend has not reversed. A histogram peak followed by declining bars often precedes a signal line crossover, giving you an early warning to prepare for a potential trade. The histogram crossing from negative to positive (or vice versa) is equivalent to the MACD line crossing the signal line. Look for histogram divergences where price makes a new high but the histogram makes a lower high — this is often the earliest warning of a momentum shift that will eventually lead to a trend change.</p></section>
    <section id="divergences"><h2>MACD Divergences</h2><p>MACD divergences work similarly to RSI divergences but focus on the relationship between price and the MACD line or histogram. Bullish divergence occurs when price makes lower lows while MACD makes higher lows — selling momentum is weakening. Bearish divergence occurs when price makes higher highs while MACD makes lower highs — buying momentum is fading. MACD histogram divergences are often earlier than MACD line divergences but can be less reliable. The most powerful MACD divergences occur on daily and weekly timeframes after extended trends. Always wait for a confirmation signal — such as a MACD crossover or price breaking a trend line — before acting on a divergence, as divergences can persist for extended periods during strong trends.</p></section>
    <section id="strategies"><h2>MACD Trading Strategies</h2><p>The MACD crossover strategy enters long on bullish crossovers and short on bearish crossovers, filtered by the MACD being above or below the zero line. This is the simplest application. The MACD histogram reversal strategy enters when the histogram reverses direction after reaching an extreme — this provides earlier entries than waiting for the full crossover. The MACD zero-line rejection strategy buys when the MACD line pulls back to the zero line and bounces during an uptrend — this represents a trend continuation after a correction. Combine MACD with RSI for powerful confirmation: a bullish MACD crossover with RSI above 50 or crossing above 50 is a higher-probability setup. Use MACD on a higher timeframe for trend direction and a lower timeframe for entry timing to improve signal quality.</p></section>
  </LearnPageLayout>);
}
