import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Decentralized Exchange (DEX) Guide (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Complete guide to decentralized exchanges. Learn how DEXs work, how to use them, popular platforms, and the advantages of non-custodial trading." };

export default function Page() {
  return (<LearnPageLayout title="Decentralized Exchange (DEX) Guide" categoryName="Crypto Exchanges" categorySlug="exchanges" readTime="10 min" intro="Decentralized exchanges let you trade crypto directly from your wallet without trusting a central authority with your funds. They have become a cornerstone of the DeFi ecosystem, processing billions in daily volume. This guide covers everything you need to know about DEXs." toc={[
        { id: "how-dexs-work", title: "how-dexs-work", level: 2 },
        { id: "how-dexs-work", title: "How DEXs Work", level: 2 },
        { id: "amm-vs-orderbook", title: "amm-vs-orderbook", level: 2 },
        { id: "amm-vs-order-book-dexs", title: "AMM vs Order Book DEXs", level: 2 },
        { id: "popular-dexs", title: "popular-dexs", level: 2 },
        { id: "popular-dexs-by-chain", title: "Popular DEXs by Chain", level: 2 },
        { id: "how-to-use", title: "how-to-use", level: 2 },
        { id: "how-to-use-a-dex", title: "How to Use a DEX", level: 2 },
        { id: "risks", title: "risks", level: 2 },
        { id: "dex-risks", title: "DEX Risks", level: 2 },
        { id: "cex-vs-dex", title: "cex-vs-dex", level: 2 },
        { id: "when-to-use-cex-vs-dex", title: "When to Use CEX vs DEX", level: 2 }
      ]} faqs={[{question:"Do I need KYC to use a DEX?",answer:"No. DEXs are permissionless — you connect a wallet and trade immediately with no identity verification."},{question:"Are DEXs safe?",answer:"DEXs eliminate exchange counterparty risk but introduce smart contract risk. Always use audited, established protocols and start with small amounts."},{question:"Can I trade any token on a DEX?",answer:"DEXs are permissionless, so any token with a liquidity pool can be traded. However, this also means scam tokens are present. Always verify contract addresses before trading."}]} relatedArticles={[{title:"AMM Explained",href:"/exchanges/learn/amm-explained",category:"Exchanges"},{title:"Impermanent Loss Explained",href:"/exchanges/learn/impermanent-loss-explained",category:"Exchanges"},{title:"Centralized vs Decentralized Exchanges",href:"/exchanges/compare/centralized-vs-decentralized",category:"Exchanges"}]}>
      <section id="how-dexs-work"><h2>How DEXs Work</h2><p>Decentralized exchanges operate through smart contracts on blockchains. Unlike centralized exchanges where a company holds your funds and matches orders, DEXs execute trades directly between users' wallets. The smart contracts handle trade execution, price calculation, and settlement automatically. Your assets remain in your wallet until the moment a trade executes, eliminating the need to trust a central custodian. This non-custodial model means no single entity can freeze your funds, censor your trades, or misappropriate your assets.</p></section>
      <section id="amm-vs-orderbook"><h2>AMM vs Order Book DEXs</h2><p>Most DEXs use Automated Market Makers (AMMs) that use mathematical formulas to determine prices based on the ratio of tokens in liquidity pools. Uniswap, Jupiter, and PancakeSwap are AMM-based. Some newer DEXs like Hyperliquid and dYdX use on-chain order books similar to centralized exchanges. AMMs are simpler and work well for most trades but can suffer from higher slippage on large orders. Order book DEXs offer tighter spreads and are better for active trading.</p></section>
      <section id="popular-dexs"><h2>Popular DEXs by Chain</h2><p>On Ethereum: Uniswap (largest AMM), Curve (stablecoin swaps), Balancer (customizable pools). On Solana: Jupiter (aggregator), Raydium (AMM), Orca (AMM). On BSC: PancakeSwap. On Arbitrum: GMX (perpetuals), Camelot. Cross-chain: THORSwap (native cross-chain swaps). For perpetual futures: Hyperliquid and dYdX are the leaders. Each chain's DEX ecosystem has different strengths in terms of speed, cost, and available tokens.</p></section>
      <section id="how-to-use"><h2>How to Use a DEX</h2><p>Step 1: Set up a compatible wallet (MetaMask for Ethereum, Phantom for Solana). Step 2: Fund your wallet by transferring crypto from an exchange or another wallet. Step 3: Navigate to the DEX website and connect your wallet. Step 4: Select the tokens you want to swap and enter the amount. Step 5: Review the quoted price, slippage, and fees. Step 6: Approve the token for trading (first-time only for each token). Step 7: Confirm the swap transaction in your wallet. Step 8: Wait for the blockchain to process the transaction.</p></section>
      <section id="risks"><h2>DEX Risks</h2><p>Smart contract risk is the primary concern — bugs in DEX code can lead to fund losses. Use established, audited protocols. Token risk is high on DEXs because anyone can create a trading pool for any token, including scam tokens. Always verify contract addresses through official project channels. Slippage risk is significant on low-liquidity pools. Impermanent loss affects liquidity providers. Front-running and sandwich attacks can worsen your trade execution.</p></section>
      <section id="cex-vs-dex"><h2>When to Use CEX vs DEX</h2><p>Use a CEX for fiat on-ramps, high-frequency trading, and when you need customer support. Use a DEX for self-custody trading, accessing tokens not listed on CEXs, participating in DeFi, and when privacy is important. Many experienced users use both: CEX for fiat conversion and major trades, DEX for new tokens, DeFi, and maintaining self-custody.</p></section>
    </LearnPageLayout>);
}
