import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `How to Bridge Tokens Between Chains (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Step-by-step guide to bridging crypto between Ethereum, Layer 2s, and other blockchains. Compare bridges, understand risks, and minimize fees.",
  keywords: ["bridge tokens", "cross-chain bridge", "Layer 2 bridge", "crypto bridge"],
};

export default function Page() {
  return (
    <LearnPageLayout title="How to Bridge Tokens Between Chains" categoryName="Crypto Wallets" categorySlug="wallets" readTime="7 min" intro="Bridging allows you to move crypto assets between different blockchain networks. As the multi-chain ecosystem expands, bridging has become an essential skill for accessing DeFi protocols, lower fees, and opportunities across Ethereum, Layer 2s, and alternative chains. This guide covers how bridges work, which to use, and how to stay safe." toc={[{id:"what-is",title:"What Is a Crypto Bridge?",level:2},{id:"types",title:"Types of Bridges",level:2},{id:"how-to",title:"How to Bridge Step by Step",level:2},{id:"safety",title:"Bridge Safety and Risks",level:2}]} faqs={[{question:"How long does bridging take?",answer:"Bridge times vary significantly. Native Layer 2 bridges to Arbitrum and Optimism take about 10 minutes for deposits but 7 days for withdrawals back to mainnet due to the optimistic rollup challenge period. Third-party bridges like Stargate, Across, and Hop complete in minutes in both directions. Fast bridge services sacrifice some decentralization for speed by fronting liquidity."},{question:"Can I bridge any token to any chain?",answer:"Not every token is available on every chain. Bridges can only transfer tokens that have liquidity or wrapped representations on the destination chain. Major tokens like ETH, USDC, and USDT are available on most chains. Smaller tokens may only exist on their native chain. Check bridge interfaces for available token pairs before planning your transfer."},{question:"What if my bridge transaction fails?",answer:"Most bridge failures return tokens to your source address, though this may take some time. If a bridge transaction appears stuck, check the bridge interface for a transaction status page. Some bridges have recovery mechanisms for failed transfers. Never attempt a second bridge transaction before confirming the status of the first one."}]} relatedArticles={[{title:"Gas Fees Explained",href:"/wallets/learn/gas-fees-explained",category:"Wallets"},{title:"EVM vs Solana Wallets",href:"/wallets/compare/evm-vs-solana-wallets",category:"Compare"},{title:"Wallet for DeFi Guide",href:"/wallets/learn/wallet-for-defi-guide",category:"Wallets"}]}>
      <section id="what-is"><h2>What Is a Crypto Bridge?</h2><p>A crypto bridge is a protocol that enables transferring assets between different blockchain networks that cannot natively communicate with each other. Blockchains are isolated systems — Ethereum does not inherently know about transactions on Solana, and Arbitrum cannot directly access assets on Polygon. Bridges solve this by locking tokens on the source chain and minting equivalent wrapped representations on the destination chain, or by using liquidity pools on both chains to facilitate swaps. When you bridge ETH from Ethereum to Arbitrum, for example, your ETH is locked in a bridge contract on Ethereum while an equivalent amount of ETH is released to you on Arbitrum. The process works in reverse when you bridge back. Different bridge architectures offer varying trade-offs between speed, cost, security, and decentralization. Understanding these trade-offs is essential for choosing the right bridge for your needs and risk tolerance.</p></section>
      <section id="types"><h2>Types of Bridges</h2><p>Native bridges are operated by the destination chain itself, like the official Arbitrum Bridge or Optimism Gateway. These are the most secure option for Layer 2 networks because they inherit the security guarantees of the rollup mechanism, but they often have longer withdrawal periods — up to 7 days for optimistic rollups. Third-party bridges like Stargate, Across, Hop Protocol, and Synapse operate independently and support multiple chains with faster transfer times. They use various security models including liquidity pools, optimistic verification, and relay networks. Aggregator bridges like LI.FI and Socket scan multiple bridges to find the cheapest and fastest route for your specific transfer. Centralized exchange bridges — depositing on one chain and withdrawing on another — offer simplicity but require trusting the exchange. Each bridge type has distinct risk profiles: native bridges are safest but slowest, third-party bridges balance speed and security, and centralized bridges are convenient but custodial during the transfer.</p></section>
      <section id="how-to"><h2>How to Bridge Step by Step</h2><p>First, ensure you have the destination chain configured in your wallet — most EVM wallets support adding custom networks through sites like Chainlist. Verify you have enough native tokens on the destination chain for gas fees, or use a bridge that includes gas on arrival. Navigate to your chosen bridge interface and connect your wallet. Select the source chain, destination chain, token, and amount. The bridge will display the estimated output amount, fees, and transfer time. Review these carefully — some bridges charge significant fees or have unfavorable exchange rates. Approve the token for spending if prompted, then confirm the bridge transaction. Wait for the transaction to confirm on the source chain and for the bridge to process the transfer. Monitor progress through the bridge&apos;s interface — most provide a transaction status tracker. Once completed, switch your wallet to the destination network to verify your tokens have arrived. Save the transaction hash for reference in case you need to troubleshoot.</p></section>
      <section id="safety"><h2>Bridge Safety and Risks</h2><p>Bridges have historically been the most exploited sector in crypto, with billions of dollars lost to bridge hacks including the Ronin Bridge, Wormhole, and Nomad exploits. The risk arises because bridges hold massive pools of locked assets, making them attractive targets. Minimize risk by using established bridges with strong security track records and regular audits. Prefer native Layer 2 bridges for moving assets between Ethereum and its rollups — these inherit Ethereum&apos;s security model. For third-party bridges, check the total value locked, audit history, and team reputation before trusting them with significant amounts. Bridge smaller test amounts before sending large transfers. Always verify you are using the official bridge URL — bookmark trusted bridge interfaces rather than finding them through search engines where phishing sites may appear. Be cautious with bridges offering unusually high liquidity incentives, as these may indicate elevated risk. Never approve unlimited token spending for bridge contracts — approve only the exact amount you intend to bridge.</p></section>
    </LearnPageLayout>
  );
}
