import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Crypto Fear and Greed Index Guide (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Understand the Crypto Fear and Greed Index. Learn how it works, what it measures, how to interpret its readings, and how to use it in your trading strategy." };

export default function Page() {
  return (<LearnPageLayout title="Fear and Greed Index Guide" categoryName="Crypto Trading" categorySlug="trading" readTime="7 min" intro="The Crypto Fear and Greed Index is one of the most watched sentiment indicators in crypto. It condenses multiple market data points into a single 0-100 score that reflects the emotional state of the market. Understanding how to read and use this index can improve your trading timing and help you avoid emotional decision-making." toc={[
        { id: "how-it-works", title: "how-it-works", level: 2 },
        { id: "how-the-index-works", title: "How the Index Works", level: 2 },
        { id: "components", title: "components", level: 2 },
        { id: "index-components", title: "Index Components", level: 2 },
        { id: "interpreting", title: "interpreting", level: 2 },
        { id: "interpreting-the-index", title: "Interpreting the Index", level: 2 },
        { id: "trading-signals", title: "trading-signals", level: 2 },
        { id: "using-it-for-trading", title: "Using It for Trading", level: 2 },
        { id: "limitations", title: "limitations", level: 2 },
        { id: "limitations", title: "Limitations", level: 2 }
      ]} faqs={[{question:"Who publishes the Fear and Greed Index?",answer:"The most widely cited version is published by Alternative.me and updated daily. Other versions exist from different providers with slightly different methodologies. The Alternative.me version has been the industry standard since 2018."},{question:"What is a good Fear and Greed reading to buy?",answer:"Historically, readings below 20 (extreme fear) have corresponded with excellent buying opportunities over longer time horizons. However, the index can stay in extreme fear during bear markets, so it should be combined with other analysis for timing."},{question:"How accurate is the Fear and Greed Index as a trading signal?",answer:"As a contrarian indicator at extremes, it has been reasonably reliable over multi-week timeframes. However, it should not be used in isolation. It works best when combined with technical, on-chain, and fundamental analysis for confirmation."}]} relatedArticles={[{title:"Sentiment Analysis Guide",href:"/trading/learn/sentiment-analysis-guide",category:"Trading"},{title:"Crypto Market Cycles",href:"/trading/learn/crypto-market-cycles",category:"Trading"},{title:"Crypto Trading Psychology",href:"/trading/learn/crypto-trading-psychology",category:"Trading"}]}>
    <section id="how-it-works"><h2>How the Index Works</h2><p>The Crypto Fear and Greed Index generates a daily score from 0 to 100. Scores of 0-24 indicate extreme fear, 25-49 indicate fear, 50 is neutral, 51-74 indicate greed, and 75-100 indicate extreme greed. The index is calculated by analyzing multiple market data sources and weighting them to produce a single composite score. The concept is borrowed from CNNMoney's Fear and Greed Index for traditional markets but adapted specifically for cryptocurrency. The daily update provides a snapshot of market sentiment that can be tracked over time to identify trends in investor emotion. Sustained extreme readings (multiple days or weeks at an extreme) are more significant than brief spikes.</p></section>
    <section id="components"><h2>Index Components</h2><p>Volatility (25% weight): Current Bitcoin volatility and maximum drawdowns compared to 30-day and 90-day averages. Higher volatility increases fear. Market momentum and volume (25%): Current volume and momentum compared to recent averages. High positive momentum increases greed. Social media (15%): Analysis of Twitter and Reddit post volume and sentiment related to Bitcoin and crypto. High engagement with positive sentiment increases greed. Surveys (15%): Polling of crypto investors to gauge sentiment directly (when available). Bitcoin dominance (10%): Rising Bitcoin dominance suggests fear (investors fleeing to perceived safety), while declining dominance suggests greed (risk appetite for altcoins). Google Trends (10%): Search volume for Bitcoin-related terms and the nature of searches (panic searches increase fear).</p></section>
    <section id="interpreting"><h2>Interpreting the Index</h2><p>The index is most useful at extremes. Extreme fear (below 20) historically marks periods when the market is oversold and investor capitulation is near completion. These readings have corresponded with major market bottoms in 2018, 2020, and 2022. Extreme greed (above 80) marks periods of euphoria where the market is likely overbought. These readings have appeared near major market tops. However, the index can remain at extremes for extended periods — extreme fear during a prolonged bear market does not mean the bottom is in tomorrow. Look for the index to spike to an extreme and then begin recovering as a more useful signal. The transition from extreme fear toward neutral often aligns with the early stages of a recovery. The transition from extreme greed toward neutral often precedes corrections.</p></section>
    <section id="trading-signals"><h2>Using It for Trading</h2><p>Contrarian strategy: Increase buying activity when the index reads below 20 and increase selling or profit-taking when it reads above 80. This simple approach has produced strong long-term results but requires patience. Momentum confirmation: In the middle range (30-70), the index can confirm momentum. A rising index supports bullish price action. A declining index warns of potential weakness. Regime identification: Sustained fear readings indicate bear market conditions — adjust strategies accordingly. Sustained greed readings indicate bull market conditions. DCA adjustment: Increase your regular DCA amount when the index is in extreme fear territory and decrease it during extreme greed. This value-weighted DCA approach buys more at lower sentiment (likely lower prices) and less at higher sentiment. Always combine Fear and Greed readings with your technical analysis rather than trading solely on the index.</p></section>
    <section id="limitations"><h2>Limitations</h2><p>The index is based primarily on Bitcoin and may not accurately reflect sentiment for specific altcoins or sectors. Social media data can be manipulated by bots and coordinated campaigns. The weighting of components is somewhat arbitrary and may not capture all relevant sentiment factors. During unique macro events (regulatory actions, black swan events), the index may lag actual sentiment shifts. The index provides a general sentiment reading but does not predict the magnitude or timing of price moves. Most importantly, the index tells you what the crowd is feeling, not what price will do. In trending markets, sentiment can remain extreme while price continues in the same direction for weeks or months. Use the index as one input in a broader analysis framework rather than as a standalone trading signal.</p></section>
  </LearnPageLayout>);
}
