import { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `What Is a Liquidity Pool? Definition & Guide (${CURRENT_YEAR}) | CryptoDegen`,
  description: "Learn what liquidity pools are in DeFi, how they enable decentralized trading, how liquidity providers earn fees, and the risks of providing liquidity.",
};

export default function PoolPage() {
  return (
    <LearnPageLayout title="What Is a Pool?" categoryName="Learn Crypto" categorySlug="learn" readTime="5 min read"
      intro="A liquidity pool is a collection of funds locked in a smart contract that facilitates decentralized trading, lending, and other DeFi activities. Pools replace traditional order books by allowing traders to swap tokens directly against pooled liquidity. Liquidity providers deposit token pairs into pools and earn trading fees proportional to their share. Pools are the fundamental building block of automated market makers (AMMs) and the DeFi ecosystem."
      toc={[{ id: "definition", title: "What Is a Pool?", level: 2 }, { id: "how-pools-work", title: "How Liquidity Pools Work", level: 2 }, { id: "providing-liquidity", title: "Providing Liquidity", level: 2 }, { id: "pool-risks", title: "Pool Risks", level: 2 }]}
      faqs={[{ question: "How do liquidity pools make money for providers?", answer: "Liquidity providers earn a share of trading fees generated by swaps in their pool. Uniswap V3 charges 0.01-1% per trade depending on the pool tier. This fee is split among all LPs in proportion to their share of the pool. Some pools also receive additional token incentives from protocols seeking to attract liquidity." },
        { question: "What is impermanent loss?", answer: "Impermanent loss occurs when the price ratio of tokens in your pool changes from when you deposited. The greater the divergence, the more you would have earned by simply holding the tokens. It is called impermanent because the loss is only realized when you withdraw. If prices return to the original ratio, the loss disappears. Trading fees earned may offset impermanent loss." }]}
      relatedArticles={[{ title: "Impermanent Loss", href: "/learn/glossary/impermanent-loss", category: "Glossary" }, { title: "AMM Explained", href: "/learn/amm-explained", category: "Learn Crypto" }, { title: "Farming", href: "/learn/glossary/farming", category: "Glossary" }, { title: "What Is a DEX?", href: "/learn/what-is-a-dex", category: "Learn Crypto" }]}
    >
      <h2 id="definition">What Is a Pool?</h2>
      <p>A liquidity pool is a smart contract holding reserves of two or more tokens that enables automated trading. Instead of matching individual buy and sell orders, pools use mathematical formulas to price trades based on the ratio of tokens in the pool. The most common formula is x * y = k (constant product), where swapping one token for another changes the ratio and thus the price. This mechanism ensures continuous liquidity for any trade size.</p>

      <h2 id="how-pools-work">How Liquidity Pools Work</h2>
      <p>When a trader swaps ETH for USDC in a pool, they add ETH and remove USDC, changing the pool&apos;s ratio and shifting the effective price. Larger trades relative to pool size create more price impact (slippage). Deep pools with more liquidity offer better pricing because each trade has a smaller proportional impact on the ratio. AMMs like Uniswap V3 introduced concentrated liquidity, allowing LPs to focus their capital in specific price ranges for greater capital efficiency.</p>

      <h2 id="providing-liquidity">Providing Liquidity</h2>
      <p>To provide liquidity, you deposit token pairs in the required ratio and receive LP tokens representing your pool share. On Uniswap V3, you choose a price range for concentrated liquidity positions. Your share of trading fees accrues continuously and is claimable when you withdraw. Some protocols offer additional incentives in their native tokens to attract liquidity to specific pools, a practice known as liquidity mining or yield farming.</p>

      <h2 id="pool-risks">Pool Risks</h2>
      <p>Impermanent loss is the primary risk, where price divergence between paired tokens causes your position to underperform a simple hold strategy. Smart contract risk applies to the pool contract itself. Rug pulls can occur in pools with unverified or malicious tokens. Low-liquidity pools are vulnerable to price manipulation. Always research both tokens in a pool, verify the pool contract, and ensure sufficient trading volume to generate meaningful fees relative to impermanent loss risk.</p>
    </LearnPageLayout>
  );
}
