import { Metadata } from "next";
import Link from "next/link";
import AuthorAttribution, { getAuthorForSection } from "@/components/AuthorAttribution";
import ReviewPage from "@/components/ReviewPage";
import { CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `TrueFi Review (2026): Uncollateralized DeFi Lending | degen0x`,
  description: "In-depth TrueFi review covering uncollateralized institutional lending, TRU token staking, on-chain credit scoring, and managed portfolio products.",
  alternates: { canonical: "/defi-lending/reviews/truefi" },
  openGraph: { type: "website", images: [{ url: "/og-default.svg", width: 1200, height: 630 }] },
  twitter: { card: "summary_large_image" }};

const breadcrumbData = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://degen0x.com/' },
    { '@type': 'ListItem', position: 2, name: 'Defi Lending', item: 'https://degen0x.com/defi-lending' },
    { '@type': 'ListItem', position: 3, name: 'Reviews', item: 'https://degen0x.com/defi-lending/reviews' },
    { '@type': 'ListItem', position: 4, name: 'Truefi', },
  ],
};

export default function TrueFiReview() {
  return (
    <>
      <ReviewPage
      product={{
        name: "TrueFi",
        slug: "truefi",
        rating: 3.9,
        description: "TrueFi is an uncollateralized DeFi lending protocol that uses on-chain credit scoring and TRU token governance to facilitate institutional lending.",
        pros: ["On-chain credit scoring for borrower assessment", "Higher yields from uncollateralized lending premium", "TRU staking provides insurance and governance", "Portfolio manager system for professional credit management"],
        cons: ["Higher default risk without collateral backing", "Historical exposure to borrower defaults", "Smaller TVL limits lending capacity"],
        bestFor: "DeFi lenders comfortable with credit risk seeking higher yields",
        affiliateUrl: "#",
        category: "defi-lending",
      }}
      categoryName="DeFi Lending"
      categorySlug="defi-lending"
      overview="TrueFi is a decentralized protocol for uncollateralized lending that brings traditional credit market dynamics to DeFi. The platform enables institutional borrowers to access capital without posting crypto collateral, relying instead on creditworthiness assessments, legal agreements, and TRU token staking for risk management. TrueFi introduced one of the first on-chain credit scoring systems, allowing the community to evaluate borrower risk through quantitative analysis and TRU holder voting. The protocol supports both automated lending pools and individually managed portfolios run by professional credit managers. Since launch, TrueFi has facilitated significant loan origination volume to borrowers including trading firms, fintech companies, and emerging market lenders. The protocol navigated challenges during the 2022 downturn and continues developing its credit infrastructure with enhanced risk management."
      sections={[
        { id: "credit-scoring", title: "On-Chain Credit Scoring", content: "TrueFi pioneered an on-chain credit scoring mechanism that evaluates borrower creditworthiness through multiple factors. The system considers the borrower's repayment history on the platform, company background and financial health, proposed loan terms, and current market conditions. TRU token holders participate in the credit assessment process by voting on whether to approve individual loan requests, creating a decentralized credit committee with skin-in-the-game evaluation. The credit score influences the interest rate offered to borrowers, with higher-risk borrowers paying more. This transparent, community-driven approach to credit assessment is a significant innovation over opaque traditional lending." },
        { id: "lending-pools", title: "Lending Pool Structure", content: "TrueFi operates multiple lending pools denominated in different stablecoins. Lenders deposit assets into these pools and receive tfTokens representing their share. When borrowers are approved, they draw funds from the relevant pool with interest payments flowing back proportionally. Each pool has risk parameters including maximum loan sizes, concentration limits, and minimum credit scores. The protocol also supports lines of credit where approved borrowers can draw and repay flexibly within pre-approved limits. Pool utilization rates influence yields, with higher utilization generally meaning better returns for lenders." },
        { id: "tru-staking", title: "TRU Token & Staking", content: "The TRU token serves as governance token, insurance mechanism, and credit assessment tool. TRU stakers provide a first-loss buffer for lending pools, meaning staked tokens are first to be liquidated in the event of borrower default. In return, stakers earn a portion of interest generated by lending activity. TRU holders also vote on borrower approvals, protocol parameters, and treasury management. The staking mechanism creates strong alignment between token holders and platform health, as stakers are directly exposed to credit quality of approved borrowers." },
        { id: "managed-portfolios", title: "Managed Portfolios", content: "TrueFi expanded to support individually managed portfolios run by professional credit managers who have discretion over borrower selection, loan terms, and risk management within protocol parameters. This brings traditional credit management expertise to DeFi while maintaining on-chain transparency. Managed portfolios can focus on niches such as emerging market lending, trade finance, or revenue-based financing, allowing lenders to choose portfolios matching their risk preferences." },
      ]}
      fees={{ "Protocol Fee": "Percentage of interest income", "Origination Fee": "Charged to borrowers at loan creation", "Exit Fee": "Applicable for early pool withdrawals", "Gas Costs": "Standard Ethereum gas fees" }}
      security={["TRU staking as first-loss insurance buffer", "On-chain credit scoring for borrower assessment", "Legal agreements with institutional borrowers", "Diversified pool structure", "Smart contract audits by multiple firms", "Bug bounty program"]}
      features={["On-chain credit scoring system", "TRU governance and insurance staking", "Multiple stablecoin lending pools", "Managed portfolio products", "Lines of credit for approved borrowers", "Professional portfolio manager system"]}
      faqs={[
        { question: "How does TrueFi handle borrower defaults?", answer: "Staked TRU tokens serve as the first-loss buffer to partially compensate lenders. The protocol also pursues legal recovery against borrowers through signed loan agreements. The TRU community participates in governance decisions about handling default situations." },
        { question: "What yields can I expect on TrueFi?", answer: "Yields vary based on market conditions and borrower demand but are typically higher than overcollateralized protocols because lenders are compensated for taking credit risk. Additional TRU token rewards may further boost effective yields during incentive periods." },
        { question: "Is TrueFi safe for beginners?", answer: "TrueFi involves uncollateralized lending which carries higher risk than overcollateralized protocols like Aave. Beginners should understand that while yields are higher, there is genuine default risk. Start with small amounts and diversify across multiple pools if using the protocol." },
      ]}
      relatedReviews={[{ name: "Maple Finance", slug: "/defi-lending/reviews/maple-finance" }, { name: "Clearpool", slug: "/defi-lending/reviews/clearpool" }]}
      relatedGuides={[{ title: "DeFi Credit Scoring", href: "/defi-lending/learn/defi-credit-scoring" }, { title: "Undercollateralized Lending", href: "/defi-lending/learn/undercollateralized-lending" }]}
    />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbData) }} />
          <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({"@context": "https://schema.org", "@type": "WebPage", "name": "On-Chain Credit Scoring", "description": "In-depth TrueFi review covering uncollateralized institutional lending, TRU token staking, on-chain credit scoring, and managed portfolio products.", "url": "https://degen0x.com/defi-lending/reviews/truefi", "datePublished": "2026-04-13", "dateModified": "2026-04-13"}) }} />
    </>
  );
}
