import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Chart Patterns Guide for Crypto Trading (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Master essential chart patterns for crypto trading. Learn triangles, wedges, flags, head and shoulders, double tops/bottoms, and how to trade them profitably." };

export default function Page() {
  return (<LearnPageLayout title="Chart Patterns Guide" categoryName="Crypto Trading" categorySlug="trading" readTime="11 min" intro="Chart patterns are formations created by price movements that signal potential future direction. They represent the collective psychology of buyers and sellers forming recognizable shapes. Learning to identify and trade chart patterns gives you a systematic framework for finding high-probability trading setups." toc={[
        { id: "reversal-patterns", title: "reversal-patterns", level: 2 },
        { id: "reversal-patterns", title: "Reversal Patterns", level: 2 },
        { id: "continuation-patterns", title: "continuation-patterns", level: 2 },
        { id: "continuation-patterns", title: "Continuation Patterns", level: 2 },
        { id: "triangle-patterns", title: "triangle-patterns", level: 2 },
        { id: "triangle-patterns", title: "Triangle Patterns", level: 2 },
        { id: "trading-patterns", title: "trading-patterns", level: 2 },
        { id: "how-to-trade-patterns", title: "How to Trade Patterns", level: 2 },
        { id: "reliability", title: "reliability", level: 2 },
        { id: "pattern-reliability", title: "Pattern Reliability", level: 2 }
      ]} faqs={[{question:"Which chart patterns are most reliable in crypto?",answer:"Symmetrical triangles, bull and bear flags, and head and shoulders patterns tend to be among the most reliable in crypto markets. Patterns on higher timeframes (daily, weekly) are significantly more reliable than those on lower timeframes."},{question:"How do I calculate price targets from patterns?",answer:"Most patterns have measured move targets. For head and shoulders, measure the distance from the head to the neckline and project that distance from the breakout point. For triangles and flags, project the prior move's length from the breakout point."},{question:"Do chart patterns work in all market conditions?",answer:"Continuation patterns (flags, triangles) work best in trending markets. Reversal patterns (head and shoulders, double tops) work best at the end of extended trends. In choppy, directionless markets, pattern reliability decreases significantly."}]} relatedArticles={[{title:"Head and Shoulders Pattern",href:"/trading/learn/head-and-shoulders-pattern",category:"Trading"},{title:"Double Top Bottom Pattern",href:"/trading/learn/double-top-bottom-pattern",category:"Trading"},{title:"Bull Bear Flags",href:"/trading/learn/bull-bear-flags",category:"Trading"}]}>
    <section id="reversal-patterns"><h2>Reversal Patterns</h2><p>Head and shoulders is the most well-known reversal pattern. It consists of three peaks where the middle peak (head) is higher than the two surrounding peaks (shoulders). The neckline connects the lows between the peaks. A break below the neckline signals a bearish reversal. The inverse head and shoulders is the bullish counterpart at market bottoms. Double tops form when price reaches a resistance level twice and fails both times, creating an M-shape. A break below the trough between the two tops confirms the reversal. Double bottoms are the bullish mirror, forming a W-shape at support. Triple tops and bottoms add a third test of the level, making the eventual break more powerful. Rounding tops and bottoms show gradual, sustained shifts in market sentiment over longer periods.</p></section>
    <section id="continuation-patterns"><h2>Continuation Patterns</h2><p>Bull flags form when a strong upward move (the flagpole) is followed by a shallow, downward-sloping consolidation (the flag). The pattern resolves with a breakout to the upside, continuing the prior trend. Bear flags are the inverse. Pennants are similar to flags but form a small symmetrical triangle shape during the consolidation instead of a rectangular channel. Wedges can be continuation or reversal patterns depending on context. A falling wedge in an uptrend typically resolves with an upside breakout (continuation). A rising wedge in a downtrend typically breaks downward. Rectangles are horizontal consolidation patterns where price bounces between parallel support and resistance — they can break in either direction but tend to continue the prior trend.</p></section>
    <section id="triangle-patterns"><h2>Triangle Patterns</h2><p>Ascending triangles have a flat upper resistance line and a rising lower trend line, showing increasing buying pressure. They typically break upward. Descending triangles have a flat lower support line and a falling upper trend line, showing increasing selling pressure. They typically break downward. Symmetrical triangles have both a declining upper trend line and a rising lower trend line, showing compression from both sides. They can break in either direction but often continue the prior trend. The breakout from triangles should occur in the final third of the triangle's length — breakouts too early may not have sufficient compression. Volume should decrease as the triangle forms and increase significantly on the breakout. The measured move target for triangles is the height of the triangle's widest point projected from the breakout.</p></section>
    <section id="trading-patterns"><h2>How to Trade Patterns</h2><p>Wait for the pattern to complete and for a breakout to occur before entering — anticipating pattern completion leads to frequent losses from failed patterns. Enter on the breakout candle close or on the retest of the breakout level. Use the measured move technique for setting price targets: for head and shoulders, measure head-to-neckline distance and project from breakout. For flags, project the flagpole length from the flag breakout. For triangles, project the widest point of the triangle. Place stop-losses at logical invalidation points — for a head and shoulders, above the right shoulder; for a double bottom, below the second bottom. Volume should confirm the breakout. Risk-reward should be at least 2:1 based on the measured move target and your stop-loss distance.</p></section>
    <section id="reliability"><h2>Pattern Reliability</h2><p>Not all patterns are equally reliable. Patterns with clear, well-defined structure are more reliable than messy, ambiguous formations. Patterns on higher timeframes (daily and above) are more reliable than those on intraday charts. Patterns confirmed by volume (increasing on breakout) are more reliable than those without volume confirmation. The preceding trend matters — reversal patterns after extended trends are more reliable than those forming mid-range. Context is crucial: a bearish head and shoulders forming at a major resistance level with bearish RSI divergence is far more reliable than the same pattern in isolation. Track your pattern trading results to identify which patterns work best for the specific markets and timeframes you trade — your personal statistics are more valuable than general reliability claims.</p></section>
  </LearnPageLayout>);
}
