import { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `What Is Reserve Rights (RSR)? Price, Guide & How to Buy (${CURRENT_YEAR}) | degen0x`,
  description: "Learn about Reserve Rights (RSR), the governance token of the Reserve Protocol for asset-backed stablecoins. Discover RSR tokenomics and how to buy.",
};

export default function ReserveRightsPage() {
  return (
    <LearnPageLayout
      title="What Is Reserve Rights (RSR)? Price, Guide & How to Buy"
      categoryName="Investing"
      categorySlug="investing"
      readTime="8 min read"
      intro="Reserve Rights (RSR) is the governance and backstop token of the Reserve Protocol, a platform for creating asset-backed stablecoins called RTokens. RSR can be staked on individual RTokens to provide overcollateralization insurance, earning yield from the underlying assets in return for absorbing first-loss risk if the backing falls below 100%."
      toc={[
        { id: "what-is", title: "what-is", level: 2 },
        { id: "what-is-reserve-rights", title: "What Is Reserve Rights?", level: 2 },
        { id: "how-it-works", title: "how-it-works", level: 2 },
        { id: "how-does-reserve-rights-work", title: "How Does Reserve Rights Work?", level: 2 },
        { id: "tokenomics", title: "tokenomics", level: 2 },
        { id: "rsr-tokenomics", title: "RSR Tokenomics", level: 2 },
        { id: "use-cases", title: "use-cases", level: 2 },
        { id: "key-use-cases", title: "Key Use Cases", level: 2 },
        { id: "how-to-buy", title: "how-to-buy", level: 2 },
        { id: "how-to-buy-rsr", title: "How to Buy RSR", level: 2 },
        { id: "risks", title: "risks", level: 2 },
        { id: "risks-and-considerations", title: "Risks and Considerations", level: 2 }
      ]}
      faqs={[
        { question: "What is Reserve Rights?", answer: "RSR is the governance and backstop token for the Reserve Protocol, which enables permissionless creation of asset-backed stablecoins (RTokens). RSR can be staked on RTokens to earn yield and provide overcollateralization insurance." },
        { question: "Where can I buy RSR?", answer: "RSR is available on Coinbase, Binance, KuCoin, and other major exchanges." },
        { question: "Is Reserve Rights a good investment?", answer: "RSR offers yield through RToken staking and exposure to the asset-backed stablecoin sector. Success depends on RToken adoption and the protocol's ability to attract significant TVL." },
      ]}
      relatedArticles={[
        { title: "Best Cryptos to Buy", href: "/investing/best/cryptos-to-buy", category: "Investing" },
        { title: "How to Invest in Crypto", href: "/investing/learn/how-to-invest-in-crypto", category: "Investing" },
      ]}
    >
      <section id="what-is"><h2>What Is Reserve Rights?</h2><p>Reserve Rights (RSR) is a token within the Reserve Protocol ecosystem that serves as both governance and overcollateralization insurance for asset-backed stablecoins. The Reserve Protocol allows anyone to create permissionless, asset-backed stablecoins (RTokens) composed of baskets of ERC-20 tokens including other stablecoins, yield-bearing assets, and tokenized real-world assets. eUSD and ETH+ are prominent RTokens built on the protocol.</p><p>RSR holders can stake their tokens on specific RTokens, providing an additional insurance layer. If an RToken's collateral loses value, staked RSR is sold to recapitalize the backing. In exchange for this risk, RSR stakers earn a portion of the yield generated by the RToken's underlying collateral basket. This creates a market-driven insurance mechanism for decentralized stablecoins.</p></section>
      <section id="how-it-works"><h2>How Does Reserve Rights Work?</h2><p>The Reserve Protocol operates through a governance system where RSR stakers on each RToken can vote on basket composition changes, revenue distribution, and other parameters. Each RToken defines its collateral basket (e.g., a mix of USDC, DAI, and yield-bearing tokens), and the protocol automatically manages rebalancing and revenue distribution. When collateral generates yield, revenue is split between RToken holders and RSR stakers according to the configured ratio.</p><p>If a collateral token depegs or loses value, the protocol first uses excess collateral to maintain backing, then auctions staked RSR to purchase replacement collateral. This first-loss position means RSR stakers bear the risk of collateral failure in exchange for their yield, similar to how insurance providers earn premiums for assuming risk.</p></section>
      <section id="tokenomics"><h2>RSR Tokenomics</h2><p>RSR has a total supply of 100 billion tokens with a portion still subject to slow unlock schedules. The large supply means per-token price is very low, but market cap reflects the total value. RSR is burned when sold to recapitalize undercollateralized RTokens, creating a deflationary mechanism tied to insurance events. Staking yields vary by RToken based on collateral composition and risk parameters. The protocol has attracted significant TVL through its higher-yield RTokens.</p></section>
      <section id="use-cases"><h2>Key Use Cases</h2><p>RSR is used for staking as overcollateralization insurance on RTokens, governance over RToken parameters, and earning yield from collateral baskets. The Reserve Protocol enables creation of custom stablecoins, yield-bearing dollar assets, diversified collateral baskets, and inflation-hedging currencies. The protocol's permissionless nature allows anyone to design and deploy new RTokens for specific use cases.</p></section>
      <section id="how-to-buy"><h2>How to Buy RSR</h2><p>RSR is available on Coinbase, Binance, KuCoin, and other major exchanges. After purchasing, stake RSR on preferred RTokens through the Reserve app at register.app to earn yield. Evaluate the risk profile of each RToken's collateral basket before staking. Store in MetaMask or any Ethereum-compatible wallet.</p></section>
      <section id="risks"><h2>Risks and Considerations</h2><p>RSR stakers face first-loss risk if RToken collateral fails, meaning staked RSR can be liquidated to recapitalize the system. The large total supply and remaining unlock schedule create potential sell pressure. RToken adoption is still growing and not yet at scale. Smart contract risk across the protocol's complex collateral management system is significant. Regulatory classification of RSR's insurance-like function is unclear. Competition from other stablecoin protocols and yield platforms is ongoing.</p></section>
    </LearnPageLayout>
  );
}
