import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Double Top and Double Bottom Patterns (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Learn to trade double top and double bottom patterns in crypto. Understand pattern identification, confirmation, measured moves, and common trading mistakes." };

export default function Page() {
  return (<LearnPageLayout title="Double Top and Double Bottom Patterns" categoryName="Crypto Trading" categorySlug="trading" readTime="8 min" intro="Double tops and double bottoms are classic reversal patterns that form when price tests a key level twice and fails to break through. These M-shaped (double top) and W-shaped (double bottom) formations are among the most frequently occurring and tradable patterns in crypto markets." toc={[
        { id: "double-top", title: "double-top", level: 2 },
        { id: "double-top-pattern", title: "Double Top Pattern", level: 2 },
        { id: "double-bottom", title: "double-bottom", level: 2 },
        { id: "double-bottom-pattern", title: "Double Bottom Pattern", level: 2 },
        { id: "confirmation", title: "confirmation", level: 2 },
        { id: "confirmation-and-entry", title: "Confirmation and Entry", level: 2 },
        { id: "measured-moves", title: "measured-moves", level: 2 },
        { id: "measured-move-targets", title: "Measured Move Targets", level: 2 },
        { id: "variations", title: "variations", level: 2 },
        { id: "variations-and-tips", title: "Variations and Tips", level: 2 }
      ]} faqs={[{question:"Do the two peaks/troughs need to be at exactly the same price?",answer:"No. A small variance of 1-3% between the two peaks or troughs is normal. What matters is that price clearly fails to make a new high (or low) on the second attempt, showing that the level is acting as strong resistance (or support)."},{question:"How long between the two peaks should I wait?",answer:"The time between peaks typically ranges from 2 weeks to 3 months on daily charts. Patterns that form too quickly (within a day or two) are less reliable. Adequate time between peaks allows sentiment to shift and creates a more significant pattern."},{question:"What if there is a third test of the level?",answer:"A third test creates a triple top or triple bottom, which is also a valid reversal pattern. Triple tops and bottoms are less common but generally more powerful because the level has been tested and held three times, building stronger support or resistance."}]} relatedArticles={[{title:"Chart Patterns Guide",href:"/trading/learn/chart-patterns-guide",category:"Trading"},{title:"Head and Shoulders Pattern",href:"/trading/learn/head-and-shoulders-pattern",category:"Trading"},{title:"Support and Resistance Levels",href:"/trading/learn/support-resistance-levels",category:"Trading"}]}>
    <section id="double-top"><h2>Double Top Pattern</h2><p>A double top forms when price rises to a resistance level, pulls back, rallies again to approximately the same level, and fails again. The pattern looks like the letter M. The first peak establishes the resistance level. The trough between the peaks (the neckline) creates a support level. The second peak shows that buyers could not push past the resistance despite a second attempt, indicating that the uptrend is losing strength. Volume often declines on the second peak compared to the first, confirming weakening buying pressure. The pattern is confirmed when price breaks below the neckline (the support level formed by the trough between the two peaks). Until this break occurs, the pattern is only potential — many double top attempts fail and price continues higher.</p></section>
    <section id="double-bottom"><h2>Double Bottom Pattern</h2><p>A double bottom is the bullish mirror of the double top, forming a W-shape at market bottoms. Price falls to a support level, bounces, declines again to approximately the same level, and bounces again. The first trough establishes support. The second trough confirms that sellers cannot push price lower. The peak between the two troughs forms the neckline. Volume often increases on the second bounce, showing growing buying interest. The pattern is confirmed when price breaks above the neckline. Double bottoms are particularly significant after extended downtrends in crypto — they often mark the accumulation phase where smart money is buying while the general market remains bearish. In crypto, double bottoms at round number support levels are especially common and reliable.</p></section>
    <section id="confirmation"><h2>Confirmation and Entry</h2><p>Never trade a double top or bottom before the neckline break confirms it. Many patterns fail — the second peak may not hold, and price continues trending. Wait for a decisive close beyond the neckline, ideally with above-average volume. The conservative entry enters after the neckline break and a subsequent retest of the neckline as new resistance (for double tops) or support (for double bottoms). This retest happens in roughly 60% of cases and provides the best risk-reward entry. The aggressive entry enters on the neckline break itself. For a double bottom, place your stop below the two troughs. For a double top, place your stop above the two peaks. The neckline break should be clean — a close significantly beyond the level, not a marginal wick that quickly reverses.</p></section>
    <section id="measured-moves"><h2>Measured Move Targets</h2><p>The minimum price target for a double top or bottom is the height of the pattern projected from the neckline break. For a double top: measure the distance from the peaks to the neckline, then subtract that distance from the neckline break point. If the peaks are at $50,000 and the neckline is at $45,000, the target is $40,000 ($45,000 - $5,000). For a double bottom: add the pattern height to the neckline break point. These measured moves represent minimum targets — price often continues beyond them. Use the measured move as your primary target and adjust based on other support and resistance levels. Some traders take partial profits at the measured move and trail a stop on the remainder for potential extended moves.</p></section>
    <section id="variations"><h2>Variations and Tips</h2><p>Adam and Eve variations describe the shape of the peaks or troughs. Adam tops are sharp, V-shaped. Eve tops are rounded, U-shaped. Adam and Eve combinations (one sharp, one rounded) tend to be particularly reliable. The Eve bottom (rounded) suggests more thorough accumulation than the sharp Adam bottom. In crypto, double top and bottom patterns frequently form around psychologically significant price levels like $10,000, $20,000, or $50,000 for Bitcoin. Watch for RSI or MACD divergence between the two peaks or troughs — if RSI is lower on the second peak of a double top, or higher on the second trough of a double bottom, it strengthens the reversal signal. Failed double tops that break above the resistance can lead to powerful continuation moves as short sellers cover and new buyers enter on the breakout.</p></section>
  </LearnPageLayout>);
}
