import { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `What Is SuperVerse (SUPER)? Price, Guide & How to Buy (${CURRENT_YEAR}) | CryptoDegen`,
  description: "Learn about SuperVerse (SUPER), the gaming and NFT ecosystem platform. Discover SUPER tokenomics and how to buy.",
};

export default function SuperPage() {
  return (
    <LearnPageLayout title="What Is SuperVerse (SUPER)? Price, Guide & How to Buy" categoryName="Investing" categorySlug="investing" readTime="8 min read" intro="SuperVerse (SUPER), formerly known as SuperFarm, is a Web3 gaming and NFT ecosystem that includes game development, an NFT marketplace, and a blockchain gaming launchpad. The platform aims to build a comprehensive gaming metaverse where players can access multiple games, trade NFTs, and participate in a unified token economy powered by SUPER." toc={[{id:"what-is",title:"What Is SuperVerse?",level:2},{id:"how-it-works",title:"How Does SuperVerse Work?",level:2},{id:"tokenomics",title:"SUPER Tokenomics",level:2},{id:"use-cases",title:"Key Use Cases",level:2},{id:"how-to-buy",title:"How to Buy SUPER",level:2},{id:"risks",title:"Risks and Considerations",level:2}]} faqs={[{question:"What is SuperVerse?",answer:"SuperVerse is a Web3 gaming and NFT ecosystem that includes game studios, an NFT marketplace (GigaMart), and a gaming metaverse. SUPER is the utility and governance token."},{question:"Where can I buy SUPER?",answer:"SUPER is available on Binance, Coinbase, KuCoin, and other exchanges."},{question:"Is SuperVerse a good investment?",answer:"SuperVerse has pivoted from NFT farming to gaming. Success depends on its games gaining traction and the broader web3 gaming market maturing."}]} relatedArticles={[{title:"Best Cryptos to Buy",href:"/investing/best/cryptos-to-buy",category:"Investing"},{title:"How to Invest in Crypto",href:"/investing/learn/how-to-invest-in-crypto",category:"Investing"}]}>
      <section id="what-is"><h2>What Is SuperVerse?</h2><p>SuperVerse started as SuperFarm, an NFT farming platform, before rebranding to focus on building a comprehensive Web3 gaming ecosystem. The project now encompasses game development through its Impostors studio (a social deduction game inspired by Among Us), the GigaMart NFT marketplace, and various tools for game developers to integrate blockchain features. The rebrand reflected a strategic shift from pure NFT infrastructure to a broader gaming metaverse vision.</p><p>The project is led by Elliot Wainman, a prominent crypto content creator, which has given SuperVerse significant community visibility. The ecosystem aims to attract both crypto-native and traditional gamers through accessible gaming experiences built on blockchain technology.</p></section>
      <section id="how-it-works"><h2>How Does SuperVerse Work?</h2><p>The SuperVerse ecosystem includes multiple components. Impostors is the flagship social deduction game where players complete tasks and identify imposters in a sci-fi setting with blockchain-based character NFTs. GigaMart is the NFT marketplace designed for gaming assets with zero marketplace fees. The SuperVerse SDK provides tools for game developers to integrate Web3 features. SUPER token connects these components through staking, governance, and in-game utility across the ecosystem.</p></section>
      <section id="tokenomics"><h2>SUPER Tokenomics</h2><p>SUPER has a total supply of 1 billion tokens distributed across ecosystem incentives, team, investors, and community. The token features staking mechanisms where holders lock SUPER for platform benefits and governance rights. Token burns occur through marketplace activity and gaming transactions. The token's long-term value depends on the SuperVerse ecosystem generating sustained user activity across its games and marketplace.</p></section>
      <section id="use-cases"><h2>Key Use Cases</h2><p>SUPER is used for ecosystem governance, staking for platform benefits, in-game purchases across SuperVerse titles, GigaMart marketplace transactions, and developer tools access. The token serves as the economic backbone connecting games, marketplace, and community within the SuperVerse ecosystem.</p></section>
      <section id="how-to-buy"><h2>How to Buy SUPER</h2><p>SUPER is available on Binance, Coinbase, KuCoin, and other exchanges. It can also be purchased on Uniswap. After buying, SUPER can be staked on the platform or used within the ecosystem. Store in MetaMask or any Ethereum-compatible wallet.</p></section>
      <section id="risks"><h2>Risks and Considerations</h2><p>SuperVerse has undergone multiple pivots from NFT farming to gaming, raising questions about strategic focus. The Impostors game faces steep competition from established social deduction titles. Web3 gaming adoption remains challenging, and SuperVerse needs to demonstrate it can attract and retain players. GigaMart competes with dominant NFT marketplaces like OpenSea and Blur. The project's ambitious scope across games, marketplace, and developer tools creates execution risk. Celebrity-founder projects face unique scrutiny regarding long-term commitment.</p></section>
    </LearnPageLayout>
  );
}
