import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Passphrase vs Password in Crypto Wallets (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Understand the difference between passphrases, passwords, seed phrases, and PINs in crypto wallets. Learn when and how to use each security layer.",
  keywords: ["passphrase", "password", "BIP39 passphrase", "wallet security", "25th word"],
};

export default function Page() {
  return (
    <LearnPageLayout title="Passphrase vs Password in Crypto Wallets" categoryName="Crypto Wallets" categorySlug="wallets" readTime="7 min" intro="Crypto wallets use multiple security layers that can be confusing. Passphrases, passwords, seed phrases, and PINs each serve different purposes. Understanding these distinctions is essential for properly securing your digital assets without accidentally locking yourself out." toc={[{id:"definitions",title:"Understanding Each Security Layer",level:2},{id:"bip39",title:"BIP39 Passphrase (25th Word)",level:2},{id:"when-to-use",title:"When to Use Each",level:2},{id:"risks",title:"Risks and Considerations",level:2}]} faqs={[{question:"What is the 25th word?",answer:"The 25th word refers to a BIP39 passphrase — an optional additional word or phrase added to your seed phrase that creates an entirely different wallet. Even with the same 24-word seed phrase, different passphrases generate different wallets. This provides plausible deniability and additional security."},{question:"Can I change my wallet password without changing my seed phrase?",answer:"Yes. Your wallet password encrypts the local key storage and can be changed without affecting your seed phrase or blockchain addresses. However, a BIP39 passphrase cannot be changed without creating a new wallet and transferring funds."},{question:"What happens if I forget my passphrase?",answer:"If you set a BIP39 passphrase and forget it, you cannot access the wallet it created. The seed phrase alone will restore a different wallet (the one without the passphrase). Your funds in the passphrase-protected wallet are effectively lost. This is why passphrase usage requires careful documentation."}]} relatedArticles={[{title:"Seed Phrase Guide",href:"/wallets/learn/seed-phrase-guide",category:"Wallets"},{title:"Private Key Management",href:"/wallets/learn/private-key-management",category:"Wallets"},{title:"Wallet Security Best Practices",href:"/wallets/learn/wallet-security-best-practices",category:"Wallets"}]}>
      <section id="definitions"><h2>Understanding Each Security Layer</h2><p>Crypto wallets employ several distinct security mechanisms that users often conflate. A seed phrase (12 or 24 words) is your master backup — it derives all private keys and can restore your wallet anywhere. A wallet password encrypts your local key storage so that someone who physically accesses your device cannot immediately use your wallet. A PIN serves a similar function on hardware wallets, protecting the device from unauthorized use. A passphrase (BIP39) is an entirely different concept — it is an optional additional input that, combined with your seed phrase, creates a completely separate wallet with different addresses and keys. Each layer protects against different threats and operates independently of the others.</p></section>
      <section id="bip39"><h2>BIP39 Passphrase (25th Word)</h2><p>The BIP39 passphrase is the most powerful and least understood security feature. When enabled, you choose any word, phrase, or string of characters that becomes part of your key derivation. The same 24-word seed phrase with passphrase &quot;alpha&quot; creates a completely different wallet than with passphrase &quot;beta&quot; or with no passphrase at all. This provides plausible deniability — if forced to reveal your seed phrase, you can show the wallet without the passphrase (which you might keep empty or with minimal funds) while your main holdings remain hidden behind the passphrase-protected wallet. Trezor, Ledger, and Coldcard all support BIP39 passphrases. The passphrase is case-sensitive and whitespace-sensitive, so it must be recorded with absolute precision.</p></section>
      <section id="when-to-use"><h2>When to Use Each</h2><p>Use a strong wallet password always — it is your first line of defense against device theft. Use a hardware wallet PIN for the same reason. Use a BIP39 passphrase only if you understand the implications thoroughly and have a reliable method to store both the seed phrase and passphrase separately. The passphrase adds protection against seed phrase theft (an attacker who finds your seed phrase cannot access passphrase-protected funds) but adds risk of self-lockout if you forget or misrecord it. For most users, a hardware wallet with a strong PIN and a securely stored seed phrase provides sufficient security. BIP39 passphrases are an advanced feature best suited for high-value holdings where the additional security justifies the additional complexity.</p></section>
      <section id="risks"><h2>Risks and Considerations</h2><p>The primary risk with BIP39 passphrases is permanent fund loss through forgetting or misrecording the passphrase. Unlike passwords, there is no reset mechanism — the passphrase is mathematically part of the key derivation, and recovering funds without the exact passphrase is computationally infeasible. Store your passphrase separately from your seed phrase so that compromise of either one alone does not expose your funds. If storing physically, keep the seed phrase and passphrase in different secure locations. Consider including passphrase information in your estate plan so heirs can access funds. Test your passphrase setup by recovering the wallet on a second device before sending significant funds to verify you have recorded everything correctly.</p></section>
    </LearnPageLayout>
  );
}
