import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `NFT Storage Guide (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Learn how to safely store, display, and manage NFTs in crypto wallets. Covers ERC-721, ERC-1155 standards, cold storage, and security best practices.",
  keywords: ["NFT storage", "NFT wallet", "ERC-721", "NFT security", "cold storage NFT"],
};

export default function Page() {
  return (
    <LearnPageLayout title="NFT Storage Guide" categoryName="Crypto Wallets" categorySlug="wallets" readTime="7 min" intro="Non-fungible tokens represent unique digital assets stored on the blockchain, from art and collectibles to gaming items and membership passes. Properly storing and securing your NFTs requires understanding how they work at a technical level and which wallets offer the best NFT management features." toc={[
        { id: "how-stored", title: "how-stored", level: 2 },
        { id: "how-nfts-are-stored-on-chain", title: "How NFTs Are Stored On-Chain", level: 2 },
        { id: "wallets", title: "wallets", level: 2 },
        { id: "best-wallets-for-nft-storage", title: "Best Wallets for NFT Storage", level: 2 },
        { id: "cold-storage", title: "cold-storage", level: 2 },
        { id: "cold-storage-for-valuable-nfts", title: "Cold Storage for Valuable NFTs", level: 2 },
        { id: "security", title: "security", level: 2 },
        { id: "nft-security-best-practices", title: "NFT Security Best Practices", level: 2 }
      ]} faqs={[{question:"Are my NFTs stored in my wallet?",answer:"Your wallet stores the private key that controls ownership, not the actual NFT media. The NFT itself is a token on the blockchain that points to metadata and media files typically stored on IPFS, Arweave, or centralized servers. Your wallet proves you own the token, which in turn references the associated artwork or digital asset."},{question:"Can I lose my NFTs if the marketplace shuts down?",answer:"No. NFTs exist on the blockchain independently of any marketplace. If OpenSea or another platform shut down, your NFTs remain in your wallet. However, marketplace-specific features like collection pages and offer history would disappear. The on-chain ownership record is permanent as long as the blockchain continues operating."},{question:"Should I use a separate wallet for NFTs?",answer:"Using a dedicated wallet for valuable NFTs is a strong security practice. Your minting and trading wallet faces more risk from malicious contract interactions. Transferring valuable NFTs to a clean hardware wallet that rarely connects to dApps significantly reduces the chance of theft through approval exploits or phishing attacks."}]} relatedArticles={[{title:"Wallet Security Best Practices",href:"/wallets/learn/wallet-security-best-practices",category:"Wallets"},{title:"Wallet Drainer Scams",href:"/wallets/learn/wallet-drainer-scams",category:"Wallets"},{title:"Best NFT Wallets",href:"/wallets/best/nft",category:"Best Of"}]}>
      <section id="how-stored"><h2>How NFTs Are Stored On-Chain</h2><p>NFTs on Ethereum primarily use two token standards: ERC-721 for unique one-of-one tokens and ERC-1155 for semi-fungible tokens that support multiple editions. The smart contract maintains a registry of token IDs mapped to owner addresses. Each token ID points to a metadata URI that contains the NFT&apos;s name, description, attributes, and a link to the media file. The critical distinction is that the blockchain stores ownership records and metadata references, but the actual image, video, or audio file is typically stored off-chain. Best-practice projects use decentralized storage like IPFS or Arweave where content is addressed by its hash, making it immutable and censorship-resistant. Lower-quality projects may store media on centralized servers that could go offline. When evaluating an NFT&apos;s long-term value, checking where its metadata and media are stored is as important as the artwork itself. On-chain NFTs that store all data directly on the blockchain are the most durable but are limited in media complexity due to storage costs.</p></section>
      <section id="wallets"><h2>Best Wallets for NFT Storage</h2><p>MetaMask remains the most widely compatible wallet for NFT interactions, supporting viewing and transferring NFTs across Ethereum and EVM chains. The mobile app includes an NFT gallery feature for browsing your collection. Phantom excels for Solana NFTs with built-in gallery views, collection organization, and direct marketplace integration. Rainbow wallet provides one of the best NFT viewing experiences with beautiful rendering, collection grouping, and ENS integration. Zerion and Rabby also offer strong NFT displays alongside their DeFi portfolio features. For hardware security, Ledger Live includes NFT management capabilities and works with MetaMask for secure marketplace interactions. The ideal setup for active NFT traders combines a hot wallet for minting and trading with a hardware wallet vault for valuable long-term holdings. Whichever wallet you choose, ensure it supports the blockchain networks where your NFTs live — Ethereum, Solana, Polygon, and other chains each have their own NFT ecosystems.</p></section>
      <section id="cold-storage"><h2>Cold Storage for Valuable NFTs</h2><p>For high-value NFTs, cold storage on a hardware wallet provides the strongest security guarantee. Transfer valuable pieces to a Ledger or Trezor-secured address that you never connect to dApps or marketplaces. This eliminates the risk of malicious approval exploits, phishing-induced signatures, and wallet drainer attacks that target active trading wallets. The process is straightforward: send the NFT from your hot wallet to your hardware wallet address using any marketplace or directly through a wallet interface. The NFT will appear in Ledger Live or can be viewed through a connected MetaMask instance without exposing it to dApp interactions. Some collectors maintain a three-wallet strategy — a burner wallet for risky mints, a main wallet for trusted marketplaces, and a vault wallet on hardware for long-term storage. Air-gapped wallets offer even stronger protection for extremely valuable collections, though they require more complex transaction signing workflows for NFT transfers.</p></section>
      <section id="security"><h2>NFT Security Best Practices</h2><p>The most common NFT theft vector is malicious token approvals — signing transactions that grant unlimited spending permission to attacker contracts disguised as legitimate minting or trading interfaces. Always verify the contract address before signing any transaction, and use wallets like Rabby that simulate transactions and show you exactly what will happen before you confirm. Never click links in unsolicited messages claiming free mints or special offers. Revoke token approvals from contracts you no longer use through Revoke.cash or similar tools. Be cautious with unexpected NFTs appearing in your wallet — some are designed to lure you to malicious websites when you try to sell them. Enable all available security features in your wallet including transaction simulation, phishing warnings, and suspicious site alerts. For valuable collections, set up a hardware wallet vault and only move pieces to your trading wallet when you intend to list them. Document your NFT holdings and their locations as part of your broader digital asset estate plan.</p></section>
    </LearnPageLayout>
  );
}
