import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Margin Calls in Crypto Trading Explained (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Understand margin calls and liquidation in crypto trading. Learn how maintenance margin works, what triggers liquidation, and how to avoid losing your position." };

export default function Page() {
  return (<LearnPageLayout title="Margin Calls and Liquidation Explained" categoryName="Crypto Exchanges" categorySlug="exchanges" readTime="8 min" intro="A margin call is a warning that your leveraged position is approaching liquidation. Understanding how margin calls work, what triggers them, and how to respond can save you from devastating losses in leveraged crypto trading." toc={[
        { id: "what-is-margin-call", title: "what-is-margin-call", level: 2 },
        { id: "what-is-a-margin-call", title: "What Is a Margin Call?", level: 2 },
        { id: "how-liquidation-works", title: "how-liquidation-works", level: 2 },
        { id: "how-liquidation-works", title: "How Liquidation Works", level: 2 },
        { id: "liquidation-price", title: "liquidation-price", level: 2 },
        { id: "calculating-your-liquidation-price", title: "Calculating Your Liquidation Price", level: 2 },
        { id: "avoiding-liquidation", title: "avoiding-liquidation", level: 2 },
        { id: "how-to-avoid-liquidation", title: "How to Avoid Liquidation", level: 2 },
        { id: "insurance-funds", title: "insurance-funds", level: 2 },
        { id: "insurance-funds-and-socialized-losses", title: "Insurance Funds and Socialized Losses", level: 2 }
      ]} faqs={[{question:"Will I owe money if I get liquidated?",answer:"On most crypto exchanges, the liquidation engine closes your position before your losses exceed your margin. However, in extreme market conditions with rapid price gaps, there is a small risk of negative balance. Many exchanges have insurance funds that cover these cases."},{question:"Can I add margin to prevent liquidation?",answer:"Yes. Adding more margin to your position increases your collateral and moves your liquidation price further away. However, this increases your total capital at risk and is generally not recommended as a default strategy."},{question:"How fast does liquidation happen?",answer:"Liquidation is typically instantaneous once the maintenance margin threshold is breached. The exchange's liquidation engine automatically closes your position at the best available market price. In volatile markets, the execution price may be worse than expected."}]} relatedArticles={[{title:"How to Use Leverage",href:"/exchanges/learn/how-to-use-leverage",category:"Exchanges"},{title:"Perpetual Futures Explained",href:"/exchanges/learn/perpetual-futures-explained",category:"Exchanges"},{title:"Order Types Explained",href:"/exchanges/learn/order-types-explained",category:"Exchanges"}]}>
    <section id="what-is-margin-call"><h2>What Is a Margin Call?</h2><p>A margin call occurs when your account equity falls below the required maintenance margin level. In traditional markets, a margin call is a notification requiring you to deposit additional funds or close positions. In crypto, most exchanges skip the formal margin call and proceed directly to automatic liquidation. Some exchanges display warnings as your position approaches the liquidation price — these are the crypto equivalent of margin calls. The margin ratio (your equity divided by required margin) determines how close you are to liquidation. When this ratio hits 100% or drops below the maintenance margin requirement, liquidation is triggered. Monitoring your margin ratio is essential for managing leveraged positions.</p></section>
    <section id="how-liquidation-works"><h2>How Liquidation Works</h2><p>When your margin ratio breaches the maintenance threshold, the exchange's liquidation engine takes over your position. The engine attempts to close your position at the best available price to recover the borrowed funds. On well-designed exchanges, the liquidation process happens in stages. First, the engine may partially close your position to bring the margin ratio back above the threshold. If the price continues moving against you, additional portions are liquidated. Full liquidation closes the entire position. The exchange typically charges a liquidation fee (0.5-1.5% of position value) which goes to the insurance fund. The liquidation price is always worse than simply closing the position yourself because of these fees and the market impact of forced selling.</p></section>
    <section id="liquidation-price"><h2>Calculating Your Liquidation Price</h2><p>Your liquidation price depends on your entry price, leverage, margin mode, and the exchange's maintenance margin rate. For a simplified long position: liquidation price = entry price * (1 - 1/leverage + maintenance margin rate). At 10x leverage with a 0.5% maintenance rate, a long position entered at $50,000 would have a liquidation price around $45,250 — roughly a 9.5% drop. At 5x leverage, the liquidation price moves to approximately $40,500 — a 19% drop. Most exchanges display your liquidation price on the position dashboard. Always note this price before entering a trade and set stop-losses well above it. Remember that in fast-moving markets, your actual closing price during liquidation may be worse than the theoretical liquidation price due to slippage.</p></section>
    <section id="avoiding-liquidation"><h2>How to Avoid Liquidation</h2><p>The most effective strategy is using lower leverage — even reducing from 10x to 5x roughly doubles the price distance to liquidation. Always set stop-loss orders at a price well above your liquidation level. With isolated margin, your maximum loss is capped at the allocated margin, which protects the rest of your account. Use position sizing that ensures no single trade can significantly damage your overall portfolio. Avoid holding leveraged positions through major news events, protocol upgrades, or FOMC meetings where sudden price moves can gap past your stop-loss and trigger direct liquidation. Monitor your positions regularly and reduce size or add margin if the market moves against you significantly. Diversifying across multiple smaller positions instead of one large position also reduces overall liquidation risk.</p></section>
    <section id="insurance-funds"><h2>Insurance Funds and Socialized Losses</h2><p>Exchange insurance funds exist to cover cases where liquidations result in losses beyond the trader's margin — called bankrupt orders. When a position is liquidated at a price worse than the bankruptcy price, the insurance fund covers the deficit. Major exchanges maintain substantial insurance funds: Binance's fund exceeds $1 billion, Bybit's is several hundred million. If the insurance fund is depleted during extreme market events, some exchanges implement socialized losses (auto-deleveraging), where profitable traders on the winning side have portions of their profits redistributed to cover the deficit. This is rare but has occurred during flash crashes. The size and health of an exchange's insurance fund is an important factor when choosing where to trade with leverage.</p></section>
  </LearnPageLayout>);
}
