import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = { title: `Volume Analysis Guide for Crypto Trading (${CURRENT_YEAR}) | ${SITE_NAME}`, description: "Master volume analysis for crypto trading. Learn how to confirm trends, spot reversals, and use volume indicators like OBV and VWAP for better trading decisions." };

export default function Page() {
  return (<LearnPageLayout title="Volume Analysis Guide" categoryName="Crypto Trading" categorySlug="trading" readTime="8 min" intro="Volume is the number of units traded during a given period and is one of the most underappreciated tools in crypto trading. It confirms price movements, reveals the strength behind trends, and provides early warning of reversals. This guide covers how to interpret volume and use volume-based indicators effectively." toc={[
        { id: "basics", title: "basics", level: 2 },
        { id: "volume-basics", title: "Volume Basics", level: 2 },
        { id: "volume-price", title: "volume-price", level: 2 },
        { id: "volume-and-price-relationship", title: "Volume and Price Relationship", level: 2 },
        { id: "indicators", title: "indicators", level: 2 },
        { id: "volume-indicators", title: "Volume Indicators", level: 2 },
        { id: "advanced", title: "advanced", level: 2 },
        { id: "advanced-volume-analysis", title: "Advanced Volume Analysis", level: 2 },
        { id: "strategies", title: "strategies", level: 2 },
        { id: "volume-based-strategies", title: "Volume-Based Strategies", level: 2 }
      ]} faqs={[{question:"Why is volume important in crypto trading?",answer:"Volume confirms price action. A breakout on high volume is more likely to sustain than one on low volume. Volume reveals the conviction behind moves — strong hands or weak hands. It is the only indicator that is not derived from price, providing independent confirmation."},{question:"What is considered high volume in crypto?",answer:"Volume is relative. Compare current volume to the average volume over 20-50 periods. Volume significantly above average (1.5-2x or more) is considered high. What matters is the relative change, not the absolute number."},{question:"Can volume be faked in crypto?",answer:"Yes. Wash trading (fake volume) is a known issue on some exchanges. Use volume data from reputable exchanges. CoinGecko and Messari provide adjusted volume data that attempts to filter wash trading. Cross-reference volume across multiple exchanges."}]} relatedArticles={[{title:"Technical Analysis Basics",href:"/trading/learn/technical-analysis-basics",category:"Trading"},{title:"How to Read Crypto Charts",href:"/exchanges/learn/how-to-read-crypto-charts",category:"Exchanges"},{title:"Volume Profile Explained",href:"/exchanges/learn/volume-profile-explained",category:"Exchanges"}]}>
    <section id="basics"><h2>Volume Basics</h2><p>Volume represents the total number of units (tokens, contracts) traded during a specific time period. On a daily chart, volume shows how many tokens changed hands that day. Volume typically appears as vertical bars at the bottom of a price chart, often color-coded green for up days and red for down days. Average volume over 20 periods provides a baseline for comparison. Above-average volume indicates increased interest and participation. Below-average volume suggests lack of interest or conviction. In crypto, volume varies significantly between exchanges for the same asset, so compare volume on a per-exchange basis or use aggregated volume from data providers. The 24-hour volume figure commonly shown on price trackers aggregates volume across all exchanges.</p></section>
    <section id="volume-price"><h2>Volume and Price Relationship</h2><p>Rising price with rising volume confirms a healthy uptrend — increasing participation supports the move. Rising price with falling volume warns of potential weakness — fewer traders are supporting the advance. This divergence often precedes pullbacks. Falling price with rising volume confirms selling pressure — the decline has conviction. Falling price with falling volume suggests the selloff is losing momentum and a bottom may be forming. Volume spikes at market turning points are common — capitulation selling (extreme high volume at a bottom) often marks the end of downtrends. Euphoric buying (extreme high volume at a top) often marks the end of uptrends. These volume climaxes represent the last wave of participants joining the move before exhaustion.</p></section>
    <section id="indicators"><h2>Volume Indicators</h2><p>On-Balance Volume (OBV) creates a running total of volume, adding volume on up days and subtracting on down days. When OBV trends higher while price is flat, accumulation is occurring — a bullish sign. When OBV trends lower while price is flat, distribution is happening. VWAP (Volume Weighted Average Price) calculates the average price weighted by volume throughout the day, used primarily by institutional traders. Price above VWAP is bullish; below is bearish. Accumulation/Distribution Line combines price and volume to show whether a stock is being accumulated (bought) or distributed (sold). Volume Moving Average overlays a moving average on volume bars, making it easy to identify above-average and below-average volume periods at a glance.</p></section>
    <section id="advanced"><h2>Advanced Volume Analysis</h2><p>Cumulative Volume Delta (CVD) tracks the running total of buy volume minus sell volume, revealing whether buyers or sellers are more aggressive over time. Rising CVD with rising price confirms bullish momentum. Falling CVD with rising price (divergence) warns of potential reversal. Volume profile shows volume traded at each price level, identifying high-volume nodes (strong support and resistance) and low-volume nodes (areas where price moves quickly). Order flow analysis examines individual transactions on the order book, showing the intensity and size of buying versus selling in real time. These advanced tools require dedicated software (Bookmap, Exocharts, Footprint charts) but provide significantly deeper insight than basic volume bars for traders willing to invest in learning them.</p></section>
    <section id="strategies"><h2>Volume-Based Strategies</h2><p>The volume breakout strategy requires breakouts to be confirmed by volume at least 1.5x the 20-period average. Breakouts on low volume are likely false and should be avoided. The volume divergence strategy identifies periods where price makes new highs but volume declines (or price makes new lows but volume declines), signaling potential reversals. The VWAP bounce strategy buys when price pulls back to VWAP in an intraday uptrend and sells when price rallies to VWAP in a downtrend. The volume climax strategy looks for extreme volume spikes combined with long wicks or doji candles at key support or resistance levels — these exhaustion signals often mark significant turning points. Always use volume as confirmation alongside your primary strategy rather than as a standalone signal.</p></section>
  </LearnPageLayout>);
}
