import { Metadata } from "next";
import Link from "next/link";
import AuthorAttribution, { getAuthorForSection } from "@/components/AuthorAttribution";
import RelatedContent from '@/components/RelatedContent';
import AutoTOC from '@/components/AutoTOC';
import ReadingTime from '@/components/ReadingTime';
import LastUpdated from '@/components/LastUpdated';


export const metadata: Metadata = {
  title: "How to Set Up MetaMask Wallet: Complete Step-by-Step Guide",
  description: "Complete MetaMask setup guide: download, create wallet, secure seed phrase, add networks (Ethereum, Polygon, Arbitrum, Base), connect dApps, and manage gas",
  keywords: ['metamask wallet', 'how to set up metamask', 'wallet setup', 'ethereum wallet', 'seed phrase'],
  openGraph: {
    type: 'article',
    title: "How to Set Up MetaMask Wallet: Complete Step-by-Step Guide",
    description: 'Download MetaMask, create wallet, secure recovery phrase, add networks, connect to dApps.',
    publishedTime: '2026-04-10T00:00:00Z',
    modifiedTime: '2026-04-10T00:00:00Z',
    url: 'https://degen0x.com/learn/how-to-set-up-metamask-wallet',
    images: [{ url: 'https://degen0x.com/og-learn.svg', width: 1200, height: 630, alt: 'MetaMask Wallet Setup' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: "How to Set Up MetaMask Wallet: Complete Step-by-Step Guide",
    description: 'Download, create, secure, and configure your MetaMask wallet for Ethereum, Polygon, Arbitrum, and Base.',
    image: 'https://degen0x.com/og-learn.svg',
  },
  alternates: {
    canonical: 'https://degen0x.com/learn/how-to-set-up-metamask-wallet',
  },
};

const structuredData = {
  '@context': 'https://schema.org',
  '@type': 'Article',
  headline: 'How to Set Up MetaMask Wallet: Complete Step-by-Step Guide',
  description: 'Step-by-step guide to set up MetaMask: download, create wallet, backup seed phrase, add networks, connect dApps.',
  image: 'https://degen0x.com/og-learn.svg',
  datePublished: '2026-04-10',
  dateModified: '2026-04-10',
  author: { '@type': 'Organization', name: 'degen0x' },
  mainEntity: {
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'Is MetaMask safe to use?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'MetaMask is safe for most users when you follow security best practices: never share your 12-word seed phrase, enable password protection, use hardware wallets for large holdings (Ledger, Trezor), and verify URLs before connecting. MetaMask extension has 30M+ users and is audited regularly. However, users are responsible for private key management—MetaMask cannot recover lost funds or stolen seed phrases.',
        },
      },
      {
        '@type': 'Question',
        name: 'What is a seed phrase and why is it important?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'A seed phrase (also called mnemonic or recovery phrase) is a 12-word sequence generated by MetaMask that can restore your entire wallet on any device. It controls access to all your funds. Anyone with your seed phrase can steal your crypto. Write it down offline, store it securely in a vault or safe, and never type it anywhere except MetaMask during setup or recovery. Back it up immediately—losing it means losing access to your wallet forever.',
        },
      },
      {
        '@type': 'Question',
        name: 'How do I add a new blockchain network to MetaMask?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Open MetaMask, click the network dropdown (top left), select "Add Network," and enter the RPC details (Chain ID, RPC URL, Symbol). For Polygon, use Chain ID 137, RPC https://polygon-rpc.com. For Arbitrum, use 42161, https://arb1.arbitrum.io/rpc. For Base, use 8453, https://mainnet.base.org. dApps auto-prompt network switching, so you can also click "Switch Network" when connecting.',
        },
      },
      {
        '@type': 'Question',
        name: 'What are gas fees and how do I set them?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Gas fees are payment to miners/validators for processing transactions. On Ethereum mainnet, they average $2-50 per transaction depending on network congestion. When sending a transaction, click "Edit" to customize gas: set lower gas price for non-urgent txs (save cost) or higher for fast inclusion. Or use "Market," "Standard," or "Fast" presets. Layer 2s (Arbitrum, Polygon, Base) cost 10-100x less: $0.01-0.50 per transaction.',
        },
      },
      {
        '@type': 'Question',
        name: 'How do I connect MetaMask to a dApp like Uniswap?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Visit the dApp (e.g., uniswap.org), click "Connect Wallet," select "MetaMask," and approve the connection popup. MetaMask will show your account and network. You can then interact with the dApp (swap, stake, provide liquidity). The dApp can view your address and request transaction signing, but cannot access your private keys or seed phrase. Always verify the URL is correct before connecting.',
        },
      },
      {
        '@type': 'Question',
        name: 'Can I import an existing wallet into MetaMask?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Yes. During setup, select "Import Wallet" and paste your 12-word seed phrase (or private key). This restores all addresses and funds from that wallet. You can also use "Add Account" within MetaMask to derive additional addresses from the same seed phrase. If you have funds on Ethereum, they will appear automatically. Multi-chain funds (Polygon, Arbitrum) require switching networks first.',
        },
      },
    ],
  },
};

const h1Style: React.CSSProperties = { fontSize: 36, fontWeight: 800, marginBottom: 16, background: 'linear-gradient(135deg, #6366f1, #06b6d4)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', lineHeight: 1.2 };
const h2Style: React.CSSProperties = { fontSize: 24, fontWeight: 700, marginTop: 40, marginBottom: 16, color: '#a78bfa', borderBottom: '2px solid #2d2254', paddingBottom: 12 };
const badgeStyle: React.CSSProperties = { padding: '6px 12px', borderRadius: 6, fontSize: 12, fontWeight: 600, marginRight: 8, marginBottom: 16, display: 'inline-block' };
const infoBoxStyle: React.CSSProperties = { background: '#161b22', border: '1px solid #30363d', borderRadius: 12, padding: 20, marginBottom: 24, lineHeight: 1.8 };


const breadcrumbData = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://degen0x.com/' },
    { '@type': 'ListItem', position: 2, name: 'Learn', item: 'https://degen0x.com/learn' },
    { '@type': 'ListItem', position: 3, name: 'How To Set Up Metamask Wallet', },
  ],
};

export default function MetaMaskWalletSetup() {
  const tableOfContents = [
    { id: 'download-install', title: 'Step 1: Download and Install MetaMask' },
    { id: 'create-wallet', title: 'Step 2: Create Your Wallet' },
    { id: 'seed-phrase', title: 'Step 3: Backup Your Seed Phrase' },
    { id: 'verify-phrase', title: 'Step 4: Verify Your Seed Phrase' },
    { id: 'set-password', title: 'Step 5: Set a Strong Password' },
    { id: 'add-networks', title: 'Step 6: Add Blockchain Networks' },
    { id: 'custom-tokens', title: 'Step 7: Add Custom Tokens' },
    { id: 'gas-settings', title: 'Step 8: Configure Gas Settings' },
    { id: 'connect-dapps', title: 'Step 9: Connect to dApps' },
    { id: 'security-tips', title: 'Security Best Practices' },
    { id: 'faq', title: 'FAQ' },
  ];

  const infoBoxStyle = {
    background: '#161b22',
    border: '1px solid #30363d', borderLeft: '3px solid #a78bfa', borderLeft: '3px solid #a78bfa',
    borderRadius: 12,
    padding: 20,
    marginBottom: 24,
    lineHeight: 1.8,
  };

  const h1Style = {
    fontSize: 36,
    fontWeight: 800,
    marginBottom: 16,
    background: 'linear-gradient(135deg, #6366f1, #06b6d4)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  };

  const h2Style = {
    fontSize: 24,
    fontWeight: 700,
    marginTop: 40,
    marginBottom: 16,
    color: '#a78bfa', borderBottom: '2px solid #2d2254', paddingBottom: 12,
  };

  const h3Style = {
    fontSize: 18,
    fontWeight: 600,
    marginTop: 20,
    marginBottom: 12,
    color: '#e6edf3',
  };

  const badgeStyle = {
    display: 'inline-block',
    padding: '6px 12px',
    borderRadius: 6,
    fontSize: 12,
    fontWeight: 600,
    marginRight: 8,
    marginBottom: 16,
  };

  const linkStyle = { color: '#58a6ff', textDecoration: 'none' };

  const tableStyle = {
    width: '100%',
    borderCollapse: 'collapse' as const,
    marginBottom: 24,
    fontSize: 14,
  };

  const thStyle = {
    background: '#0d1117',
    border: '1px solid #30363d',
    padding: 12,
    textAlign: 'left' as const,
    fontWeight: 700,
    color: '#e6edf3',
  };

  const tdStyle = {
    border: '1px solid #30363d',
    padding: 12,
    color: '#8b949e',
  };

  return (
    <article id="top" style={{ background: '#0d1117', color: '#e6edf3', minHeight: '100vh', padding: '40px 20px', scrollBehavior: 'smooth' }}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbData) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
      <div style={{ maxWidth: 800, margin: '0 auto' }}>
        <nav aria-label="Breadcrumb" style={{ marginBottom: 20, fontSize: 13, color: '#8b949e' }}>
          <Link href="/" style={{ color: '#8b949e', textDecoration: 'none' }}>Home</Link>
          <span style={{ margin: '0 6px' }}>›</span>
          <Link href="/learn" style={{ color: '#8b949e', textDecoration: 'none' }}>Learn</Link>
          <span style={{ margin: '0 6px' }}>›</span>
          <span style={{ color: '#c9d1d9' }}>MetaMask Setup</span>
        </nav>

        <div style={{ marginBottom: 32 }}>
          <span style={{ ...badgeStyle, background: '#6366f1', color: '#fff' }}>Learn</span>
          <span style={{ ...badgeStyle, background: '#3d444d', color: '#e6edf3' }}>Beginner</span>
          <h1 style={h1Style}>How to Set Up MetaMask Wallet</h1>
          <LastUpdated pathKey="/learn/how-to-set-up-metamask-wallet" />
          <ReadingTime />
          <AutoTOC />
          <p style={{ fontSize: 16, color: '#8b949e', marginBottom: 20 }}>
            MetaMask is the most popular self-custody wallet with 30M+ users. This guide walks you through downloading MetaMask, securing your 12-word seed phrase, configuring networks (Ethereum, Polygon, Arbitrum, Base), adding tokens, and connecting to dApps safely.
          </p>
          <div style={{ display: 'flex', gap: 24, fontSize: 14, color: '#8b949e', marginBottom: 24 }}>
            <span>Updated: April 10, 2026</span>
            <span>Reading time: 12 min</span>
          </div>
        </div>

        <AuthorAttribution
          author="DegenSensei"
          role="Content Lead"
          publishedDate="2026-04-10"
          updatedDate="2026-04-10"
          readingTime={12}
          section="learn"
        />


        <nav aria-label="Table of Contents" style={{ ...infoBoxStyle, marginBottom: 32 }}>
          <h3 style={{ fontSize: 16, fontWeight: 700, marginBottom: 16, color: '#e6edf3' }}>Table of Contents</h3>
          <ol style={{ marginLeft: 20, color: '#58a6ff' }}>
            {tableOfContents.map(item => (
              <li key={item.id} style={{ marginBottom: 8 }}>
                <a href={`#${item.id}`} style={linkStyle}>{item.title}</a>
              </li>
            ))}
          </ol>
        </nav>

        <section id="download-install">
          <h2 style={h2Style}>Step 1: Download and Install MetaMask</h2>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            MetaMask is available as a browser extension (Chrome, Firefox, Edge, Safari) and mobile app (iOS, Android). For beginners, the desktop extension is recommended for security and ease of use. Go to metamask.io and click "Download" to access the official browser extension store.
          </p>
        {/* editorial-voice */}
        <div style={{ background: '#1a1625', border: '1px solid #2d2254', borderRadius: 10, padding: '20px 24px', marginTop: 32, marginBottom: 32 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
            <span style={{ fontSize: 18 }}>💡</span>
            <strong style={{ color: '#a78bfa', fontSize: 15 }}>Why This Matters</strong>
          </div>
          <p style={{ fontSize: 14, color: '#c9d1d9', lineHeight: 1.7, margin: 0, fontStyle: 'italic' }}>
            Understanding this concept is a prerequisite for making informed decisions in DeFi. Most losses in crypto come from misunderstanding the fundamentals.
          </p>
        </div>
          <h3 style={h3Style}>Desktop Installation</h3>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            After installation, you&apos;ll see the MetaMask fox icon in the top-right toolbar. Click it to open the wallet and begin setup. The extension integrates seamlessly with Ethereum, Polygon, Arbitrum, Base, and hundreds of other networks.
          </p>
          <h3 style={h3Style}>Mobile Installation</h3>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            Download from Apple App Store or Google Play Store. Mobile supports the same seed phrase as desktop, allowing wallet sync across devices when using the same recovery phrase.
          </p>
          <div style={infoBoxStyle}>
            <strong style={{ color: '#58a6ff' }}>Tip:</strong> Always verify you&apos;re on metamask.io before installing. Fake MetaMask extensions exist—check the official publisher name: ConsenSys Software Inc.
          </div>
        </section>

        <section id="create-wallet">
          <h2 style={h2Style}>Step 2: Create Your Wallet</h2>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            Open the MetaMask extension and click "Create a Wallet." Accept the terms and conditions, then click "Create." MetaMask will generate a 12-word seed phrase (recovery phrase) using BIP-39 standard cryptography.
          </p>
          <h3 style={h3Style}>What Happens During Creation</h3>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            The 12-word mnemonic controls your private key and all your funds. MetaMask stores the seed phrase encrypted on your device only—MetaMask servers never see or store it. You must backup this phrase before proceeding.
          </p>
        </section>

        <section id="seed-phrase">
          <h2 style={h2Style}>Step 3: Backup Your Seed Phrase</h2>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            After wallet creation, MetaMask displays your 12-word seed phrase. Write down all 12 words in order on a piece of paper or metal plate (for durability). Do NOT screenshot it or store it digitally anywhere.
          </p>
          <div style={{ ...infoBoxStyle, borderColor: '#ef4444', borderLeftWidth: 4 }}>
            <strong style={{ color: '#ef4444' }}>Warning:</strong> If you lose your seed phrase and forget your password, your wallet and all funds are lost forever. There is no account recovery or customer support. Backup now—do not skip this step.
          </div>
          <h3 style={h3Style}>Storage Best Practices</h3>
          <ul style={{ color: '#8b949e', lineHeight: 1.8, marginLeft: 20, marginBottom: 16 }}>
            <li style={{ marginBottom: 8 }}>Write on paper or metal (Ledger includes metal cards for backup)</li>
            <li style={{ marginBottom: 8 }}>Store in a safe, vault, or safe deposit box</li>
            <li style={{ marginBottom: 8 }}>Never email, text, screenshot, or share digitally</li>
            <li style={{ marginBottom: 8 }}>Consider storing copies in multiple secure locations</li>
            <li style={{ marginBottom: 8 }}>Protect from fire and water damage</li>
          </ul>
        </section>

        <section id="verify-phrase">
          <h2 style={h2Style}>Step 4: Verify Your Seed Phrase</h2>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            After backing up, MetaMask prompts you to confirm your seed phrase. Click on each word in the correct order to verify you wrote it down correctly. This ensures you didn&apos;t miss any words.
          </p>
          <h3 style={h3Style}>Why This Matters</h3>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            Testing now prevents disaster later. If you typed a word incorrectly when backing up, you&apos;ll fail this verification and know to redo the backup. Once you fund the wallet, you won&apos;t get a second chance.
          </p>
        </section>

        <section id="set-password">
          <h2 style={h2Style}>Step 5: Set a Strong Password</h2>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            Create a password (8+ characters, letters, numbers, symbols) to encrypt your MetaMask vault locally. This password protects your wallet on your device only—it does NOT recover your funds if lost. You can reset it with your seed phrase.
          </p>
          <h3 style={h3Style}>Password Guidelines</h3>
          <ul style={{ color: '#8b949e', lineHeight: 1.8, marginLeft: 20, marginBottom: 16 }}>
            <li style={{ marginBottom: 8 }}>Use 16+ characters for maximum security</li>
            <li style={{ marginBottom: 8 }}>Mix uppercase, lowercase, numbers, and symbols</li>
            <li style={{ marginBottom: 8 }}>Avoid dictionary words and personal info</li>
            <li style={{ marginBottom: 8 }}>Store in a password manager (1Password, Bitwarden, KeePass)</li>
          </ul>
          <div style={infoBoxStyle}>
            <strong style={{ color: '#58a6ff' }}>Note:</strong> If you forget your password, reset it using your seed phrase. The password only encrypts your local vault, not your funds.
          </div>
        </section>

        <section id="add-networks">
          <h2 style={h2Style}>Step 6: Add Blockchain Networks</h2>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            MetaMask starts on Ethereum mainnet by default. You can add other networks (Polygon, Arbitrum, Base) to manage funds across chains. Click the network dropdown (top-left of MetaMask) and select "Add Network."
          </p>
          <h3 style={h3Style}>Popular Networks to Add</h3>
          <table style={tableStyle}>
            <thead>
              <tr>
                <th style={thStyle}>Network</th>
                <th style={thStyle}>Chain ID</th>
                <th style={thStyle}>RPC URL</th>
                <th style={thStyle}>Avg. Gas</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td style={tdStyle}>Ethereum</td>
                <td style={tdStyle}>1</td>
                <td style={tdStyle}>https://eth.drpc.org</td>
                <td style={tdStyle}>$2-50</td>
              </tr>
              <tr>
                <td style={tdStyle}>Polygon</td>
                <td style={tdStyle}>137</td>
                <td style={tdStyle}>https://polygon-rpc.com</td>
                <td style={tdStyle}>$0.01-0.05</td>
              </tr>
              <tr>
                <td style={tdStyle}>Arbitrum One</td>
                <td style={tdStyle}>42161</td>
                <td style={tdStyle}>https://arb1.arbitrum.io/rpc</td>
                <td style={tdStyle}>$0.05-0.20</td>
              </tr>
              <tr>
                <td style={tdStyle}>Base</td>
                <td style={tdStyle}>8453</td>
                <td style={tdStyle}>https://mainnet.base.org</td>
                <td style={tdStyle}>$0.01-0.10</td>
              </tr>
            </tbody>
          </table>
          <h3 style={h3Style}>How to Add a Network</h3>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            Click "Add Network" → "Add a popular network" (for Polygon, Arbitrum, Base) or "Add a custom network." Enter Network Name, Chain ID, RPC URL, Symbol, and Block Explorer URL. Click Save to add the network to your wallet.
          </p>
        </section>

        <section id="custom-tokens">
          <h2 style={h2Style}>Step 7: Add Custom Tokens</h2>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            MetaMask shows your native token balance by default. To view other tokens (USDC, UNI, AAVE), you must add them manually. Click "Import Tokens" and paste the contract address from Etherscan.
          </p>
          <h3 style={h3Style}>Common Token Addresses (Ethereum)</h3>
          <table style={tableStyle}>
            <thead>
              <tr>
                <th style={thStyle}>Token</th>
                <th style={thStyle}>Symbol</th>
                <th style={thStyle}>Contract Address</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td style={tdStyle}>USD Coin</td>
                <td style={tdStyle}>USDC</td>
                <td style={tdStyle}>0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48</td>
              </tr>
              <tr>
                <td style={tdStyle}>Uniswap</td>
                <td style={tdStyle}>UNI</td>
                <td style={tdStyle}>0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984</td>
              </tr>
              <tr>
                <td style={tdStyle}>Aave Token</td>
                <td style={tdStyle}>AAVE</td>
                <td style={tdStyle}>0x7Fc66500c84A76Ad7e9c93437E434122A1f9AcDd</td>
              </tr>
              <tr>
                <td style={tdStyle}>Tether USD</td>
                <td style={tdStyle}>USDT</td>
                <td style={tdStyle}>0xdAC17F958D2ee523a2206206994597C13D831ec7</td>
              </tr>
            </tbody>
          </table>
          <h3 style={h3Style}>Finding Token Addresses</h3>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            Search for the token on Etherscan.io, copy the contract address, and paste into MetaMask. Always verify the address matches the official token—scammers create fake tokens with similar names.
          </p>
        </section>

        <section id="gas-settings">
          <h2 style={h2Style}>Step 8: Configure Gas Settings</h2>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            Gas fees pay validators to process transactions. When sending funds or interacting with dApps, MetaMask shows estimated gas cost. Click "Edit" to customize gas price and limit based on network congestion.
          </p>
          <h3 style={h3Style}>Gas Price Tiers</h3>
          <table style={tableStyle}>
            <thead>
              <tr>
                <th style={thStyle}>Setting</th>
                <th style={thStyle}>Speed</th>
                <th style={thStyle}>Cost (ETH)</th>
                <th style={thStyle}>Use Case</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td style={tdStyle}>Low</td>
                <td style={tdStyle}>30-60 min</td>
                <td style={tdStyle}>$1-5</td>
                <td style={tdStyle}>Non-urgent transfers</td>
              </tr>
              <tr>
                <td style={tdStyle}>Standard</td>
                <td style={tdStyle}>5-15 min</td>
                <td style={tdStyle}>$5-15</td>
                <td style={tdStyle}>Normal DeFi activity</td>
              </tr>
              <tr>
                <td style={tdStyle}>Fast</td>
                <td style={tdStyle}>1-5 min</td>
                <td style={tdStyle}>$15-50</td>
                <td style={tdStyle}>Time-sensitive swaps</td>
              </tr>
            </tbody>
          </table>
          <h3 style={h3Style}>Manual Gas Customization</h3>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            For advanced users, "Advanced Options" allows setting custom gas price (in Gwei) and gas limit. Check Etherscan Gas Tracker for current Gwei prices. Layer 2s are 10-100x cheaper: Arbitrum $0.01-0.50, Polygon $0.001-0.05.
          </p>
          <div style={infoBoxStyle}>
            <strong style={{ color: '#58a6ff' }}>Pro Tip:</strong> Use Layer 2 networks (Arbitrum, Polygon, Base) for frequent transactions. Ethereum mainnet is best for large transfers due to settlement security.
          </div>
        </section>

        <section id="connect-dapps">
          <h2 style={h2Style}>Step 9: Connect to dApps</h2>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            Once your wallet is set up and funded, connect to decentralized applications (dApps) like Uniswap (DEX), Aave (lending), or Curve (stablecoin swaps). Visit the dApp and click "Connect Wallet."
          </p>
          <h3 style={h3Style}>Connection Process</h3>
          <ol style={{ color: '#8b949e', lineHeight: 1.8, marginLeft: 20, marginBottom: 16 }}>
            <li style={{ marginBottom: 8 }}>Go to the dApp (e.g., uniswap.org, aave.com, curve.fi)</li>
            <li style={{ marginBottom: 8 }}>Click "Connect Wallet" and select "MetaMask"</li>
            <li style={{ marginBottom: 8 }}>MetaMask prompts to approve connection—select your account and click "Next"</li>
            <li style={{ marginBottom: 8 }}>Approve permissions (usually just viewing address, not spending funds)</li>
            <li style={{ marginBottom: 8 }}>You can now interact with the dApp and conduct transactions</li>
          </ol>
          <h3 style={h3Style}>Popular dApps to Connect To</h3>
          <ul style={{ color: '#8b949e', lineHeight: 1.8, marginLeft: 20, marginBottom: 16 }}>
            <li style={{ marginBottom: 8 }}><strong>Uniswap</strong> (DEX) - swap tokens across Ethereum, Polygon, Arbitrum, Base</li>
            <li style={{ marginBottom: 8 }}><strong>Aave</strong> (Lending) - deposit tokens to earn yield or borrow</li>
            <li style={{ marginBottom: 8 }}><strong>Curve Finance</strong> (Stablecoin DEX) - swap stablecoins with low slippage</li>
            <li style={{ marginBottom: 8 }}><strong>OpenSea</strong> (NFT Marketplace) - buy, sell, mint NFTs</li>
            <li style={{ marginBottom: 8 }}><strong>Lido Finance</strong> (Staking) - stake ETH for stETH (Ethereum liquid staking)</li>
          </ul>
          <div style={infoBoxStyle}>
            <strong style={{ color: '#58a6ff' }}>Safety:</strong> Always verify the dApp URL before connecting. Phishing sites mimic real dApps. Bookmark trusted dApps and access via bookmark, not search results.
          </div>
        </section>

        <section id="security-tips">
          <h2 style={h2Style}>Security Best Practices</h2>
          <h3 style={h3Style}>Never Share or Screenshot Seed Phrase</h3>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            Anyone with your 12 words owns your wallet. MetaMask staff will never ask for it. Store it offline only. No legitimate company will request your seed phrase—if they do, it&apos;s a scam.
          </p>
          <h3 style={h3Style}>Use Hardware Wallets for Large Sums</h3>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            For holdings above $5,000-10,000, consider a hardware wallet (Ledger Nano S Plus $60, Trezor Model T $99, Coldcard $120). These sign transactions offline, preventing hacks even if your computer is compromised.
          </p>
          <h3 style={h3Style}>Enable Security Settings</h3>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            Open MetaMask → Settings → Security & Privacy. Enable "Show custom network warnings" and "Show incoming transactions." Disable "Allow sites to detect your installed wallet" for more privacy.
          </p>
          <h3 style={h3Style}>Verify Transaction Details</h3>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            Before approving any transaction, carefully review the recipient address and amount. Malicious dApps or exploits can trick you into sending funds to attacker addresses.
          </p>
          <h3 style={h3Style}>Keep MetaMask Updated</h3>
          <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 16 }}>
            MetaMask updates regularly with security patches. Enable auto-update in browser settings or check for updates weekly. Outdated versions may be vulnerable to exploits.
          </p>
        </section>

        <section id="faq">
          <h2 style={h2Style}>FAQ</h2>
          <div style={infoBoxStyle}>
            <h3 style={h3Style}>Is MetaMask safe to use?</h3>
            <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 0 }}>MetaMask is safe for most users when you follow security best practices: never share your 12-word seed phrase, enable password protection, use hardware wallets for large holdings (Ledger, Trezor), and verify URLs before connecting. MetaMask extension has 30M+ users and is audited regularly. However, users are responsible for private key management—MetaMask cannot recover lost funds or stolen seed phrases.</p>
          </div>

          <div style={infoBoxStyle}>
            <h3 style={h3Style}>What is a seed phrase and why is it important?</h3>
            <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 0 }}>A seed phrase is a 12-word sequence generated by MetaMask that can restore your entire wallet on any device. It controls access to all your funds. Anyone with your seed phrase can steal your crypto. Write it down offline, store it securely in a vault or safe, and never type it anywhere except MetaMask during setup or recovery. Back it up immediately—losing it means losing access to your wallet forever.</p>
          </div>

          <div style={infoBoxStyle}>
            <h3 style={h3Style}>How do I add a new blockchain network to MetaMask?</h3>
            <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 0 }}>Open MetaMask, click the network dropdown (top left), select "Add Network," and enter the RPC details (Chain ID, RPC URL, Symbol). For Polygon, use Chain ID 137, RPC https://polygon-rpc.com. For Arbitrum, use 42161, https://arb1.arbitrum.io/rpc. For Base, use 8453, https://mainnet.base.org. dApps auto-prompt network switching, so you can also click "Switch Network" when connecting.</p>
          </div>

          <div style={infoBoxStyle}>
            <h3 style={h3Style}>What are gas fees and how do I set them?</h3>
            <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 0 }}>Gas fees are payment to miners/validators for processing transactions. On Ethereum mainnet, they average $2-50 per transaction depending on network congestion. When sending a transaction, click "Edit" to customize gas: set lower gas price for non-urgent txs (save cost) or higher for fast inclusion. Or use "Market," "Standard," or "Fast" presets. Layer 2s (Arbitrum, Polygon, Base) cost 10-100x less: $0.01-0.50 per transaction.</p>
          </div>

          <div style={infoBoxStyle}>
            <h3 style={h3Style}>How do I connect MetaMask to a dApp like Uniswap?</h3>
            <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 0 }}>Visit the dApp (e.g., uniswap.org), click "Connect Wallet," select "MetaMask," and approve the connection popup. MetaMask will show your account and network. You can then interact with the dApp (swap, stake, provide liquidity). The dApp can view your address and request transaction signing, but cannot access your private keys or seed phrase. Always verify the URL is correct before connecting.</p>
          </div>

          <div style={infoBoxStyle}>
            <h3 style={h3Style}>Can I import an existing wallet into MetaMask?</h3>
            <p style={{ color: '#8b949e', lineHeight: 1.8, marginBottom: 0 }}>Yes. During setup, select "Import Wallet" and paste your 12-word seed phrase (or private key). This restores all addresses and funds from that wallet. You can also use "Add Account" within MetaMask to derive additional addresses from the same seed phrase. If you have funds on Ethereum, they will appear automatically. Multi-chain funds (Polygon, Arbitrum) require switching networks first.</p>
          </div>
        </section>

        <div style={{ ...infoBoxStyle, marginTop: 48, fontSize: 13, color: '#8b949e' }}>
          <strong>Disclaimer:</strong> This content is for informational purposes only. MetaMask is a non-custodial wallet—you control your funds. degen0x is not responsible for lost funds, stolen seed phrases, or user error. Always verify contract addresses and dApp URLs before interacting. Do your own research before making financial decisions.
        </div>
      </div>
        {/* related-guides */}
        <nav aria-label="Related guides" style={{ marginTop: 48, padding: "24px", background: "#161b22", border: "1px solid #30363d", borderRadius: 12 }}>
          <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 16, color: "#e6edf3" }}>Continue Reading</h3>
          <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "grid", gap: 12 }}>
            <li><Link href="/tools/bitcoin-mempool-visualizer" style={{ color: "#58a6ff", textDecoration: "none", fontSize: 15 }}>Bitcoin Mempool Visualizer</Link></li>
            <li><Link href="/tools/bitcoin-rainbow-chart" style={{ color: "#58a6ff", textDecoration: "none", fontSize: 15 }}>Bitcoin Rainbow Chart</Link></li>
            <li><Link href="/tools/blockchain-explorer-tool" style={{ color: "#58a6ff", textDecoration: "none", fontSize: 15 }}>Blockchain Explorer Tool</Link></li>
            <li><Link href="/tools/compound-interest-crypto-calculator" style={{ color: "#58a6ff", textDecoration: "none", fontSize: 15 }}>Compound Interest Crypto Calculator</Link></li>
          </ul>
        </nav>

{/* section-footer */}
        <div style={{ background: '#1a1625', border: '1px solid #2d2254', borderRadius: 8, padding: '16px 20px', marginTop: 40, marginBottom: 20 }}>
          <p style={{ fontSize: 13, color: '#8b949e', lineHeight: 1.7, margin: 0 }}>
            <strong style={{ color: '#a78bfa' }}>Educational disclaimer:</strong> This guide is for informational purposes only and does not constitute financial advice.
            Crypto involves significant risk — do your own research before making any decisions. Learn more about <a href="/about" style={{ color: '#a78bfa' }}>our team</a>.
          </p>
        </div>
      
        {/* section-footer */}
        <div style={{ background: '#1a1625', border: '1px solid #2d2254', borderRadius: 8, padding: '16px 20px', marginTop: 40, marginBottom: 20 }}>
          <p style={{ fontSize: 13, color: '#8b949e', lineHeight: 1.7, margin: 0 }}>
            <strong style={{ color: '#a78bfa' }}>Educational disclaimer:</strong> This guide is for informational purposes only and does not constitute financial advice.
            Crypto involves significant risk — do your own research before making any decisions. Learn more about <a href="/about" style={{ color: '#a78bfa' }}>our team</a>.
          </p>
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({"@context": "https://schema.org", "@type": "WebPage", "name": "How to Set Up MetaMask Wallet: Complete Step-by-Step Guide", "description": "Complete MetaMask setup guide: download, create wallet, secure seed phrase, add networks (Ethereum, Polygon, Arbitrum, Base), connect dApps, and manage gas", "url": "https://degen0x.com/learn/how-to-set-up-metamask-wallet", "datePublished": "2026-04-13", "dateModified": "2026-04-13"}) }} />
</div>
      <RelatedContent category="learn" currentSlug="/learn/how-to-set-up-metamask-wallet" />
      </article>
  );
}
