import type { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { SITE_NAME, CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `AML/KYC in Crypto Guide (${CURRENT_YEAR}) | ${SITE_NAME}`,
  description: "Guide to Anti-Money Laundering (AML) and Know Your Customer (KYC) requirements in cryptocurrency including regulations, verification processes, and compliance.",
  keywords: ["KYC crypto", "AML crypto", "crypto compliance", "identity verification crypto", "cryptocurrency KYC", "anti-money laundering crypto"],
};

export default function AmlKycCryptoGuidePage() {
  return (
    <LearnPageLayout title="AML/KYC in Crypto Guide" categoryName="Crypto Education" categorySlug="learn" readTime="7 min" intro="Anti-Money Laundering (AML) and Know Your Customer (KYC) regulations are foundational compliance requirements for cryptocurrency businesses worldwide. These regulations require exchanges and service providers to verify user identities and monitor transactions for suspicious activity. Understanding AML/KYC helps you navigate the compliance landscape as a crypto user."
      toc={[
        { id: "what-is-aml-kyc", title: "What Are AML & KYC?", level: 2 },
        { id: "crypto-requirements", title: "Crypto-Specific Requirements", level: 2 },
        { id: "verification-process", title: "The Verification Process", level: 2 },
        { id: "blockchain-analytics", title: "Blockchain Analytics", level: 2 },
        { id: "user-perspective", title: "The User Perspective", level: 2 },
      ]}
      faqs={[
        { question: "Why do exchanges require KYC?", answer: "Exchanges are legally required to verify customer identities under anti-money laundering regulations in most jurisdictions. Failure to comply can result in criminal penalties, loss of banking relationships, and regulatory shutdown. KYC helps prevent money laundering, terrorist financing, sanctions evasion, and fraud." },
        { question: "Can I use crypto without KYC?", answer: "Self-custodial wallets and some decentralized exchanges do not require KYC. However, converting between crypto and fiat currency through regulated channels requires KYC in virtually all jurisdictions. Using no-KYC services may also create compliance issues and limit your ability to use funds with regulated service providers." },
        { question: "What information is required for KYC?", answer: "Typical KYC requirements include government-issued photo ID, proof of address, and sometimes a selfie for liveness verification. Enhanced due diligence for higher-risk customers or larger transactions may require source of funds documentation, employment information, and additional identity verification." },
      ]}
      relatedArticles={[
        { title: "Crypto Regulation Overview", href: "/learn/crypto-regulation-2026", category: "Learn" },
        { title: "Crypto Travel Rule", href: "/learn/crypto-travel-rule", category: "Learn" },
        { title: "Crypto Licensing Guide", href: "/learn/crypto-licensing-guide", category: "Learn" },
        { title: "Is Cryptocurrency Safe?", href: "/learn/is-cryptocurrency-safe", category: "Learn" },
      ]}
    >
      <section id="what-is-aml-kyc"><h2>What Are AML & KYC?</h2><p>Anti-Money Laundering (AML) refers to the set of laws, regulations, and procedures designed to prevent criminals from disguising illegally obtained funds as legitimate income. Know Your Customer (KYC) is a component of AML that requires financial institutions to verify the identity of their customers. Together, AML/KYC creates a framework for monitoring, detecting, and reporting suspicious financial activity.</p><p>These requirements are governed by the Financial Action Task Force (FATF) at the international level, with each country implementing its own AML legislation. In the US, the Bank Secrecy Act and its amendments form the primary AML framework. In the EU, Anti-Money Laundering Directives establish requirements. Cryptocurrency businesses (classified as Virtual Asset Service Providers by FATF) are subject to the same fundamental obligations as traditional financial institutions.</p></section>
      <section id="crypto-requirements"><h2>Crypto-Specific Requirements</h2><p>Cryptocurrency exchanges, custodians, and other VASPs must implement Customer Identification Programs (CIP) to verify user identities, Customer Due Diligence (CDD) to understand customer relationships and risk profiles, ongoing transaction monitoring to detect suspicious patterns, and Suspicious Activity Reporting (SAR) for flagged transactions. Enhanced Due Diligence (EDD) applies to higher-risk customers and transactions.</p><p>Crypto-specific AML challenges include the pseudonymous nature of blockchain transactions, the ability to create unlimited addresses, cross-chain transfers that complicate tracing, mixing and privacy services that obscure transaction trails, and the global accessibility of permissionless protocols. These characteristics have driven the development of specialized blockchain analytics tools and crypto-specific compliance procedures.</p></section>
      <section id="verification-process"><h2>The Verification Process</h2><p>Typical KYC verification on cryptocurrency exchanges involves several tiers. Basic verification requires an email address and may limit functionality. Intermediate verification requires government-issued ID and allows higher transaction limits. Full verification may require proof of address, source of funds documentation, and liveness checks (video or biometric verification to confirm the person matches the ID).</p><p>Identity verification is typically processed through specialized third-party providers who use optical character recognition (OCR) to read documents, facial recognition to match selfies to ID photos, and database checks to verify document authenticity. Processing times range from minutes (automated) to days (manual review). Enhanced verification for high-value accounts or suspicious activity triggers additional documentation requirements and may involve direct communication with the compliance team.</p></section>
      <section id="blockchain-analytics"><h2>Blockchain Analytics</h2><p>Blockchain analytics firms like Chainalysis, Elliptic, and TRM Labs provide tools that help VASPs meet their AML obligations. These tools trace transaction flows across blockchains, identify addresses associated with known criminal activity (sanctions, darknet markets, stolen funds), and score transactions based on risk factors. Exchanges use these tools to screen incoming deposits and flag suspicious withdrawal patterns.</p><p>The effectiveness of blockchain analytics has improved significantly, with the ability to trace funds through complex transaction chains, across different blockchains, and sometimes through privacy-enhancing techniques. Law enforcement agencies use the same tools for investigations, and blockchain analytics evidence has been used in numerous criminal prosecutions. This traceability, combined with exchange KYC records, means that cryptocurrency is often less anonymous than cash for financial crime purposes.</p></section>
      <section id="user-perspective"><h2>The User Perspective</h2><p>For individual users, KYC requirements mean providing personal information to exchanges, which introduces data security considerations — exchanges have been breached and customer data exposed. Use reputable exchanges with strong security practices and data protection policies. Be cautious about completing KYC on lesser-known platforms where data protection may be inadequate.</p><p>Maintain records of your crypto transactions for tax and compliance purposes. Be aware that exchanges may freeze accounts or request additional documentation if transaction patterns trigger compliance alerts. Cooperating promptly with legitimate compliance requests from regulated exchanges helps resolve issues quickly. If you are concerned about privacy, understand that self-custody and peer-to-peer transactions offer more privacy than exchange-based activity, but consider the compliance implications for your jurisdiction.</p></section>
    </LearnPageLayout>
  );
}
