import { Metadata } from "next";
import LearnPageLayout from "@/components/LearnPage";
import { CURRENT_YEAR } from "@/lib/constants";

export const metadata: Metadata = {
  title: `What Is Rocket Pool (RPL)? Price, Guide & How to Buy (${CURRENT_YEAR}) | degen0x`,
  description:
    "Learn about Rocket Pool (RPL), the decentralized Ethereum staking protocol. Discover how it works, tokenomics, use cases, and how to buy RPL.",
};

export default function RocketPoolPage() {
  return (
    <LearnPageLayout
      title="What Is Rocket Pool (RPL)? Price, Guide & How to Buy"
      categoryName="Investing"
      categorySlug="investing"
      readTime="8 min read"
      intro="Rocket Pool is a decentralized Ethereum staking protocol that allows anyone to run a validator node with as little as 8 ETH (compared to Ethereum's 32 ETH requirement) or stake any amount of ETH to receive rETH, a liquid staking token. Designed with decentralization as a core principle, Rocket Pool distributes validators across a permissionless set of node operators."
      toc={[
        { id: "what-is", title: "what-is", level: 2 },
        { id: "what-is-rocket-pool", title: "What Is Rocket Pool?", level: 2 },
        { id: "how-it-works", title: "how-it-works", level: 2 },
        { id: "how-does-rocket-pool-work", title: "How Does Rocket Pool Work?", level: 2 },
        { id: "tokenomics", title: "tokenomics", level: 2 },
        { id: "rpl-tokenomics", title: "RPL Tokenomics", level: 2 },
        { id: "use-cases", title: "use-cases", level: 2 },
        { id: "key-use-cases", title: "Key Use Cases", level: 2 },
        { id: "how-to-buy", title: "how-to-buy", level: 2 },
        { id: "how-to-buy-rpl", title: "How to Buy RPL", level: 2 },
        { id: "risks", title: "risks", level: 2 },
        { id: "risks-and-considerations", title: "Risks and Considerations", level: 2 }
      ]}
      faqs={[
        {
          question: "What is Rocket Pool?",
          answer: "Rocket Pool is a decentralized Ethereum staking protocol with permissionless node operation and rETH liquid staking, emphasizing decentralization over market share.",
        },
        {
          question: "Where can I buy RPL?",
          answer: "RPL is available on Coinbase, Binance, Kraken, and Uniswap. It is an ERC-20 token on Ethereum.",
        },
        {
          question: "Is Rocket Pool a good investment?",
          answer: "Rocket Pool prioritizes decentralization which appeals to the Ethereum community, but has smaller market share than Lido. This is not financial advice. Do your own research.",
        },
      ]}
      relatedArticles={[
        { title: "Best Cryptos to Buy", href: "/investing/best/cryptos-to-buy", category: "Investing" },
        { title: "How to Invest in Crypto", href: "/investing/learn/how-to-invest-in-crypto", category: "Investing" },
        { title: "Lido DAO", href: "/investing/crypto/lido", category: "Investing" },
      ]}
    >
      <h2 id="what-is">What Is Rocket Pool?</h2>
      <p>
        Rocket Pool was founded by David Rugendyke and launched in 2021 as a decentralized alternative to centralized and semi-centralized staking providers. The protocol allows anyone to become a node operator by depositing 8 ETH (reduced from 16 ETH through the Atlas upgrade) and RPL collateral, while regular users can stake any amount of ETH to receive rETH, a value-accruing liquid staking token.
      </p>
      <p>
        Unlike Lido&apos;s curated node operator model, Rocket Pool uses a permissionless system where anyone meeting the collateral requirements can run a node. This decentralized approach is endorsed by the Ethereum community as healthier for network decentralization, as it distributes validator power across thousands of independent operators rather than a select few.
      </p>

      <h2 id="how-it-works">How Does Rocket Pool Work?</h2>
      <p>
        Node operators create minipools by depositing 8 ETH along with a minimum of 2.4 ETH worth of RPL as collateral insurance. The protocol matches operator ETH with ETH from regular stakers to form full 32 ETH validators. rETH is a non-rebasing token whose exchange rate against ETH increases over time as staking rewards accumulate, making it tax-efficient in many jurisdictions.
      </p>
      <p>
        The RPL collateral requirement protects stakers against node operator slashing or poor performance. If a node operator is penalized, their RPL stake can be burned to compensate rETH holders. Node operators earn a commission on the staking rewards generated by the pooled ETH in addition to their own staking rewards.
      </p>

      <h2 id="tokenomics">RPL Tokenomics</h2>
      <p>
        RPL has a total supply of approximately 20 million tokens with 5% annual inflation used for node operator rewards. RPL is required as collateral for node operators (minimum 10% of deposited ETH value in RPL), used for governance voting, and distributed as supplemental rewards to node operators. The collateral requirement creates structural demand for RPL tied to protocol growth.
      </p>

      <h2 id="use-cases">Key Use Cases</h2>
      <p>
        RPL enables permissionless Ethereum node operation with lower capital requirements, liquid staking through rETH for any ETH amount, decentralized staking that strengthens Ethereum&apos;s validator diversity, and governance over protocol upgrades and parameters. rETH is used across DeFi as collateral and liquidity in various protocols.
      </p>

      <h2 id="how-to-buy">How to Buy RPL</h2>
      <p>
        To buy RPL, register on Coinbase, Binance, or Kraken. Complete identity verification, deposit funds, and purchase RPL tokens. To stake ETH with Rocket Pool, visit the Rocket Pool website and deposit ETH to receive rETH. To become a node operator, deposit 8 ETH plus RPL collateral through the Rocket Pool smartnode interface.
      </p>

      <h2 id="risks">Risks and Considerations</h2>
      <p>
        Rocket Pool has significantly smaller market share than Lido, and rETH liquidity across DeFi is lower than stETH. The RPL collateral requirement creates a circular dependency where RPL price declines could force node operators to add more collateral or exit. Competition from Lido, Coinbase, and newer liquid staking solutions pressures growth.
      </p>
      <p>
        The RPL inflation model dilutes non-staking holders by 5% annually. Smart contract risk is present though Rocket Pool&apos;s contracts have been extensively audited. Protocol upgrades that reduce RPL collateral requirements (as seen in Atlas) can reduce demand for the token. The decentralization premium that Rocket Pool commands may not translate to proportional token value capture.
      </p>
    </LearnPageLayout>
  );
}
